"""Authored adult companion facts and everyday life; never runtime-generated."""
# cm/kg, bust-waist-hips in cm. Standing height excludes horns, ears and halos.
PHYSICAL = {
 'mira':(165,61,(94,73,99),'Softly curved, with an archivist’s unhurried bearing.','Ordinary standing height and approximate body mass.'),
 'tamsin':(160,57,(91,69,96),'Compact and supple, with capable hands and rounded hips.','Mass includes her feline ears and tail; height is measured to the crown of her head.'),
 'iona':(170,64,(96,72,101),'Naturally curvy and lightly athletic from survey work, with rose-toned skin, near-black waves, elegant dark horns and a slender spaded tail.','Height excludes horns; mass includes her embodied demonic features.'),
 'aurelia':(178,79,(101,77,106),'Tall, with a strong back and softly rounded proportions.','Mass includes her feathered wings; height excludes the halo. Clothing needs separate wing openings.'),
 'neris':(168,62,(93,71,98),'Smooth, balanced proportions in her usual embodied form.','Approximate measurements of her stable embodied form, not a claim that an elemental has human physiology.'),
 
 'sabine':(167,59,(92,69,97),'Slender, softly curved, with deliberate, economical movement.','Embodied measurements; her vampiric ancestry does not make her weightless.'),
 'koharu':(158,47,(82,61,86),'Slight and slender, with narrow shoulders and adult proportions.','Height excludes fox ears; mass includes her single full tail. Her clothes leave room for it.'),
 'zahra':(155,54,(88,67,94),'Short, softly curvy and non-muscular, with narrow shoulders and graceful hands.','Her height measures her solid body; the drifting smoke at her hair tips adds no standing height.'),
 'fenna':(169,63,(94,72,100),'Agile and athletic, with sturdy walking legs and gentle curves.','Height excludes wolf ears; mass includes her substantial tail. Skirts need a comfortable tail opening.'),
 'kaede':(194,118,(122,90,122),'Tall and fit, with a full bust, defined waist, rounded hips and subtle muscle definition.','Height excludes horns; ordinary human size charts fit her poorly. These are individual measurements.'),
 'elowen':(176,65,(94,72,100),'Tall and slender, with softly rounded hips and an upright posture.','Her long ears are not included in height; these are individual adult proportions, not an elven standard.'),
 'nyssara':(163,58,(91,70,96),'Compact and lightly athletic, with a practical, relaxed stance.','Her ancestry does not determine a particular body type; the numbers describe this individual.'),
 'sylva':(173,70,(99,76,104),'Supple and full-hipped, with celadon-green living-sapwood skin, subtle natural woodgrain, leaf ears, a small budding crown and bare green feet.','Standing height excludes her budding twig crown. Approximate settled-form mass includes living bark and varies with seasonal hydration.'),
}
# Earlier facts remain known after a disclosure. Attraction is a preference, not consent.
PERSONAL = {
'mira':dict(hand='Right',habit='Writes jokes in the margins of her own notebooks.',history='Her first private collection was a bundle of discarded catalogue cards. She liked the evidence of what other readers had wanted to find.',comfort='Spiced tea, a shared blanket and terrible poetry read with complete seriousness.',worry='She sometimes makes herself useful before asking whether she is welcome.',attraction='Patient attention, clever teasing and someone who remembers a remark she thought nobody heard.',turnoff='Being corrected for sport, public pressure to flirt, and treating her quietness as permission.',affection='Reading shoulder to shoulder; a good-night kiss when she has invited you to stay.',private='She is bolder in a written note than face to face, and enjoys watching you discover that.',initiative=('A shelf for ridiculous things','Mira has reserved a small stack of harmlessly dreadful poems. “An archive should preserve pleasure as well as importance. Will you help me choose one?”','research'),idle=('Checking the date on a borrowed volume.','Comparing two poems and trying not to smile.','Reading a favourite passage with her feet tucked beneath her.')),
'tamsin':dict(hand='Left',habit='Tests a repaired seam with her thumb before putting it down.',history='She learned binding on books that had already been repaired badly. The first cover she kept was crooked, but it opened without hurting the pages.',comfort='Honey tea, soft fabric and an afternoon when nobody has an urgent repair.',worry='She can mistake being needed for being wanted, and is learning to ask for company without offering a service.',attraction='Reliability, gentle humour and attention that continues after the practical problem is solved.',turnoff='Pulling her tail, uninvited ear touching and compliments that make her sound like household equipment.',affection='Leaning against a familiar shoulder; being asked before a hand moves to her ears or tail.',private='She likes a sincere compliment about the woman wearing the apron, especially on a day she has chosen not to wear it.',initiative=('The repair that can wait','Tamsin lays down a perfectly serviceable ribbon. “I was going to mend this again. I think I would rather have tea with somebody who will let it remain imperfect.”','workArrangements'),idle=('Sorting a few lengths of thread by feel.','Mending something of her own, without a deadline.','Warming both hands around a cup after putting her tools away.')),
'iona':dict(hand='Right',habit='Taps the rhythm of a tune while checking a route.',history='Her earliest map recorded where travellers could hear music through an open door. Her colleagues called it impractical, then kept asking to borrow it.',comfort='Apple cordial, a half-finished song and a plan that leaves room for a detour.',worry='She wants a home without making every journey feel like a betrayal of it.',attraction='Curiosity, an easy laugh and someone who can make an invitation without turning it into an obligation.',turnoff='Jealous tests, being treated as a dangerous novelty, and demands to prove she will never leave.',affection='Dancing without an audience; a hand offered openly rather than used to steer her.',private='She enjoys a bold compliment followed by the patience to let her decide how to answer.',initiative=('A map of pleasant interruptions','Iona sketches the rooms where music carries best. “This is not a shortcut to work. It is a route through a better afternoon. Shall we test the first stop?”','expeditions'),idle=('Humming while checking a pencilled route.','Writing down a fragment of music.','Keeping a quiet rhythm against the side of her cup.')),
'aurelia':dict(hand='Right',habit='Checks a lamp’s wick before settling down beside it.',history='At the hospice she kept a cracked lantern because an anxious traveller recognised its light. Useful things did not have to look faultless.',comfort='Mint tea, a quiet walk and a place where her wings can rest comfortably.',worry='She sometimes remains on watch long after anyone has asked her to.',attraction='Steady warmth, understated courage and someone who notices when she needs to stop being capable.',turnoff='Putting her on a pedestal, assuming her ancestry makes her morally perfect, or handling her feathers without asking.',affection='A hand resting between her shoulders when invited; close company with room for her wings.',private='Being called beautiful matters more to her when she is plainly off duty and has done nothing to earn the compliment.',initiative=('A light nobody has to tend tonight','Aurelia checks the nearby lamp, then deliberately leaves it alone. “It is working. I would like to practise believing that, and take a little walk instead.”','headquarters'),idle=('Inspecting a wick, then sitting down instead of finding another duty.','Stretching one folded wing clear of the furniture.','Watching a steady light without keeping vigil.')),
'neris':dict(hand='Right',habit='Turns a cup once in her hands before drinking.',history='She once spent a week making a cup perfectly symmetrical, only to prefer the imperfect one that felt better in her palm.',comfort='Citrus water, an elegant puzzle and an answer she is allowed to find slowly.',worry='She can polish away the part of an idea that made it interesting.',attraction='Observant compliments, playful curiosity and confidence that can admit a wrong guess.',turnoff='Being treated as a specimen, demands to demonstrate her body’s properties, or touching without invitation.',affection='Shared puzzles at a small table; letting a companion hold her hand while she explains an idea.',private='She enjoys being admired, but finds a perceptive question more alluring than a rehearsed line.',initiative=('The cup that fits a hand','Neris offers two ordinary cups. “One is more regular. One is nicer to use. I would like an opinion from somebody prepared to disagree with me.”','workshop'),idle=('Tracing the rim of a favourite cup.','Trying a small glass puzzle without consulting its solution.','Holding a cool drink and letting an unfinished answer wait.')),

'sabine':dict(hand='Left',habit='Aligns a letter’s edge before breaking its seal.',history='She kept a box of cancelled seals: agreements whose owners had been allowed to change their minds. It became her favourite part of the old archive.',comfort='Rose cordial, word games and a beautifully phrased refusal that everyone accepts.',worry='Old obligations can make even a kind invitation sound like another claim on her time.',attraction='Verbal confidence, dry wit and a partner who can negotiate honestly without making affection feel contractual.',turnoff='Oaths demanded as proof of love, jokes about ownership and uninvited attention to her fangs.',affection='A deliberate hand offered across a table; private kisses with no audience to impress.',private='She enjoys a little theatrical flirtation when both people know that the performance can stop at any moment.',initiative=('A seal with no obligation','Sabine sketches an entirely unnecessary monogram. “A letter inviting somebody to do nothing ought to have a suitably magnificent seal. Would you help me make it excessive?”','workshop'),idle=('Examining an old seal under ordinary lamplight.','Inventing a more elegant ending to a sentence.','Leaving a calling card beside a comfortable chair.')),
'koharu':dict(hand='Right',habit='Pockets useful offcuts, then forgets which pocket.',history='Her first paid repair was a stage dragon whose jaw fell off during its grand entrance. The actor made the accident funny; she stayed up rebuilding the hinge so he could choose when it happened.',comfort='Spiced plum tea, a sketching corner and permission to leave an idea unfinished.',worry='An offered improvement can sound like a criticism; she is learning to ask before fixing.',attraction='Practical kindness, a quick laugh and interest in her jokes as well as her careful hands.',turnoff='Crude ancestry jokes, uninvited ear or tail touching, and assuming her build tells you what she wants.',affection='An arm around her waist when welcomed; working beside someone who knows when to put the tools down.',private='She likes playful praise for an outfit she chose, especially if you also notice the clever fastening.',initiative=('The useful offcut','Koharu finds a little wooden offcut in her apron. “This could become three things. I would rather choose one with company than improve all three alone.”','workshop'),idle=('Looking for an offcut she knows she put somewhere sensible.','Sketching a small joint on reused paper.','Setting an unfinished drawing where she can find it tomorrow.')),
'zahra':dict(hand='Left',habit='Checks the balance of a chair before trusting its comfort.',history='She learned careful measurement from irrigation channels that looked level and were not. Her teacher taught her to keep an ember steady before warming a delicate joint.',comfort='Barley tea, carving a small bird and companionable silence.',worry='People can mistake a little visible magic for a promise that she can solve any problem.',attraction='Quiet confidence, honest appreciation and someone comfortable being gently held by her.',turnoff='Demands for wishes, treating her as a curiosity, and assuming her magic replaces careful work.',affection='Long, welcome hugs; a companion settling comfortably beside her without treating her small stature as permission to pick her up.',private='She likes being asked to rest her head on somebody else’s shoulder, with room for her smoky curls to settle.',initiative=('A bird no bigger than a thumb','Zahra turns a small carving between careful fingertips. “The wings are still wrong. Would you sit with me while I work them out? You need not give advice.”','headquarters'),idle=('Checking a carved bird against the morning light.','Smoothing an edge with patient little movements.','Testing a chair, then accepting that she is allowed to be comfortable.')),
'fenna':dict(hand='Right',habit='Notices exits before choosing the most comfortable seat.',history='Her first route notes included good places to stop in the rain. She still judges a map partly by whether it helps someone decide not to keep walking.',comfort='Berry cordial, rain on glass and knowing that a door is open even when she chooses to stay.',worry='Closeness can feel like losing the right to take a little space.',attraction='Playful independence, quick humour and invitations with a real, easy way to say no.',turnoff='Possessiveness, surprise tail grabbing and treating every solitary walk as rejection.',affection='Walking close enough for hands to brush, then asking; a comfortable shoulder after a long route.',private='She likes being caught looking at you as much as catching you admiring her, provided nobody turns it into a demand.',initiative=('A route with a place to stop','Fenna marks a sheltered turn on an old sketch. “The useful discovery is that you can stop here. Shall we plan a walk that does not need to achieve anything?”','expeditions'),idle=('Checking the weather before choosing to remain indoors.','Adding a sheltered stopping place to a route sketch.','Listening to the building settle, with her tail comfortably clear of the chair.')),
'kaede':dict(hand='Right',habit='Replays a difficult move after a game, even when she won.',history='The first glass colour she controlled reliably was a modest smoky grey. She kept practising it while other apprentices chased spectacular effects.',comfort='Smoked tea, a fair game and an opponent who enjoys learning.',worry='She can make enthusiasm sound like certainty and wants people to know they may disagree.',attraction='A spirited equal, frank compliments and the courage to say what one wants without issuing a challenge.',turnoff='Humiliation disguised as teasing, fetishising her size, and turning every intimate moment into a contest.',affection='A close, unhurried embrace; letting either person lead without keeping score.',private='She finds a partner’s delighted composure more attractive than a performance of fearlessness.',initiative=('The game after the victory','Kaede resets a small game board. “I won that move without understanding it. A rematch would be pleasant; working it out together might be better.”','development'),idle=('Replaying one move with a thoughtful frown.','Checking a colour sketch against an older attempt.','Setting out a game without deciding who ought to win.')),
'elowen':dict(hand='Left',habit='Asks a question before offering a remedy.',history='She once repaired a household ward by changing its instructions rather than its strength. Its owners finally understood how to look after it themselves.',comfort='Herbal tea, arranging flowers and thoughtful company without ceremony.',worry='A wish to help can become a habit of deciding what other people need.',attraction='Attentiveness, gentle candour and someone who lets elegance coexist with ordinary awkwardness.',turnoff='Idealising her ancestry, patronising people with less experience and unsolicited advice about her body.',affection='A hand held during an unhurried conversation; kisses that leave room for a smile.',private='She enjoys a compliment that catches her by surprise, particularly when she is being mischievous rather than composed.',initiative=('A ward someone else can understand','Elowen has rewritten a small practice instruction in plain language. “Would you read this as though you had never met me? I want it to work when I am not there.”','spells'),idle=('Trimming the end of one flower stem.','Reading an instruction aloud to hear where it becomes unclear.','Putting a small arrangement where somebody else may enjoy it.')),
'nyssara':dict(hand='Right',habit='Writes the limits beside an inscription’s promised effect.',history='In her home settlement, a good enchanter signed the failures as well as the finished work. She kept that habit after leaving the underground workshops.',comfort='Blackberry cordial, low light and a conversation without a rehearsed conclusion.',worry='She tires of having to explain that independence is not secrecy.',attraction='Precision, curiosity without entitlement and a quietly confident invitation.',turnoff='Assumptions that drow are cruel or seductive by nature, interrogations about her past and surprise touching.',affection='Sitting close in comfortable silence; an offered hand she can choose to take.',private='She likes a little uncertainty in flirtation, but wants the boundaries themselves to be perfectly clear.',initiative=('The useful limit','Nyssara taps the smallest line in an inscription note. “This is where I wrote what it cannot do. It is the part I most want another person to read.”','focus'),idle=('Comparing two carefully labelled material samples.','Adding a limitation beside an inscription sketch.','Watching a patch of sky without trying to name every star.')),
'sylva':dict(hand='Left',habit='Keeps fallen leaves if their colours please her.',history='She once saved a propagation bed by taking fewer cuttings and letting it look untidy. Healthy growth, she decided, did not owe anyone a performance.',comfort='Honey water, a warm seat and a growing thing left room to change.',worry='People can mistake her patience for endless availability.',attraction='Unhurried affection, playful attention and care that does not try to possess what it loves.',turnoff='Treating her as decoration, plucking leaves from her body and expecting her to heal every unhappy mood.',affection='Resting together in a warm patch of light; touch invited around, never through, tender new growth.',private='She enjoys a lingering compliment and a partner who can be cheerfully distracted from an efficient plan.',initiative=('Leave one cutting on the plant','Sylva holds an empty propagation label. “This one can wait. I thought we might decide what to leave growing, instead of only what to bring away.”','restoration'),idle=('Turning a fallen leaf to see both colours.','Checking a growing shoot, then leaving it alone.','Enjoying the last warm place without making a task of it.')),
}
PAIRS = [
 ('aurelia','koharu','A lamp allowed to be ordinary',[
 ('A useful warmth','Koharu likes the lamp’s uneven colour. Aurelia checks whether it lights the doorway clearly. Both are trying to make somebody feel welcome.','They test the doorway first, then keep the warm variation that does not spoil its light.'),
 ('The third inspection','Aurelia checks the lamp again. Koharu asks whether she distrusts the work. Aurelia admits she finds it difficult to stop watching over a useful thing.','Koharu hears the worry without defending the lamp again. Aurelia agrees to sit down before another inspection.'),
 ('Off duty, together','The lamp has remained perfectly ordinary. Aurelia and Koharu bring their cups beneath it, with no tools between them.','They give the light no further attention for an entire conversation, which both regard as a success.')]),
 ('mira','neris','The puzzle in the margin',[
 ('An answer worth keeping','Mira wants to preserve every attempted solution. Neris would rather keep one elegant answer. “People need to see how it was found,” Mira says. “They also need to find the answer,” Neris replies.','They make a clean answer page and keep the untidy attempts behind it.'),
 ('A very tidy disagreement','Neris has removed a repeated note; Mira thought its repetition showed the moment an idea changed. Neither wants the other’s work to disappear.','Neris asks before cutting a note; Mira marks which repetitions carry a new thought.'),
 ('Two kinds of clarity','Mira brings the revised pages. Neris has added a small arrow to the solution, then asks to hear the funniest failed attempt.','They keep both voices in the finished notebook, and begin another puzzle together.')]),
 ('tamsin','zahra','The chair and the cushion',[
 ('Something that holds','Zahra has found a comfortable chair. Tamsin offers to mend its cushion, then admits she might be inventing a reason to stay nearby.','Zahra asks for company first; the cushion becomes an optional extra.'),
 ('Help, or a hovering pair of hands','Tamsin keeps reaching to improve the seam. Zahra says quietly that she wanted to learn the stitch herself. “I thought I was helping,” Tamsin answers.','They agree that Zahra asks for help when she wants it, and Tamsin can enjoy watching without supervising.'),
 ('An uneven stitch, proudly kept','Zahra shows a repaired corner that is unmistakably her own work. Tamsin smiles at it before finding anything to correct.','The cushion stays a little uneven. They choose it for the next evening’s comfortable silence.')]),
 ('iona','fenna','A walk with two endings',[
 ('The interesting detour','Iona proposes following a tune heard across the courtyard. Fenna has already marked a sheltered route home. “We can keep both possibilities,” she says.','They mark a meeting place and leave the rest of the walk open.'),
 ('Waiting without a promise','Fenna came back early and Iona worried she had spoiled the outing. Fenna says she simply wanted quiet; Iona admits she would have liked a word.','They agree on a brief goodbye, without requiring either person to justify leaving.'),
 ('Both ways lead home','Iona returns with a new refrain. Fenna brings a note about a dry bench. Each asks about the part of the afternoon she did not share.','They keep a shared map with separate paths, and make another invitation without demanding matching footsteps.')]),
 
 ('sabine','kaede','Rules for a pleasant defeat',[
 ('Before the first move','Sabine proposes an elaborate wager. Kaede asks for one rule: either player can choose a different stake before the game begins.','They settle on the loser choosing the next tea, with no hidden obligations.'),
 ('A joke that missed','Sabine makes a polished joke about surrender. Kaede does not laugh. “I like a contest,” she says, “not being made small.” Sabine sets her piece down.','Sabine apologises plainly. Kaede explains which teasing she enjoys instead of requiring perfect guesses.'),
 ('A worthy rematch','Kaede offers the board again. Sabine asks whether her opponent would prefer a serious game or a ridiculous one.','They choose the mood together; the winner is allowed delight and the loser an equally comfortable chair.')]),
 ('koharu','nyssara','Whose unfinished idea?',[
 ('A tray for the awkward pieces','Koharu proposes a better tray for Nyssara’s materials. Nyssara likes the idea but wants to keep the original labels, including the failures.','They sketch a tray around the labels instead of making the labels fit the tray.'),
 ('An improvement nobody requested','Koharu moves two sample jars into a neater order. Nyssara can no longer find the comparison she was making. Koharu notices the problem before offering another fix.','Koharu puts them back and asks what the arrangement meant. Nyssara explains the experiment, not just the irritation.'),
 ('A space left deliberately empty','The new tray has an unfinished corner. Koharu asks before suggesting what it might hold. Nyssara says she would like to leave it undecided.','They sketch a first design together, disagree about its handle, and write both suggestions beside the drawing before stopping for tea.')]),
 ('elowen','sylva','The patient cutting',[
 ('A careful recommendation','Elowen suggests trimming a shoot for stronger growth. Sylva asks what kind of growth they actually want. The question makes Elowen put the scissors down.','They agree on the purpose before choosing a method, and leave one shoot untouched for comparison.'),
 ('Care with room to answer','Elowen has written a thorough care schedule. Sylva worries it leaves no room to notice what changes. Elowen admits the schedule makes her feel useful.','They keep the observations and loosen the timetable; either can ask for a pause.'),
 ('What the untidy plant taught them','The untrimmed shoot has taken its own direction. Sylva asks Elowen what she notices; Elowen answers before offering advice.','They record what actually happened, share a laugh over their confident first plan, and keep both plants.')]),
]

# Each initiative answers the invitation with a specific exchange.
INITIATIVE_REPLIES = {'mira': ('“Bad verse tells you what people were trying to enjoy,” Mira says. “This poet compares his beloved to a '
          'reliable cupboard. I cannot decide whether she married him or bought furniture.”',
          'You read the cupboard poem aloud. Mira solemnly repeats its final line: “Your hinges never fail me.” '
          'Neither of you survives a second reading without laughing.',
          'You offer to choose one poem, rather than sort the whole stack. “The cupboard, then,” Mira says. “A small '
          'commitment to a very sturdy romance.”'),
 'tamsin': ('Tamsin turns the ribbon over. “The seam holds. I keep wanting to redo it because one stitch is longer. '
            'Nobody but me will notice, and I will miss my tea.”',
            'You pour the tea while Tamsin puts the ribbon in a drawer. “Honey, please. And if I reach for that '
            'drawer, ask me whether I can taste the tea with a needle in my hand.”',
            'You can stay for one cup. Tamsin puts out two. “One cup is company. You need not offer me an entire '
            'afternoon to make it count.”'),
 'iona': ('“The stairwell holds the low notes,” Iona says. “The courtyard loses them to the wind. I want to hear the '
          'same refrain in both places before I choose where to sing it.”',
          'Iona hums a refrain in the stairwell, then tries it through the open courtyard door. The last note '
          'disappears outside. “An excellent place for a bad singer,” she decides. “I shall stay in here.”',
          'You offer to hear the first stop today. “Then the stairwell gets a private concert,” Iona says. “Do stand '
          'where I can see whether you enjoy it.”'),
 'aurelia': ('“The wick is trimmed and there is enough oil,” Aurelia says. “I keep checking because leaving feels '
             'careless. I would like to look at the courtyard without counting its exits.”',
             'On the short walk, Aurelia notices a chipped stone shaped like a sleeping dog. She points out its folded '
             'ear. “I have passed that stone a hundred times. I should have looked down sooner.”',
             'You offer a short walk before returning to your own plans. “To the courtyard and back,” Aurelia agrees. '
             '“If I stop to inspect a hinge, you may remind me about the dog-shaped stone.”'),
 'neris': ('Neris points to a shallow dip beside one handle. “My thumb rests here. The perfect one makes me pinch '
           'harder. I dislike losing an argument to my own thumb, but it has evidence.”',
           'You compare the handles. Neris watches your grip, then tries the cups again herself. “The uneven one,” she '
           'decides. “I shall have to find a less dignified use for symmetry.”',
           'You offer an opinion about the grip, without pretending to judge the glaze. “Good,” Neris says. “I asked '
           'for a hand, not a committee.” She passes you the uneven cup.'),
 'sabine': ('“An enormous crown over a very small cushion,” Sabine proposes. “Below it: By Our Command, Kindly Sit '
            'Down. A command which its recipient may ignore, naturally.”',
            'You suggest two trumpeters announcing the cushion. Sabine adds them to the sketch. “Excellent. The '
            'invitation will require more ceremony than the occasion can possibly survive.”',
            'You offer one suggestion and leave the drawing to her. “One is plenty,” Sabine says. “I have already '
            'appointed myself an entire committee on unnecessary grandeur.”'),
 'koharu': ('“A peg, a wedge, or a little boat,” Koharu says, holding up the offcut. “The grain would make a fine hull. '
           'For once I would like to make something whose job is to float.”',
           'You vote for the boat. Koharu sketches a curved bow on the wood and gives it a square little cabin. “Too '
           'grand for a pond? Good. Its captain has ambitions.”',
           'You can help choose, but cannot stay for the carving. “That still settles it,” Koharu says. “The boat. You '
           'can criticise its seaworthiness when it has a bottom.”'),
 'zahra': ('Zahra shows you the underside of a wing. “Too thick here. A sparrow folds it close; mine looks as if it '
            'is carrying two doors.” She marks where to remove a sliver.',
            'You sit while Zahra pares the wing. After a few careful strokes she turns the bird toward you. “One door '
            'removed.” Her grin is brief and pleased.',
            'You offer a little company, but no carving advice. “That was the invitation,” Zahra says, moving a chair '
            'beside hers. “You may, however, tell me if it starts looking like a fish.”'),
 'fenna': ('“This wall blocks the rain from the west,” Fenna says. “The bench farther on does not. A fine view is a '
           'poor argument when water is running down your neck.”',
           'You trace a short walk to the sheltered wall and back. Fenna crosses out the longer loop. “There. A route '
           'with the rare courage to end near a comfortable seat.”',
           'You ask for a short walk. “To the shelter and home, then,” Fenna says. “I promise no surprise hill. A hill '
           'is a particularly rude thing to hide in an invitation.”'),
 'kaede': ('Kaede restores the pieces to the earlier position. “You had to protect this corner. Moving my centre piece '
           'gave you two threats to answer. I saw only one of them.”',
           'You replay the position slowly. Kaede stops before the winning move. “There. I was watching your hand, not '
           'the corner.” She smiles. “A victory rescued from the indignity of being accidental.”',
           'You offer to study the move without a full rematch. “Agreed,” Kaede says. “Understanding one good move '
           'should take less time than repeating six bad ones.”'),
 'elowen': ('Elowen reads the revision aloud: “Check the chalk line before lighting the practice lamp. If the line has '
            'a gap, leave the lamp unlit and ask for help.” She has crossed out “verify the integrity of the '
            'boundary.”',
            'You read the instruction without her prompting. Elowen points at the crossed-out phrase. “I used five '
            'words to avoid saying ‘look for a gap’. I shall try to resist the urge to sound impressive.”',
            'You offer to read it once as a beginner, rather than judge the ward itself. “Exactly what I need,” Elowen '
            'says. “Tell me where the words make you guess.”'),
 'nyssara': ('“This practice inscription warns when its line is broken. It does not mend the break,” Nyssara says. “A '
             'reader who confuses those things will trust a warning to do a repair.”',
             'You read the limit back to her. Nyssara adds it beside the title as well as beneath the diagram. “There. '
             'Now someone must work considerably harder to overlook it.”',
             'You offer to check the wording, while leaving the enchantment test to her. “A useful distinction,” '
             'Nyssara says. “I want an honest reader, not a second signature on a test you have not made.”'),
 'sylva': ('Sylva points to a shoot with only two small leaves. “Taking this now would leave the stem almost bare. I '
           'can wait for another pair. An empty label is cheaper than a dead cutting.”',
           'You put the label beside the pot for another day. Sylva turns it blank side out. “There. We have '
           'successfully resisted writing a timetable for a leaf.”',
           'You offer to look with her, but leave the choice of cuttings to her. “Then look at this little curl,” '
           'Sylva says. “That is the next leaf. I would rather show it to you than cut it off.”'),
 'velis': ('“You took yours less sweet last time,” Velis says. “I remembered that more easily than the figures in this '
           'morning’s ledger. I prefer the practical use of a good memory to be tea.”',
           'Velis puts the ledger beneath her chair and tastes her tea. “Pear and too much cinnamon. Mine, I mean. I '
           'was distracted by trying to get yours right.” She laughs and adds hot water to her own.',
           'You can stay for a cup, but have no time for business. “Fortunately, I have brought no business,” Velis '
           'says. “If a ledger appears, we shall blame the furniture.”'),
 'rhess': ('“The relief answered, and I closed the watch book,” Rhess says. She sets a carved bird beside the cups. '
           '“Now I would like your opinion. Sparrow, or a very determined potato?”',
           'You turn the little carving to examine its wings. Rhess waits, then supplies her own verdict. “Sparrow '
           'from this side. Potato from that one. I shall display it carefully.”',
           'You can share tea but cannot stay all evening. “Tea is enough,” Rhess says. She places the bird facing '
           'you. “And one opinion on the beak, if you have it.”')}
