"""Authored multi-exchange conversations. Plans here grant no inventory or work.

A personal story has three exchanges, then a two-exchange follow-up. Each
approach, preference and final stance has its own answer. The engine supplies
only the currently reached question; future text is never sent to the client.
"""

def person(title, opening, approaches, question, options, uncertainty, privacy,
           decision, endings, followups, unresolved, tradition):
    return dict(title=title, opening=opening, approaches=approaches, question=question,
                options=options, uncertainty=uncertainty, privacy=privacy,
                decision=decision, endings=endings, followups=followups,
                unresolved=unresolved, tradition=tradition)

# approach = label, answer. Preference = label, answer; neither is inferred.
PERSONAL = {
'mira': person('The ending worth defending',
 'Mira has two books ready for a shared reading. “One ends with a reunion. The other ends with a very plausible divorce. I admire the second and keep reaching for the first. This is damaging my reputation for sound judgement.”',
 [('Ask what makes the reunion convincing','“The husband comes back for the dog before he knows his wife has forgiven him. It is a small choice the author bothered to show. I believe that more readily than his speech.”'),
  ('Say a comforting ending can still be badly earned','“Quite. A wedding does not repair three hundred pages of selfishness. But I think this one earns its reunion. I would like the chance to argue the case.”'),
  ('Tease her for hiding a favourite behind a respectable choice','“I put the impressive one on top. You have discovered my entire system of literary fraud.” She swaps the books.')],
 '“What makes you want to return to a story: people finding their way back to one another, or an ending that follows the evidence even when it hurts?”',
 [('I usually want a hopeful ending','“Then I will bring the reunion. You may still object to the speech; I have underlined the worst sentence for that purpose.”'),('I prefer a convincing ending, even if it is unhappy','“The divorce, then. You should know that I intend to complain about it while defending its logic.”')],
 '“Then a passage from each. You need not establish a lifelong reading policy before borrowing a book.”',
 '“Fair enough. I will choose a passage I like and leave your reasons to you.”',
 '“I want to keep a short shelf of books people actually reread. My favourite goes on it, even if I cannot persuade you about the ending.”',
 [('Help her keep both books on the shelf','“Yes. Put them beside one another. I want a reader to be able to choose an argument.”'),('Say you are not convinced the reunion is earned','“Then we still disagree. I shall bring the dog’s scene next time. You may bring your best objection.”'),('Ask her to choose the passage herself','“Gladly. I wanted your opinion, not permission to like it. Expect the dog.”')],
 ['Mira opens the reunion at a folded corner. “I remembered your preference for hope. He has returned for the dog. His wife has not yet agreed to anything.”',
  'Mira opens the other novel. “You wanted an ending that follows the evidence. They divide the household goods, then both reach for the same ugly bowl. I wish the author had been less convincing.”',
  'Mira brings one page from each novel. “Two endings, as promised. We can choose after reading them.”',
  'Mira has chosen the dog’s scene. “My selection this time. You may enjoy it without submitting an account of your taste.”'],
 '“I still think the reunion is earned. You thought otherwise; I have not quietly recorded a conversion.”',
 'Read one disputed passage together, with space for both opinions.'),

'tamsin': person('The repair and the guessing game',
 'Tamsin has set a damaged book beside a bag of game counters. “Someone asked for one loose stitch. I can see three more that will go soon. I also told myself I would play tonight. Apparently I have become difficult to keep an appointment with.”',
 [('Ask which repair is needed before the book can be used','“The loose stitch at the hinge. The others can wait if the owner opens it carefully. I should explain that instead of silently offering an entire evening.”'),
  ('Ask whether she would accept someone else postponing her game','“I would be cross. Politely, which is sometimes worse.” Tamsin closes the book. “That is an inconveniently fair question.”'),
  ('Ask which object she planned to impersonate in the game','“A kettle with a grievance. It has been rehearsing while I count stitches.” Her ears lift. “It may demand compensation.”')],
 '“When we have an evening free, would you rather play something or read beside each other?”',
 [('I would enjoy a game together','“Good. I shall keep the counters out. You may interrogate the kettle after it has settled its grievance.”'),('I would enjoy reading side by side','“Then bring your book. I may interrupt once if mine introduces a secret twin.”')],
 '“We can leave both books and counters within reach. Deciding after sitting down is allowed.”',
 '“Then I will tell you what I fancy doing and ask whether you want to join. No explanation required.”',
 '“I will offer the essential stitch and a later appointment for the rest. Tonight I want to use the chair, not spend the evening keeping it ready.”',
 [('Support the limited repair and keep her company afterwards','“Thank you. If I reach for a fourth stitch, point at the counters. I will understand.”'),('Say she should leave all the repair work for another day','“I would rather secure the loose page before handing it back. We differ on that. I can still stop after the stitch I actually offered.”'),('Leave the decision with her and ask about the kettle','“A wise retreat. The kettle alleges that everyone admires the cups while expecting it to do the work.”')],
 ['Tamsin has the counters ready. “The loose page is secure. The rest has an appointment. This time the kettle will answer five questions, most of them resentfully.”',
  'Tamsin brings her own book. “The stitch is finished; the larger repair is waiting. You said you liked reading together. I have saved the chair nearest the lamp.”',
  'Tamsin puts counters beside two books. “Both possibilities. We can decide now that we are sitting down.”',
  'Tamsin opens the counter bag. “I want to play. Would you like a place in the first round?”'],
 '“You would have put the whole repair aside. I still wanted that page secured. I did stop there.”',
 'Keep a shared evening for books or a game, with the work put away.'),

'iona': person('A detour worth announcing',
 'Iona traces a short courtyard walk, then adds a loop past the stairwell. “There may be music there. I would like to go and find out. I am also aware that my short walks acquire extra corners without consultation.”',
 [('Ask what she hopes to hear','“A fiddle tune I heard through the door yesterday. The player stopped before the last measure. It has been going round my head, badly finished, ever since.”'),
  ('Point out that a surprise detour changes someone else’s plans','“Yes. Pleasant for me does not automatically mean welcome for you. I could announce the extra corner before taking it. A radical advance in surveying.”'),
  ('Offer a terrible ending for the unfinished tune','Iona taps the rhythm while you invent a final thump. “Decisive. Unmusical. We should find the player before I begin remembering your version.”')],
 '“When I invite you for a walk, do you like a destination agreed beforehand, or room for a detour?”',
 [('I like knowing the plan before we leave','“Then I will name the route and ask before changing it. You may still discover that my estimate of one tune was optimistic.”'),('I enjoy an optional detour','“Then I will point out temptations as we pass. Optional remains part of the arrangement.”')],
 '“I can offer the turn when we reach it. You can decide with the actual weather in front of you.”',
 '“Then each invitation can stand on its own. You need not give me a rule for every future walk.”',
 '“I will keep the extra loop on the sketch and name it when I invite someone. I do not want to become a person who stops noticing interesting doors.”',
 [('Agree that she can offer the detour without assuming it','“Exactly. Music here, home there. Two honest arrows.”'),('Say some invitations should stay as simple as promised','“I agree about the promise. I still want to ask when something catches my ear. You can tell me that today the straight route matters.”'),('Ask her to choose where she wants to go tonight','“The stairwell. One unfinished tune has occupied quite enough of my attention.”')],
 ['Iona holds up her sketch. “Courtyard, stairwell, then back. I remembered that you like the route stated first. Would you like to hear the ending I found?”',
  'Iona pauses with the route sketch. “There is a tune to hear at the extra corner. You said a detour could be welcome. Shall I play it for you here first?”',
  'Iona brings the completed refrain. “The weather may choose the walk. We can at least hear the tune indoors before deciding.”',
  'Iona taps a rhythm on the table. “I found the last measure. Would you listen?”'],
 '“You wanted some walks to stay as promised. I still like an unexpected turn, so I shall ask before adding one.”',
 'Compare a route and a tune before choosing the next walk.'),

'aurelia': person('The lamp beside the window',
 'Aurelia has moved a lamp away from the window. “The room is easier to read in now. It is harder to look outside without the lamp reflecting in the glass. I keep improving the light for a task nobody is doing.”',
 [('Ask what she actually wants to do here tonight','“Look outside. Then perhaps talk. I trimmed the wick before asking myself that question.” She lowers the shade. “Habit is an efficient servant with very limited judgement.”'),
  ('Say a well-lit room is still useful','“Certainly. I like being able to find my cup. I also like the sky, and neither preference needs to defeat the other for the whole evening.”'),
  ('Ask whether the stars filed a complaint','“Their last message consisted of several small points of light. I was hoping for a clearer signature.” She turns the lamp down, smiling.')],
 '“Would you choose a bright place to read together, or a dimmer seat by the window for conversation?”',
 [('I would choose the reading light','“Then I can arrange it behind our shoulders. Enough for the page, without making us squint at each other.”'),('I would choose the window seat','“Then a covered lamp and somewhere safe to put the cups. I can enjoy the sky without furnishing the floor with broken crockery.”')],
 '“We can try both seats. Moving a chair need not establish a doctrine.”',
 '“Then I shall offer a seat when you come. You can choose it without defending your reasons.”',
 '“I want a lamp we can adjust without somebody standing over it. I also want to remember that I can choose what the room is for.”',
 [('Help her compare the two seats','“Take that one. Tell me when the light reaches your eyes. I can see the page perfectly from a chair that may be dreadful for you.”'),('Defend keeping the stronger light on','“I still prefer the window tonight. I can leave your reading corner lit. We need not share a preference to share a room.”'),('Ask her to choose a seat for herself first','“By the window.” She sits before making another adjustment. “There. An unexpectedly quick decision.”')],
 ['Aurelia has angled the lamp behind two chairs. “You preferred reading light. I checked the glare from your side this time. Will you try the page?”',
  'Aurelia has covered the lamp nearest the window. “You chose the view. The cups have a table, and the lamp no longer reflects straight into our eyes.”',
  'Aurelia leaves both chairs free. “Reading corner or window? We can decide after looking at the sky.”',
  'Aurelia sits by the window. “Would you like the other chair? The reading lamp is there if you prefer it.”'],
 '“You defended the brighter room. I still like this view. Both lamps have controls; we can survive the disagreement.”',
 'Choose a comfortable seat and something worth reading or looking at.'),

'neris': person('The beautiful handle that pinches',
 'Neris offers you a drawing of two cups. “That handle looks much better. That one fits my hand. I want the beautiful one to win, which is why I have not asked it to hold anything yet.”',
 [('Ask where the narrow handle catches her hand','“Here, against the knuckle when I lift it.” She demonstrates with her fingers. “It looks graceful because I have drawn the hand out of the problem.”'),
  ('Defend making an object just for its beauty','“I do defend that. I could make a vase with exactly this curve. Calling it a cup is where the awkward promise begins.”'),
  ('Accuse her of trying to flatter her own drawing','“It has been exceptionally responsive to praise. Much less demanding than my thumb.” She draws the thumb back into the sketch.')],
 '“If both worked properly, would you choose the striking colour or the shape that feels best in your hand?”',
 [('I would choose the striking colour','“Then I will show you the blue edge first. I may still make you pick it up before accepting the compliment.”'),('I would choose the comfortable shape','“Then I will hand you the plain one before distracting you with the glaze. A stern test of my restraint.”')],
 '“We can compare them in use. You do not have to choose from my highly persuasive picture.”',
 '“Then I will ask about each piece. You can like one without joining a school of cup design.”',
 '“I will keep the curve for a vase and widen the cup’s handle. I am disappointed. I also think I have found two things I want to make.”',
 [('Support keeping both ideas for different purposes','“Yes. The curve survives, and somebody gets to finish their tea with comfortable fingers.”'),('Say the narrower handle could still suit another person','“It might. I will label the size honestly instead of pretending it suits everyone. I still want a cup I enjoy using myself.”'),('Ask to see the next drawing before judging','“Good. I will bring the hand as well as the cup this time.”')],
 ['Neris brings two colour sketches. “You chose the striking colour. Look at the blue against the clear edge. I have widened the handle in both versions.”',
  'Neris offers a paper outline of the revised handle. “You chose comfort. There is room for the knuckle now. I want to know whether I have made the curve dull.”',
  'Neris lays both designs beside each other. “Still undecided? Good. I have given you a more honest comparison.”',
  'Neris shows the revised cup drawing. “Wider handle, blue edge. I wanted to show you where the drawing has changed.”'],
 '“You thought the narrow handle could suit someone else. I have kept that possibility. I still prefer the wider one for mine.”',
 'Compare the look and feel of her next design without choosing a permanent winner.'),

'sabine': person('The invitation with too much trumpet',
 'Sabine has drawn a tiny trumpet beside an invitation to tea. “I made the wording simple. Then I became bored with it. Nobody should have to decode an invitation, but surely they may enjoy receiving one.”',
 [('Ask which part she wants to keep','“The ridiculous title: A Gathering of People Unreasonably Fond of Tea. The time must remain perfectly ordinary. Four.”'),
  ('Say the flourish could make a casual visit feel formal','“True. I would be appalled if somebody dressed anxiously for my joke. Perhaps the plain sentence belongs first.”'),
  ('Ask whether the trumpet announces the kettle','“Only when the kettle achieves a particularly distinguished boil. I refuse to award honours for mere steam.”')],
 '“How would you like me to invite you: plainly, or with a little theatre around a clear question?”',
 [('I prefer a plain invitation','“Tea at four, if you would like it. There. I shall try not to decorate the time.”'),('I enjoy a playful flourish','“Then you shall receive a title absurd enough to disqualify itself from official use, followed by the actual invitation.”')],
 '“I can ask plainly and see whether you laugh at the trumpet. We need not sign a treaty about stationery.”',
 '“Then I shall choose the wording and leave you free to answer the invitation itself.”',
 '“I will put the time first and keep my ridiculous title below it. I want clarity without pretending that I have become a solemn person.”',
 [('Help her make the time unmistakable','“Four, written once in large letters. A devastating blow to suspense.”'),('Say the trumpet makes too much of tea','“Then you and the trumpet remain at odds. I like it. I can send you the plain version without dismissing my tiny musician.”'),('Ask her to read the invitation in her best ceremonial voice','“Tea. At four.” She bows. “I have condensed the ceremony. Its dignity has suffered terribly.”')],
 ['Sabine presents a card reading Tea at four, if you would like it. “The plain version. I did not even put the trumpet on the back.”',
  'Sabine lifts a card. “You are invited to a Gathering of People Unreasonably Fond of Tea. Four o’clock. The trumpet regrets it cannot attend.”',
  'Sabine has written the time above a small trumpet. “A clear question, optional decoration. Shall we have tea?”',
  'Sabine puts two cups on the table. “Would you like to stay? I have already enjoyed drawing the invitation.”'],
 '“You still find the trumpet excessive. I remain fond of it. Your invitation need not carry it.”',
 'Exchange an invitation whose wording suits the recipient.'),

'koharu': person('The bird with one proud wing',
 'Koharu has carved a bird whose left wing sits higher than the right. “I could level it. I like the way it looks as though somebody has insulted its workmanship. I suspect I am defending a mistake because it resembles me.”',
 [('Ask whether the uneven wing makes it unstable','“No. The base is flat. It is a disagreement with symmetry, not with standing up.” She sets it on the table to show you.'),
  ('Say fixing a mistake need not erase the bird’s expression','“Fair. I could lower the wing and keep the brows. I have been acting as though my only choices were this bird or a completely boring one.”'),
  ('Ask what insult the bird has received','“Someone called it a coat hook. It is considering legal action against the entire household.”')],
 '“When something familiar has a harmless imperfection, do you like keeping that mark, or having it neatly repaired?”',
 [('I like keeping a mark with a history','“Then I will ask before smoothing it away. The fact that I can remove a scratch is not an instruction to do it.”'),('I usually prefer a neat repair','“Then I will show you what can be changed without weakening the piece. You need not collect every old mistake.”')],
 '“It depends on the object for me too. I can show you the options when there is an actual scratch to discuss.”',
 '“Then we will discuss the particular object, if you ever bring me one. I will not assume.”',
 '“This bird keeps its wing. I want to try a second with the angles matched, to see whether the expression survives.”',
 [('Encourage the comparison','“Yes. Two offended birds, differently offended. A very small exhibition.”'),('Say you would still lower the first bird’s wing','“I believe you. I am keeping it. We can disagree about something that does not need to hold up a person.”'),('Ask whether the second bird will object to being compared','“Bitterly. I shall place them facing away from each other.”')],
 ['Koharu sets down the original bird. “You like a mark with a history. This wing has survived my urge to sand it. The new sketch is straighter and considerably less indignant.”',
  'Koharu shows you a sketch of the second bird. “You prefer a neat repair. I used matching wing angles here. I have kept the eyebrows, because they were innocent.”',
  'Koharu puts the bird beside its straighter sketch. “Two particular cases. Which expression works better?”',
  'Koharu shows you the original and the new sketch. “I wanted to compare them. You may tell me which one looks less like a coat hook.”'],
 '“You would still change this wing. I am keeping it. The second design gives your argument a fair hearing.”',
 'Compare two small designs and keep room for different tastes.'),

'zahra': person('The missing fourth note',
 'Zahra taps three notes on the table, waits, then repeats them. “I like the pause. I also want to finish the tune before somebody decides I have forgotten the rest. Wanting approval has made this a surprisingly complicated three notes.”',
 [('Ask what the pause does to the tune','“Makes you lean towards the next note. When it repeats instead, you hear the first one differently. I want a music box that can do that without becoming irritating.”'),
  ('Say an unfinished tune can become irritating','“Yes. Especially after six turns. I would like you to tell me before I fit it into a box and begin calling the repetition a feature.”'),
  ('Ask whether the fourth note has demanded better wages','“It has seen what the first three are doing and declined the position.” She taps them again, smiling.')],
 '“When I show you work I am proud of, would you rather I explain the small details or let you try it before I talk?”',
 [('I enjoy hearing how the details work','“Then I will show you where the pause goes. Stop me if I begin explaining a second mechanism before you have heard the first.”'),('I would rather try or hear it first','“Then I will let it play. No pointing over the best part. I can manage that.”')],
 '“I can offer both. Listen once, then decide whether you want to see what makes it stop.”',
 '“Then I will ask when I have something to show you. It need not be a rule.”',
 '“I am keeping the pause for now. I also want a second ending, with the fourth note, so I can compare them after the novelty wears off.”',
 [('Ask to compare both endings later','“Good. I trust the second hearing more than the first delighted face.”'),('Say you prefer a tune that resolves','“Then I know what you will listen for. I still prefer the pause. Perhaps neither of us needs to win.”'),('Tell her to choose the version she wants to keep','“The pause. I wanted that answer to be mine. Thank you for not filling it in.”')],
 ['Zahra has drawn the timing of both endings. “You wanted the details. The fourth note falls here; in my preferred version, the same space stays empty.”',
  'Zahra taps the two endings without explanation. After the second, she asks, “Which one would you want to hear again?”',
  'Zahra taps both endings, then leaves the drawing face down. “You can decide whether you want the mechanism after the tune.”',
  'Zahra taps the revised tune. “I wanted another listener. Would you hear it once?”'],
 '“You preferred the ending with a fourth note. I still like the pause. The disagreement has survived another hearing.”',
 'Hear a small piece of work before deciding how much explanation to share.'),

'fenna': person('The story with the name left out',
 'Fenna begins a story, then stops before the innkeeper’s name. “The best detail would tell you who it was. He trusted me with the part I want to make funny. This is an awkward occasion to possess a good memory.”',
 [('Ask what can be told without identifying him','“The misunderstanding: he thought the parcel was a hat; it was a tea cosy. The rest explains why that mattered to him. That part is his.”'),
  ('Say leaving out the name may not protect him','“You are right. The road and the season might be enough. I can keep the tea cosy and invent a different owner, provided I call it fiction.”'),
  ('Ask her to make herself the foolish character instead','“I once followed a man through the rain because his coat matched my guide’s. He asked why I was inspecting his turnips. That embarrassment is entirely mine to distribute.”')],
 '“What do you enjoy more when we trade stories: a polished joke, or the awkward true version?”',
 [('I enjoy an openly invented, funny version','“Then I will announce the invention before the giant bird appears. You will never be required to put it on a map.”'),('I prefer the true version, including the awkward parts','“Then I will keep the turnips and admit that I did not discover my mistake promptly.”')],
 '“I can tell you which sort it is before starting. You can choose then.”',
 '“Then I will offer a story and let you decide whether to hear it. No review of your taste required.”',
 '“I will keep his story private. The tea cosy may acquire a completely imaginary duke, who deserves whatever happens to his hat.”',
 [('Ask for the imaginary duke another evening','“He will be insufferable and clearly labelled. I am looking forward to him already.”'),('Say even the tea-cosy detail feels borrowed too closely','“I see the concern. I think the isolated mistake is common enough to invent around. I will change the parcel as well if the story starts resembling him.”'),('Leave the story aside and ask about the turnips','“Enormous. That should have been my first warning. Our guide had promised a bridge.”')],
 ['Fenna adopts a grand voice. “The entirely imaginary duke mistook a bread basket for his ceremonial hat. The cook objected because he was still wearing the rolls.”',
  'Fenna sits down. “The true turnip account: I followed him all the way to his kitchen door. When he asked my business, I said I had been promised a bridge. He offered directions and a turnip.”',
  'Fenna offers a choice before beginning. “An invented duke wearing his lunch, or the true account of my accidental visit to a turnip field?”',
  'Fenna brings a short story. “I have a fictional duke who has mistaken lunch for headwear. Interested?”'],
 '“You were uneasy about borrowing the parcel mistake. I changed the object and the setting. His private circumstances are nowhere in it.”',
 'Name whether a story is true or invented before sharing it.'),

'kaede': person('The rematch she wants too much',
 'Kaede has reset a board after losing. “I enjoyed that move until it beat me. Now I want a rematch immediately, which may be an unfair description of wanting my pride back.”',
 [('Ask what made the move work','“I defended the centre so well that I stopped watching the edge. It went around me. I would like to notice that before congratulating myself next time.”'),
  ('Ask whether the other player owes her a rematch','“No. I may ask. They may quite reasonably want to enjoy having won.” She moves her hand away from the pieces.'),
  ('Offer to congratulate her on a very instructive defeat','“I shall accept the adjective and dispute your tone.” Her expression breaks. “Yes. It was a good move.”')],
 '“When we play together, do you enjoy a serious contest or a looser game with room to experiment?”',
 [('I enjoy a serious, fair contest','“Then I shall try to win. No hidden handicap, no lecture after the last move unless you ask.”'),('I prefer a relaxed game where we can try things','“Then we can rewind a move by agreement. I will still enjoy finding a clever one. Relaxed need not mean inattentive.”')],
 '“We can choose the tone before each game. I am capable of asking before setting up a tournament.”',
 '“Then I will name the sort of game I am offering and leave you free to refuse it.”',
 '“I am leaving the board for now. Later I will ask for a rematch and congratulate the move before trying to defeat it.”',
 [('Support asking later','“Good. I can spend the interval finding a better opening, which is a considerably less generous motive.”'),('Say an immediate rematch could still be friendly','“It could. I do not trust my present reason for asking. Tonight I want a little distance from my own sulking.”'),('Ask what she wants to do while the board waits','“Compare the glass colours by the window. Something I cannot win by moving faster.”')],
 ['Kaede sets the board ready. “A serious contest, as you prefer. I have a new opening and no intention of telling you what it is. Would you like to play?”',
  'Kaede leaves one side of the board clear. “A trial position. We can take back a move if we both agree. I remembered that you wanted room to experiment.”',
  'Kaede waits before placing the pieces. “Serious match or trial position? We can choose the rules before we start.”',
  'Kaede has a board ready. “I would like a rematch. No obligation to rescue my pride. Are you interested?”'],
 '“You thought an immediate rematch could be friendly. I agree in principle. I was annoyed enough to prefer waiting.”',
 'Agree the kind of game before playing it.'),

'elowen': person('The yellow flowers nobody prescribed',
 'Elowen has drawn yellow flowers where she might grow another medicinal herb. “I can give you an excellent reason for the herb. The flowers would please me every time I opened the door. I am annoyed that I keep treating that as the weaker argument.”',
 [('Ask whether replacing the herb would leave a shortage','“No. This is a small personal pot, not the infirmary bed. I am arguing with an imaginary crisis to avoid choosing a colour.”'),
  ('Say usefulness can be a pleasure too','“Certainly. I like seeing a remedy ready when somebody needs it. I also want to like something without making it earn a place in the cupboard.”'),
  ('Ask which illness the yellow flowers would fail to cure','“An excess of solemn advice. I suspect they would only irritate the sufferer.” She smiles and adds another bloom to the sketch.')],
 '“When your day has been difficult, would you usually like me to listen first or help think of something practical?”',
 [('I usually want someone to listen first','“Then I will begin with what happened, not a list of repairs to your day. You can ask for suggestions afterwards.”'),('I usually want help thinking through a practical next step','“Then I will ask which part can change and offer one suggestion. You still get to say it will not help.”')],
 '“I can ask at the time. A difficult day need not arrive with instructions attached.”',
 '“Then I will ask what you want in the moment. You need not tell me about a difficult day at all.”',
 '“The pot gets yellow flowers. I may grumble if they wilt, and I reserve the right to plant something else without claiming a personal revelation.”',
 [('Ask to see which flowers she chooses','“Yes. I want an opinion on the colour, not a diagnosis.”'),('Say you would have chosen the useful herb','“I believe you. I am choosing the flowers. There is enough herb in the proper bed for both of us to survive my extravagance.”'),('Ask her to stop defending the choice and enjoy planning it','“Fair. Yellow in the middle, blue at the edge. Now I have a much more enjoyable disagreement to consider.”')],
 ['Elowen brings the flower sketch. “I have been enjoying the planning. How has your day been? You said listening helps, so I shall start there.”',
  'Elowen brings the flower sketch. “I settled the pot by asking what actually needed changing. You like a practical next step too. Is there something you want to think through, or shall we just discuss the colours?”',
  'Elowen leaves the sketch between you. “Company, a suggestion, or an argument about yellow and blue? We can choose now.”',
  'Elowen shows you the flower sketch. “I wanted to share the colours. You need not give me an account of your day in exchange.”'],
 '“You would have chosen the herb. I still want the flowers. I have stopped presenting them as a treatment.”',
 'Ask what kind of company would help, without assuming a remedy is wanted.'),

'nyssara': person('The explanation that lost its reader',
 'Nyssara has crossed out half a practice note. “Someone asked why the line turned here. I gave the history of the pattern. They thanked me and copied the turn incorrectly. I had answered an impressive question nobody asked.”',
 [('Ask what the short answer should have been','“The return line must meet the outside branch, not cross the centre. Start there. Give the history if they want to know why the convention exists.”'),
  ('Say the reader may have needed to ask again','“They may. I had also made asking again look expensive. I can explain without making the price an entire afternoon.”'),
  ('Ask whether she has filed the discarded lecture somewhere safe','“Under preventable delays. I have retained a copy in case its author forgets the lesson.”')],
 '“When you ask me about something unfamiliar, would you like the short answer first or the reasoning from the beginning?”',
 [('Give me the short answer first','“Then one sentence, followed by a question about whether you want the rest. I can learn this discipline.”'),('I enjoy following the reasoning from the beginning','“Then I will show the steps, and leave pauses where you can question them. Length is not a substitute for a place to enter the argument.”')],
 '“I can ask how much detail you want before beginning. That may save us both a splendidly unnecessary lecture.”',
 '“Then I will answer the question you actually ask and check whether you want more.”',
 '“I am keeping a short instruction above the longer explanation. I will not discard the reasoning, but the reader should not have to excavate the answer.”',
 [('Support giving the reader both levels','“Yes. The answer first, its support below. The page can be patient even when I am not.”'),('Say simplifying it might hide an important condition','“That is the risk. The short line must include the condition that makes it true. I will shorten the history before shortening the warning.”'),('Ask to try the revised instruction without prompting','“Gladly. I will keep my hands off the pencil until you finish.”')],
 ['Nyssara points to the revised line. “Short answer first, as you prefer: join the outside branch. Would you like to check the drawing before I explain the convention?”',
  'Nyssara lays out two diagrams. “You wanted the reasoning. This branch carries the return; crossing the centre would join it to the wrong path. Follow both with your finger.”',
  'Nyssara has the short note above the diagrams. “One sentence or the full reasoning? Both are ready.”',
  'Nyssara offers the revised page. “Would you try this instruction? Tell me if you want an explanation.”'],
 '“You warned me about hiding a condition. I kept the condition and removed the historical introduction. You may still find a missing step.”',
 'Choose the amount of explanation before following a design together.'),

'sylva': person('A picture that refuses to stay still',
 'Sylva has arranged fallen leaves into a picture. One edge has curled out of place. “I could press them flatter. I like the shadow that edge makes. I wanted a picture and have apparently invited the materials to edit it.”',
 [('Ask why the edge is curling','“That part has dried faster. Pressing it now would change the shadow, and perhaps split the edge. I can enjoy it today without pretending it will stay.”'),
  ('Say she could preserve the arrangement with a drawing','“Yes. I would like that. The drawing would keep the shapes while the leaves continued being leaves. I need not choose one kind of keeping.”'),
  ('Ask whether the leaf has improved her composition','“It has put itself in front of the yellow one. Confident. Rather poor manners.” She turns the tray to inspect its shadow.')],
 '“When you spend time among plants, do you enjoy tending something, or looking without having a task?”',
 [('I enjoy having something small to tend','“Then I can show you a pot and explain what it needs before handing you a watering can.”'),('I enjoy looking without taking on a task','“Then the warm seat is enough. I shall resist placing a useful implement in your hand.”')],
 '“We can decide from the day. A plant needing water does not mean every visitor came to provide it.”',
 '“Then I will offer company without assuming what you want to do here.”',
 '“I will draw the arrangement and leave the leaves loose. Later the shadow may be different. I want to see that as well.”',
 [('Offer to compare the drawing with the leaves later','“Yes. I want another pair of eyes when I begin claiming it was always arranged this well.”'),('Say pressing the leaves would preserve more of the original','“It would preserve the shapes better. I prefer watching this edge change. We are choosing different things to keep.”'),('Ask to enjoy the picture now before making plans','“A sensible request. This is the light I arranged it for.”')],
 ['Sylva points to a small pot beside the leaf picture. “You said you enjoy tending something. The soil is still damp underneath; today its care is leaving the water alone.”',
  'Sylva has kept the warm seat clear. “You wanted to look without a task. The curled leaf now casts its shadow across the yellow one. What do you see?”',
  'Sylva leaves a seat beside the tray. “Looking, a little tending, or simply company? I can offer all three without deciding for you.”',
  'Sylva turns the leaf picture towards the light. “The edge has moved. Would you like to see it?”'],
 '“You would have pressed the leaves. I still want the changing shadow. The drawing keeps a record of what we both saw.”',
 'Notice a small change together, with tending offered rather than assumed.'),

'velis': person('The appointment she crosses out',
 'Velis has crossed a meeting out of her diary. “We agreed the delivery yesterday. I arranged another conversation to make absolutely certain we agreed. This has become an expensive way to avoid choosing how to spend a free morning.”',
 [('Ask whether anyone is waiting for a new answer','“No. Both copies match. I would only be asking the supplier to repeat herself with better stationery.”'),
  ('Say checking can prevent a costly mistake','“It can. This particular check would confirm that I dislike an empty line in my diary. I should not charge somebody else an hour for that discovery.”'),
  ('Offer to book an appointment to discuss the empty appointment','“I shall decline in triplicate. We can spend the saved time congratulating ourselves on efficiency.”')],
 '“Would you choose an outing with stalls and people, or an evening looking at the stars away from the noise?”',
 [('I would choose the market and its company','“Then I will remember the pear stall before the invoice office. You may remind me which sort of outing we chose.”'),('I would choose a quiet evening with the stars','“Then I will bring a warm cup and leave the appointment book inside. I would like that too.”')],
 '“Weather and inclination can decide. I can offer both without booking either on your behalf.”',
 '“Then I will make a specific invitation when the time comes. You can answer that one.”',
 '“I am leaving my next free morning unplanned. I will send a short note cancelling the unnecessary meeting. The rest of the page belongs to whatever I choose.”',
 [('Support keeping the free time','“Good. I shall try to experience it without preparing an account of its benefits.”'),('Say she might miss a useful chance to talk to the supplier','“I might. I can write a personal letter instead of inventing business. I would rather ask about her family than inspect the same figures again.”'),('Ask her to choose something enjoyable now','“A pear. Then a walk. A remarkably affordable answer after all that deliberation.”')],
 ['Velis has marked the pear stall on a small map. “You chose the market. This is a plan for pleasure, so I have left the supplier’s office off the route. Would you look at it with me?”',
  'Velis brings a warm cup and a sky sketch. “You chose the stars. I cannot arrange the clouds, but I can arrange a seat and leave the ledger closed.”',
  'Velis has a market sketch beside a sky chart. “Both possibilities remain. Which would you like to plan?”',
  'Velis brings a cup. “I would like company while I look at this sky chart. Interested?”'],
 '“You thought the supplier might have something worth saying. I wrote a personal question instead of scheduling another check of the accounts.”',
 'Make an invitation for pleasure without disguising it as business.'),

'rhess': person('The shelf away from the window',
 'Rhess has placed her carved bird on a shelf she cannot see from the watch window. “It is better lit here. I keep moving it back to where I can look at the road and my belongings at once. Apparently even my bird is expected to take a shift.”',
 [('Ask what she wants to see when she comes into the room','“The bird, the bent pin, something belonging to a person I knew. I would like to remember them before counting who might be on the road.”'),
  ('Say keeping the road in sight can be reassuring','“It is. It can also keep me standing after I have handed over. I want somewhere to sit where looking is a choice again.”'),
  ('Ask whether the bird has submitted a request for relief','“Repeatedly. Its expression has been misunderstood as permanent willingness.” Rhess turns the offended beak towards the room.')],
 '“When we sit together after a long day, would you like conversation, or company without having to fill the silence?”',
 [('I would like to talk','“Then I will bring a story with an ending instead of a watch report. The crow has been generous with material.”'),('I would enjoy quiet company','“Then we can sit without pretending we have run out of things to say. I would like to try that.”')],
 '“I can ask when you arrive. A long day can change the answer.”',
 '“Then I will offer a seat and let you decide what to share. You need not explain the choice.”',
 '“The bird stays here. I can hand over the watch and cross the room to my own chair. It is a small distance I have made unnecessarily difficult.”',
 [('Offer to sit by the new shelf','“Yes. You will have to endure the bird looking critical. It has survived worse company than ours.”'),('Say she need not avoid the window to enjoy time off','“Perhaps later. At present I find the different seat helps. I want to use the help rather than prove I do not need it.”'),('Ask which keepsake should go beside the bird','“The bent pin. It is less judgemental, though only because it has no face.”')],
 ['Rhess has two chairs by the shelf. “You wanted conversation. The crow watched me tie a new lamp cord, then stole the knot as well. I have accidentally been training an expert.”',
  'Rhess has left a chair beside hers. “You preferred quiet company. I have tea and nothing you need to answer. Would you sit?”',
  'Rhess offers the chair by the shelf. “A story or a quiet cup? We can choose after you sit down.”',
  'Rhess gestures to the chair. “Would you like some company? The bird has been disappointingly silent about its day.”'],
 '“You thought the window could remain part of my evening. I am still using the other chair. It helps me stop checking.”',
 'Share a seat after the watch, with conversation or quiet chosen at the time.'),
}

# Follow-ups contain a new event, not just a reminder of the first conversation.
# Each has three ways into the activity, then a real choice about repeating it.
FOLLOWUP = {
'mira': (
 [('Ask her to read the passage she is defending','Mira reads: “He took the old lead from its hook. The dog rose. His wife did not.” She looks up. “He has returned. Forgiveness remains her decision. That is why I defend it.”'),
  ('Ask what the unhappy ending gets right','“Neither wants the ugly bowl. Each thinks the other must want it, because they bought it together. Eventually she asks. They laugh, and still separate. Affection survives; their marriage does not.”'),
  ('Ask which sentence she would cut','“He says their love is an unconquered kingdom. After behaving like an unreliable tenant for most of the book.” Mira puts her finger over the sentence. “A measurable improvement.”')],
 '“Would you like to make this a habit? One passage, and neither reader required to surrender an opinion.”',
 ('Yes—bring another passage when we have time','“I shall choose one with a defensible sentence and an indefensible hat. We ought to vary the prosecution.”'),
 ('I enjoyed this reading; leave the next one open','“Certainly. The books will remain available without enrolling you in a debating society.”')),
'tamsin': (
 [('Ask the kettle what it wants','Tamsin cups her hands like a spout. “Recognition, a dry shelf, and for somebody else to be full of hot water for once.” She drops the voice. “You get four more questions. The kettle is counting.”'),
  ('Ask about the book she brought','“A traveller tries to leave a town where every street bears his name. He has just asked directions and been told to turn left at himself. I would have thrown the map away.”'),
  ('Ask how she kept the larger repair from taking over','“I wrote down what I had agreed to mend. When I noticed another stitch, I added it to the later appointment instead of taking the book apart. Then I put the needle away where sitting down could win.”')],
 '“Shall we keep an occasional evening for this? We can choose books or counters when we sit down.”',
 ('Yes—keep an evening for books or a game','“Then the chair belongs to a person before it belongs to a pile of repairs. I would like that.”'),
 ('Let us enjoy tonight without making a standing plan','“Tonight is a perfectly good size. The kettle has made no plans beyond its next complaint.”')),
'iona': (
 [('Ask to hear the completed tune','Iona taps three quick beats, pauses, then hums a falling pair of notes. “That is the ending. I kept trying to make it climb. No wonder it sounded as though it had missed a stair.”'),
  ('Ask to compare the route before deciding on a walk','“Straight across the courtyard for the short walk. The stairwell adds one turn and a flight back down. I can offer either without quietly attaching the other.” She marks both with separate arrows.'),
  ('Try the deliberately awful ending again','You supply the emphatic thump. Iona winces, then repeats it. “Unfortunately memorable. We have made a second version, and I fear the worse one will survive.”')],
 '“Another tune and a route sketch next time? We can decide which, if either, deserves a walk.”',
 ('Yes—bring both, and we will choose then','“Good. A suggestion with an actual turning point. I shall endeavour not to name it a formal expedition.”'),
 ('Leave another walk undecided for now','“Agreed. We have finished the tune, which was the part bothering me today.”')),
'aurelia': (
 [('Ask to compare the two seats','Aurelia opens a book under the lamp, then turns it towards the window. “Here I can read the small letters. There I can follow the outline of the trees outside. Moving the chair is simpler than making one seat do both jobs.”'),
  ('Ask what she hopes to see in the sky','“The first few stars before the rest appear. I like that short interval when I can count them without immediately losing my place.” She leaves the book closed.'),
  ('Suggest the lamp has been working too hard to impress her','“It has been promoted beyond its competence. It will return to illuminating pages.” Aurelia adjusts the shade. “I sympathise with the mistake.”')],
 '“Shall we choose between a page and the window again sometime, once we know what we actually want to do?”',
 ('Yes—ask me when you next want company','“I will. Two seats, a clear question, and no obligation to admire my lamp arrangement.”'),
 ('Enjoy this evening without planning another','“Gladly. There is a star I have already lost count of.”')),
'neris': (
 [('Ask what changed in the handle','“The inside curve is wider here, where the knuckle rests. I kept the outer line nearly the same. I was treating a cramped finger as the price of a pretty silhouette. That was poor design.”'),
  ('Ask about the blue edge','“A narrow blue band makes the clear body look brighter. Cover the whole drawing in blue and the handle disappears against it. I want you to see the shape I worked so hard to rescue.”'),
  ('Say you still prefer the original outline','“So do I, on paper. That is why it became the vase drawing. I can be fond of a line without asking every object to use it.” She places the two sketches apart.')],
 '“Would you like to compare another design with me sometime? You may criticise it before I become excessively attached.”',
 ('Yes—show me the next design while it can still change','“Then I will bring the rough drawing. The handsome finished version is much better at winning an argument it has not earned.”'),
 ('Leave future comparisons open','“Of course. This one already has a better handle for being discussed.”')),
'sabine': (
 [('Accept the tea and ask for the ordinary version','“Tea, if you would like it. There is a chair.” Sabine pushes the card aside. “I can manage a whole invitation without a herald. I may need a biscuit afterwards.”'),
  ('Ask what happened to the absent trumpet','“A dispute over billing. The kettle insisted on top position, citing its indispensable contribution. I refused to mediate an argument between objects before my first cup.”'),
  ('Say the wording should depend on who receives it','“Yes. If the joke makes someone wonder whether they are welcome, it has failed at its only useful task. I can save the ridiculous title for someone who enjoys it.”')],
 '“Another invitation sometime? I can keep the question clear and choose the decoration with the recipient in mind.”',
 ('Yes—invite me again when you want company','“Then you will know the time before you meet any imaginary officials. A modest but durable promise.”'),
 ('Let this invitation be enough for now','“Entirely acceptable. An invitation is not a subscription.”')),
'koharu': (
 [('Compare the two birds’ expressions','“The straight one looks alert. This one looks personally wronged.” Koharu turns the original towards its sketch. “I have proved symmetry can survive the eyebrows. I have not proved it is funnier.”'),
  ('Ask how she would make the next wing match','“Mark both tips from the same line before carving either. I judged the first by eye, then trusted the mistake while measuring the second. It was a very orderly way to be wrong.”'),
  ('Defend the bird against the coat-hook accusation','“Thank you. It has neither the strength nor the temperament for coats.” She turns it towards the room. “It may now resume disapproving of the furniture.”')],
 '“Would you look at the next small carving while it is still a sketch? I could use an opinion before giving it a permanent expression.”',
 ('Yes—show me the sketch first','“Good. Easier to move a pencil line than explain why every bird I carve looks furious.”'),
 ('Leave the next carving for another occasion','“Fair. This one has received enough attention to become unbearable.”')),
'zahra': (
 [('Hear the pause and the resolved ending again','Zahra taps the same three notes twice. The first time she lets the silence last; the second she adds a lower fourth note. “The fourth settles it. The gap makes me want the beginning again. I still choose the gap.”'),
  ('Ask how she would make the pause repeat reliably','“Leave that space without a pin on the cylinder. The wheel keeps turning; nothing strikes. Silence needs room in the mechanism just as much as a note does.”'),
  ('Ask whether the fourth note accepted its new job','“It has agreed to occasional work in the alternative ending. Very sensible terms. I ought to negotiate so well.” She gives it one emphatic tap.')],
 '“Will you hear another version once I have something different to show? I do not want to make you praise the same three notes forever.”',
 ('Yes—bring it when there is a new change to hear','“Then I will tell you what changed after you have had a chance to notice. I want the answer, not an examination pass.”'),
 ('Let these versions stand for now','“Good enough. I know which I want to keep; that was the difficult part.”')),
'fenna': (
 [('Ask how the imaginary duke’s mistake ends','“He announces that wearing bread is an ancient family custom. The cook asks which ancient relative will pay for it. He buys the rolls and spends the ceremony feeding crumbs to pigeons. They are his most enthusiastic audience.”'),
  ('Ask what happened after the turnip farmer offered directions','“I asked him to describe my actual guide. He said, ‘Wet coat, no turnips.’ That narrowed it down considerably. I found the bridge and carried the turnip all day because refusing it seemed ruder than being lost.”'),
  ('Ask how she decides whose embarrassment is hers to tell','“Mine is the easy case. With someone else’s, I ask whether they would recognise the story and whether they gave me permission. Changing a name does not answer either question.”')],
 '“Another story sometime? I will tell you whether it is true before asking you to believe the improbable part.”',
 ('Yes—keep that distinction when we trade stories','“Gladly. The duke may acquire a horse with better judgement. My actual journeys will have to manage without one.”'),
 ('Keep these two stories without promising another evening','“Done. Two ridiculous hats would be excessive in one sitting anyway.”')),
'kaede': (
 [('Ask to see the move that beat her','Kaede sets up the position. “I put both guards in the centre. This piece went along the edge, and I had no move left to stop it.” She demonstrates the path. “I wanted you to admire the defence. I should have inspected what it left open.”'),
  ('Ask to try a move without turning it into a full match','“One position, then. We can compare your route with the edge move.” Kaede waits for you to point before moving any pieces. “I can be curious about an answer without recording a winner.”'),
  ('Ask whether her pride survived waiting','“Bruised, active, making suggestions. I congratulated the move. I still intend to beat it. Those feelings have agreed to share the board.”')],
 '“Another game sometime, with the rules and the mood agreed before the first move?”',
 ('Yes—ask what kind of game we want first','“Agreed. If I want a serious contest, I will say so. You can offer something else without being accused of fearing my brilliant opening.”'),
 ('Leave another game open for now','“Fair. I can study this position without conscripting an opponent.”')),
'elowen': (
 [('Keep the conversation on the flower colours','“Yellow at the centre, blue near the rim. Too much blue and the yellow looks stranded. I have spent longer considering this than several useful decisions, and I am enjoying myself.”'),
  ('Ask her to listen while you decide what to discuss','Elowen puts the sketch down. “Take your time. You can begin wherever the day became difficult, or decide you would rather look at flowers.” She leaves the next words to you.'),
  ('Ask how she chose one practical next step','“I checked whether the herb was actually needed. It was not. That removed an imaginary obligation and left a real choice. For another problem, I would ask what one part we could actually change.”')],
 '“Would you like me to keep asking what kind of company you want, instead of assuming every visit needs advice?”',
 ('Yes—ask before offering advice','“I will. And when I bring a flower sketch, you may assume I would also enjoy discussing flowers.”'),
  ('Decide what we need each time without a standing arrangement','“Certainly. We can ask a small question when there is a real occasion.”')),
'nyssara': (
 [('Try the short instruction on the diagram','You trace the return to the outside branch. Nyssara watches without reaching for the pencil. “That is the intended route. One sentence has survived contact with a reader. I am cautiously pleased.”'),
  ('Ask which condition she kept in the short version','“Follow the outside branch only when it carries the return. I added that condition above the drawing. A short instruction that is wrong in the next example is an efficient way to create a larger problem.”'),
  ('Ask what remains in the longer explanation','“Why this branch carries the return, and how to identify it in a differently arranged pattern. The history goes last. Its author has recovered from the demotion.”')],
 '“Would you try another explanation when I have one? You may ask for one sentence or the entire argument.”',
 ('Yes—let me choose the level of detail','“Good. I will ask before delivering the argument. You may interrupt if I forget to leave a place for questions.”'),
 ('Leave another lesson unplanned','“Agreed. This page has already become more useful.”')),
'sylva': (
 [('Compare the leaf with the drawing','“The earlier outline ends here. The leaf now bends far enough to hide part of the yellow one.” Sylva moves a finger beside the shadow without touching the leaf. “I would have drawn a different picture today.”'),
  ('Ask how she knows the pot does not need water','“The surface is pale, but the soil just underneath still clings together. More water now would keep the roots wet. Looking carefully can be the whole task.”'),
  ('Ask whether the badly mannered leaf has apologised','“No. It has promoted itself to the foreground.” Sylva turns the tray. “I am beginning to think it understood the light better than I did.”')],
 '“Shall we look again when something has changed? A new leaf or a different shadow is enough reason for a visit.”',
 ('Yes—show me a change when you notice one','“I will. I can tell you whether anything needs tending before you choose to help.”'),
 ('Enjoy this arrangement without promising another visit','“Then this is the version we have seen together. I am glad you caught the shadow.”')),
'velis': (
 [('Look at the market route with her','“Pear stall here, cloth colours here, and this corner has a good view of people pretending not to haggle.” Velis folds the business address underneath. “We may buy nothing. I want to remember that looking is possible.”'),
  ('Ask what she notices on the sky chart','“How little it resembles an appointment book. The marks show where to look, not how long I am permitted to enjoy it.” She finds a cluster near the edge. “I would like to recognise these without consulting the page every time.”'),
  ('Ask whether leaving the diary empty felt strange','“Yes. I reached for it twice. The second time I wrote ‘pear’ in the margin and closed it. I refuse to invoice the fruit for teaching me perspective.”')],
 '“Another invitation for pleasure sometime, with the activity stated honestly?”',
 ('Yes—invite me without finding a business reason','“Then I will ask for your company. A refreshingly short proposal.”'),
 ('Keep the next free evening unplanned','“Agreed. I will resist making an appointment to preserve it.”')),
'rhess': (
 [('Ask how the crow stole the knot','“It waited until I left the loose end hanging, pulled it through, and carried the whole cord off. I tied a shorter end next time. The crow watched with the expression of a tradesperson inspecting inferior work.”'),
  ('Sit quietly with her by the shelf','Rhess settles into her chair. She drinks before the cup cools, looks once at the bird, and leaves the watch window alone. After a while she nudges the spare cup within your reach.'),
  ('Ask about the bent pin beside the bird','“A cloak fastening. I bent it freeing a traveller from a thorn hedge after she insisted she knew a shorter path. She laughed first. I kept the pin because I like remembering that part of the journey.”')],
 '“Would you sit here again sometime? We can ask whether it is a talking evening when you arrive.”',
 ('Yes—keep me a place when you want company','“I will ask. The bird will probably object, but it has yet to offer useful grounds.”'),
 ('Enjoy this evening and leave another visit open','“Fair enough.” Rhess lifts her cup. “This one has been a good evening.”')),
}

def pair(people, title, nodes, later_title, later_nodes):
    return dict(people=people, title=title, nodes=nodes,
                laterTitle=later_title, laterNodes=later_nodes)

# The residents speak to each other, keep their own decisions and may still
# disagree. The player can question, participate or listen without arbitrating.
PAIRS = {
'mira:nyssara': pair(['mira','nyssara'], 'The note and the missing example', [
 ('Mira taps Nyssara’s margin note. “This tells me what is wrong. It does not show me how to fix it.” Nyssara answers, “The derivation is on the preceding page.” “Then the note should say so. I cannot hear you pointing from inside a book.”', [
  ('Ask Nyssara what she expected the reader to know','“That they had read the preceding page,” Nyssara says. Mira opens the book in the middle. “I came here looking for this example.” Nyssara considers that. “A reasonable use I made unnecessarily awkward.”'),
  ('Ask Mira what would make the note useful','“A corrected line, then the page number,” Mira says. “I may want the reasoning afterwards.” Nyssara nods. “I can supply both without copying the whole argument.”'),
  ('Listen while they inspect the page','Mira follows the incorrect line with her finger. Nyssara turns back a page, then stops. “Yes. You should not need me here to find that.” She brings the pages together.')]),
 ('Nyssara writes a corrected line and a reference. Mira says, “Now remove ‘obviously’.” Nyssara raises an eyebrow. “It is obvious from the example.” “Then the example can do the work without insulting its reader.”', [
  ('Ask what “obviously” contributes','Nyssara looks at the sentence. “My impatience, principally.” She crosses out the word. Mira says, “An unusually economical edit.”'),
  ('Say an advanced reader might appreciate a shorter note','“Then they can stop after the corrected line,” Mira says. Nyssara adds, “And the reference preserves the depth. That is the part I will not remove.”'),
  ('Ask them to keep both a quick answer and a reference','“That is my preference,” Nyssara says. Mira smiles. “We have reached agreement on a page with two different readers in mind.”')]),
 ('Mira wants to test the note without Nyssara explaining over her shoulder. Nyssara agrees, then draws her hand away from the page. “I will be elsewhere. Within reasonable distance of a complaint.”', [
  ('Ask to hear whether the example works later','“We will bring the failed step, if there is one,” Mira says. Nyssara adds, “And an actual correction. We have enough opinions about the word obvious.”'),
  ('Leave the test between them','Mira turns the page back. “Good. I want to try it before discussing it again.” Nyssara stands. “I shall practise being absent from my own explanation.”')])],
 'The example gets its own answer', [
 ('Mira has followed the revised example. “The corrected line works. The page reference was wrong.” Nyssara takes the note. “A fine demonstration of why I should also test the parts I consider beneath testing.”', [
  ('Ask what the reference should point to','“The second example, not the first,” Nyssara says. “The first reverses the branch.” Mira has already written the new page number on a scrap beside it.'),
  ('Ask Mira whether the shorter note was enough','“For this case, yes. Then I read the derivation because I wanted to know why.” Nyssara looks pleased. “A considerably better reason than being unable to proceed.”'),
  ('Let them finish the correction together','Nyssara changes the reference. Mira checks the number against the book before handing it back. “Now I can complain about the argument itself.” “Excellent,” Nyssara says.')]),
 ('Nyssara asks Mira to check the next example when it is ready. Mira answers, “If you also read my introduction and tell me where you stop caring.” They have arranged an exchange of criticism themselves.', [
  ('Ask to see the next corrected example','“Once we have checked the page numbers,” Mira says. Nyssara adds, “You may hold us to that humiliatingly practical condition.”'),
  ('Wish them a useful exchange and leave them to it','“Useful may include irritating,” Mira says. “I can tolerate that,” Nyssara replies, “provided the irritation includes a correction.”')])]),
'tamsin:zahra': pair(['tamsin','zahra'], 'A pause in the guessing game', [
 ('Tamsin shakes a bag of counters. “Five questions. You are guessing an object.” Zahra taps a rhythm on the table. “Can the object make a sound?” “It can. You have used one question to make my kettle extremely pleased with itself.”', [
  ('Ask whether the kettle is supposed to be secret','Tamsin freezes. Zahra stops tapping. “I was going to guess a hammer.” Tamsin puts a counter back. “A revised first round is now required.”'),
  ('Suggest Zahra choose the next secret object','“All right,” Zahra says. “It is small and takes longer to make than people think.” Tamsin laughs. “You have described everything on your bench.”'),
  ('Listen to them negotiate a new first round','Zahra asks whether Tamsin can be a less talkative object. “A sealed jar,” Tamsin offers. “It contains opinions.” Zahra says, “Then it will not stay sealed.”')]),
 ('Zahra wants time to think before answering. Tamsin likes the quick mistakes. “Those are the funny part,” Tamsin says. Zahra answers, “They are also the part that makes me feel as though I am being examined.”', [
  ('Ask what would keep it a game for both of them','“No counting down,” Zahra says. Tamsin considers it. “Then I can be dramatic about my own answers, and leave yours alone.”'),
  ('Say they may prefer different kinds of rounds','“We do,” Tamsin says. “I can enjoy a slower one without pretending it is my favourite.” Zahra smiles. “And I can laugh at your kettle without wanting to perform it.”'),
  ('Let Zahra explain what she needs','“A pause is not a failed answer,” Zahra says. Tamsin puts the counters down. “Fair. I have been filling it because I like hearing the next thing.”')]),
 ('Tamsin offers another round without a timer. Zahra agrees. “You may provide one extremely impatient kettle between rounds.” “It will be honoured,” Tamsin says.', [
  ('Join as another guesser','“Then one question each,” Zahra says. Tamsin holds up the bag. “And nobody is allowed to name the answer while explaining the rules. I have been informed this spoils the game.”'),
  ('Leave them to try their new arrangement','Zahra takes a counter and thinks. Tamsin waits, then mouths an extravagant yawn only after Zahra starts laughing. “Between rounds,” Zahra reminds her.')])],
 'The quiet answer wins a round', [
 ('Zahra has chosen a music box as her secret object. Tamsin guesses a lock, a clock, and a very elaborate beetle. Zahra finally says, “It plays.” Tamsin points at the bag. “I should have listened to the silence instead of inventing legs.”', [
  ('Ask whether the slower round worked','“Yes,” Zahra says. “I got to enjoy the wrong guesses before answering.” Tamsin adds, “I enjoyed the beetle. We may have found a workable pace.”'),
  ('Defend the elaborate beetle','“It was a magnificent beetle,” Tamsin says. Zahra taps four tiny steps. “I could almost hear it. That does not make it the answer.”'),
  ('Ask for one more clue before another guess','Zahra thinks, then taps three notes. Tamsin waits until the pause ends. “A box with a very particular opinion about the fourth note.”')]),
 ('Tamsin puts the counters away herself. “Another evening, same pace?” Zahra nods. “And perhaps a different kettle.” “I cannot promise staffing changes,” Tamsin says.', [
  ('Ask to join another round when they invite you','“You will be welcome,” Zahra says. Tamsin adds, “No practice examination. Just a bag of counters and occasionally an object with grievances.”'),
  ('Let the game remain something they arrange together','“We will,” Tamsin says. Zahra takes the empty cups. “She chooses the ridiculous voice. I get time to answer. It is a fair arrangement.”')])]),
'iona:rhess': pair(['iona','rhess'], 'The route with an extra turn', [
 ('Iona has marked a pleasant detour on a route sketch. Rhess marks the return before dark. “I want both on the page,” Rhess says. Iona answers, “So do I. I object to the detour being treated as a navigational failure.”', [
  ('Ask Iona what makes the extra turn worth taking','“You can hear the water below the old steps,” Iona says. “I want to stop and listen.” Rhess nods. “Then call it a stop. I can plan for one.”'),
  ('Ask Rhess what would make the return clear','“A point where we choose to turn back,” Rhess says. Iona draws a line at the steps. “Here. We can decide while we still have the short way home.”'),
  ('Listen while they compare the sketch','Iona traces the longer route; Rhess measures the return with her finger. “I do want to see it,” Rhess says. “I also want to stop calculating whether we have stayed too long.”')]),
 ('Iona proposes deciding at the steps. Rhess wants to agree a latest return as well. “I would rather have one limit than keep asking,” Rhess says. Iona answers, “One limit. Not an inspection at every corner.”', [
  ('Ask whether they can name one limit now','“Turn back when the courtyard bell sounds,” Rhess says. Iona nods. “And until then, we may actually listen to the water.”'),
  ('Say the longer route can remain optional','“It will,” Iona says. Rhess adds, “And I can choose the shorter one without being accused of disliking the view.”'),
  ('Ask them what they each want from the walk','“Something I have not noticed before,” Iona says. “An hour when I am not on watch,” Rhess replies. Iona looks at the return line. “Then that belongs on the same page.”')]),
 ('They leave the walk as an invitation, with the return marked. Rhess says, “I shall bring a cup if we go.” Iona grins. “A major concession to standing somewhere without a task.”', [
  ('Ask to compare their impressions after they try it','“I will tell you what we heard,” Iona says. Rhess adds, “I will try to tell you something besides the time we returned.”'),
  ('Leave them to choose their own afternoon','Rhess folds the sketch. “We can arrange that.” Iona says, “And if it rains, we may discover the extraordinary convenience of a roof.”')])],
 'A view from the courtyard', [
 ('Iona and Rhess have been listening from the courtyard instead. “The water carried this far today,” Iona says. Rhess lifts her cup. “So we stayed here. I enjoyed being able to put the route sketch away.”', [
  ('Ask what they heard','“Two sounds,” Iona says. “A low rush, then a sharper splash when the flow struck the step.” Rhess adds, “And Iona trying to give them both a tune.”'),
  ('Ask whether changing the plan caused trouble','“We agreed before leaving,” Rhess says. Iona adds, “Neither of us needed the long route to justify wanting company.”'),
  ('Tease them about discovering the courtyard','“An overlooked expedition,” Iona says. “Excellent access to chairs.” Rhess adds, “And nobody needed rescuing from an interesting corner.”')]),
 ('Rhess keeps the route sketch for another day. Iona leaves the return line exactly where it is. Their preferences have not become identical; they have found a way to choose a walk together.', [
  ('Ask them to invite you when they want a third walker','“We will name the route,” Rhess says. “And the optional turn,” Iona adds. They exchange an amused look over the sketch.'),
  ('Let them keep planning their walks together','“We intend to,” Iona says. Rhess puts her cup down. “It is a pleasant disagreement when both routes lead home.”')])]),
'aurelia:sylva': pair(['aurelia','sylva'], 'Who gets the window light?', [
 ('Aurelia has turned a reading chair towards the window. Sylva has moved a leaf tray into the same light. “The shadow changes here,” Sylva says. Aurelia answers, “So does my ability to read the small print.”', [
  ('Ask how much space the tray needs','Sylva spreads her fingers beside it. “This much. I do not need the chair.” Aurelia looks at the low stool. “Then perhaps we have been moving the wrong thing.”'),
  ('Ask when Aurelia wants to read there','“While the light reaches the page without glare,” Aurelia says. Sylva points to the tray’s edge. “That is also when I want to look. A timetable would not help much.”'),
  ('Watch them try the stool beside the chair','Sylva places the tray on the stool. Aurelia sits, opens her book, and shifts one elbow. “I can read.” Sylva crouches beside the leaves. “And I can see the shadow.”')]),
 ('Aurelia wants the stool kept clear for the tray. Sylva hesitates. “Someone else may want to sit.” Aurelia answers, “Then we should ask instead of treating a convenient arrangement as a permanent claim.”', [
  ('Ask how they will leave room for someone else','“Tray back on the table after looking,” Sylva says. Aurelia closes her book. “And no book left in the chair to reserve a person-shaped space.”'),
  ('Say a regular place could still be useful','“Yes,” Aurelia says. “A usual place, not an exclusive one.” Sylva nods. “That lets us ask without acting as though we have been evicted.”'),
  ('Let them settle the shared space','Sylva draws the stool back a little. Aurelia tests the light again. “Here,” Aurelia says. “Both fit, and the path stays clear.”')]),
 ('They decide to use the window together when they both want it, then put their things away. Sylva says, “You may tell me if a leaf reaches your book.” Aurelia smiles. “I shall review its contribution.”', [
  ('Ask to see the arrangement another day','“Bring a page if you like,” Aurelia says. Sylva adds, “Or just look. I have enough leaves without assigning everyone one.”'),
  ('Leave them to enjoy the light','Aurelia returns to her page. Sylva turns the tray a fraction. For a while neither needs the other to move.')])],
 'A leaf enters the margin', [
 ('A curled leaf has dropped onto Aurelia’s open page. She holds it up. “Your contributor has arrived.” Sylva examines it. “It has chosen the margin. Better manners than I expected.”', [
  ('Ask whether the shared window is working','“Yes,” Aurelia says. “We put the tray away when we finish.” Sylva adds, “I get to see the shadow without defending a stool all afternoon.”'),
  ('Ask Aurelia for her review of the leaf','“Concise. Uneven structure. Strong colour.” Sylva takes it back. “It will be devastated by the middle point.”'),
  ('Ask what changed in the leaf picture','“The gap it left,” Sylva says. “Now the light reaches the yellow leaf beneath it.” Aurelia looks over. “That part is easier to see from here too.”')]),
 ('Sylva returns the fallen leaf to the tray. Aurelia asks to see the next arrangement before she opens her book. They have begun noticing what interests the other without needing to share the same hobby.', [
  ('Ask to join them when the window is free','“We can find another chair,” Aurelia says. Sylva adds, “And ask what you came to do before offering you a tray.”'),
  ('Leave the window to their two activities','Aurelia returns to the page. Sylva turns the tray towards her once, then lets her read.')])]),
'neris:kaede': pair(['neris','kaede'], 'A colour worth arguing over', [
 ('Neris holds a blue glass sample beside a clear one. Kaede prefers the darker edge. “It gives the shape an outline,” Kaede says. Neris answers, “It also hides the curve I spent all morning drawing.”', [
  ('Ask to compare them against the same background','Kaede puts both on white paper. Neris points at the blue edge. “Now you can see where it swallows the handle.” Kaede leans closer. “Yes. I was judging the colour by itself.”'),
  ('Ask Kaede what she likes about the stronger outline','“You can recognise it from across the room,” Kaede says. Neris nods. “I want to enjoy it in someone’s hand. We have chosen different distances.”'),
  ('Listen while they exchange the samples','Kaede holds the pale sample farther away. Neris lifts the dark one near the window. Each pauses before repeating her first opinion.')]),
 ('Kaede suggests a narrow dark band. Neris wants the handle left clear. “I can accept a strong rim,” Neris says. “I will not spend the curve just to make the cup louder.” Kaede smiles. “That was almost an accusation.”', [
  ('Ask them to sketch that combination','Neris draws a thin dark rim. Kaede stops her before it reaches the handle. “Here. I want the outline, not a stripe through everything.”'),
  ('Say two versions may serve different tastes','“I would keep the darker one,” Kaede says. “And I the clearer,” Neris answers. “We can compare them without declaring one of us unable to see.”'),
  ('Ask which part neither wants to give up','“The clear handle,” Neris says. “A visible rim,” Kaede replies. Neris moves the samples apart. “Those do not actually conflict.”')]),
 ('They keep two sketches. Kaede says, “I still prefer the stronger blue.” Neris answers, “I know. That is why I wanted you to look before I called mine finished.”', [
  ('Ask to see the next comparison','“In the same light,” Kaede says. Neris adds, “And against the same paper. We have discovered the scandalous advantage of a fair comparison.”'),
  ('Leave them to develop their own versions','Neris labels the sketches by colour rather than winner. Kaede notices and laughs. “I deserved that.”')])],
 'The same blue in different light', [
 ('Neris and Kaede have placed their sketches near the window. “The dark rim looks almost black here,” Kaede says. Neris turns it towards the lamp. “And blue here. We were also disagreeing about where we imagined using it.”', [
  ('Ask whether either has changed her preference','“I want a slightly lighter blue,” Kaede says. “Still stronger than hers.” Neris smiles. “A revision I can recognise without claiming victory.”'),
  ('Ask what the comparison taught Neris','“To show the intended light with the design,” Neris says. “A colour name leaves out half the experience.” Kaede adds, “And to let someone move the sample.”'),
  ('Ask them to keep both versions on the page','Neris places the drawings side by side. Kaede writes “window” and “lamp” below them. “Now the labels tell us something useful.”')]),
 ('Kaede asks Neris to look at a future glass colour she is considering. Neris agrees on condition that she may move it between the window and the lamp. “You would have done that anyway,” Kaede says.', [
  ('Ask to be included when there is a new comparison','“Bring an opinion,” Neris says. Kaede adds, “Preferably one you will let the light interfere with.”'),
  ('Let them exchange opinions directly','“Gladly,” Neris says. Kaede returns the blue sample. “I enjoy an argument where we both end up seeing more.”')])]),
'sabine:velis': pair(['sabine','velis'], 'The invitation and the account book', [
 ('Sabine proposes a tea gathering with a ridiculous title. Velis asks how many cups. “You have gone straight to an inventory,” Sabine says. Velis answers, “Someone always discovers the missing cup after the guests arrive.”', [
  ('Ask what each wants to settle first','“Whether anyone would enjoy coming,” Sabine says. “Whether we can host the number invited,” Velis replies. Sabine considers that. “A small invitation answers both more easily.”'),
  ('Ask Sabine to say the invitation plainly','“Tea at four, for a few people who want company,” Sabine says. Velis closes the ledger. “That I can help with. I was preparing for your title to require a procession.”'),
  ('Ask Velis what would keep planning small','“Use the cups already here. Ask before assuming anyone will help,” Velis says. Sabine nods. “And nobody writes a budget for my trumpet drawing.”')]),
 ('Velis offers to check the cups once. Sabine offers to write a clear invitation with a foolish title beneath it. “Once,” Sabine repeats. “I heard you,” Velis says. “The cups will not need a second interview.”', [
  ('Ask whether either wants to host alone','“No,” Sabine says. “I want her company too.” Velis looks up from the table. “Then put my seat in the plan before giving me another task.”'),
  ('Say the title still sounds too elaborate','“Then the first line will serve you,” Sabine says. Velis adds, “I will judge the title after I know where to sit.”'),
  ('Listen while they divide what they actually want to do','Sabine takes the paper; Velis counts the cups and stops. Sabine leaves a chair for her. “There,” Velis says. “That is a plan with an ending.”')]),
 ('They settle on a small invitation and seats for both hosts. Sabine says, “The ceremony may be shortened.” Velis answers, “I will support any ceremony that ends before the tea cools.”', [
  ('Ask how the invitation turns out later','“You will see the clear time before the foolish title,” Sabine says. Velis adds, “And I will be sitting down when you arrive.”'),
  ('Leave the gathering for them to arrange','“We can manage it,” Velis says. Sabine draws one tiny trumpet. “The planning committee has adjourned before becoming permanent.”')])],
 'Two hosts sit down', [
 ('Sabine has brought the finished invitation for Velis to read. Velis has already put her cup by her chair. “Tea at four,” she reads. “Then something about distinguished steam.” Sabine bows. “The essential information survived.”', [
  ('Ask Velis if she is enjoying the invitation','“Yes. I know when it is, and I am not being asked to certify the steam,” Velis says. Sabine adds, “An exacting standard, generously met.”'),
  ('Ask whether they need any more planning','“No,” they say together. Velis laughs first. Sabine folds the invitation and puts it beside the cup.'),
  ('Ask Sabine why she kept the silly title','“Because it makes me want to be there,” Sabine says. “The clear time makes it possible for someone else to join.” Velis nods. “That distinction I appreciate.”')]),
 ('Velis suggests that next time she choose the place and Sabine write the invitation. Sabine agrees, provided Velis leaves herself a seat. They are making the next decision between them.', [
  ('Ask for an invitation if they arrange another gathering','“You will get an actual question,” Sabine says. Velis adds, “With the place and time. We have developed a fondness for those details.”'),
  ('Let them keep their new arrangement','“I shall choose a place with sufficient chairs,” Velis says. Sabine smiles. “And I shall endeavour to distinguish the chair from an honorary office.”')])]),
'koharu:elowen': pair(['koharu','elowen'], 'The pot and its uneven stand', [
 ('Koharu has sketched a stand for Elowen’s flower pot. Elowen points to a small carved notch. “That looks like a bird.” Koharu answers, “It began as a correction. I am deciding whether to admit that before accepting the compliment.”', [
  ('Ask whether the notch affects the stand’s strength','“No,” Koharu says. “The weight rests here, well away from it.” Elowen taps the sketch. “Then I am allowed to like the bird without endangering the flowers.”'),
  ('Ask Elowen why she likes the accidental shape','“It looks curious,” Elowen says. “Everything I own need not look as though it was approved for an infirmary shelf.” Koharu adds a beak to the drawing.'),
  ('Ask whether Koharu would rather correct it','“Part of me would,” Koharu says. “Part of me is relieved somebody saw a bird before seeing the slip.” Elowen answers, “Both descriptions can be true.”')]),
 ('Koharu wants to make the feet match precisely. Elowen asks whether that will spoil the irregular shape. “The feet keep the pot upright,” Koharu says. “I can be whimsical above them. Not underneath a wet pot.”', [
  ('Ask her to show the difference on the sketch','Koharu draws a level line beneath the feet. “This must match.” She circles the bird. “This may have opinions.” Elowen laughs. “Now I know which part I am admiring.”'),
  ('Say the flower pot need not become another useful project','“I want to make it,” Koharu says. “The useful part does not cancel that.” Elowen nods. “Fair. I object to being assigned usefulness, not to enjoying it.”'),
  ('Let them work out the proportions','Elowen marks the pot’s width. Koharu moves the feet farther apart. “There. Enough space for the pot, and no reason to exile the bird.”')]),
 ('They keep the drawing as a possible design. Elowen chooses yellow beside the carved bird. Koharu says, “I would have chosen blue.” “Then you may look disapprovingly at the sketch,” Elowen replies.', [
  ('Ask to see how the colours look together later','“On paper first,” Koharu says. Elowen adds, “I am enjoying this part. We need not pretend the pot is already made.”'),
  ('Leave the colour disagreement with them','“It is a manageable disagreement,” Koharu says. Elowen adds a second yellow flower. “I am managing it very confidently.”')])],
 'A blue edge, a yellow centre', [
 ('Elowen has coloured the design yellow at the centre and blue near the rim. Koharu points at the edge. “A concession?” Elowen answers, “A colour I liked after trying it. You may be pleased without calling it a surrender.”', [
  ('Ask Koharu what she thinks of the revised drawing','“The blue makes the yellow clearer,” Koharu says. “I still might have used more of it.” Elowen smiles. “A preference successfully surviving new information.”'),
  ('Ask whether the carved bird kept its place','“Here,” Elowen says. Koharu points at the level feet below it. “And its opinions still do not affect the structure.”'),
  ('Let them enjoy the drawing without improving it','Elowen lays down the pencil. Koharu looks once more, then leaves it alone. “Yes,” she says. “I like this version.”')]),
 ('Koharu asks if she may keep a copy of the little bird. Elowen agrees. “You drew it.” “You noticed what it could be,” Koharu says. Koharu traces the beak again before copying it.', [
  ('Ask them to show you a future design if they make one','“We will bring the drawing,” Elowen says. Koharu adds, “And specify which crooked parts are intentional.”'),
  ('Leave the sketch and its credit with them','Koharu copies the bird on a spare corner. Elowen turns the flower sketch towards the light and leaves the pencil down.')])]),
'fenna:rhess': pair(['fenna','rhess'], 'The story and the person in it', [
 ('Fenna begins a roadside story about following the wrong man into a turnip field. She describes his unusual cloak. Rhess interrupts. “That might identify him.” Fenna sets the detail aside. “Then I need another way to make the mistake clear.”', [
  ('Ask which part of the story Fenna wants to tell','“That I followed the wrong person for half a mile,” Fenna says. Rhess answers, “You can tell us about your certainty. You were very certain.”'),
  ('Ask Rhess whether an unnamed version would be enough','“Not if everyone recognises the cloak,” Rhess says. Fenna nods. “A hidden name is not much privacy when I describe the only red cloak on the road.”'),
  ('Let Fenna try a version without the traveller’s details','“I followed a coat instead of checking a face,” Fenna says. Rhess waits. Fenna grins. “Yes. The foolish part survived.”')]),
 ('Fenna wants an ending that earns a laugh. Rhess points to the detail Fenna has just supplied: “You asked for the bridge while standing in a turnip field.” Fenna winces. “I was hoping you would consider that part less memorable.”', [
  ('Ask whether Fenna is comfortable being the joke','“I am, if I get to tell it,” Fenna says. Rhess nods. “That seems a useful rule for this conversation.”'),
  ('Ask Rhess what makes the story worth remembering','“You admitted the mistake and asked directions,” Rhess says. “I wanted to know how you got back before I wanted to laugh.” Fenna looks at her. “Then that part stays.”'),
  ('Ask Fenna to tell the actual ending','“The farmer gave me directions and a turnip,” Fenna says. “I brought both back.” Rhess asks, “Did you eat it?” “At supper,” Fenna says. “It was the most useful part of the detour.”')]),
 ('Fenna decides to keep her own mistake and omit the traveller. Rhess says, “You can still make it funny.” Fenna answers, “I have been provided with excellent evidence.”', [
  ('Ask to hear how the revised telling goes','“I will keep the turnip,” Fenna says. Rhess adds, “And I will ask before suggesting where the joke should fall.”'),
  ('Leave the story for them to share in their own way','Fenna tries the first sentence on Rhess, who lets her finish before offering one shorter word. They are already improving the telling together.')])],
 'The turnip gets the last word', [
 ('Fenna reads her new ending to Rhess: “I returned with directions, a turnip, and reduced confidence in identifying people by their coats.” Rhess considers it. “The turnip still deserves the last word.”', [
  ('Ask Fenna if she agrees','“Yes. ‘The turnip knew as much about the route as I did, and was better received at supper.’” Rhess laughs. “That one.”'),
  ('Ask Rhess why that ending works for her','“It ends with what happened when she came back,” Rhess says. “We had food and a story. Nobody else’s private business had to become the price of the joke.”'),
  ('Listen to both versions before commenting','Fenna reads each ending. Rhess smiles at the second before it finishes. “An unusually clear review,” Fenna says. “I shall keep that one.”')]),
 ('Rhess asks Fenna to let her check another travel story if it includes a detail that might identify someone. Fenna agrees, while keeping the right to defend a good sentence. “Naturally,” Rhess says. “I would worry if you did not.”', [
  ('Ask to hear another story once they have checked it','“You may get a better ending for the delay,” Fenna says. Rhess adds, “And fewer identifiable coats.”'),
  ('Leave the next story between them','Fenna folds the page. Rhess asks whether the turnip was really as large as described. “We still have artistic matters to discuss,” Fenna tells you.')])]),
}
