"""Personal disclosures with distinct, authored player replies.

These are desires and preferences, not completed quests or promises. Stable
curious/warm/candid keys retain their existing relationship effects. Historical
openings, player lines and replies stay in the campaign's memory records.
"""

def scene(opening, curious, warm, candid):
    return {'opening': opening, 'choices': dict(zip(('curious', 'warm', 'candid'),
            ({'label': label, 'response': response} for label, response in (curious, warm, candid))))}

# goal, value, tension: consistent directions, not a script every topic must repeat.
CHARACTER = {
'mira': ('Make neglected letters and ordinary people’s stories as easy to find as famous histories.', 'Credit the person behind an account and keep evidence that challenges her reading.', 'She can become more interested in winning an argument than hearing its answer.'),
'tamsin': ('Make repairs people can afford and understand, and keep time for games and reading of her own.', 'A person’s well-used belongings deserve careful work regardless of their price.', 'She volunteers too quickly, then resents work she has not admitted she cannot take on.'),
'iona': ('Keep routes that include shelter, music and the people worth visiting, with a home to return to.', 'Give travellers accurate information without choosing their destination for them.', 'She sometimes avoids an awkward reply by making another journey.'),
'aurelia': ('Make dependable lamps and clear handovers so care does not depend on one exhausted keeper.', 'Keep promises she has actually made and tell people plainly when a plan changes.', 'She can mistake checking again for helping, even when someone else has taken responsibility.'),
'neris': ('Make glassware people enjoy holding and looking through, including designs that are beautiful in use.', 'A lovely finish must not conceal a fault from the person using it.', 'She can polish her favourite feature while overlooking the part that makes the object work.'),
'sabine': ('Make difficult agreements understandable and write invitations people are pleased to receive.', 'People should know what they are agreeing to and be free to refuse.', 'Her pleasure in a clever line can outrun her attention to the person hearing it.'),
'koharu': ('Build a travelling puppet stage its performers can repair, and make people laugh without making anyone the victim.', 'Keep promises to performers and preserve what an owner values; a harmless surprise should amuse its recipient too.', 'She can start redesigning something before asking whether anyone wants it changed.'),
'zahra': ('Make well-fitted equipment and delicate mechanisms with precise ember work; build a music box with a tune she would choose herself.', 'Judge work by how it serves the person using it, including its least conspicuous parts.', 'She enjoys a loud story but can use it to avoid showing careful work she cares about more.'),
'fenna': ('Keep routes and stories that help strangers find a welcome, and stay long enough to hear other people’s stories.', 'Protect a confidence and give credit to the people who make a road welcoming.', 'She can use a joke to dodge a question when she worries the answer will disappoint someone.'),
'kaede': ('Become a more adaptable teacher and competitor while returning to coloured glasswork for pleasure.', 'Win honestly, explain a method clearly, and acknowledge the person who outplayed her.', 'She can turn an enjoyable game into unsolicited instruction or refuse it to avoid looking inexperienced.'),
'elowen': ('Help people understand their own care and household wards, and grow flowers she chooses for their colour and scent.', 'Listen to the request before deciding what another person needs.', 'She reaches for a remedy when somebody wants to complain, and struggles with problems she cannot fix.'),
'nyssara': ('Write examples apprentices can question and verify without depending on a master’s reputation.', 'Keep credit, evidence and warnings specific; a maker’s ancestry does not establish whether her work is sound.', 'She can answer an imprecise question so sharply that the questioner stops asking.'),
'sylva': ('Keep healthy parent plants, share cuttings responsibly and collect colours from fallen leaves.', 'Find out what a plant needs before deciding what to take from it.', 'She can leave her preferences unstated and then be irritated when others fail to infer them.'),
'velis': ('Arrange dependable supplies without passing a supplier’s mistakes to the least powerful worker; make time for stargazing and letters.', 'A profitable agreement is a poor one if the person carrying its cost never agreed to it.', 'She can turn a personal invitation into a negotiation or fill a free morning with unnecessary business.'),
'rhess': ('Build a watch with real relief and preserve the small keepsakes that remind her who she has known.', 'Keep people informed, share responsibility and return when she says she will.', 'She can take over another person’s shift rather than admit she is worried about handing it over.'),
}

FAMILIAR = {
'mira': scene('Mira lays an old catalogue card beside a blank one. “Someone saved the title and omitted the woman who copied the book. I want an archive where finding her does not require an argument with the catalogue.”',
 ('Ask how she would find an overlooked copyist', '“Start with the colophon, then compare the hand with signed letters. If I cannot identify her, write that down. ‘Unknown’ is honest. Leaving her out suggests nobody did the work.”'),
 ('Ask what she would put in a collection of her own', '“Letters, marginal arguments, and one truly dreadful poem so visitors do not become overawed.” Mira smiles. “My first collection was discarded catalogue cards. I liked finding out which books people had stopped looking for.”'),
 ('Ask what she does when evidence contradicts a favourite reading', '“Check it, object to it privately, then change the entry.” Mira taps the blank card. “I am quite capable of making the objection last too long. Ask me which part I can actually prove.”')),
'tamsin': scene('Tamsin turns a worn cover in her left hand. “I like the books people cannot bear to replace. I would rather make a repair they can afford than persuade them the damage is fashionable.”',
 ('Ask what makes a repair worth keeping', '“It opens properly, protects the pages, and can be mended again. Gold on the spine is a separate question.” Tamsin runs her thumb along the seam. “I learnt a great deal from bad repairs. They make their objections very clear.”'),
 ('Ask what she wants to do when the work is finished', '“Honey tea, my own book, and a guessing game I have a chance of winning. I enjoy feeding people. I would also like an evening where nobody remembers me primarily for the soup.”'),
 ('Ask how she decides when to turn down another job', '“Too late, usually. I say yes because I know how to help, then discover that I have promised the same hour twice.” She puts the cover down. “I am trying to check the hour before offering it.”')),
'iona': scene('Iona opens a map dotted with music halls and sheltered benches. “A route ought to tell you where you can stop as well as how quickly you can leave. I want to keep making this kind.”',
 ('Ask why she began marking places with music', '“I was tired of arriving somewhere and knowing the bridges better than the people. My colleagues mocked the map until it rained. Then everyone wanted the hall with a dry floor and a good fiddle.”'),
 ('Ask what makes her want to return to a place', '“An unanswered conversation. A musician I want to hear again. Someone who remembers that I prefer apple cordial.” Iona taps an unmarked margin. “I can measure a threshold in one visit. The rest takes longer.”'),
 ('Ask what she leaves out of a public map', '“Private addresses, unless their owners offer them. And guesses disguised as shortcuts. If I have not walked a turn, I mark it unverified. An attractive line on paper is a poor excuse for someone else’s wet boots.”')),
'aurelia': scene('Aurelia adjusts a lamp so its light reaches both chairs. “I want good lighting to survive a change of keeper. If only I can trim it properly, I have made myself necessary and everyone else’s evening difficult.”',
 ('Ask what a new keeper needs to know first', '“How to recognise an uneven flame, where the spare wick is, and whom to call if the housing cracks. Then let them do it while I watch. Handing over a lamp is easy. Handing over confidence takes practice.”'),
 ('Ask what she liked at the hospice besides her work', '“The arguments over mint tea. I preferred less mint, which apparently made me an enemy of breakfast.” Aurelia smiles. “And the traveller who repaired my cracked lantern’s handle before leaving. I like receiving a gift that someone has thought about.”'),
 ('Ask how she avoids checking someone else’s work twice', '“I ask them what they found, then accept the answer unless I have a specific reason not to. I am better at explaining this than doing it.” She sits down. “You may remind me that the chair is not part of the inspection.”')),
'neris': scene('Neris offers you two empty cups to compare. “I want to make the one people reach for when nobody is watching. Perfect circles win compliments. A comfortable handle gets used.”',
 ('Ask what she checks before the decoration', '“The base, the rim, then the handle under the weight of a drink. I once spent a week on symmetry and preferred the uneven attempt in my own hand. It was an irritatingly persuasive result.”'),
 ('Ask which part she enjoys making most', '“The colour at the edge where the light passes through. Blue going almost clear.” Neris turns a cup. “Then I want someone to disagree with my colour names over citrus water. I maintain that sea-green is a perfectly adequate answer.”'),
 ('Ask what happens when her favourite design is uncomfortable', '“I change it. After complaining. If I show it to you and ask only whether it is beautiful, ask whether you may hold it.” She grins. “That will expose the question I have been avoiding.”')),
'sabine': scene('Sabine sets a cancelled seal beside her letter paper. “I kept this because someone was relieved when it broke. Agreements ought to be understandable while they are still in force. I would like to spend less time explaining them after the damage.”',
 ('Ask why she keeps cancelled seals', '“They remind me that an agreement can end properly. This one released an apprentice whose loan had already been repaid. The wording had continued working long after the debt should have stopped.”'),
 ('Ask what she writes for pleasure', '“Invitations, provided I like the recipient. Word games. Descriptions of pompous people that I have the sense not to send.” Sabine smiles. “Rose cordial improves my restraint. A little.”'),
 ('Ask whether she ever values cleverness more than clarity', '“Often enough to need the question. I once wrote three pages to ask someone to supper. They replied, ‘When?’” She folds the sheet. “Thursday would have been a much stronger opening.”')),
'koharu': scene('Koharu empties a hinge pin and three offcuts onto the table. “I want performers to fix my stage without sending for me. And a few wooden birds with terrible manners. One has already heckled a dragon.”',
 ('Ask what makes a design easy to repair', '“You can reach the fastenings, see how the parts meet, and replace one without breaking two more. I would like the next maker to swear at my handwriting, not at a glued-shut hinge.”'),
 ('Ask about the birds she wants to carve', '“Expressions first. A very disapproving beak, uneven wings. I made my first book stand from a discarded chair; I still like finding a shape in somebody else’s offcut.” She turns a scrap in her fingers. “This could be a particularly cross sparrow.”'),
 ('Ask what she does when an owner prefers an awkward old design', '“Ask why. I have sanded too quickly in the past. A scratch may be a height mark; a crooked rail may be somebody’s first attempt.” Koharu sets down the pin. “It still needs to hold. That does not mean every old mark has to go.”')),
'zahra': scene('Zahra rolls a small wooden peg between finger and thumb. “I learnt to measure water channels. Now I like making things that fit into a palm. Both become troublesome when somebody says ‘close enough’ too soon.”',
 ('Ask what working with channels taught her', '“Let the water test the slope before finishing the sides. My teacher praised patience because haste meant digging twice. I remember the praise. I remember the second trench more clearly.”'),
 ('Ask what she wants to make for herself', '“A music box with a tune I do not tire of after six turns. I enjoy the pause before a melody repeats.” Zahra taps three notes. “And I want to carve the bird on its lid myself, however many beaks I break.”'),
 ('Ask whether she gets tired of being asked about strength', '“When it replaces every other question. I am proud of being strong. I am also proud of fitting a latch you cannot hear.” She smiles. “You may ask about either. Just occasionally remember the second.”')),
'fenna': scene('Fenna marks a covered bench on a route sketch. “Somebody keeps that roof sound and asks a story in return for tea. I want maps to remember people like that. Otherwise the road looks as though it maintains itself.”',
 ('Ask what belongs beside the bench mark', '“Who welcomes travellers, whether you should knock, and when the water rises across the path. ‘Good place to stop’ is how you send somebody to a locked door in the rain.”'),
 ('Ask what makes her stay after telling her own story', '“Somebody asking about the potter instead of the punchline. Or starting a better story.” Fenna grins. “A warm bench and berry cordial help. I am not claiming mysterious depths in the presence of good seating.”'),
 ('Ask when she leaves a good story untold', '“When it belongs to someone who would hate hearing it repeated. I can remove the name and still identify them with one detail. Being funny is not a defence if I have broken a confidence.”')),
'kaede': scene('Kaede sets a game piece beside a coloured glass chip. “I want to be harder to predict across a board. I also want to work with this colour again. I should be capable of having an interest without arranging a contest around it.”',
 ('Ask what she wants to improve in her teaching', '“Knowing when an explanation has become an interruption. If someone asks for one opening, I should not give them the history of every defeat that taught it to me.”'),
 ('Ask what she enjoys about glasswork', '“Colour changes as the piece cools. You cannot bully it into keeping the shade you liked in the furnace.” Kaede holds the chip to the light. “I like having to look carefully. And yes, I still want the next piece to be better.”'),
 ('Ask what losing fairly means to her', '“Name the move that beat me. Congratulate the person who made it. Resist explaining how I ought to have won.” She pauses. “I can do all three. I sometimes need longer for the last.”')),
'elowen': scene('Elowen places a lemon-balm leaf beside a page of ward instructions. “I want people to understand what they use every day. I also want a flower bed where ‘because I like the yellow’ is an adequate planting plan.”',
 ('Ask how she makes an instruction clearer', '“Name what somebody can see and what to do about it. ‘Look for a gap in the chalk’ is better than ‘verify the boundary’. If my reader has to ask me to translate it, I have not finished.”'),
 ('Ask what she would put beside the yellow flowers', '“Something blue, something tall, and lemon balm close enough to brush with my sleeve. My first pot stood outside my teacher’s door. A cat adopted it as a rival. The plant survived; the saucer did not.”'),
 ('Ask what makes her advice hard to receive', '“I sometimes give it before anyone asks. A tired person says their day was dreadful, and I start reorganising it.” Elowen closes the page. “They may want a witness, not another set of instructions.”')),
'nyssara': scene('Nyssara draws a junction with one line ending short. “I would like an apprentice to be able to question this even if a celebrated master signed it. A good explanation should survive being checked.”',
 ('Ask why she signs failed experiments', '“So nobody mistakes them for anonymous work that may be quietly discarded. The next person should know who can explain the conditions. I learnt that in the workshops at home. Embarrassment is cheaper than repeating a failure.”'),
 ('Ask what she enjoys away from the worktable', '“Rain in the stone channels, blackberry cordial, and a mystery whose solution uses a clue the reader was actually given.” Her mouth tilts. “I forgive fictional murder more readily than an undisclosed second staircase.”'),
 ('Ask whether she always welcomes an apprentice’s questions', '“I would like to say yes. I can be impatient when the question is imprecise.” Nyssara looks at the drawing. “Then I must ask what they meant. Silence may look efficient, but it tells me nothing about what they understood.”')),
'sylva': scene('Sylva sorts two fallen leaves by colour. “I want cuttings people can grow successfully, not the fullest tray. I also want to keep leaves just because they are copper at the edges. These are separate projects.”',
 ('Ask how she decides how many cuttings to take', '“Look at the parent first. Leave enough healthy growth for it to recover, then take only what I have room to tend. I crowded a propagation bed once. A full tray was a poor substitute for living plants.”'),
 ('Ask what she sees in the copper leaves', '“The edge stays bright beside blue-green and disappears beside yellow. I want to arrange a picture that changes when the light moves.” Sylva offers the leaves for comparison. “You may prefer the yellow. I intend to disagree politely.”'),
 ('Ask how visitors can know which plants she wants left alone', '“I should label them and tell people why. Looking displeased after somebody reaches for a cutting is too late.” She sets the leaves down. “I cannot ask everyone to infer my wishes from a pot’s position.”')),
'velis': scene('Velis compares two delivery copies. “I want reliable supplies. I do not want ‘reliable’ to mean that a porter quietly pays for every mistake above his name. There are accounts I would rather lose.”',
 ('Ask how she traces a disputed charge', '“Compare the order, the goods received and the porter’s copy. Find where they stopped agreeing before choosing who owes money. The person standing nearest the shortage is not necessarily the person who caused it.”'),
 ('Ask what she would do with a morning free of appointments', '“Buy a pear without investigating the entire harvest. Write a letter that contains no quantities. Stay out late enough to look at the stars, then sleep past an unnecessary meeting.” She smiles. “I am particularly fond of the last possibility.”'),
 ('Ask about a profitable journey she chose to delay', '“A porter needed to reach his family. I missed a good departure so he could go. His next letter was mostly about the baby; the tea recipe was on the back.” Velis folds the copies. “I kept the recipe. I do not regret the departure.”')),
'rhess': scene('Rhess opens a box containing a wooden bird and a bent pin. “I want a watch that still works when I leave the tower. And a shelf for these where I can see them without packing them for the next shift.”',
 ('Ask what makes a proper handover', '“A name, a time, the road conditions and a reply that the next keeper understood. Leaving a lamp burning is not the same as leaving somebody in charge. I stayed too long under instructions written for a watch of six.”'),
 ('Ask why she keeps the bent pin', '“My first watch partner used it when my cloak clasp broke. He said the bend would stop me borrowing it twice. Then he refused it back.” Rhess smiles. “Coins are useful. That pin reminds me of a particular voice.”'),
 ('Ask how she knows when worry has become taking over', '“When I repeat the inspection after the relief has reported it done. If I distrust something, I should name it. If I am simply anxious, volunteering their shift away will not teach either of us to share it.”')),
}

# Private tiers keep physical details in the profile, instead of making a
# companion recite measurements in response to every possible conversational tone.
TRUSTED = {
'mira': ('“I sometimes correct a sentence before asking what its writer meant. It is an unpleasant way to discover I wanted to win.”', ('Ask what helps her notice', '“Ask me to repeat your point before answering it. If I cannot, I have been composing my rebuttal instead of listening.”'), ('Ask what kind of attention she enjoys', '“Remember which book I disliked, then bring me a better argument for it. Or tea. I can be reached by several methods.”'), ('Tell her you will challenge a correction you disagree with', '“Good. Name the part. I may argue, but you should not have to surrender your sentence to keep my company.”')),
'tamsin': ('“I worry people would stop visiting if I had nothing ready for them. I know that is a poor reason to keep a tray in my hands.”', ('Ask how she would like a visit to begin', '“Ask whether I want company before asking what needs doing. Some days I will want help. Some days I will want to tell you why a book annoyed me.”'), ('Offer to pour while she chooses the conversation', '“Yes, please. Then I want your ruling on whether a story may introduce a secret twin in its last chapter. I have strong objections.”'), ('Say you need her to tell you when she has taken on too much', '“I can do that. If I say there is no room for another repair, believe me before I find a way to fit it in at my own expense.”')),
'iona': ('“Sometimes I pack because leaving is easier than replying to a difficult letter. A road gives me an excellent excuse to postpone it.”', ('Ask what question she finds difficult', '“How long I mean to stay. I want to answer honestly without making affection sound like a departure notice.”'), ('Tell her you enjoy hearing from her wherever she is', '“Then I shall write about more than the weather. Expect firm opinions about music and a drawing of anything I cannot adequately complain about in words.”'), ('Say a changed plan is easier to accept when she tells you', '“Fair. I can say I have changed my mind before giving you a beautifully prepared route as though it were inevitable.”')),
'aurelia': ('“I like being dependable. I do not like discovering that I have made myself too tired to be kind. I tend to notice that part last.”', ('Ask which signs she misses', '“Checking the same latch, giving the same instruction twice, becoming cross when someone asks a fair question. Those are reasons to hand over, not proof I should stay.”'), ('Ask what she would enjoy receiving for once', '“Tea with very little mint, and an invitation that tells me where to sit. You may leave the evening’s entertainment unspecified. I shall survive the uncertainty.”'), ('Tell her you will mention when her checking interrupts you', '“Please do. ‘You have asked me that already’ is clear enough. I may be embarrassed. You need not pretend the interruption did not happen.”')),
'neris': ('“I can hear criticism of a design as criticism of my taste. Then I spend ten minutes defending the colour when someone said the handle pinches.”', ('Ask how she would separate the two', '“Ask me to use it as you did. I can argue with an adjective. A cramped thumb is harder to dispute.”'), ('Ask what compliment she most enjoys', '“That you reached for it again. Or that you noticed the blue edge I spent so long getting right. Specific admiration is very welcome.”'), ('Say you will mention a flaw even when she is pleased with a piece', '“Do. Let me be disappointed for a moment, then show me. If I only wanted applause, I should not have asked you to test it.”')),
'sabine': ('“I rehearse an apology until it sounds impossible to refuse. That is precisely when I should stop rehearsing.”', ('Ask what she wants to change about it', '“Say what I did, apologise, then hear the answer. If they are still angry, that is information, not a cue for my next speech.”'), ('Tell her she can speak without entertaining you', '“Then I should like to complain that my best ribbon has a knot in it. Not a symbol. An actual knot. I have been losing to it all morning.”'), ('Say you will ask directly when you cannot tell whether she means a compliment', '“Please do. I may wish you had admired the phrasing first. That is my vanity to manage, not your puzzle to solve.”')),
'koharu': ('“I can see a better joint so clearly that I stop asking why somebody kept the old one. That is how a repair becomes an argument.”', ('Ask what she checks with an owner first', '“What must keep working, what must keep looking the same, and which marks matter. Three questions before I reach for the tools.”'), ('Ask what kind of company she likes while working', '“Someone interested enough to ask, and comfortable enough to tell me when I have explained the hinge twice. Spiced plum tea is also persuasive.”'), ('Tell her you may prefer an imperfect object left alone', '“Then say so. I will tell you if it is unsafe. If it is merely inconvenient, you are entitled to your inconvenient chair.”')),
'zahra': ('“I show people the little ember first. If they laugh at that, I do not have to find out whether they care about the small piece I am proud of.”', ('Ask which small piece she wants someone to notice', '“A latch that opens with one finger and does not rattle shut. I would like someone to use it and ask how I made the catch.”'), ('Ask to hear a tune she likes', 'Zahra taps three slow notes, leaves a pause, then repeats them. “I like that unfinished moment. You wait for a fourth note that never comes. A small trick, very well made.”'), ('Say you enjoy the loud stories too', '“So do I. I am not asking you to look solemn whenever I make a joke. Just occasionally ask me about the hinge.”')),
'fenna': ('“When I think I have disappointed someone, I reach for a joke before I know what they are actually asking.”', ('Ask what she wants you to do when she dodges a question', '“Ask it again without following the joke. I will know you noticed. It saves us both a very clever and completely useless detour.”'), ('Tell her a quiet visit is welcome too', '“Good. I might bring a book and interrupt your reading only when mine does something unforgivable. I promise to begin with the page number.”'), ('Say a joke can hurt even when she meant to reassure', '“Yes. I need to ask what landed badly, not explain why it ought to have been funny. I can keep the explanation for my own bruised pride.”')),
'kaede': ('“I dislike being a beginner in front of people who know I am good at something else. It is a foolish comparison. I make it anyway.”', ('Ask what helps her try', '“A clear first step and somebody who will answer a question without pretending my attempt was excellent. I can tolerate clumsy. False praise gives me nothing to improve.”'), ('Offer to learn an unfamiliar game together', '“Yes. Genuinely unfamiliar. Do not lose on purpose for my benefit; I will notice and be twice as annoyed.”'), ('Say you sometimes want to play without being taught', '“Then say ‘no coaching’ before we begin. I will ask before commenting. I still reserve the right to admire a move that beats me.”')),
'elowen': ('“I want to help so badly that I can make somebody’s bad afternoon into a problem they must explain to me correctly.”', ('Ask what helps her listen first', '“Let the person finish. Then ask whether they want a suggestion. I know the method. Practising it when I think I already have the answer is harder.”'), ('Ask what kind of care she appreciates', '“Remember how I like my tea. Ask whether I want company. If I have lost the scissors again, you may laugh while helping me look.”'), ('Tell her you may refuse a good suggestion', '“Of course. It may be sensible and still not be what you want to do. I can be disappointed without making you responsible for that.”')),
'nyssara': ('“I want my work questioned. I do not want every question about my work to become a trial of whether I should be trusted to exist here.”', ('Ask how she distinguishes the two', '“Ask what a line does, which conditions I tested, or why a warning is missing. Those have answers. Suspicion attached to my name cannot be repaired by another diagram.”'), ('Ask what makes her comfortable sharing unfinished work', '“Someone who can say ‘I do not understand this junction’ rather than pretending they do. I would rather explain it twice than discover a polite misunderstanding later.”'), ('Say you will still raise specific concerns', '“I expect you to. Respect is not a request to lower your standards. Give me the same precise criticism you would give a maker you already like.”')),
'sylva': ('“I sometimes leave a pot apart because I do not want it disturbed, then become annoyed that nobody understood the arrangement. It is a rather private language.”', ('Ask what she plans to say instead', '“This plant is not for cuttings. This one may be touched, gently. I need to name the difference before somebody has to discover it from my expression.”'), ('Ask what company she likes when she is tired', '“A warm seat, honey water, and somebody willing to compare two nearly identical leaf colours. You do not have to agree. I would like you to look.”'), ('Tell her you need her to ask directly for solitude', '“Yes. I cannot expect you to read a leaf at my wrist correctly. Sometimes it curls because I am cold. Sometimes I simply want my own afternoon.”')),
'velis': ('“A free hour still tempts me to arrange a meeting. Then I complain that there is no time for anything but business.”', ('Ask how she chooses which meeting can wait', '“Whether anything changes if we do not hold it. If all I am doing is confirming an answer I already have, I can write it down and go outdoors.”'), ('Ask what she wants people to remember about her', '“That I like spiced pear tea, that I write back, and that I can be persuaded to watch the stars. My contacts are useful. I would prefer not to be introduced as a list of them.”'), ('Say affection should not require an equal favour in return', '“Agreed. If you bring me tea, I can enjoy it before planning repayment. You may need to remind me after the second cup.”')),
'rhess': ('“I can say the relief is competent and still listen for every signal after handing over. The part that worries does not read the roster.”', ('Ask what helps her leave the window', '“A clear report, a named keeper and something I want to do next. I am learning that the last part needs arranging too.”'), ('Ask which keepsake she wants on her new shelf first', '“The carved bird. Its maker could carve through any argument. He gave it to me after I learnt when to stop talking.” Rhess smiles. “I am still considering how pointed a gift it was.”'), ('Say she must tell you when she wants help rather than another shift', '“Fair. ‘I am worried; will you sit with me?’ is a request I can make. Taking over the watch does not answer it nearly as well.”')),
}

# Three different ways to discuss affection; none of these lines grants a future
# act, changes an invitation mode, or replaces the existing partnership gate.
PRIVATE = {
'mira': ('“I like being flirted with by someone who has listened to what I actually said. The book is a good excuse to sit close; it need not be the only subject.”', '“A precise compliment. Tell me which line made you laugh, or that you came to see me. I would rather hear one true sentence than a beautifully general description.”', '“Ask for the place beside me. I am likely to make a joke about the handwriting. You may correctly suspect that I wanted you closer.”', '“Do not turn a private remark into a public challenge. I enjoy teasing when I can answer for myself, without a room waiting to see whether I will.”'),
'tamsin': ('“I like being wanted when I have nothing to bring. No repaired book, no tray. Just me.”', '“Remember a preference, ask how I am, and wait for the answer. I enjoy a compliment much more when it does not lead to another favour.”', '“Ask to sit beside me. Offer your hand. I can say what I want from there; you need not make the invitation elaborate.”', '“Do not turn caring for you into my permanent role. Some evenings I want to be the one receiving the warm cup and the attention.”'),
'iona': ('“I like a playful invitation with a real answer behind it. Ask me to dance because you want to dance with me.”', '“Confidence, a good question, and someone who can laugh when we choose the same wrong step. Perfection would leave us much less to talk about.”', '“Offer a hand and name the invitation. One dance, a walk, a kiss. I may negotiate the music, but you will know my answer.”', '“Keep a private joke private unless I agree to share it. Flirting with you is not a promise to entertain an audience.”'),
'aurelia': ('“I enjoy a direct invitation. It gives me something more pleasant to consider than whether I have missed a hint.”', '“Dependability matters to me. So does a little mischief. A person can keep a promise and still make me laugh over the tea.”', '“Ask me to sit close, then tell me what you hoped to do together. I like knowing that my company was part of your plan.”', '“Let off duty mean off duty. If I decline an invitation, do not make it another task I have failed to complete.”'),
'neris': ('“I like being noticed in detail. There is a difference between admiring a water elemental and noticing what I chose to wear.”', '“Curiosity, mutual teasing, and someone who tells me which colour caught their eye. You may disagree about the name of it.”', '“Ask for my hand or a kiss. Leave room for me to suggest something else. I enjoy having a part in the invitation.”', '“Concentration is not agreement. If I am studying something and you want my attention, say my name and wait for an answer.”'),
'sabine': ('“I enjoy admiration. I also enjoy knowing the person offering it will survive being told ‘not tonight’.”', '“A perceptive compliment, delivered as though you mean it. I will probably tease you. That need not mean I am avoiding the answer.”', '“Ask plainly, then allow me a little flourish in accepting. Directness need not put me out of work entirely.”', '“Do not treat charm as agreement. I can enjoy a conversation without agreeing to every possibility somebody finds in it.”'),
'koharu': ('“I like attention that is for me, even when nothing needs fixing. I am attempting to make that easier to recognise.”', '“Notice what I chose or ask about something I enjoy. Competence is attractive. So is knowing when to put the tools down.”', '“Sit beside me and ask whether I want to hold your hand. It occupies at least one hand I might otherwise use to adjust a hinge.”', '“Ask before touching me or rearranging my work. Surprise improvements have taught me enough to prefer a question first.”'),
'zahra': ('“I enjoy feeling wanted without being asked to prove anything. You may admire the lights in my hair without asking for a wish.”', '“Patience, a warm laugh, and somebody who notices careful work. I like strength too. I simply have more than one interest.”', '“Ask to sit close. A hand offered palm up is easy to understand. I will tell you whether I want it.”', '“Do not assume that looking unusual makes me less sensitive to touch. Ask what feels comfortable. You will get a clearer answer.”'),
'fenna': ('“I like a person who can return a joke and hear the serious sentence after it. I intend to offer both.”', '“Curiosity and a little mischief. Remember a detail I thought you had missed and you will have my attention very quickly.”', '“Ask whether I want company, then say what kind. If I hide the answer in a joke, you may ask me to be less professionally entertaining.”', '“Do not repeat a confidence for a laugh. I want to know which stories stay between us.”'),
'kaede': ('“I like an invitation that does not require me to impress you before I can accept it.”', '“Purpose, patience, and someone willing to disagree with me. Losing a fair argument can be remarkably attractive. Do not arrange one for that reason.”', '“Ask directly for time together. I appreciate a clear question far more than being challenged to demonstrate how much I care.”', '“No tests of affection. If you want reassurance, ask. I would rather answer than discover I was being scored.”'),
'elowen': ('“I like someone remembering what I enjoy, instead of only what I can do for them.”', '“Specific kindness. Bring the tea I like, ask about the cutting, tell me why you wanted to see me. I notice those things.”', '“Ask to sit close or offer an embrace. I can be tired and still want affection. I can also want only the tea.”', '“Do not make my being kind a promise to keep giving. Ask, and believe the answer even if it is not what you hoped.”'),
'nyssara': ('“I enjoy attention that does not turn into an attempt to solve me. There are things I would rather tell you myself.”', '“An exact question, a considered compliment, and a person who can tolerate an unanswered question without treating it as a challenge.”', '“Name what you would like. I have no objection to ‘May I kiss you?’ It is mercifully difficult to misinterpret.”', '“A declined question remains declined. We can choose another subject and still enjoy the evening.”'),
'sylva': ('“I like someone looking closely without assuming looking gives them leave to touch. I can offer my hand myself.”', '“Patience, curiosity and noticing a colour I chose. I enjoy affection that leaves time to answer instead of hurrying to the next thing.”', '“Ask to stay beside me. Then we can decide whether we want conversation, a hand to hold, or something quieter.”', '“Do not assume that because I welcome one kind of closeness I have offered another. Ask when the invitation changes.”'),
'velis': ('“I like being invited without having to decide what I owe in return. I am still learning not to create an account myself.”', '“Plain promises, perceptive humour, and someone who remembers my tea. A compliment without an attached request is especially persuasive.”', '“Tell me you would like my company and name a time. You need not make a case for why I should enjoy it.”', '“Affection is not repayment. Neither of us should agree because the other has accumulated enough favours.”'),
'rhess': ('“I like someone remembering the little things I have kept. It tells me they were listening after the report ended.”', '“Dependability and gentle humour. I enjoy a person who can make me laugh without making my worry the whole joke.”', '“Ask to sit within reach. Offer a hand. I would rather answer a simple invitation than wonder whether I imagined it.”', '“Do not treat loyalty as an unlimited promise. I may need rest or my own evening, even when I am very glad you came.”'),
}

def disclosure(who, tier):
    if tier == 'familiar':
        return FAMILIAR[who]
    if tier == 'trusted':
        opening, *choices = TRUSTED[who]
        return scene(opening, *choices)
    opening, attraction, invitation, boundary = PRIVATE[who]
    return scene(opening,
                 ('Ask what draws her to someone', attraction),
                 ('Ask how she likes to be invited closer', invitation),
                 ('Ask what she wants you to avoid', boundary))

# Pair conversations retain the shared event, with different questions and
# answers before the common resolution. A player never speaks for either woman.
PAIR_CHOICES = {
('aurelia','koharu'): [
 (('Ask whether the uneven colour hides the step', 'Aurelia places her boot on the step. “The edge is clear.” Koharu turns the shade slightly. “Then we can keep the warm patch without pretending it is a defect.”'), ('Say the warmer light makes you want to sit here', '“That was the intention,” Koharu says. Aurelia checks the step from your chair. “And you can stand again without missing that edge. I am satisfied.”'), ('Ask them to test the lamp before arguing about it', 'Koharu turns the shade while Aurelia checks the doorway from each chair. “No glare here,” Aurelia says. “Good,” Koharu answers. “Now I may defend the colour without making you guess about the step.”')),
 (('Ask Aurelia what has changed since the last check', '“Nothing,” Aurelia admits. “I was checking because I was still thinking about it.” Koharu sets down her cup. “Tell me if something changes. You have already seen it hold.”'), ('Invite them both to sit where they can enjoy the lamp', 'Koharu takes the chair farther from the switch. “There. You will have to ask me to stand up.” Aurelia laughs and sits beside her. “A surprisingly effective arrangement.”'), ('Tell Koharu a repeated check need not mean mistrust', '“It feels like being asked to defend the same joint twice,” Koharu says. Aurelia answers, “That is fair. The worry was mine. I should have named it before making it your inspection.”')),
 (('Ask Koharu what she likes making when nobody commissions it', '“Wooden birds with unreasonable expressions.” Koharu draws a pointed beak on a scrap. Aurelia says it resembles the hospice goose. “That goose had strong opinions about official ribbons.”'), ('Ask Aurelia to tell Koharu the goose story', 'Aurelia imitates the official: “Return that at once.” Then the goose, with considerably more conviction. Koharu laughs into her cup. “Did it?” “For bread. The official had offered only rank.”'), ('Ask whether either of them would actually change the lamp now', 'Koharu considers the shade. “No. I like it.” Aurelia nods. “The doorway is clear.” They leave it alone and begin arguing about whether Koharu’s sketch looks more like a goose or an offended sparrow.')),
],
('mira','neris'): [
 (('Ask who will need the failed attempts', '“Someone stuck at the same turn,” Mira says. Neris answers, “And someone who only wants the answer needs a way past us.” They put the solution first and the attempts behind it.'), ('Say you would enjoy seeing how they disagreed', '“You will need several pages,” Neris warns. Mira adds, “And an appreciation of how graciously I changed my mind.” Neris fetches the clean solution sheet. “We shall include the date of that rare event.”'), ('Suggest a clean answer with the attempts attached', 'Neris places the answer on top. Mira numbers the earlier attempts. “A reader can choose how lost to become,” Mira says. “Excellent,” Neris replies. “We have supplied a way out.”')),
 (('Ask which repetition changed the idea', 'Mira points to the second copy: “Here I reversed the arrow. The words are the same; the direction is not.” Neris marks the difference. “Then that is what the note needs to say.”'), ('Offer to help compare the two pages', 'You hold the pages side by side. Neris spots the reversed arrow before Mira reaches for her pencil. “Yes, keep that copy. I missed the important change while admiring the tidy wording.”'), ('Ask them to mark changes before removing a note', '“A margin mark for a new thought,” Mira suggests. “And ask before crossing it out,” Neris adds. “I would prefer one question now to reconstructing your entire argument later.”')),
 (('Ask for the funniest failed solution', '“I rotated every piece except the board,” Mira says. “Then complained that the last piece was upside down.” Neris rotates the notebook. “A difficulty that yielded to revolutionary methods.”'), ('Suggest trying the next puzzle together', 'Neris lays out the new pieces. Mira turns the board once before touching them. “I am applying hard-won knowledge.” Neris smiles. “Good. This time the arrow is on the back.”'), ('Ask whether the clean answer still shows where they went wrong', 'Neris points to a note beneath the solution: rotate the board before reversing the pieces. Mira nods. “My humiliation has become a searchable instruction. The archive is working as intended.”')),
],
('tamsin','zahra'): [
 (('Ask whether the cushion actually needs mending tonight', 'Zahra presses the split seam. “Soon, but nobody will fall through it.” Tamsin sits. “Then I would like to stay for the conversation first.”'), ('Invite Tamsin to take the other chair', '“I was hoping you would,” Zahra tells her. “You may inspect the upholstery tomorrow.” Tamsin smiles. “You are making that chair sound remarkably tempting.”'), ('Ask Tamsin whether she wants to mend or wants company', '“Company,” Tamsin says after a moment. Zahra moves the loose thread out of sight. “That is easier to arrange. Sit.”')),
 (('Ask Zahra which part of the stitch is difficult', '“Keeping the spacing while I pull the thread.” Tamsin shows one stitch on a spare scrap, then puts her own needle down. Zahra tries again. “That was enough. Let me finish this length.”'), ('Offer to hold the cushion while Zahra tries', 'You hold the corner steady. “Thank you,” Zahra says. Tamsin folds her hands around her cup. “I can watch without taking the needle. I am demonstrating exceptional restraint.”'), ('Ask Tamsin to wait until Zahra requests help', '“You are right,” Tamsin says. “I was correcting the seam before you had finished it.” Zahra nods. “Tell me if it will come apart. Let me decide whether the spacing bothers me.”')),
 (('Ask Zahra which stitch she would do differently next time', 'She points to the turn. “Shorter there. The cloth pulls when I sit.” Tamsin checks it once. “It holds. You can change the next one without undoing this.”'), ('Try the cushion and praise how comfortable it is', 'Zahra watches you sit. “That was the purpose.” Tamsin smiles at the uneven corner. “Then it has passed the test that matters tonight.”'), ('Ask Tamsin whether she would leave the repair as it is', '“Yes. The thread is secure. Straightening it would be for my eyes, not the chair.” Zahra settles back. “An excellent distinction. Please remember it while I enjoy the cushion.”')),
],
('iona','fenna'): [
 (('Ask where they will meet if they take different routes', '“The covered bench by the courtyard,” Fenna says. Iona marks it. “Then I can follow the fiddle without making you follow me.”'), ('Say you would like to hear the music too', 'Iona taps the rhythm on the map. “Good. We can see whether the player knows another tune.” Fenna marks the bench. “I may join you after I check which way stays dry.”'), ('Suggest keeping both routes on the sketch', '“Music here, shelter here,” Iona says. Fenna draws the connecting turn. “And a meeting place, so neither of us has to guess which preference won.”')),
 (('Ask what Iona thought had gone wrong', '“I thought Fenna had left because I kept following the music.” Fenna shakes her head. “I was tired. I should have said so before turning back.”'), ('Tell them the outing can still be enjoyable if one leaves early', '“It was enjoyable,” Fenna says. “That is what I forgot to tell her.” Iona smiles. “A brief review on departure. Five words would have saved me several inventive explanations.”'), ('Suggest saying goodbye without requiring a defence', 'Fenna tries, “I have enjoyed this. I am going back.” Iona nods. “Perfect. I can wish you a dry walk instead of trying to repair an imaginary offence.”')),
 (('Ask what each found after they separated', 'Iona sings, “Turn by the water, wait by the door.” Fenna taps the map. “A bench whose roof overhangs far enough to keep your knees dry.” Iona considers it. “A good place to learn the chorus.”'), ('Ask them to combine the refrain and the dry bench', 'Fenna claims the sheltered seat while Iona taps out the tune. “If that line repeats again, I shall know it against my will,” Fenna says. “Exactly,” Iona replies. “An efficient rehearsal.”'), ('Ask what they would do differently on another walk', '“Say when I mean to turn back,” Fenna answers. “Ask whether the next detour appeals before taking it,” Iona adds. They mark both paths for the next outing.')),
],
('sabine','kaede'): [
 (('Ask what the wager would require from the loser', 'Sabine begins listing obligations, then stops at Kaede’s expression. “Tea. The loser chooses the next tea.” Kaede nods. “Something I can agree to before I know the result.”'), ('Suggest playing for the privilege of choosing tea', '“You have reduced my splendid wager to refreshments,” Sabine says. Kaede reaches for a piece. “And made it acceptable. Shall we begin?”'), ('Ask them to state every condition before the first move', 'Sabine gives the short version: the loser chooses tea, no errands or added forfeits. Kaede repeats it back. “Now I can concentrate on defeating you.”')),
 (('Ask Kaede which part of the joke bothered her', '“You made losing sound like permission to order me about,” Kaede says. Sabine puts down her piece. “I am sorry. I meant to boast. I chose a worse joke than that required.”'), ('Invite Sabine to try a joke about her own move instead', '“My strategy is to look certain until the board agrees,” Sabine offers. Kaede finally smiles. “That one I recognise. You may continue at your own expense.”'), ('Ask Sabine to acknowledge the objection before defending the joke', '“You are right,” Sabine tells Kaede. “I made your loss sound like a loss of say in the evening. I am sorry.” Kaede answers, “Tease the move. Leave my dignity out of the wager.”')),
 (('Ask what would make a ridiculous game enjoyable for both', 'Kaede considers. “Announce our plans in absurd titles. Keep the actual rules.” Sabine lifts a piece. “The Ill-Advised Advance of the Overconfident Pawn. I feel well prepared.”'), ('Encourage a rematch with their usual competitive spirit', '“No handicaps,” Kaede says. Sabine nods. “And no victory speech longer than the game.” They begin, each watching the other’s first move with renewed interest.'), ('Ask them to agree the tone before choosing the first move', '“Serious game,” Kaede says. “Ridiculous commentary permitted?” Sabine asks. “About the pieces.” Sabine bows to her pawn. “A difficult evening for this gentleman.”')),
],
('koharu','nyssara'): [
 (('Ask why the failed samples need their labels', '“So I know which conditions failed,” Nyssara says. Koharu measures the widest label. “Then the tray needs to fit the explanation, not merely the jar.”'), ('Offer to lay out the samples while they sketch', 'Nyssara places each label facing the same way. Koharu draws dividers around the groups. “Much better,” she says. “I can see which spaces belong together.”'), ('Ask which parts of the old arrangement must remain', '“These pairs and their dates,” Nyssara says. Koharu marks them on the drawing before adding a handle. “Then I know what I must not improve away.”')),
 (('Ask what the two jars were comparing', '“The same mix in daylight and shade,” Nyssara says. “Sorted by colour, they look like different mixtures.” Koharu returns them to their paired positions. “I moved the answer because it looked untidy.”'), ('Offer to help restore the original pairs', 'Nyssara reads the dates while you hold the labels and Koharu moves the jars back. “There,” Nyssara says. “Now the change in light is visible again.” Koharu asks before touching the next pair.'), ('Ask Koharu to check the purpose before rearranging another sample', '“I should have asked,” Koharu says. Nyssara points to the two jars. “Daylight and shade. Same mix. The space between them was doing work, even without a divider.”')),
 (('Ask why Nyssara wants the corner empty', '“For the next comparison. I do not know how many jars it will need.” Koharu leaves the divider loose. “Then we can fit that part later without rebuilding the tray.”'), ('Suggest tea before they decide about the handle', '“A welcome interruption,” Nyssara says. Koharu writes narrow grip and wider grip beside the sketch. “We can compare them with something warmer than a pencil in our hands.”'), ('Point out that an empty space needs no immediate use', '“Agreed,” Koharu says, rubbing out a proposed compartment. “I was furnishing it to make the drawing look finished.” Nyssara leaves the corner clear and asks about the handle instead.')),
],
('elowen','sylva'): [
 (('Ask what they want the plant to do', '“Keep enough leaf to recover, then compare branching,” Sylva says. Elowen puts down the scissors. “One trimmed shoot and one untouched. Otherwise we will have a strong opinion and no comparison.”'), ('Offer to label an untouched shoot for comparison', 'Elowen writes the date; Sylva marks which shoot remains untrimmed. “Now we will remember what we actually did,” Elowen says, “instead of improving the account next week.”'), ('Ask whether trimming is needed at all', 'Sylva checks the leaves. “Not for its health today. We wanted more branches.” Elowen nods. “Then let us call it an experiment, not necessary care.”')),
 (('Ask which signs should change the watering schedule', '“Dryness below the surface and firmness in the stem,” Sylva says. Elowen adds both beside the dates. “Check those first. Watering because the page says so is how I drown a perfectly good cutting.”'), ('Offer to keep the observations beside the schedule', 'Elowen adds columns for soil and leaves. Sylva points to the empty spaces. “Room for what surprises us.” Elowen smiles. “I was rather hoping nothing would. This is a better record.”'), ('Say a schedule should prompt a check rather than demand water', '“Check daily, water when the soil calls for it,” Elowen writes. Sylva nods. “And record what we found, including the days we did nothing.”')),
 (('Ask what changed in the untrimmed shoot', '“It grew longer towards the light,” Elowen says. “The trimmed one branched lower.” Sylva turns the pots for comparison. “Neither did what our first sketch promised exactly. We should keep the sketch.”'), ('Ask which plant each of them now prefers', 'Elowen chooses the branched shoot. Sylva likes the long curve of the other. “Good,” Elowen says. “We have discovered two tastes and one reason to stop calling the untidy one a failure.”'), ('Ask them to separate the result from their original prediction', 'They record longer growth on the untrimmed shoot and lower branching on the trimmed one. “Less magnificent than ‘improved plant’,” Elowen says. “Much easier to check,” Sylva replies.')),
],
('velis','tamsin'): [
 (('Repeat Tamsin’s question about Velis’s favourite food', '“Pears, spiced tea, and bread while the crust is still crisp,” Velis answers. Tamsin smiles. “That was easier than an account of the flour’s entire journey. I will save you a plate.”'), ('Ask Tamsin what she would cook with the flour', '“A small loaf with a good crust.” She turns to Velis. “Do you like that?” Velis nods. “Very much. I should have answered the personal question before defending the purchase.”'), ('Say knowing the grower need not replace knowing the guest', 'Velis laughs. “Fair. Her flour is excellent. I like it as warm bread, preferably eaten sitting down.” Tamsin points to the spare chair. “We can arrange the last part immediately.”')),
 (('Ask how they would choose a sensible delivery size', '“Start with what we actually used, then leave a margin,” Velis says. Tamsin asks for smaller deliveries while they learn. They write down a proposal for the pantry controls; no order changes during the conversation.'), ('Offer to compare the next few meals before they order more', 'Tamsin notes what remains after supper. Velis adds the delivery interval. “Enough for a decision after we have evidence,” she says. They leave the actual pantry target for you to set in the supply controls.'), ('Ask how they would pause an unnecessary delivery', '“A clear notice before it is packed,” Velis says. Tamsin asks her to put that beside the proposed amount. They agree to review consumption before anyone changes the standing order.')),
 (('Ask what Velis would choose for tomorrow’s supper', '“Something I did not select by comparing three suppliers.” Tamsin laughs. “That leaves several promising vegetables.” Velis asks for the bread again and stays at the table.'), ('Pass Velis the bread and invite her to stay', '“Thank you.” Velis sets her crate notes beneath the ledger. Tamsin asks whether she wants the heel. “Very much. I had intended to negotiate for it with considerably more ceremony.”'), ('Remind Velis the unopened crates can wait until morning', 'Velis checks the list once. “Nothing perishable. You are right.” She closes it. Tamsin slides her plate back within reach. “Then I would like to hear the rest of your pear story.”')),
],
('rhess','velis'): [
 (('Ask Rhess who carved the bird', '“A watchkeeper who could carve through any argument. He gave it to me when I finally stopped interrupting.” Velis studies the offended beak. “A likeness?” Rhess says, “I have chosen not to ask.”'), ('Ask what makes a small keepsake worth keeping', '“A particular voice,” Rhess says. “The bird’s maker could say ‘let me finish’ without looking up from the wood.” Velis nods. “I kept a tea recipe for much the same reason. I can hear the porter describing it.”'), ('Say the bird’s meaning is not its sale price', '“Exactly,” Rhess says. Velis smiles. “I was going to ask about the carving, not make an offer.” Rhess shows her the broken tail and explains the startled salute that caused it.')),
 (('Ask Velis what the message actually says', 'Velis reads, “Axle repaired. Safe at the inn. Arriving tomorrow.” Rhess exhales. “That answers the question I was inventing dangers around.” She accepts the tea.'), ('Offer to wait with Rhess while Velis checks the message', 'Velis brings the porter’s note and tea: he is safe at the inn and expects to arrive tomorrow. Rhess moves back from the gate. “Then we can wait somewhere with chairs.”'), ('Ask Rhess to distinguish a late arrival from a missing person', '“We had no report. Now we do,” Rhess says when Velis brings the note. The porter is safe, delayed until tomorrow. “I can stop treating a repaired axle as a rescue to arrange.”')),
 (('Ask Rhess where she wants the bird to stand', '“Here, where I see it when I come in.” She sets the bird on the shelf. Velis steps back to look. “It appears to disapprove of the doorway.” Rhess smiles. “Then it will feel at home.”'), ('Invite Velis to stay while Rhess unpacks the other keepsakes', 'Rhess brings out the bent pin and the smooth button. “Supper, then I will tell you about these.” Velis takes the offered chair without asking about the shelf’s cost.'), ('Ask whether the shelf is a gift or a loan', '“A gift,” Velis says. “No receipt and no favour outstanding.” Rhess sets the bird on it. “Then supper is an invitation. You may accept that separately.” Velis does.')),
],
}

def pair_choices(a, b, index):
    choices = PAIR_CHOICES[(a, b)][index]
    return dict(zip(('curious', 'warm', 'candid'),
                    ({'label': label, 'response': reply} for label, reply in choices)))

INVITATION_REPLIES = {
'mira': (('Ask which entries resist her categories', '“A traveller’s diary full of recipes and a cookbook full of family arguments. Where would you look for either?” Mira leaves two cards blank for your answer.'), '“Another time, then.” Mira keeps the two cards beside the index and returns to the troublesome headings.'),
'tamsin': (('Ask what she wants to talk about over tea', '“Whether a secret twin in the final chapter is ever forgivable. I have finished a book and need someone to disagree with the author.” Tamsin points to the spare cup.'), '“All right. I shall keep the chair for my book.” Tamsin smiles and takes her own cup to the table.'),
'iona': (('Ask which part of the tune needs an ending', 'Iona taps the last two beats. “It promises another line and stops. I want either a proper farewell or an excellent excuse to repeat the chorus.”'), '“Another evening, perhaps.” Iona taps the unresolved rhythm once more. “I may have found an ending by then. No promises about its quality.”'),
'aurelia': (('Ask which part of the courtyard she wants to see', '“The climbing flowers near the gate. I usually notice whether their stems obstruct the latch. I should like to discover what colour they are.” Aurelia leaves her gloves behind.'), '“Thank you for telling me. I shall take the short circuit.” Aurelia pauses at the flowers before continuing on her own.'),
'neris': (('Ask what the two drawings explain differently', '“This one follows the parts. That one follows what moves first.” Neris puts them side by side. “I know the mechanism too well to notice which step I have left out.”'), '“Fair enough. I shall try following my own arrows and see where I get lost.” Neris turns the drawings towards herself.'),
'sabine': (('Ask why she wants to tell the unpolished version', '“Because I failed to retrieve a ladder with a three-page letter. The version in which I sound clever is missing the part where I finally asked for it at the door.”'), '“Then I shall save the ladder’s dramatic entrance.” Sabine folds the page. “Enjoy your evening.”'),
'koharu': (('Ask what the spare joint is meant to test', '“Whether this notch holds without another peg. If it fails, I want to see which edge gives first.” Koharu sets the scrap on the bench. “Hands clear when we put weight on it.”'), '“All right. I can test the scrap myself.” Koharu sets your chair clear of the bench before returning to the joint.'),
'zahra': (('Ask why the pegs need a careful hand', '“The grain must run along them. A cross-grained peg can snap even when it fits perfectly.” Zahra holds one against the light. “Look at this line before you judge the size.”'), '“Of course. They will keep.” Zahra gathers the pegs into a shallow dish and chooses one to examine herself.'),
'fenna': (('Ask what she wants kept private', '“The names and the place. You can hear the joke without acquiring a story to repeat about someone you might meet.” Fenna waits to see whether that suits you.'), '“Fair enough. I shall keep this one.” Fenna sits back without asking you for a reason.'),
'kaede': (('Ask which turn in the cord she wants to practise', '“The crossing before the last loop. I keep pulling it tight before checking which side is underneath.” Kaede loosens it so you can see both strands.'), '“Another time.” Kaede lays the cord beside her instead of making a case for the exercise.'),
'elowen': (('Ask what she would like to do while the basket waits', '“Describe the flower arrangement I want to make. No remedy attached. I am considering yellow in the middle and would welcome a second opinion.”'), '“Of course. I may sit here a little anyway.” Elowen closes the basket and makes herself comfortable.'),
'nyssara': (('Ask what first appealed to her about the work', '“A faulty line can be followed. You can show where it joins the wrong branch, even if the person who drew it is very important.” Nyssara smiles. “That remains an attraction.”'), '“All right.” Nyssara returns the chair to its place. “The account will keep until we both want the conversation.”'),
'sylva': (('Ask what she wants to notice before moving the shoot', '“Whether it has its own roots and which way the leaves are reaching. It may need space, or it may still depend on the parent.” Sylva points to the stem without pulling it.'), '“That is fine. I want to look a little longer.” Sylva turns back to the shoot, leaving it where it grew.'),
}

CAMP_QUESTIONS = {
'mira': ('Ask what she would read purely for pleasure', '“An adventure whose thief has to live with the consequences. Seasickness, unpaid bills, somebody recognising the stolen coat.” Mira smiles. “A grand escape is more convincing if breakfast remains a problem.”'),
'tamsin': ('Ask which guessing-game role she would choose tonight', '“An offended kettle. You get five questions. If you ask whether I boil, I shall say only when provoked.” Tamsin settles into the comfortable seat. “Begin.”'),
'iona': ('Ask why she chose such a short song', '“Because a chorus we can both remember is better than three verses I must perform alone.” Iona taps the beat. “‘Bring the boat home, leave your boots by the door.’ Your turn, if you like.”'),
'aurelia': ('Ask what she would like to do after the journey', '“Read beside a well-placed lamp without trimming it halfway through the page. I have excellent theories about comfortable lighting. I would like to benefit from one.”'),
'neris': ('Ask which repair almost interrupted her rest', '“A folding handle on this cup. Then I realised a loose hinge would tip the drink into my lap.” Neris shows you the perfectly serviceable handle. “I propose to celebrate the repair I have wisely not made.”'),
'sabine': ('Ask what she likes about the ribbon', '“The colour against this coat. And the fact that I chose it before asking whether it served a purpose.” Sabine lifts one end. “You may now tell me whether it has improved the entrance.”'),
'koharu': ('Ask what she would make with no practical use', '“A wooden bird with such a pointed expression that people feel judged for hanging a coat on it.” Koharu grins. “I would still smooth the wings. There is no virtue in an uncomfortable useless bird.”'),
'zahra': ('Ask the blanket commander for her next order', '“Sit. Secure a biscuit. Report any draught that reaches this command post.” Zahra draws the blanket closer. “This is a defensive operation. We shall not advance until the tea arrives.”'),
'fenna': ('Ask which kind of stop she would put on a personal map', '“Dry roof, comfortable bench, someone willing to talk without charging by the story. I want the name of the person who keeps the roof sound beside the mark.”'),
'kaede': ('Ask what she notices when she is not practising', 'Kaede holds her cup where the light catches it. “Colour through glass. I still want to make a panel with that amber at the edge. I can sit here considering it without declaring a training programme.”'),
'elowen': ('Ask which fragrant leaf she saved', '“Lemon balm. I like the scent before the water cools.” Elowen lets you smell it. “I would grow it beside a seat where I could reach it without getting up. An entirely selfish garden plan.”'),
'nyssara': ('Ask what she likes hearing while she rests', '“Rain moving through stone channels. You can hear its strength change without needing to go out in it.” Nyssara listens. “And a conversation in which nobody asks the rain to justify its design.”'),
'sylva': ('Ask what makes this particular seat so good', '“The stone has kept the warmth, and the draught misses my shoulders. Also, there is room for two cups.” Sylva pats the bench. “That last feature is underused at present.”'),
'velis': ('Ask where she would stop on a journey with no deliveries', '“A pear stall first. Then somewhere I can see the stars after the lamps are covered. I would like to judge a road by what I enjoyed, occasionally.”'),
'rhess': ('Ask what she wants to listen to instead of the signal lamp', '“The fire, and the end of a story nobody tells as a report.” Rhess turns from the horizon. “I can offer one about a crow stealing a lamp cord. It became better at the theft every time it watched me replace it.”'),
}

INITIATIVE_LABELS = {
'mira': ('Ask why she kept the cupboard poem', 'Read the poem aloud together', 'Offer to choose one poem instead of sorting the stack'),
'tamsin': ('Ask what still bothers her about the ribbon', 'Pour tea while she puts the ribbon away', 'Say you can stay for one cup'),
'iona': ('Ask why she wants to compare the two places', 'Listen to the refrain in the stairwell and courtyard', 'Offer to hear the first stop today'),
'aurelia': ('Ask what is keeping her from taking the walk', 'Join her for a short courtyard walk', 'Offer a short walk before your other plans'),
'neris': ('Ask which handle feels better to her', 'Try both handles and compare them', 'Offer to judge the grip, not the glaze'),
'sabine': ('Ask what belongs on the extravagant invitation', 'Suggest trumpeters announcing the cushion', 'Offer one suggestion and leave the drawing to her'),
'koharu': ('Ask what the offcut could become', 'Choose the little boat', 'Help choose, but leave the carving to her'),
'zahra': ('Ask which part of the bird she wants to change', 'Sit with her while she pares the wing', 'Offer company without carving advice'),
'fenna': ('Ask why the sheltered turn is worth marking', 'Help plan a short walk to the shelter and back', 'Ask for a short walk with no extra hill'),
'kaede': ('Ask which threat made the winning move work', 'Replay the position slowly together', 'Study the move without a full rematch'),
'elowen': ('Ask her to read the revised instruction', 'Read it back without her prompting', 'Check the wording as a beginner, not the ward itself'),
'nyssara': ('Ask what the inscription cannot do', 'Read the limitation back to her', 'Check the wording, leaving the enchantment test to her'),
'sylva': ('Ask why this shoot should stay on the plant', 'Set the label aside and leave the shoot growing', 'Look with her while leaving the cutting decision to her'),
'velis': ('Ask how she chose the tea', 'Sit down and compare your tea with hers', 'Say you can stay for tea but have no time for business'),
'rhess': ('Ask what she did before closing the watch book', 'Examine the carved bird with her', 'Say you can stay for tea but not all evening'),
}
