"""Twelve authored, intersecting household stories. All characters are adults."""

def beat(title,opening,left,right):
 return {'title':title,'opening':opening,'choices':{'method':{'label':left[0],'response':left[1],'dimension':'respect'},'company':{'label':right[0],'response':right[1],'dimension':'trust'}}}

def story(title,cast,room,skill,obstacles,project,beats,field):
 return {'title':title,'cast':cast.split(),'room':room,'skill':skill,'obstacles':obstacles.split(),'projectName':project,'beats':beats,'field':dict(zip(cast.split(),field))}

STORIES={
'supper':story('Nobody’s unpaid evening','tamsin zahra sabine','common-room','athletics','lift water','The shared supper shelf',[
 beat('The empty place at the table',
 'Tamsin has set places for everyone except herself. Zahra notices before the food arrives. Sabine takes the serving cloth out of Tamsin’s hands and drapes it over her own shoulder like a ceremonial sash. “A formidable office,” she announces. Tamsin laughs, then reaches to straighten it. Zahra quietly pulls out the missing chair.',
 ('Agree a small rota with a definite stopping point.','Tamsin writes three jobs, not seventeen. Zahra ladles the stew; Sabine takes the serving. Tamsin’s own line reads “sit down while it is still warm.” She underlines it twice.'),
 ('Make tonight a supper everyone brings something to.','Zahra brings bread, Sabine an alarming anecdote, and Tamsin a jar she had been saving for a more deserving occasion. “This one qualifies,” Zahra tells her. Nobody asks Tamsin to turn the offering into another responsibility.')),
 beat('Who gets to be looked after?',
 'Sabine returns wearing an elegant dress beneath the borrowed serving cloth. “I was told to dress for my station.” Zahra laughs into her cup. Tamsin admits she hates watching someone struggle with a task she can do quickly. Sabine’s smile softens: “Then you must endure the terrible sight of me becoming competent.”',
 ('Let the new server make harmless mistakes.','Sabine spills a little cordial and cleans it herself. Tamsin starts to rise; Zahra passes her the bread instead. By the second round Sabine has found a rhythm, and Tamsin has finished a whole cup while it was hot.'),
 ('Ask each person what care they actually enjoy.','Zahra wants someone to ask about her carving. Sabine wants praise that does not call her surprisingly gentle. Tamsin wants company after the dishes, without being thanked as though she were leaving. They make room for those answers.')),
 beat('A chair saved deliberately',
 'At the next gathering, Tamsin arrives last on purpose. Zahra has left a plate beside Sabine, who has already threatened the bread with a dramatic speech. Tamsin surveys the imperfect table. For once her hands stay at her sides.',
 ('Keep the rota small and review it together.','They cross out a task nobody needed. Sabine volunteers for another turn; Zahra requests a turn as guest. Tamsin sits before suggesting an improvement. The household gains a habit that can be changed without anyone failing it.'),
 ('Let the evening become pleasantly unproductive.','Sabine proposes a toast to badly folded napkins. Zahra offers a tiny wooden bird for the table. Tamsin names it the supervisor and informs it that everyone is off duty. The supervisor proves admirably silent.')),
 ],['“Count the people doing the work, not just the work itself.”','“Tell me where the load goes before I pick it up.”','“I can take a turn without making it a grand sacrifice.”']),
'watch':story('The watch that learned to rest','nyssara aurelia koharu','chapel','channeling','cipher water','The quiet watch ledger',[
 beat('Three people still awake',
 'Aurelia checks the same latch twice. Koharu pretends her late walk is aimless. Nyssara has brought a book she is not reading. They meet in the common room and discover that each believed the other two were asleep. Nobody initially finds this funny.',
 ('Separate an actual household check from a restless habit.','Aurelia names two practical checks. Nyssara writes down what would count as finished. Koharu volunteers to accompany one round, then insists that the record include the moment they return to rest.'),
 ('Ask what makes a room feel safe enough to leave.','Nyssara wants a clear way to ask for company. Koharu wants a closed door to mean privacy rather than exclusion. Aurelia wants to hear someone say the next watch is not secretly hers. They say it to one another.')),
 beat('No uniform required',
 'Koharu arrives for the discussion in a soft evening robe. Aurelia looks surprised, then realises she is still dressed as though she might be called out. Nyssara closes her unread book. “We could practise being off duty before we attempt to perfect it.” Koharu settles into the best chair to demonstrate.',
 ('Put the completed checks in the ledger and close it.','Aurelia closes the cover with unnecessary care. Nyssara moves it out of arm’s reach. Koharu offers a cup rather than another task. Their conversation begins haltingly and becomes easier when nobody asks it to justify the hour.'),
 ('Let each choose one comforting evening ritual.','Nyssara chooses a low lamp, Aurelia a clean shawl, Koharu a story that ends well without pretending nothing went wrong. They do not claim these things solve every restless night. They agree the company helps this one.')),
 beat('A light someone else can tend',
 'On the next quiet evening, Aurelia asks Koharu whether she wants company. Nyssara points to the finished checks instead of inventing another. Koharu says yes to the company and no to walking the corridors. Both answers are accepted.',
 ('Keep the record short enough that it has an ending.','They remove the speculative tasks. Aurelia places a final mark at the bottom; Koharu blows out the work lamp; Nyssara keeps the softer light. The house remains inhabited without anyone needing to patrol the conversation.'),
 ('Stay for a story with a deliberately happy ending.','Koharu tells it badly enough that Nyssara must intervene. Aurelia supplies the most improbable rescue and then laughs at herself. For a while, all three are awake because they want to be.')),
 ],['“Check the real condition, not every imaginable failure.”','“I will take this part, and tell you when it is finished.”','“We can ask for company without inventing an emergency.”']),
'fair':story('The lantern fair and the missing master of ceremonies','elowen fenna mira iona','common-room','diplomacy','bargain crossing','The little festival chest',[
 beat('Four excellent plans for the same evening',
 'Elowen proposes stories, Fenna games, Mira a contest and Iona music. Each plan assumes the others will supply the audience. They discover the problem over a table full of beautifully incompatible notes. Fenna asks whether you would like the honour of resolving everything. The others object before you have to answer.',
 ('Give every activity a modest slot and an easy exit.','Iona chooses a short set. Mira writes rules that explain how to stop playing. Elowen keeps one story in reserve, and Fenna volunteers a game that can be joined halfway through. Nobody has to stay for everything.'),
 ('Build the evening around places to gather.','A story chair, a game table and a little open space replace the programme. Iona can play when she wants; Mira can find an opponent rather than conscript one. Elowen and Fenna begin planning entrances with no official ceremony at all.')),
 beat('A wager with excellent tailoring',
 'Fenna proposes a contest for the most shameless compliment. Elowen arrives in a striking evening outfit and argues that she has already won the preliminary round. Mira demands a scoring system. Iona suggests that the judges should survive the contestants’ eyebrows before assuming responsibility.',
 ('Make wit the contest and leave clothing out of the stakes.','Mira produces a devastating compliment delivered with perfect seriousness. Elowen applauds; Fenna demands a rematch; Iona observes that the scoring system has become suspiciously poetic. Nobody has to surrender clothes, privacy or an answer.'),
 ('Ask them to compliment someone else’s contribution.','Fenna thanks Iona for making room for silence. Iona praises Mira’s unexpectedly generous rules. Mira praises Elowen’s timing; Elowen credits Fenna with turning a room of strangers into participants. The sincerity catches all four pleasantly off guard.')),
 beat('An evening that belongs to its guests',
 'The lanterns are lit. For a moment each organiser looks toward you for the opening cue, then toward the others. Elowen offers a chair, Fenna starts a game, Mira explains the rules to someone who actually asked, and Iona plays the first few notes when the room is ready.',
 ('Celebrate the work that made the evening possible.','They name the small contributions as well as the visible ones. Mira accepts a loss without requesting a tribunal; Elowen lets somebody else finish a story; Fenna sits still for Iona’s final phrase. They have learned how to share the room.'),
 ('Join as a guest and let the four host together.','Fenna saves you a place without making you the referee. Elowen’s story wanders into Mira’s terrible joke; Iona answers it with a deliberately melodramatic chord. The evening continues because everyone has something to offer, not because anyone is directing every moment.')),
 ],['“We can divide the work without dividing the company.”','“Nobody has to win every exchange.”','“Rules are useful when everyone knows how to leave the contest.”','“Let the others finish their part before you enter.”']),
 'margins':story('The argument in the margins','mira neris nyssara','library','scholarship','cipher search','The open-question cabinet',[
 beat('Three versions of the truth',
 'Mira has found three incompatible accounts of the same vanished bridge. Neris places a glass model on the table. Nyssara places nothing there at all. “A witness can be mistaken,” she says. “An elegant model can be mistaken with excellent posture.” Neris looks offended for half a second, then delighted. Mira asks you to sit before either of them wins by making the other laugh.',
 ('Give every claim its own evidence card.','Mira rules three columns. Neris agrees to label the model as a hypothesis; Nyssara agrees that refusing every hypothesis is not a method. They leave a fourth column empty for the thing none of them has noticed.'),
 ('Read the conflicting accounts aloud as people’s stories.','Nyssara gives the frightened witness a voice instead of a verdict. Neris changes where the model’s travellers stand. Mira notices that the supposed contradiction describes two different hours. They keep the uncertainty, and the people, on the same page.')),
 beat('The attractive wrong answer',
 'Neris has made the model beautiful enough that Mira keeps looking at it instead of the notes. “An occupational hazard,” Neris says, adjusting her sleeve. Nyssara taps the unsupported span. “It is flirting with the reader.” Neris counters that the reader appears susceptible. Behind the jokes, she is reluctant to take her favourite design apart.',
 ('Ask Neris to demonstrate the weak joint herself.','She presses the bridge until the slender span folds. Mira catches the little figures before they fall. Nyssara does not say she told anyone so. Neris keeps the broken joint as the most useful part of the demonstration.'),
 ('Let each person keep one cherished wrong guess.','Mira confesses to inventing an entire librarian from an ink stain. Nyssara admits that a perfectly cold explanation once concealed her uncertainty. Neris finally lifts the bridge apart. Being mistaken becomes a conversation rather than a performance.')),
 beat('A shelf that leaves room',
 'The three invite you to an informal reading. Mira has credited the glasswork; Neris has copied Nyssara’s unanswered question in the largest hand. Nyssara reads the small witness account first. Their argument has not vanished. It has become precise enough to be enjoyable.',
 ('Publish the disputed conclusion beside the evidence.','Mira writes “provisional” without apology. Neris asks to build the next comparison with Nyssara watching. “Only if I may be wrong too,” Nyssara replies. All three names remain on the work.'),
 ('Keep a chair beside the shelf for the next storyteller.','Mira moves her own chair to make space. Neris offers the glass figures to whoever tells the next version; Nyssara volunteers to listen before interrogating the timeline. The evening ends with an argument about tea, which nobody proposes to footnote.')),
 ],['“Let us write down what we actually saw before we improve the explanation.”','“I will test the small joint. You may catch the model.”','“An unanswered question can still tell us where to put our feet.”']),
 
 'steam':story('The very serious bathhouse committee','iona sabine fenna','hot-spring','diplomacy','bargain water','The leisure invitation board',[
 beat('A rule against rules about rules',
 'Iona wants a quiet soaking evening. Sabine wants lanterns and a reason to wear her beautiful robe. Fenna wants to know whether splashing counts as musical accompaniment. They have convened a committee in the common room before anyone enters the bathhouse. Sabine’s first proposal is that no committee minutes be taken while anyone is undressed.',
 ('Agree a quiet side and a lively side.','Iona marks a quiet hour as well as a quiet bench. Fenna promises to keep her games on the lively side. Sabine volunteers a robe rack and declares privacy the one luxury on which she refuses to economise.'),
 ('Send invitations that ask what each guest enjoys.','The replies favour warm water, easy conversation and somewhere dry for a cup. Fenna draws a tiny tail beside her request for enough space. Sabine folds the notes into elegant invitations; Iona adds “leaving early is allowed” in her own hand.')),
 beat('The robe, the ribbon and the wager',
 'At a clothed rehearsal, Sabine demonstrates a robe tied with theatrical precision. Fenna bets she can make Iona laugh without touching the water. “You are both being watched by a professional,” Iona warns. Sabine raises one eyebrow. Fenna immediately forgets her opening line. Iona wins without singing a note.',
 ('Keep the game to compliments and clever replies.','Fenna recovers by praising Sabine’s magnificent capacity for trouble. Sabine praises Iona’s ruthless timing. Iona thanks them both for finally discovering a game she can play while sitting still. They agree that nobody owes a performance or a piece of clothing.'),
 ('Let Iona choose an unusually gentle game.','She asks each person to name a small pleasure they rarely admit. Fenna likes having her jokes remembered. Sabine likes an invitation without a social obligation. Iona likes being allowed to stop entertaining. The room gets quieter, and more companionable.')),
 beat('Warm water, unhurried company',
 'The invitations are ready. Sabine has chosen the lantern colour; Fenna has brought enough dry towels; Iona has left her instrument at home. They pause at the threshold to ask what sort of evening you want. No one is assigned a part merely for arriving.',
 ('Enjoy the playful conversation.','Fenna turns a perfectly ordinary compliment into an elaborate bow. Sabine receives it with mock severity; Iona supplies the one devastating line that makes them both laugh. Robes and towels stay where their owners want them. The jokes are daring, the company comfortable.'),
 ('Take the quieter seats together.','Iona lets the silence last until Sabine stops filling it. Fenna rests her chin on a folded towel and admits that a good evening need not contain an audience. They leave the next invitation open, with no attendance sheet.')),
 ],['“There is a time for a joke and a time to listen for the answer.”','“Ask what the other person wants before improving the invitation.”','“I can keep the clever line until we are safely across.”']),
 'sparring':story('Strength with the audience removed','aurelia kaede zahra','training-yard','athletics','lift crossing','The paired practice rack',[
 beat('Three ways to stand your ground',
 'Kaede challenges Aurelia to a training bout. Aurelia suggests agreeing what they are practising first. Zahra suggests moving the spectators’ bench somewhere it cannot become a projectile. The disagreement is friendly until Kaede realises that both women can see how badly she wants to look composed.',
 ('Make the exercise about stopping accurately.','Zahra sets a padded target. Aurelia demonstrates a controlled halt; Kaede tries to match it and overshoots by a finger’s width. Nobody cheers or groans. The smaller goal gives all three something real to practise.'),
 ('Pair everyone once, without keeping score.','Kaede learns Zahra’s patient footwork; Zahra learns Aurelia’s warning signal; Aurelia lets Kaede interrupt a sequence that has become too automatic. Their differences stop being a ranking.')),
 beat('Pride, perspiration and a borrowed sash',
 'Zahra catches Kaede’s loose training sash before it can trip her. “You may defeat me after tying this.” Aurelia turns away to give her space, wearing a smile Kaede can hear. “If either of you tells the story,” Kaede says, “include the excellent recovery.” Zahra promises accuracy, which Kaede considers a threat.',
 ('Have Kaede teach the recovery she just improvised.','She starts defensively, then notices Zahra genuinely following. Aurelia asks a useful question instead of offering correction. By the end Kaede is proud of something she can explain, rather than something she managed to conceal.'),
 ('Call a water break before the next contest.','Aurelia sits first. Zahra talks about how long precision took her to learn. Kaede loosens her shoulders and admits that resting in front of competent people feels oddly courageous. Nobody makes her turn the admission into a speech.')),
 beat('The sound of an agreed halt',
 'The next practice begins with Kaede asking Zahra what she would like to work on. Aurelia checks the ground instead of silently taking charge. Their shared stopping signal is now a habit, not an interruption.',
 ('Demonstrate the careful sequence to the household.','Kaede explains the ugly first attempt herself. Zahra makes the heaviest movement look unhurried; Aurelia stops the demonstration exactly when agreed. The applause is for the whole sequence, including its end.'),
 ('Keep this practice for the three of them.','They put the equipment away and stay on the bench. Kaede offers a rematch at a board game; Zahra asks whether the sash has a place in the rules. Aurelia laughs before either of them can prepare a defence.')),
 ],['“Use the stopping signal. I am listening.”','“We have practised an imperfect beginning. We can still finish well.”','“Steady is a technique, not an absence of effort.”']),
 'garden':story('The garden that would not stand still','elowen sylva koharu','conservatory','artifice','repair water','The adjustable growing bench',[
 beat('A beautiful obstruction',
 'Koharu’s neat support frame has been entirely ignored by a climbing plant. Sylva regards this as useful feedback. Elowen points out that the plant has also ignored the walking route. For a moment both maker and gardener look betrayed. Then the vine drops a leaf into Koharu’s carefully labelled tray.',
 ('Build the next support to be adjusted.','Koharu replaces the fixed joint with a sliding one. Sylva offers to observe where the tendrils actually reach; Elowen marks a clear path that remains clear even when the garden has an opinion.'),
 ('Start with where people want to sit.','Elowen moves three chairs into the warm patch. Sylva follows the shade across their backs; Koharu sketches a support that makes room for conversation beneath it. The garden’s untidiness becomes part of the plan.')),
 beat('Damp sleeves and unsolicited improvements',
 'A watering line gives Koharu a cold splash. Sylva offers a dry wrap while Elowen closes the valve. Koharu tries to pretend the incident was a test. “Then I admire your commitment to repeated evidence,” Elowen says. Sylva asks whether the next improvement can wait until everyone is dry.',
 ('Repair only the joint they have agreed to repair.','Koharu puts three tempting alterations aside. Elowen holds the line while Sylva checks the roots. The repair works, and nobody’s preferred part of the garden is redesigned in the process.'),
 ('Accept the wrap and the pause.','Koharu sits with damp hair and an expression of injured dignity. Sylva admits she once moved a plant five times while insisting it was being left alone. Elowen laughs so hard she has to put the watering cup down.')),
 beat('Room for the next season',
 'The vine has taken another unexpected turn. This time Koharu loosens a joint rather than reaching for a saw. Elowen carries tea through the clear path; Sylva places a fallen blossom beside the drawing.',
 ('Leave the adjustment marks visible.','Koharu writes dates beside the changes. Sylva adds what the leaves were doing, and Elowen adds where people actually walked. None of them signs as the sole designer.'),
 ('Name the place after an afternoon, not a designer.','They call it the Long Pause. Koharu puts away her pencil before the tea cools. Sylva shifts a cushion for Elowen, who notices without turning the kindness into a project.')),
 ],['“We can keep a clear path without flattening everything around it.”','“Look at what is already holding.”','“One useful adjustment. Then we check it together.”']),
 'ribbons':story('The borrowed ribbon conspiracy','sabine tamsin neris','common-room','artifice','repair bargain','The shared fitting screen',[
 beat('An invitation with pockets',
 'Sabine proposes an evening wardrobe exchange. Tamsin asks whether any of the proposed dresses have pockets. Neris produces a beautiful clasp that is impossible to fasten alone. “A social design,” Sabine declares. Tamsin calls it a maintenance request with excellent cheekbones.',
 ('Make three practical alterations together.','Tamsin adds a discreet pocket, Neris rounds a troublesome clasp and Sabine tests whether elegance survives sitting down. It does. Sabine insists the discovery deserves a celebratory twirl.'),
 ('Let everyone choose what they want to try.','Sabine brings a daring ribboned ensemble, Tamsin a soft blouse and Neris a simple dress that makes the clasp unnecessary. Nobody votes on someone else’s neckline. The invitations are to experiment, not to be inspected.')),
 beat('A compliment that fits',
 'Behind the fitting screen, Tamsin asks for the longer ribbon. Sabine passes it without a joke, then directs her teasing at Neris, who has spent ten minutes pretending not to enjoy being admired. Neris retaliates with a precise analysis of Sabine’s carefully arranged casualness. Tamsin emerges laughing.',
 ('Offer specific compliments and ask before adjusting anything.','Tamsin likes being noticed for her choice of colour. Neris admits the plain dress was a deliberate experiment. Sabine accepts a compliment without converting it into a bargaining position. Each woman keeps the final say over her own look.'),
 ('Invite them to invent outrageous names for their ensembles.','Sabine chooses “Administrative Distraction.” Neris chooses “A Controlled Exception.” Tamsin names hers “I Am Not Fetching Anything.” They laugh, then quietly keep the names. No outfit is changed by the joke.')),
 beat('The owner of the mirror',
 'The three meet again with their own clothes and a new ease about asking for help. Neris has made a clasp that can be worked with one hand. Sabine admits she prefers the version that gives her a choice about company. Tamsin checks the pocket and declares the evening viable.',
 ('Keep a repair note beside each borrowed piece.','The notes record fit, fastening and the owner’s preferences. Sabine draws a small flourish beside “ask first.” Neris leaves space for revisions. Tamsin puts the spare ribbon where everyone can find it.'),
 ('Hold a small, clothed fashion evening.','Sabine makes an entrance; Neris steals the applause with a dry remark; Tamsin demonstrates the pocket to thunderous approval. Compliments travel in both directions. The screen remains available whenever anyone wants privacy.')),
 ],['“A well-placed question is more useful than an unsolicited adjustment.”','“Check the fastening before you trust it.”','“Let us make the clever solution usable without an audience.”']),
 'maps':story('The map with the embarrassing shortcut','fenna mira kaede','library','fieldcraft','search crossing','The honest route folio',[
 beat('Absolutely a shortcut',
 'Fenna draws a glorious shortcut through a region Mira’s old map labels “unreliable ground.” Kaede asks what makes it glorious. “The confidence of the line,” Mira answers. Fenna insists the view is excellent, then admits she has only walked half of it. They invite you to help plan an honest route.',
 ('Mark the unwalked section as a question.','Fenna draws the uncertainty herself. Kaede adds a turnaround point; Mira copies the source date beside the old warning. The route becomes less impressive and much more useful.'),
 ('Collect everyone’s worst navigation story first.','Mira once followed a catalogue reference into a pantry. Kaede once insisted that a hill had moved. Fenna supplies enough detail about her own wrong turn to make both stories seem dignified. They begin the plan on equal footing.')),
 beat('The price of a good story',
 'Fenna wants to leave the embarrassing turn out of the fair copy. Kaede surprises her by objecting. “Someone else may make the same mistake.” Mira offers to write the note without the performer’s name. Fenna studies the map, caught between wanting credit and wanting cover.',
 ('Keep Fenna’s name beside the corrected observation.','Fenna writes “I checked again” beneath the first route. Kaede adds her own correction in the same ink. Mira gives both versions a place in the record. Accuracy becomes a way of taking responsibility rather than losing face.'),
 ('Make the cautionary note into a memorable little rhyme.','Mira produces a rhyme so dreadful that Fenna demands a second draft. Kaede remembers it perfectly after one reading, which defeats the objection. They keep the useful warning and the private joke.')),
 beat('The long way chosen freely',
 'The finished route includes a longer path, a possible shortcut and several places to stop. Kaede no longer calls the longer option a retreat. Fenna has drawn a small seat at the best viewpoint; Mira has labelled it without correcting the joke.',
 ('Test the planning method against another known route.','Each spots something the others missed. Kaede asks Fenna about the ground before judging the line; Fenna asks Mira how old the report is. The questions sound like trust.'),
 ('Plan a future walk with no discovery required.','Mira requests time to read at the viewpoint. Fenna requests snacks. Kaede requests that neither of them call it a tactical picnic, then concedes the name has already stuck. The plan waits for a separate, explicit outing.')),
 ],['“I marked the part I do not know. We can use the longer way.”','“The date of the observation matters.”','“A turnaround point is part of a successful plan.”']),
 
 'encore':story('An encore nobody owes','iona elowen sabine','common-room','diplomacy','bargain search','The open rehearsal book',[
 beat('The rehearsal before the rehearsal',
 'Sabine has arranged a charming little performance. Iona would like to know when it became a performance. Elowen has brought flowers and immediately asks whether they should go back into water somewhere else. Sabine notices that her beautiful invitation left very little room for an answer.',
 ('Write a programme the performers can revise.','Iona shortens her part. Elowen offers to arrange the room rather than appear on cue. Sabine leaves a blank line where the grand finale used to be. The invitation becomes more appealing when it stops sounding inevitable.'),
 ('Begin as a rehearsal with no promise of an audience.','Iona plays an unfinished melody; Elowen hums a line while trimming a stem. Sabine sits on the floor to listen. Halfway through, she forgets to imagine how the evening will look from the door.')),
 beat('A costume with too much confidence',
 'Sabine arrives in an elegant, daring evening ensemble and announces that at least one part of the programme is ready. Iona looks her over. “A very persuasive overture.” Elowen laughs, then admits she dislikes being made the gentle centre of every arrangement. Sabine puts the flowers down to listen properly.',
 ('Give Elowen the sharpest line in the piece.','Elowen delivers it so dryly that Iona misses a note. Sabine insists on keeping the mistake in their private account of the rehearsal. Elowen is pleased to have surprised them without becoming a different person.'),
 ('Let them exchange roles for a few minutes.','Iona arranges the flowers, Sabine attempts a simple accompaniment, and Elowen directs with increasingly mischievous instructions. They learn enough about one another’s work to stop calling any of it effortless.')),
 beat('The last note is allowed to be last',
 'Their small gathering ends with Iona’s chosen final note. Someone asks for another. Sabine looks at Iona before responding; Elowen starts bringing the flowers down from their display. The pause belongs to the musician.',
 ('Thank the performers and close the programme.','Iona bows, genuinely pleased. Sabine directs the next conversation toward the guests, and Elowen finds a vase for the flowers that will stay after everyone leaves. The ending feels complete rather than abrupt.'),
 ('Invite an informal conversation after the music.','Iona puts the instrument away before joining you. Elowen repeats her wicked line by request; Sabine laughs without trying to turn it into another performance. The best encore is that they stay as guests.')),
 ],['“Listen for the point where the other person has actually finished.”','“A quieter approach can still carry a sharp idea.”','“Make an offer with room for a real answer.”']),
 'workbench':story('The machine for doing slightly less','koharu neris zahra','workshop','artifice','repair lift','The shared jig shelf',[
 beat('An unnecessarily magnificent solution',
 'Koharu has designed a device to lift a small tray. Neris proposes a glass guide that doubles its elegance. Zahra lifts the tray with one hand and asks where it needs to go. There is a long silence. Then Koharu admits that she may have enjoyed designing the problem as much as solving it.',
 ('Define the smallest job worth building for.','Zahra describes repetitive strain rather than spectacular weight. Neris removes two beautiful but useless pieces. Koharu draws a simple stop that keeps the load steady. The less impressive design finally has a purpose.'),
 ('Ask each maker which task they would happily stop doing.','Neris names holding a delicate piece while pretending her wrist is comfortable. Zahra names being asked to heat a piece before anyone has checked its measurements. Koharu names explaining that an unfinished device is not an invitation to finish it for her.')),
 beat('Hands, held steady',
 'Neris asks Zahra to hold a fitting while she aligns it. Koharu starts to correct their grip, then stops and asks. “Much better,” Zahra says. Neris adds that the sight of capable hands is distracting enough without unsolicited instruction. Koharu loses her next sentence and both women notice.',
 ('Use a spoken handover before every adjustment.','The sequence becomes slower, then smoother. Zahra no longer has to guess when Neris is done; Koharu can offer an improvement without reaching across someone. They keep the handover even when it feels unnecessary.'),
 ('Take the teasing in good humour and share the awkward part.','Koharu admits she worries that being useful is the only reason to keep her nearby. Neris puts the fitting down. Zahra asks whether she would like to stay after the work is done. The question is simple enough to answer.')),
 beat('A useful empty space',
 'The finished arrangement leaves more of the bench empty than before. Koharu resists filling it. Zahra tests the stop and sets the tray down herself. Neris places a cup in the cleared space, a more persuasive demonstration than any diagram.',
 ('Label the device with its limits.','They list the safe load and the easy release. Zahra adds the instruction to ask who is keeping the small heating ember steady. Koharu leaves room for the next maker’s observation.'),
 ('Use the free space for three cups.','They leave the contraption on the table and try to guess what a visitor would think it does. Neris proposes a spectacularly complicated egg timer. Zahra laughs and pours Koharu another cup.')),
 ],['“We know the job. We do not need to invent a grander one.”','“I will say when the fitting is secure.”','“Ask for the lift, and I will tell you what I can manage.”']),
 'rain':story('A roof, a root and a borrowed cloak','sylva tamsin aurelia','conservatory','channeling','water repair','The weather check basket',[
 beat('Rain where the rain should not be',
 'A small leak appears beside the conservatory door. Tamsin arrives with cloths, Aurelia with a bucket, and Sylva with a warning about roots beneath the threshold. All three begin different solutions at once. The bucket catches the water while they catch up with one another.',
 ('Agree the order: contain, inspect, then repair.','Aurelia keeps the walking route clear. Tamsin checks the damaged join without covering the evidence. Sylva marks the root’s living edge. Their first useful achievement is not undoing one another’s work.'),
 ('Find a temporary arrangement that lets everyone rest.','They catch the drip, dry the path and leave a visible note. Tamsin looks relieved when nobody treats a temporary measure as a moral failing. Sylva promises to check the root in daylight; Aurelia promises not to inspect it every hour.')),
 beat('The warmest cloak in the room',
 'Tamsin’s sleeve is damp. Aurelia offers her cloak; Sylva points out that Aurelia’s own shoulders are wet. The cloak passes between them until Tamsin spreads it over the back of a bench. “There. An infrastructure solution.” Sylva invites them to sit close enough to benefit. Aurelia’s solemn expression finally breaks.',
 ('Record what each person noticed.','Tamsin notes the seam, Sylva the swelling root and Aurelia the draft that moved the rain inward. Together the observations explain the leak. None would have been enough on its own.'),
 ('Leave the repair alone for one cup of tea.','Tamsin leans back under the shared cloak. Sylva talks about the sound of rain on different leaves. Aurelia listens with her hands empty. Their closeness is easy, chosen and pleasantly warmer than the corridor.')),
 beat('After the weather',
 'The rain passes. The conservatory smells of damp stone and clean leaves. Tamsin finds the cloths folded; Aurelia finds the bucket emptied; Sylva finds the root undisturbed. This time the evidence of someone else’s work is reassuring.',
 ('Keep a shared check basket by the door.','They leave simple tools and a short note explaining when to ask for help. Aurelia puts the cloak back with its owner, Tamsin takes a dry seat, and Sylva opens the clear path to the afternoon light.'),
 ('Make the sheltered bench a place to meet again.','They agree that the next gathering need not wait for bad weather. Tamsin claims the middle place under the cloak as a joke; Sylva takes the warm side; Aurelia promises to arrive without a bucket.')),
 ],['“Protect the part that is still alive.”','“A temporary fix can buy us time to choose carefully.”','“I have the path. Tell me what you need next.”']),
 
}

# Each person offers one distinct optional coda after mutual attraction has already been established.
CODAS={
'mira':'Mira closes her book with one finger marking the page. “I have an observation that would be better made somewhere quieter. You may bring that attentive expression.”',
'tamsin':'Tamsin smooths the ribbon at her wrist. “I have finished helping. Now I would like you to keep me company while I do absolutely nothing useful.”',
'iona':'Iona leans close enough that the invitation belongs only to you. “The next song is optional. Sitting beside me is the part I was hoping for.”',
'aurelia':'Aurelia loosens her shawl at the shoulders and offers her hand. “Off duty,” she says, with a smile that makes the distinction quite clear.',
'neris':'Neris notices the direction of your glance and lets the silence become playful. “An interesting hypothesis. Perhaps you should ask me about it.”',

'sabine':'Sabine adjusts a ribbon that needed no adjustment. “You may tell me the outfit was worth the trouble. I shall decide whether to let you see how pleased I am.”',
'koharu':'Koharu puts down her tools before beckoning you closer. “No broken clasp. No difficult mechanism. This is an invitation, and I am trying to make it obvious.”',
'zahra':'Zahra pats the place beside her. “I saved you some quiet.” Her smile makes the invitation considerably less solemn than the words.',
'fenna':'Fenna catches you looking and returns the look without a joke for once. Then she smiles. “There you are. I was beginning to think I would have to be subtle.”',
'kaede':'Kaede offers you her hand with mock formality. “You may consider this a challenge to spend a very pleasant evening in my company. No score will be kept.”',
'elowen':'Elowen tucks a blossom into her hair and asks whether the colour suits her. The question is sincere; the look that follows is knowingly unfair to your concentration.',
'nyssara':'Nyssara turns the lamp down a little. “There. Fewer distractions.” She pauses, then smiles. “Apart from the one I intended.”',
'sylva':'Sylva makes room in the warm patch beside her, the folds of her wrap settling around her shoulders. “You need not invent a reason to stay.”',
}
