"""Authored adult relationships, household friendships and practical rituals."""

def beat(title, opening, gentle, playful, gentle_label="Ask her to explain", playful_label="Respond playfully"):
    return {'title':title,'opening':opening,'choices':{'gentle':{'label':gentle_label,'response':gentle},'playful':{'label':playful_label,'response':playful}}}

# Each route is playable using the starting common room/library after recruitment.
# Specialist-room content is an additional route, never a wardrobe bottleneck.
PROFILES={
'mira': {'room':'library','activity':'reading','relaxed':'“I have something without quite so many scholar’s buttons. I thought I might stop dressing for an argument with a catalogue.”','daring':'“I chose this one for an evening with you. The book is coming too, but I make no promises about reading it.”','thanks':'“Then we shall call it a very promising footnote.”','tease':'“Careful. I am quite capable of turning a footnote into a chapter.”','beats':[
 beat('The stolen ship', 'Mira opens a battered adventure novel. “A thief steals a ship in this one. I first read it when I was supposed to be copying tax records. The tax records lost.”', '“The thief gets seasick. That detail convinced me more than all the sword fights.” She finds the page for you.', 'Mira points to the captain’s speech: “Return my ship and I may overlook the theft.” She answers as the thief, gripping the table: “Gladly. Turn it round. I have reconsidered the sea.” Your captain loses his dignity halfway through the reply.', 'Ask why she kept this copy', 'Offer to read the captain in a ridiculous voice'),
 beat('The captain’s injured hand', '“Our captain has forgotten which hand was injured,” Mira says, comparing two pages. “Do we forgive the author, or invent an explanation?”', '“To escape washing dishes? Entirely plausible.” She pencils the theory onto a loose bookmark.', '“Of course I am. You may cross-examine me after the shipwreck.” She moves the book between you.', 'Suggest that he exaggerated the injury', 'Accuse her of protecting her favourite novel'),
 beat('Mira’s bakery ending', 'Mira pauses at a letter tucked into the novel. “I wrote a better ending when I was nineteen. The captain retires and opens a bakery. I was very tired that year.”', '“The captain set his sword above the oven. By noon it was holding up a row of drying towels. Nobody declared war. Three people complained about the crust.” Mira lowers the letter. “Nineteen-year-old me built an oven large enough to provision a fleet. I still stand by the towels.”', 'She hands you the letter. “Your line is: ‘These rolls are not burnt. They have survived a siege.’ Please give it the dignity it deserves.” She waits a moment, then adds, “I shall be the customer asking for a refund.”', 'Ask her to read her ending', 'Volunteer to play the retired captain'),
 beat('Your next book', 'Mira closes the novel. “Next time, you choose. I want to know which book you would smuggle into a boring apprenticeship.”', 'She asks about its ending, then catches herself. “No. Save that part. I want to hear you read it.”', '“Flattery will get you another chapter.” She smiles. “It may also get you the seat beside me.”', 'Describe a story you would share with her', 'Say her reading voice has spoiled other books for you') ]},
 'tamsin': {'room':'kitchen','activity':'cooking','relaxed':'“The apron has done its day’s work. I would like to sit with you as myself, without a pocket full of lists.”','daring':'“I made this choice before I asked what anyone would think. Now I rather want to know what you think.”','thanks':'“Good. I am learning that comfortable can mean being noticed, too.”','tease':'Her ears lift. “I suspected you might say that. I was hoping, a little.”','beats':[
 beat('Her first book repair', 'Tamsin shows you a crooked old book cover. “My first repair. I pulled the thread so tight that the book would barely open. My teacher made me undo every stitch.”', '“Looser stitches, and a strip of cloth inside the hinge. I kept the cover to remind myself what rushing costs.”', '“For nearly an hour. Undoing the stitches took twenty minutes. There is a lesson in that too.”', 'Ask how she fixed it', 'Ask whether she ever argued with that teacher'),
 beat('Choosing the repair cloth', 'Tamsin has laid out two scraps of cloth. “Blue for the repaired cover, or brown? Brown would match. Blue would make the repair easy to find next time.”', '“My choice too.” She sets the brown aside. “If it fails, I want the next binder to know exactly where to look.”', 'She glances at her sleeve. “That is a thoroughly unprofessional reason. Fortunately, it is my book.”', 'Choose blue so the repair is visible', 'Suggest blue because it suits her'),
 beat('The list between the pages', '“I found something between the damaged pages,” Tamsin says. She unfolds a shopping list: lamp oil, onions, and a birthday ribbon. “I hope they remembered the ribbon.”', '“In a little envelope with the title. Receipts, letters, pressed flowers. I would hate to throw away the part someone came back for.”', '“You may invent the culprit. I insist the birthday ends well.” She settles in to hear your theory.', 'Ask whether she keeps things found in books', 'Propose a mystery about the missing ribbon'),
 beat('Reading the repaired book', 'Tamsin opens the repaired book without a creak. “There. Now I can read it without thinking about the binding. Will you sit with me for the first page?”', 'Tamsin reads: “The cook hid the last hot loaf beneath a towel. This fooled nobody. The dog sat before the towel, and the children sat before the dog.” She lowers the book. “A convincing kitchen. Now I want supper.”', '“That arrangement has some merit.” She sits beside you and lets you take its weight.', 'Ask her to choose a passage', 'Offer to hold the book if she sits closer') ]},
 'iona': {'room':'command-room','activity':'maps','relaxed':'“No dispatches tonight. I would like something soft, a closed map case, and your undistracted company.”','daring':'“I usually know where a conversation is going. Tonight I thought I would dress for a pleasant detour.”','thanks':'“Then let us leave the route pleasantly undecided.”','tease':'“A promising wrong turning. Shall we see where it leads?”','beats':[
 beat('The repainted gate', 'Iona taps an old route note. “Three houses past the blue gate. That was the address. They repainted the gate, and I delivered a love letter to a cooper.”', '“The cooper knew the handwriting. Small towns are terrible places for secret admirers.”', '“He offered to repair the sender’s barrel. A practical response, if a little discouraging.”', 'Ask how she found the right house', 'Ask whether the cooper answered the letter'),
 beat('Writing home', 'Iona is writing home. “I can describe the castle perfectly. Explaining why I stayed is harder. So far I have mentioned dry shelves and decent tea.”', 'Iona writes, “I stayed because I have someone to talk to after the maps are put away. Yesterday we argued about whether a wrong address makes a letter more interesting.” She looks up. “You may object to the summary before it goes.”', '“I said honest.” She grins and gives you the pen. “One sentence. I reserve the right to edit.”', 'Suggest mentioning someone she enjoys seeing', 'Offer a glowing description of yourself'),
 beat('A map of music', '“I used to mark every place with live music,” Iona says. “My colleagues mocked the map until they wanted somewhere pleasant to spend a rainy evening.”', '“Fiddles, and a chorus you can join after hearing it once. ‘Bring the boat home, leave your boots by the door.’ It repeats. By the third time, even the drummer remembers.” Iona taps the beat for you. “A generous song.”', '“I shall add a warning symbol beside your name.” She is already laughing before you begin.', 'Ask what kind of music she likes', 'Offer to improve the map with your singing'),
 beat('A day without errands', 'Iona puts her field case aside. “Tell me where you would go for a day if there were no supplies to collect. I want a destination you actually like.”', '“The riverside market. Sugared peel first, music after sunset. There is a pickled-eel stall I am willing to walk a long way around.” Iona asks which stalls would tempt you. “We can disagree about the eel. You must carry it yourself.”', '“Then I choose the music.” She offers her hand. “And you can tell me if I tread on your foot.”', 'Describe the place and ask her choice', 'Say the company matters more than the destination') ]},
 'aurelia': {'room':'guard-barracks','activity':'watch','relaxed':'“The watch can rest without the lamps going out. I would like you to see me when I am not standing ready.”','daring':'“I used to think being steady meant never showing what I wanted. I would like a different sort of evening with you.”','thanks':'“That feels like a kindness I can stop bracing for.”','tease':'Her wings shift with a quiet laugh. “You are making composure surprisingly difficult.”','beats':[
 beat('The cracked lantern', 'Aurelia shows you a cracked lantern. “A traveller at the hospice recognised this one from the road. We had better lamps, but he slept better when we used this.”', '“He repaired the handle before he left. I like that he wanted to leave something useful behind.”', '“No. Someone once gave me a live goose. I found it a more suitable household.”', 'Ask why she kept it', 'Ask whether she collects every grateful gift'),
 beat('Adjusting the reading light', 'Aurelia turns the lantern shutter away from your eyes. “There. Enough light for the page, less glare. People blame their sight when the lamp is badly placed.”', 'She changes the angle twice. The same cramped handwriting becomes much easier to read. “A small adjustment saves a great deal of squinting.”', 'Her wings shift as she laughs. “I was talking about the page. But I will accept the compliment.”', 'Ask her to show you the difference', 'Tell her she has improved the view already'),
 beat('The argument about mint tea', '“I miss one thing about the hospice,” Aurelia says. “The kitchen argument at dawn. Everyone had an opinion about how much mint belonged in the tea.”', '“Less mint. I wanted tea, not a mouthful of garden.” She pours yours and asks what you think.', '“You would have been very popular with the cook. Less so with me.” She slides the mint pot towards you.', 'Ask which side she took', 'Defend enough mint to wake the entire household'),
 beat('Sitting down at last', 'Aurelia checks the lamp once, then sits beside you. “It is trimmed. The door is latched. I have run out of sensible reasons to keep standing.”', '“Something you enjoyed today.” She folds her wings comfortably and listens to the answer.', '“You could have asked.” She moves nearer. “Though I admit I wanted to see whether you would.”', 'Ask what she would like to talk about', 'Tell her you were hoping she would sit close') ]},
 'neris': {'room':'hot-spring','activity':'bathing','relaxed':'“Something easy to move in, and no work belt. I like the thought of an evening with nothing to carry except a conversation.”','daring':'“I chose this for an evening by the warm water. Staying to talk with you was the other part of the plan.”','thanks':'“Then I shall enjoy the evening without measuring it.”','tease':'“I thought you might appreciate the experiment.” Her smile is bright and direct.','beats':[
 beat('The wagons on the bridge', 'Neris taps the side of a cup. “The bridge near my old home made this note when a cart crossed it. I could tell the flour wagon from the fish wagon before either arrived.”', '“Flour rattled. Fish sloshed. The driver of the fish wagon also swore at the same pothole every day.”', 'She listens to your exaggerated approach. “That is a person hoping to be noticed. A very loud species.”', 'Ask how the wagons sounded different', 'Challenge her to identify your footsteps'),
 beat('The comfortable cup', 'Neris has two cups: one perfectly round, one slightly uneven. “Everyone praises that one,” she says, pointing to the round cup. “This one is nicer to hold.”', 'The uneven handle gives your thumb more room. She watches you notice. “Exactly. Hands are not perfectly round either.”', '“Terribly. I have to compliment its glaze before using the other one.” She demonstrates with great solemnity.', 'Try both and compare the handles', 'Ask whether the favourite cup gets jealous'),
 beat('The misleading puzzle piece', '“I tried making a puzzle with no misleading pieces,” Neris says. “It was solved in a minute. Apparently being fair and being interesting require separate thought.”', 'Neris places the pieces edge to edge. One notch is rounded; the other ends in a shallow point. “Same outline from above, different joint. Turn it before deciding.” She waits while you try. “That pause is what the first puzzle lacked.”', '“Only the recoverable kind.” She turns the piece over and waits for your expression to change.', 'Ask to see the troublesome piece', 'Accuse her of enjoying your confusion'),
 beat('What amused you at supper', 'Neris brings the comfortable cup and sits near you. “No puzzle tonight. I want to hear the story behind that expression you had at supper.”', 'She asks enough questions to reconstruct the scene, then imitates your unsuccessful attempt not to laugh.', '“Were you?” Her smile widens. “Then I may need to hear your observations in some detail.”', 'Tell her what amused you', 'Say you were watching her') ]},
 
 'sabine': {'room':'library','activity':'letters','relaxed':'“For once, I should like to receive company without looking as if I expect a formal objection.”','daring':'“I have grown rather fond of allowing you to see when I am enjoying myself. This seemed an appropriate declaration.”','thanks':'“How agreeable. No elaborate defence of happiness required.”','tease':'“Do continue. I find your lack of diplomatic restraint quite refreshing.”','beats':[
 beat('The box of cancelled seals', 'Sabine opens a box of cancelled seals. “This one ended a warehouse lease. This one released an apprentice. Very dull objects, until you know who was relieved to see them broken.”', '“The apprentice’s. She had already repaid the loan twice. Someone finally read the small print aloud.”', '“The box was mine. Several of its contents had less straightforward journeys.” Her smile suggests she will tell you another time.', 'Ask which seal she kept first', 'Ask whether she stole the whole box'),
 beat('The overcomplicated love letter', '“I wrote an appalling love letter once,” Sabine says. “Three pages, two legal metaphors, and no actual invitation. The reply asked me to be specific.”', '“Supper on Thursday. It worked considerably better.” She folds a blank sheet. “A useful lesson in brevity.”', '“‘Should your affections be unencumbered by prior claim, I submit myself for consideration at a mutually agreeable table.’” Sabine covers her face with the letter. “I wanted supper. Please remember that before judging the sentence.”', 'Ask what she wrote back', 'Ask to hear the worst legal metaphor'),
 beat('A card with just her name', 'Sabine pushes a calling card towards you. “No titles. Just my name. I used to think a long introduction made people listen more carefully.”', '“People remembered the title and forgot the question. I would rather be answered than announced.”', '“Keep going. You have not reached my distinguished service to the tea tray.” She writes down the best part.', 'Ask what changed her mind', 'Invent an absurdly long title for her'),
 beat('A direct invitation', 'Sabine shuts her letter case. “I would like you to stay and talk. There: a complete invitation in ten words. I am improving.”', '“The author claims she attended two weddings on opposite sides of the river, both at noon, during a flood.” Sabine opens the memoir. “Then she describes the wine in loving detail. I believe the wine. I suspect somebody else’s wedding.”', '“Then sit closer.” She lets the request stand, watching for your answer with a pleased smile.', 'Accept and ask what she has been reading', 'Tell her you prefer her direct invitations') ]},
 'koharu': {'room':'workshop','activity':'making','relaxed':'“The tools can stay on the bench. I would like to find out who I am when I am not somebody’s next repair.”','daring':'“I made something for myself, and I like how I look in it. I would be pleased if you noticed.”','thanks':'“There. That was easier than pretending I did not care.”','tease':'“Careful. Compliments like that might encourage me.”','beats':[
 beat('The uneven book stand', 'Koharu produces a tiny book stand with one uneven leg. “My first. Made from a chair nobody wanted. I kept trying to improve it until my neighbour told me to put a folded card underneath.”', '“Perfectly. Infuriating woman.” She turns the stand over to show you the card still tucked beneath it.', '“You have a future selling furniture.” She sets it on the table and tests your sales pitch.', 'Ask if the card worked', 'Suggest calling the short leg adjustable'),
 beat('What is in her pockets', 'Koharu empties her pockets: a hinge pin, three offcuts and a button. “I was looking for my pencil. Apparently I have brought half a workshop instead.”', 'You separate the useful pieces from the splinters. The pencil turns up behind her ear. She asks you not to mention it.', '“Left: possibly useful. Right: definitely useful. Hidden pocket: things I have lost.” She finds another button.', 'Help her sort what is worth keeping', 'Offer to label her pockets'),
 beat('The marks beneath the table', '“A customer wanted every scratch removed from a table,” Koharu says. “Then recognised the height marks under the edge. His children had put them there.”', '“The loose joints. He kept the marks. I now ask before sanding anything with a history.”', '“Only if I have to crawl underneath. Dust in the hair should count as skilled labour.”', 'Ask what she repaired in the end', 'Ask whether she charges extra for detective work'),
 beat('The indignant wooden bird', 'Koharu sets a little carved bird on the table. “I made this without measuring it six times. The wings do not match. I like its offended expression.”', 'She points to two shallow cuts. “Most of the attitude is in the eyebrows. I may have borrowed yours.”', '“Then stop interrupting and admire it.” She laughs and turns the bird towards you.', 'Ask her to show you how she carved the face', 'Tell her it resembles its maker when interrupted') ]},
 'zahra': {'room':'smithy','activity':'forge','relaxed':'“The forge is out. I want soft cloth, a comfortable seat, and nobody asking me to lift anything.”','daring':'“I like being strong. I like being beautiful too. Tonight I felt like making both rather obvious.”','thanks':'“Good. No surprise in your voice. I appreciate that.”','tease':'“That is a look I could get used to.” She grins.','beats':[
 beat('The channel that looked level', 'Zahra lays a wooden channel on the table and pours in a little water. It pools at one end. “Looks level, does it not? My teacher let me discover that problem with a much larger channel.”', '“Water first, pride later. A straight edge helps, but water gives the final opinion.”', '“Boots, trousers, teacher. He laughed until I handed him the shovel.”', 'Ask how she learned to check the slope', 'Ask how wet that first lesson became'),
 beat('Carving the tiny beak', 'Zahra is carving a bird small enough to hide in her palm. “The beak keeps breaking. A larger bird would be easier, but that would be surrender.”', 'She rests it against a leather pad. “A sharp blade and very little force. That is the part people do not expect me to enjoy.”', '“A tempting fraud. Unfortunately, I would know.” She examines the bird and begins a smaller beak.', 'Ask to see how she supports the wood', 'Offer to call it a rare beakless species'),
 beat('The flooded-mill song', '“I sang while I worked today,” Zahra admits. “The rhythm helped. The tune apparently frightened someone in the corridor.”', 'Zahra sings, low and rough: “The miller asked the river, ‘Will you kindly wait till spring?’ The river took his doorstep. He had asked the wrong thing.” She taps the beat. “The words survive my singing better than the tune does.”', '“Good. Then they will not know whom to blame.” She counts you in and laughs at the first line.', 'Ask which song she was singing', 'Offer to sing badly with her'),
 beat('The finished bird', 'Zahra has finished the little bird. “The beak survived. I thought you should see it before I drop it behind something heavy.”', '“A fox. A seated one. Four standing legs would be asking for trouble.” She turns the bird so you can see its folded wing.', 'She raises an eyebrow, then smiles. “You could have led with that. There is room beside me.”', 'Admire the small details and ask what comes next', 'Say you came to admire the carver too') ]},
 'fenna': {'room':'common-room','activity':'tavern','relaxed':'“No trail gear tonight. A soft blouse and a chair I do not have to fold up before leaving.”','daring':'“I thought I might stay for the last dance. With you, if you are willing to risk my dreadful directions.”','thanks':'“Then we can take the evening at walking pace.”','tease':'Her tail sways. “Excellent. I was hoping for an accomplice.”','beats':[
 beat('The bench beside the road', 'Fenna points to a bench drawn on an old trail map. “Best stop on that road. Dry roof, decent view, and the owner only asked for one story in payment.”', '“The one about a mule refusing a bridge. I left out that the mule was right.”', '“No. He supplied the tea. I have some professional standards.”', 'Ask which story paid for her seat', 'Ask whether she charged the owner for the sequel'),
 beat('What happened to the cake', '“I shortened that mule story for years,” Fenna says. “I thought everyone wanted the clever ending. The interesting part was waiting together in the rain.”', '“A potter, two cousins who were not speaking, and a boy carrying a cake. By sunset we were all arguing about the cake.”', '“The cousins each demanded the larger slice. The boy cut the last piece in half, ate the crumb between them and said he had charged for arbitration.” Fenna laughs. “It was his cake. We had somehow forgotten that part.”', 'Ask who else was stranded there', 'Insist on hearing what happened to the cake'),
 beat('Your turn to tell a story', 'Fenna glances at her packed boots, then leaves them where they are. “I used to move on whenever I ran out of stories. I am discovering that other people have some.”', 'She interrupts once to ask about the least important detail, then catches herself and lets you finish.', '“Dangerous permission. I have an excellent account of a mule you may have met.” She grins.', 'Tell her a story from your own travels', 'Tell her she is allowed to repeat a favourite'),
 beat('The missing dance step', 'Fenna holds out a hand. “The tune has only four steps. I know three with confidence. Shall we find the fourth together?”', '“Left foot aside, right foot beside it, left foot back.” Fenna counts as you try. For the fourth step she attempts a turn, meets your shoulder and stops laughing long enough to say, “A bow. The fourth step should definitely be a bow.”', '“Only if you tread on both feet.” She draws you into the first step, still smiling.', 'Ask her to teach you the first three', 'Say you will follow if she promises not to run away') ]},
 'kaede': {'room':'training-yard','activity':'practice','relaxed':'“Practice is finished. I would like clothing that does not suggest I am about to lift a training post.”','daring':'“I can be careful and bold at the same time. Tonight I would like to be bold with you.”','thanks':'“Then I can stop pretending this was an entirely practical decision.”','tease':'“A worthy response.” She smiles with deliberate confidence.','beats':[
 beat('Rescuing half a cup', 'Kaede turns a chipped cup in her hand. “I caught it before it hit the floor. Then squeezed too hard. A very successful rescue of half a cup.”', '“Carrying filled cups. Slowly. Nobody applauds that sort of training, which may be why it works.”', '“You would disqualify me for spilling, then ask for more tea. I know your methods.”', 'Ask how she practised a gentler grip', 'Offer to judge a tea-carrying competition'),
 beat('A game without a lecture', 'Kaede lays out a strategy game. “I will explain the rules once. After that, you may beat me without receiving a lecture about how you did it.”', '“Take the centre and you can move in either direction, but both flanks remain exposed. Stay near an edge and you have less to defend, but less room to retreat.” Kaede withdraws her hand. “I recommend the centre. You are welcome to make me regret explaining it.”', 'She considers it. “An unexpectedly serious condition. Agreed.”', 'Ask which opening she recommends for a beginner', 'Ask whether the no-lecture rule applies when she wins'),
 beat('The surprising move', 'Kaede stops halfway through describing a lost match. “I keep explaining the move I should have made. What I actually enjoyed was being surprised.”', 'Kaede places her pieces across the centre and leaves one at the edge. “I expected an attack here.” She moves the opposing piece along the edge and behind her line. “I defended the route I wanted them to take. They declined.”', 'She studies your choice for far too long before realising what you are doing. “I deserved that.”', 'Ask her to show you the surprising move', 'Offer to surprise her with an obviously terrible move'),
 beat('An evening without a contest', 'Kaede clears the game away. “I would like an evening with you that I do not try to win. I am saying that aloud so you may remind me.”', 'She pours carefully and asks what has occupied your thoughts today. The board stays closed.', '“You already have it.” She leans closer, looking more amused than competitive.', 'Suggest tea and a conversation', 'Ask what counts as winning her attention') ]},
 'elowen': {'room':'infirmary','activity':'herbs','relaxed':'“I have put the remedies away. I would like an evening where neither of us needs to be made better.”','daring':'“I chose something lovely for no medicinal reason at all. I find I rather want you to notice.”','thanks':'“That is a pleasantly simple answer. I shall try not to complicate it.”','tease':'“I suspected you would be bad for my composure. Happily, it needs very little treatment.”','beats':[
 beat('The lemon-balm pot', 'Elowen offers you a crushed leaf to smell. “Lemon balm. People always ask what it treats. Today I planted it because I like the scent.”', '“In a cracked pot outside my teacher’s door. It survived several mistakes and one very determined cat.”', '“Only if you agree to go outdoors occasionally.” She tucks the leaf into her own pocket.', 'Ask where she first grew it', 'Ask whether she is prescribing a better afternoon'),
 beat('The alarm that noticed every candle', 'Elowen describes a ward that kept waking its owners. “It was meant to report smoke. It reported every candle. Strength was not the problem; the instructions were.”', '“Separate cooking smoke from a growing fire. Then explain the difference to the people using it. They needed to understand their own alarm.”', '“Its owners certainly did. They had become attached to blaming the chimney.”', 'Ask how she changed the instructions', 'Ask whether the ward complained about the criticism'),
 beat('Her own day', '“You asked how I was,” Elowen says. “I nearly answered with a list of everyone else. I am tired, pleased with the herb bed, and annoyed that I misplaced my scissors.”', '“The mint rooted. Two lemon-balm cuttings did not; I kept their soil too wet. The third has one new leaf.” Elowen brightens, then frowns. “And I left the scissors beside that pot. There. The report has finally been of some use to me.”', '“One person. Very discreet. I suspect the culprit is me.” She laughs and stays seated.', 'Ask about the part that pleased her', 'Offer a search party for the missing scissors'),
 beat('Tea made to your taste', 'Elowen sets down two cups. “I made yours the way you liked it last time. If I remembered incorrectly, tell me before politely drinking the whole thing.”', '“Too much mint?” Elowen asks. You say you would prefer a little less next time. She makes a note, then puts the pot away. “Now, an unrelated complaint: whoever calls scissors easy to keep track of has not owned mine.”', 'She smiles over the rim of her cup. “Good. I was hoping the tea would not receive all the credit.”', 'Taste it and give her an honest answer', 'Say you mainly came for the person pouring it') ]},
 'nyssara': {'room':'enchanting-room','activity':'enchanting','relaxed':'“The assay tools are away. I would like to feel at home without carrying evidence of what I can do.”','daring':'“I am accustomed to choosing every visible detail carefully. This one is meant to tell you I am pleased to be here with you.”','thanks':'“Good. I would rather be understood than explained.”','tease':'“You noticed the intended effect.” Her smile is small and unmistakable.','beats':[
 beat('Her maker’s mark', 'Nyssara draws her maker’s mark. “The broken line is intentional. It identifies my work even when the edge of an inscription wears away.”', '“My first master. He could identify a careless repair from the other end of a room. I preferred signing mine before he asked.”', '“A charm that rang at the wrong hour for six days. My name was perfectly legible.”', 'Ask who taught her to design it', 'Ask if she has ever signed something embarrassing'),
 beat('Rain in the stone channels', 'Nyssara pauses at the sound of rain. “At home, channels in the stone carried it past the workshops. I could tell a shower from a storm without seeing the sky.”', '“The sound, and knowing who was still awake from which bench lamp showed under a door.”', '“Regrettably, no. Stone is an excellent accomplice to a confident singer.”', 'Ask what she misses about those workshops', 'Ask whether the rain ever drowned out bad singing'),
 beat('The unenchanted pendant', 'Nyssara places a plain pendant on the table. “No enchantment. I liked the weight and the curve. I keep having to tell people it does nothing.”', '“A stall selling broken fittings. I filed one edge smooth. The seller looked disappointed when I refused the matching lock.”', '“It has failed repeatedly. I would have to offer a refund.” She puts it on anyway.', 'Ask where she found it', 'Suggest claiming it wards off tedious questions'),
 beat('Wearing it for your visit', 'Nyssara touches the pendant at her neck. “I wanted you to see this on me instead of on the worktable. That is the entire explanation.”', 'She listens without turning the compliment into a discussion of craftsmanship. “Thank you. I was hoping you would notice.”', '“Then my plan was more successful than the clock charm.” She smiles and moves her chair closer.', 'Tell her what you like about it', 'Say you had already noticed her') ]},
 'sylva': {'room':'conservatory','activity':'growing','relaxed':'“These leaves move more easily when I sit. I wanted to stay beside you without thinking about the next growing bed.”','daring':'“I chose the new leaves because I liked how they felt, and how I felt wearing them. I wanted to share that with you.”','thanks':'“Then I can simply enjoy being seen.” Her smile is warm.','tease':'“Yes, I did arrange them on purpose.” She laughs, quite unashamed.','beats':[
 beat('The empty seed pod', 'Sylva shows you a seed pod with a split along its side. “This one will not germinate. A traveller gave it to me after describing the tree. I liked her account too much to throw it away.”', '“Broad leaves, yellow flowers, shade at the edge of a busy road. She remembered the shade most clearly.”', '“Both. Stories require fewer pots.” She turns the empty pod carefully in her fingers.', 'Ask what the tree was like', 'Ask whether she collects stories or seeds'),
 beat('The crowded roots', 'Sylva sketches two plants with tangled roots. “I put these too close once. More food did not help. They needed more room below the soil.”', '“Slowly, while the soil was damp. I lost a few roots, but both recovered. I stopped trying to make every bed look full.”', '“Then I appoint you to explain the bare patch to impatient visitors.” She adds a third, very small plant to the sketch.', 'Ask how she separated them', 'Offer to defend an untidy planting bed'),
 beat('The stubborn cutting', '“I kept fewer cuttings this season,” Sylva says. “The parent plants recovered better. I should have done it sooner, but a full tray is satisfying to look at.”', '“A woody cutting with one remaining leaf. I nearly pulled it up, then noticed the leaf was still firm. A week later there was a pale root against the pot.” Sylva smiles. “I should have checked for firmness instead of demanding a new leaf every morning.”', '“Keeper of My Remaining Patience.” She laughs. “Too long for the label, unfortunately.”', 'Ask which plant surprised her', 'Suggest giving the stubborn cutting a title'),
 beat('The copper-edged leaf', 'Sylva has kept a fallen leaf because of its copper edge. “You said you liked this colour. I wanted to see whether you would choose it again.”', 'Against the yellow-green leaf, the copper edge nearly disappears. Against a blue-green one, it stands out. “That is why I disagree,” Sylva says, moving the leaves so you can compare. “I want to see the edge, not find the closest match.”', 'She holds the leaf near her shoulder. “A flattering answer. Now give me the honest one too.”', 'Compare the colours with her', 'Tell her she wears the colour better') ]},
}

ACTIVITIES={
 'common-room':{'title':'A tavern table for two','opening':'A game board and two cups are waiting on the table. Choose a game or sit down to talk.','view':'householdWork','use':'No phase cost or resource reward. A distinct first shared activity is remembered.'},
 'library':{'title':'Read something unnecessary','opening':'You set the project notes aside and choose a passage neither of you needs to memorise.','view':'research','use':'Compare completed research through Resident stories when you want a practical shared work phase.'},
 'kitchen':{'title':'Cook at the same table','opening':'You talk over an ordinary shared meal and compare the small kitchen habits that make it feel like home.','view':'restoration','use':'This social scene consumes no stored ingredients. Harvest and preserving bonuses remain governed by staffed garden work.'},
 'conservatory':{'title':'Tend a quiet corner','opening':'You compare new growth, turn a pot towards the light and leave a little space for what neither of you expected.','view':'restoration','use':'The conversation is free. Material harvests still require the existing garden assignments and Advance.'},
 'training-yard':{'title':'Practice at an easy pace','opening':'You compare balance and footwork without keeping score, pausing whenever the conversation becomes more interesting.','view':'headquarters','use':'This friendly scene grants no advancement. Fund the yard’s actual drills for their listed one-time training awards.'},
 'hot-spring':{'title':'Company by the warm water','opening':'You choose a comfortable place by the thermal pools. Sitting on the dry ledge is as welcome as bathing. Steam softens the distant voices.','view':'headquarters','use':'Optional and free. Neris’s installed pools offer a separate two-phase thermal study with its existing one-time award.'},
 'chapel':{'title':'Share a quiet observance','opening':'You sit together in the chapel. If your companion wants to talk about her observance, you listen; otherwise you share the pause.','view':'headquarters','use':'No required belief, phase cost or numeric reward.'},
 'workshop':{'title':'Compare the things you keep','opening':'With the tools safely put aside, you discuss the well-used objects that are worth more than their materials.','view':'workshop','use':'Crafting bonuses come from the restored workshop and installed specialist bench; conversation does not create objects.'},
}

# Two-part household scenes; everyone must be resident and home, and their first personal route scene must be remembered.
PAIRS=[
 ('koharu','zahra','workshop','A joint worth arguing over','Koharu wants a repair to remain visible. Zahra wants the join to survive a careless hand. They realise they are defending different parts of the same object.','Ask them to show both methods','They place both test samples on the bench and label each with its maker’s name and method.','Ask what each method protects','Koharu says memory; Zahra says fingers. Neither considers that a small thing.','The handle that kept both ideas','The repaired handle has Zahra’s dependable fit and Koharu’s visible seam. “Compromise,” Koharu says. “Good workmanship,” Zahra corrects, smiling.'),
 ('fenna','iona','common-room','Two versions of a journey','Fenna tells the interesting route. Iona supplies the dates. Between them, a perfectly ordinary journey is becoming a very good story.','Keep both versions','Iona adds the detour in the margin; Fenna admits that knowing the day does help.','Ask about the person at the destination','Both stories arrive at the same welcoming door, and both women soften.','A map with room to wander','Iona has made a tidy route card. Fenna has added a note: leave time for the second cup. They are rather pleased with their collaboration.'),
 ('tamsin','sylva','conservatory','The leaf you almost threw away','Tamsin asks which trimmings are useful. Sylva asks what the kitchen actually enjoys using. Neither wants a garden planned entirely on somebody else’s assumptions.','Let the kitchen choose a trial','They agree on a modest shared growing plan, with space to change their minds.','Let the garden explain its limits','Tamsin revises her wish list; Sylva finds one more thing she can offer.','A meal remembered in the beds','Their new notes distinguish what grows well from what people like to eat. “A radical form of cooperation,” Tamsin says. Sylva laughs.'),
 ('elowen','nyssara','infirmary','A ward with an honest label','Elowen wants a ward’s limits written plainly. Nyssara dislikes calling a careful result a promise. The disagreement lasts until they notice they agree.','Ask for the limits first','They write a clear description of what the ward does, and what it cannot do.','Ask how someone should use it','Nyssara explains the working; Elowen translates the explanation into useful instructions.','Two hands on the same notes','A neatly labelled ward sample rests between them. Elowen has left Nyssara’s maker’s mark visible; Nyssara has kept Elowen’s plain-language note.'),
 ('aurelia','kaede','training-yard','Knowing when to stop','Kaede wants a cleaner drill. Aurelia wants the next person to know when to rest. They begin designing a practice that can be stopped without embarrassment.','Make the pause part of the drill','Aurelia demonstrates the rest signal, and Kaede practises responding immediately.','Ask the learner to set the pace','They agree to ask before increasing difficulty, and discover that both prefer it.','The practice without an audience','They run the drill quietly, pause when asked and exchange a satisfied nod. “A good session,” Kaede says. “And a good ending,” Aurelia adds.'),
 
 ('mira','sabine','library','The book neither would recommend','Mira has found Sabine reading the very sentimental story she hides behind a respectable history. Neither can sustain the accusation of poor taste.','Defend an enjoyable ending','They form an entirely unofficial defence of stories that let people come home.','Ask them to read the best passage','Sabine takes the narration; Mira supplies an appalling dramatic voice.','The unofficial shelf','Two unfashionable novels share a discreet shelf. A note in two different hands asks the next reader to put them back where they can be found.'),
 ('zahra','tamsin','kitchen','A shelf at the right height','Zahra offers to fit a shelf; Tamsin points out that useful is not the same as high enough to impress a visitor. They begin measuring from the hands that will use it.','Ask Tamsin to mark the reach','Zahra checks the mark twice and asks where the cups actually belong.','Try it before fixing it','They test the arrangement with empty cups and a great deal of commentary.','A useful place for ordinary cups','The shelf is neither grand nor ingenious. Tamsin reaches it comfortably; Zahra looks more pleased than she did at the first design.'),
]

# Follow-up choices answer the particular conversation, not a shared placeholder.
PAIR_FOLLOWUPS={
 ('koharu','zahra'):(
  'Ask how the handle keeps both designs.',
  '“The seam stays visible here,” Koharu says, turning the handle. Zahra runs a finger along its edge. “And this lip keeps a hand from catching it. You can show the repair without making someone feel it every time they lift.”',
  'Ask whether they still disagree about the finish.',
  '“She would oil everything,” Koharu says. “She would leave tool marks on a spoon,” Zahra replies. They look at the handle. “This one is finished,” they say together, then laugh.'),
 ('fenna','iona'):(
  'Ask what belongs on the route card.',
  '“The turning, the crossing and the hours,” Iona says. Fenna taps her addition. “And the house where we were offered a second cup.” Iona leaves it on the card. “A landmark. I will allow it.”',
  'Ask what happened during that second cup.',
  '“Our host wanted to know why the journey had taken so long,” Fenna says. Iona folds her arms. “I supplied the dates.” Fenna grins. “And I supplied the explanation for the dates. A balanced account.”'),
 ('tamsin','sylva'):(
  'Ask which kitchen request changed the planting notes.',
  '“Fewer leaves with a bitter stem,” Tamsin says. Sylva points to the harvesting note. “Pick these before the stems toughen. We did not need to replace the plant; we needed to agree when the kitchen would use it.”',
  'Ask what they would cook from the trial bed.',
  '“Something that tastes of the leaf before we add half the pantry,” Sylva says. “A modest demand from the gardener,” Tamsin replies. They settle on a simple broth to try later, with the stronger leaves added one at a time.'),
 ('elowen','nyssara'):(
  'Ask to hear the revised ward label.',
  'Nyssara reads: “Test sample. No treatment claim. Keep the test conditions with the result.” Elowen points to the final line. “And ask before using it on a person. That belongs in large writing.”',
  'Ask which phrase they removed.',
  '“Reliably beneficial,” Elowen says. “It did not say what benefit.” Nyssara gives a thin smile. “I replaced it with the measured result. Much less flattering. Considerably more useful.”'),
 ('aurelia','kaede'):(
  'Ask them to show the stop signal.',
  'Aurelia raises an open hand. Kaede lowers the practice weapon at once. “No finishing the movement to prove I had it,” Kaede says. “We can start again after both people are ready.”',
  'Ask who found stopping more difficult.',
  '“She stopped the drill and then began explaining three corrections,” Aurelia says. Kaede winces. “That was outside the rules.” Aurelia raises her hand again. This time Kaede laughs and lets the silence stand.'),
 ('mira','sabine'):(
  'Ask them to read the passage they defended.',
  'Sabine reads: “I crossed seven kingdoms to find you.” Mira supplies the reply in a nasal voice: “You might have answered my letter.” Sabine closes the book, laughing. “That is not the next line.” “It should be.”',
  'Ask what the shelf label should say.',
  '“Books of Questionable Merit,” Mira proposes. “That We Intend to Keep,” Sabine adds. They put both lines on the label, with enough room underneath for another title.'),
 ('zahra','tamsin'):(
  'Ask what changed between the first and final shelf plans.',
  '“The first mark was at my shoulder,” Zahra says. “Mine is lower,” Tamsin replies, reaching for a cup without stretching. Zahra nods. “I measured the wall before asking who would use the shelf.”',
  'Ask whether the cups have stopped migrating.',
  '“Mostly,” Tamsin says. “One keeps finding its way to the music box.” Zahra looks at the cup in her hand. “The shelf remains available to it. I cannot account for its social life.”'),
}
PAIR_FOLLOWUPS.update({
 ('sabine','aurelia'):(
  'Ask what ends the escort record.',
  '“The agreed destination, the time of arrival and confirmation that the escort is finished,” Sabine says. Aurelia taps the final line. “Then the next watch knows there is nobody to follow. I want that spoken as well as written.”',
  'Ask to hear their demonstration goodbye.',
  '“Your escort is complete. Good evening,” Aurelia says. Sabine waits. “No supplementary inquiry?” “No.” “You have ruined an excellent opportunity for paperwork.” Aurelia bows, entirely unrepentant.'),
 ('velis','tamsin'):(
  'Ask how much spice belongs in the recipe.',
  '“Half the first amount,” Tamsin says. “At full strength it hid everything else.” Velis nods. “I bought it for the flavour. I concede that tasting the supper as well is an advantage.”',
  'Ask whether Velis would make the detour again.',
  '“For the grower and the spice, yes,” Velis says. Tamsin moves the pot away from her reaching hand. “Then ask for the recipe next time. Seconds are available without renegotiating the route.”'),
 ('velis','fenna'):(
  'Ask which note matters when the weather turns.',
  'Fenna points to the crossing. “If this rises, take the longer track.” Velis points to the breakfast stop. “And this is where you can wait under a roof. A shorter distance is not much comfort in wet clothes.”',
  'Ask what they disagreed about on the route.',
  '“Whether breakfast counts as a delay,” Fenna says. “Only when someone orders a second plate,” Velis replies. Fenna looks wounded. “I was checking consistency. You taught me to compare samples.”'),
 ('rhess','aurelia'):(
  'Ask how the relief knows it has taken over.',
  '“I give the report, hand over the lamp and wait for an answer,” Rhess says. Aurelia nods. “Then you leave the window to the next watch. You do not need to watch them watching it.”',
  'Ask what Rhess wants to do with her time off.',
  '“Finish carving the bird’s tail,” Rhess says. Aurelia slides a chair toward her. “Then I recommend a seat facing the table.” Rhess sits, glances at the window once, and takes out the little carving.'),
})

SPECIALIST_VOICES={
 'koharu':('“I want a bench that makes the next repair easier, not one that makes me look indispensable.”','“There. Enough room for somebody else’s hands beside mine.”','“The good part is watching somebody try their own method here.”'),
 'zahra':('“Fit the station to the work and the worker. The smith should not have to wrestle both.”','“Now the useful tools are where a tired hand expects them.”','“A smoother job is a fine thing. Coming away with energy left is finer.”'),
 'fenna':('“The best tavern notices tell you who can help, not who wants to sound important.”','“A place for routes, spare thread and names worth remembering.”','“Somebody left a useful note without being asked. That is when an exchange starts working.”'),
 'iona':('“A good dispatch desk lets a letter leave without losing the person behind it.”','“The outgoing work has a place. So do the replies worth keeping.”','“We are doing more useful correspondence without asking anyone to write through supper.”'),
 'kaede':('“I want a practice circle where control matters more than an audience.”','“The marks are clear. The stop signal is clearer.”','“I like seeing someone finish a drill pleased, rather than merely exhausted.”'),
 'tamsin':('“Preserving is mostly arranging things so tomorrow’s cook can be grateful to today’s.”','“Nothing glamorous. A pantry that lets good work last.”','“Less wasted effort, more choice about what to do with a harvest. That feels like care.”'),
 'elowen':('“Preparation should have a quiet place. I cannot promise an easy day, but I can help us meet it ready.”','“There is room to prepare one more working without crowding the others.”','“I like seeing people choose what they need, rather than what they are afraid to leave out.”'),
 'nyssara':('“An assay bench should make uncertainty visible. That is how an enchanter earns trust.”','“A measured sample, a clear result and no theatrical promises.”','“The useful result is knowing why this material will hold the working.”'),
 'neris':('“Warmth should be adjustable. Comfort is not a single answer for every body.”','“Try the dry ledge first, if you prefer. The pools are an invitation.”','“Someone stayed simply because it felt pleasant. I call that a good design.”'),
 'aurelia':('“A watch light should help someone see without making every window feel observed.”','“The shutters work from a resting hand. A tired watcher deserves good tools.”','“A clear briefing and an ordinary quiet watch. I am learning to value both.”'),
 'sylva':('“Give new growth room and a sensible place to begin. The rest is attention.”','“These beds will support more cuttings while people are here to tend them.”','“Useful growth, with enough room for a few surprises. I like what we made.”'),
}

ACTIVITIES.update({
 'smithy':{'title':'Talk while the forge cools','opening':'With the fire made safe, you compare the small decisions that make a well-used tool comfortable in the hand.','view':'headquarters','use':'The conversation is free. Actual metalwork still needs funded forge jobs and assigned phases.'},
 'command-room':{'title':'Leave space beside the map','opening':'You set the dispatches aside and compare places you would like to visit without a report to deliver.','view':'expeditions','use':'To gain a one-survey field briefing, use the command room’s actual one-phase briefing job.'},
 'infirmary':{'title':'A cup without a diagnosis','opening':'You settle by the dry-herb shelves with no ailment to explain and no expectation that either person must improve the other.','view':'spells','use':'The installed specialist alcove adds its prepared-spell slot through the normal spellbook. This scene grants no healing or additional slots.'},
 'enchanting-room':{'title':'Look at an ordinary lovely thing','opening':'The assay bench is clear. You examine a pleasing, unenchanted object and let its shape be a sufficient reason to keep it.','view':'equipment','use':'Enchantment and material production remain separate funded jobs. No item is created by this conversation.'},
 'guard-barracks':{'title':'Company after the watch','opening':'With the watch notes closed, you discuss the ordinary comforts that make returning home feel different from simply arriving somewhere.','view':'headquarters','use':'Aurelia’s fitted watchroom supports its actual briefing and one-time watch drill. This social pause assigns no guards.'},
})
ACTIVITY_THOUGHTS={
 'mira':{'common-room':'“I like a game where the conversation can win.”','library':'“Read that bit again. Not because it is important; because you enjoyed it.”','kitchen':'“A recipe is a remarkably opinionated kind of history.”','conservatory':'“An archive that keeps growing new pages. Charming and deeply inconvenient.”','training-yard':'“I have decided a graceful pause counts as progress.”','hot-spring':'“A book would be a mistake here. I suppose I shall have to enjoy the company.”','chapel':'“Some thoughts improve when nobody tries to catalogue them.”','workshop':'“Someone’s useful little correction. That is the part I want to keep.”','smithy':'“A worn handle can tell you where the work actually happened.”','command-room':'“I vote for somewhere with a good second-hand bookshop.”','infirmary':'“No advice? An unusually restful consultation.”','enchanting-room':'“A lovely thing that does nothing. I defend its right to remain so.”','guard-barracks':'“The best watch report must surely be ‘everyone came home’.”'},
 'tamsin':{'common-room':'“Stay for another round. I promise not to tidy the board while you are thinking.”','library':'“I like pages that remember being opened.”','kitchen':'“The useful part is cooking for the people who are actually here.”','conservatory':'“Tell me what likes to grow before I make a menu of it.”','training-yard':'“I am learning not to apologise for asking for a slower demonstration.”','hot-spring':'“Someone else can keep track of the towels for five minutes.”','chapel':'“It is nice to share quiet without having to fill it.”','workshop':'“This is the bowl I would mend instead of replace.”','smithy':'“Fit it for the hand that will use it. I have opinions about ladles.”','command-room':'“A journey should include a sensible place to eat.”','infirmary':'“I brought company, not another job.”','enchanting-room':'“If it is lovely without a charm, we can leave the charm off.”','guard-barracks':'“A clear place for somebody’s supper is part of a good watchroom.”'},
 'iona':{'common-room':'“An evening without an itinerary. I think we can manage.”','library':'“I enjoy a second account more than a perfect copy.”','kitchen':'“Recipes travel astonishing distances without once asking for a map.”','conservatory':'“A place worth staying in is a very good reason not to plan a journey.”','training-yard':'“Tell me where you want to stop before we begin.”','hot-spring':'“No dispatch is going to improve by being read in the steam.”','chapel':'“We need not have arrived by the same road to sit together.”','workshop':'“Keep the travelling marks. They tell me somebody brought it home.”','smithy':'“The practical detail is usually what gets somebody safely to the next stop.”','command-room':'“For this map, let us mark where we would like to linger.”','infirmary':'“Sometimes the most useful message is that nothing is urgently needed.”','enchanting-room':'“No annotation required. I like the shape too.”','guard-barracks':'“A place to return to changes the whole meaning of a route.”'},
}
# Each remaining companion contributes a particular perspective to every room,
# with a different activity-specific question from the scene opening.
PERSPECTIVES={
 'aurelia':'“I like discovering what we do when nobody needs rescuing.”',
 'neris':'“Comfort is easier to notice when I stop trying to measure it.”',
 
 'sabine':'“You need not make a polished occasion of it. I am enjoying this one.”',
 'koharu':'“The useful little detail is usually where somebody took care.”',
 'zahra':'“There is a difference between showing you can and asking what would help.”',
 'fenna':'“This is the part I would leave in the story, even if it goes nowhere.”',
 'kaede':'“I am practising letting a good moment end without trying to win it.”',
 'elowen':'“We can leave a pleasant thing pleasantly uncomplicated.”',
 'nyssara':'“I enjoy having something to share that requires no demonstration.”',
 'sylva':'“Some things flourish when they are given room rather than instructions.”',
}

ACTIVITIES['dungeons']={'title':'A quiet review at the ward desk','opening':'At the unoccupied ward desk, you compare the labels on a demonstration set of keys. No occupant’s private case notes are opened. The conversation can remain an ordinary moment of company.','view':'containment','use':'This conversation grants no work or recruitment progress. Sabine’s installed release-key register shortens newly funded chamber and care projects through their normal controls.'}
SPECIALIST_VOICES['sabine']=(
 '“A release key should be easy to identify under pressure.” Sabine sketches the register beside the costed plan. “I can fit clear labels and a dependable checking method. Shall we agree the work?”',
 'Sabine checks an unused key against the register. “Key number, holder, return date. Good. The next person on duty can read this without asking me.”',
 '“Good records save time without skipping the important questions.” Sabine closes the demonstration page. “We can spend the time elsewhere. I have a comedy I would like you to hear.”')
ACTIVITY_THOUGHTS.setdefault('sabine',{})['dungeons']='“We have checked the labels. We may now have a conversation that does not require filing.” Sabine puts the demonstration keys away and turns her chair toward you.'
PAIRS.append(('sabine','aurelia','guard-barracks','The other side of the watch',
 'Aurelia asks how a night watch knows an escort has finished. Sabine points to the return column. “Preferably before it begins following someone who has already been released.” They work toward the same clear handover.',
 'Make the handover explicit','Aurelia adds a spoken confirmation; Sabine leaves a clearly marked end to the record. Neither relies on somebody guessing.',
 'Ask what each woman needs to know','Aurelia wants a safe route. Sabine wants its destination written correctly. They find room for both on one page.',
 'An unmistakable full stop','Their demonstration handover ends with an ordinary goodbye. “A promising innovation,” Sabine says. Aurelia smiles. “Let us practise keeping it that simple.”'))
