"""Non-graphic, two-adult romantic scenes. Progress changes familiarity, not entitlement.

Each row: repeat title, invitation, response, milestone title, invitation, response.
Scene endings are only exposed by the engine after an explicit choice.
"""
STAGES=('First affection','Affectionate closeness','At ease together','Private evenings')
ROWS={
'mira':[
 ('The shared bookmark','Mira sets a ribbon between the pages. “May I borrow your hand until we find out what happens next?”','You take her hand while she reads the next paragraph. The heroine makes a disastrous proposal, and Mira stops to object to its wording. “No, do not let go. I can argue with a fictional woman one-handed.”','A margin kept for you','“I used to leave these margins empty,” Mira says. “I think I would like a little more of you in my ordinary days.”','You tell her you would like that too. She writes the date beside a passage you both love, then asks for a kiss. It becomes a private reference neither of you needs to explain.'),
 ('A chapter read aloud','Mira brings a book of dreadful poems. “Would you read with me? I refuse to perform all these voices alone.”','You sit shoulder to shoulder. Mira gives the villain a nasal voice: “Yield, for my sorrow is mightier than your sword.” You answer as the hero: “Then why did you bring six swords?” Mira loses her place laughing and leans against you. “At last. A question the poet should have asked.”','Her unfinished sentence','Mira closes the book. “I sometimes start composing a clever answer before you have finished speaking. If I do that when you are telling me something important, will you stop me?”','You say you will, and ask her to do the same for you. “Agreed. Including when I have thought of an excellent joke.” She takes your hand and waits while you finish the thought she interrupted.'),
 ('The lamp left low','In a quiet room, Mira sets tomorrow’s reading aside. “A kiss, and then we can decide whether the book gets another chance?”','You kiss her and settle beneath the same blanket. Mira asks which part of the day you would happily repeat. Her answer is your visit. She puts the book aside, and the scene fades as you draw closer.','The morning bookmark','Mira turns an old bookmark over in her hand. “I like being here after the occasion is over. Would you keep making room for evenings like this?”','You agree, without turning tonight into a promise about every night. She leaves the bookmark beside tomorrow’s cups. A last kiss ends the conversation; the rest of your evening remains private.')],
'tamsin':[
 ('The second warm cup','Tamsin puts two cups on the table, then offers her hand. “Company first. You may tell me the tea is excellent later.”','“The customer had written ‘A suspiciously convenient horse’ beside the hero’s escape,” Tamsin says. “He asked me to preserve that complaint even if I lost the page number.” You ask whether the horse returns. “In the final chapter. He underlined it twice.” She laughs and reaches for your hand.','A seat she asks for','“I keep offering you a seat,” Tamsin says. “Today I would like to ask whether you will sit beside me.”','You move beside her. She asks for a kiss, and you meet her halfway. For once she is comfortable leaving the cups where they are.'),
 ('Let someone else pour','Tamsin settles on the cushions. “I would like a little fuss made over me. Is that an invitation you can accept?”','You bring the tea and a blanket. Tamsin tells you how she once repaired the wrong identical notebook, then had to explain why a shopping list had received the finest stitching in the workshop. You are still laughing when she leans against you.','The request she nearly swallowed','Tamsin starts to stand when a distant door closes, then sits back. “Nobody called. I was about to volunteer away our evening.”','You ask what she wants instead. She takes your hand and says, “This.” You stay together while she lets the small, unfamiliar answer be enough.'),
 ('The notebook can wait','Tamsin leaves her notebook outside the quiet room. “Could tonight be ours, with nothing to organise afterward?”','You join her under the blanket and share a kiss. Tamsin asks whether you prefer rain against the window or a completely silent night. You disagree, gently, until the conversation trails off and the scene closes on your evening together.','A welcome she can receive','“I know how to make someone feel welcome,” Tamsin says. “I think I am learning how to believe it when you welcome me.”','You tell her you want evenings like this too: no repairs to deliver, no guests to organize, just time together. Tamsin kisses your cheek and settles beside you. The scene ends with the notebook left closed.')],
'iona':[
 ('A small encore','Iona holds out her hand. “One turn around the room? We can be magnificently bad at it.”','You take her hand and attempt the dance. On the second turn you both step the same way and nearly collide. Iona steadies you, laughing. “We have discovered a new step. Let us never repeat it.”','The step you remember','Iona begins the same little dance, then stops. “You remembered where I trip. I rather like being known in such an unflattering detail.”','You tell her the detail is one of your favourites. She asks for a kiss at the end of the dance. This time you both remember the pause.'),
 ('Without an audience','Iona puts away a letter from home. “The musicians have changed venues again. Sit with me and tell me whether you can make sense of this.”','Iona unfolds the letter again. “Listen: ‘We are no longer at the riverside hall, for reasons obvious to everyone.’ I have been away for months.” You suggest a flood. “Plausible.” A feud over the drummer. “More plausible.” An invasion of dancing geese. She leans against your shoulder. “I shall ask about the geese first.”','The quiet is hers too','“You will tell me if I become dull?” Iona asks, then shakes her head. “No. What I mean is: may I be quiet with you?”','You welcome the quiet. She lets your joined hands rest between you, no flourish required. Eventually she smiles at how little either of you needed to add.'),
 ('After the final measure','Iona welcomes you into a quiet room. “One dance, perhaps. Then we can stop keeping count.”','After the dance, Iona asks for a kiss. You sit together and she opens a map at the riverside market. “I want to go when I have no measurements to take. There is a stall that sells sugared peel, and I resent knowing its location better than its flavours.” You talk about a visit for pleasure before drawing close again.','An ordinary return','Iona folds away a travel map. “I would like coming back to mean finding you, without needing to make an occasion of it.”','You tell her that sounds like a homecoming worth keeping. She kisses you and rests her forehead against yours. The evening closes with tomorrow’s plans still open.')],
'aurelia':[
 ('Beyond the duty board','Aurelia sets down her gloves. “Would you walk with me? No patrol route. You may choose the turning.”','You walk hand in hand. Aurelia stops to point out a swallow rebuilding beneath a crooked lintel. She remembers the same bird attacking a broom last spring. “Determination is admirable. Its choice of enemy was questionable.”','The unscheduled turning','Aurelia pauses where your walk usually ends. “There is nowhere I need to be for a while. May I stay here with you?”','You stay. She asks for a kiss, and afterwards neither of you treats the extra time as something stolen from a more important task.'),
 ('A watch willingly handed over','“The next watch is covered,” Aurelia says. “I checked once. I am resisting checking again. Will you sit with me?”','You sit close and ask about her first night on watch. She admits she mistook her own reflected lantern for a second patrol. Your laughter earns a raised eyebrow before she joins in and takes your hand.','Someone she can lean on','Aurelia admits she has been tired longer than she meant to say. “I do not need you to fix the watch. I would like you to know.”','You listen and ask whether an embrace would help. She says yes. Resting against you feels less like dropping her guard than letting you share the truth.'),
 ('The gloves outside','In a quiet room, Aurelia leaves her gloves by the door. “No reports tonight. Would you like to stay close for a while?”','You share a kiss and settle into an embrace. Aurelia asks you to help choose a story to read tomorrow; tonight, she says, she would rather stay where she is. The scene closes with her resting beside you.','A promise with room in it','“If duty calls tomorrow, I will answer,” Aurelia says. “I want you to know I will also make a point of coming back to us.”','You agree to keep making time without counting every interruption as a failure. She kisses you with an easy smile. For tonight, the watch belongs to someone else.')],
'neris':[
 ('No result to record','Neris turns her notebook face down and holds out her hand. “Would you sit close? The light is good here.”','You hold her hand while the light moves over your fingers. Neris points out a narrow blue edge and asks whether you can see it too. Your different descriptions become a cheerful argument about the names of colours.','A certainty she chooses','“I cannot prove how every evening will feel,” Neris says. “I can tell you that I would like another like this one.”','You tell her you would too. She asks for a kiss, then resists describing it as evidence. The memory is allowed to stand on its own.'),
 ('The answer can wait','Neris lifts an old cup. “This design caused me a great deal of trouble. Sit beside me and I will tell you why.”','Neris taps the old cup and lets its clear note ring out. “The customer said, ‘It leaks.’ I said, ‘Listen to the tone.’ He said, ‘I cannot drink the tone.’” You laugh, and she leans against you. “An unanswerable criticism. I kept the cup and returned his money.”','A question without a test','“When I ask whether you are happy here, I do not want the correct answer,” Neris says. “I want yours.”','You explain that you sometimes want company even when you have little to say. She asks you to tell her when that happens instead of staying away. You agree, and she takes your hand.'),
 ('Beyond the notebook','Neris puts her notebook away. “I would like an evening with you. Will you stay?”','Neris asks which cup you would save if she could keep only one. You choose the finely etched blue one. “Predictable. I would keep the chipped first attempt. It reminds me to test the base before admiring the rim.” She kisses you, pleased that you ask to see it, and settles beside you.','A useful kind of unknown','Neris smiles at the unmade plans between you. “I used to find this much uncertainty troubling. With you, I think I can leave some of it for tomorrow.”','You agree that tomorrow can have its own questions. She draws close after asking, and you share a kiss. Neither of you reaches for the notebook.')],

'sabine':[
 ('An entrance she abandons','Sabine begins a sweeping greeting, catches your expression, and laughs. “May I start again? I wanted to hold your hand.”','You take her offered hand. Sabine describes a letter whose polite wording concealed a spectacular argument about a borrowed ladder. “Three pages to say ‘bring it back’.” She asks how you would have written the reply.','The unpractised pause','Sabine loses the thread of a compliment. “I had a much better line prepared. May I kiss you instead?”','You say yes. Afterwards she lets the pause remain unfilled, smiling at you without searching for an elegant ending.'),
 ('No audience tonight','Sabine puts aside a half-finished letter. “Sit close. I want to show you what I nearly wrote.”','Sabine reads the formal draft: “Your attendance would confer distinction upon an evening of—” She stops and shows you the replacement. “Come for supper. Bring your appetite.” You prefer that one. “So did the recipient. The reply was ‘Gladly.’ A devastating defeat for distinction.” She folds the papers away and takes your hand.','What the flourish conceals','“I am good at making a moment look effortless,” Sabine says. “Sometimes that makes it difficult to admit when I need kindness.”','You ask what kindness would look like tonight. She chooses a quiet embrace and no advice. You give her both, and she allows the answer to be that simple.'),
 ('The curtain left open','In a quiet room, Sabine smiles without rehearsing it. “A private evening? No grand entrance required from either of us.”','Sabine asks what you noticed when you first met. You mention the carefully timed smile. “I was hoping you would notice it. Then you asked a sensible question and I forgot my next line.” She laughs at herself and leans closer. “I liked that you waited for the answer.” You ask to kiss her again; she agrees.','Her own way of staying','Sabine glances toward the door, then back at you. “I like that staying here is something I can choose. Tonight, I would like to.”','You welcome her choice without treating it as something owed. She takes your hand and kisses you. The rest of the evening belongs to two people who are free to ask for what they want.')],
'maren':[
 ('The sound little clasp','Maren brings a little wooden hinge. “I wanted to show you this. Then I would like you to stay for a while.”','Maren turns the wooden hinge so you can see the offset pin. “The door settles before these two faces touch. That is why it does not click.” You close it once and hear only the wood slide. She takes your hand. “You may inspect the pin again later. I did also come to see you.”','An excuse retired','Maren arrives empty-handed. “I thought I would try coming to see you without bringing a repair.”','You tell her she has brought exactly the company you wanted. She asks for a kiss, then grins at how well the unprepared visit is going.'),
 ('Tools on the shelf','Maren stretches her tired hands. “Sit with me? I have been thinking about the worst chair I ever repaired.”','Maren sketches a chair with a high rail exactly where the sitter’s elbows should go. “The maker said it encouraged good posture. I think it encouraged standing.” You suggest lowering the rail. “That was my proposal. The owner asked whether I could raise the sitter instead.” She leans against you, laughing.','Something that needs listening','“I keep offering to mend things when I visit,” Maren says. “Sometimes I cannot tell whether someone wanted my company or simply knew I would fix the door. I do not want to start doing that here.”','You tell her you want her visits even when nothing needs repair. “Then ask me to stay before showing me the hinge,” she says. You do, and she takes your hand. “Yes. I would like that.”'),
 ('Tomorrow’s work','Maren puts tomorrow’s plans away. “I would like to spend tonight with you. The repairs can wait.”','You kiss her and draw close beneath the blanket. Maren admits she can still hear one squeaking hinge from here. You promise it will survive until morning. She agrees, and the scene fades with her tools left untouched.','The care that lasts','“I like making things that endure,” Maren says. “With us, I think the important part is remembering to ask how we are doing.”','You answer and ask her in turn. A small, honest conversation becomes a kiss. The evening closes with nothing fixed in place, but something worth continuing to care for.')],
'brakka':[
 ('A quiet place beside her','Brakka pats the bench beside her. “I saved you a seat. Want to hear how the carving is going?”','You take her hand and sit beside her. Brakka tells you how a tiny carving defeated three evenings of patient work because she kept making the beak too thin. She has kept the failed birds in a row, each looking more indignant than the last.','The careful invitation','Brakka smiles, then looks briefly at your joined hands. “I would like to kiss you. Is that something you would enjoy too?”','You say yes and meet her gently. Afterwards she keeps your hand in hers, no longer trying to make the invitation sound less important than it was.'),
 ('Nothing to carry','Brakka sits beside you. “I remembered the music-box tune. May I try singing it while you are here?”','You lean together while Brakka hums the music-box tune. Her voice suits its lower notes better than she expected. When you tell her so, she tries it once more, then rests her head against yours.','The chair she need not earn','“Sometimes I feel I should bring something useful,” Brakka admits. “Even when I know why you asked me here.”','You tell her you wanted her company, and give her time to believe it. She asks for an embrace. The chair beside you becomes a place she can take without offering payment.'),
 ('A little room to rest','In a quiet room, Brakka offers her hand. “An evening together? We can decide what feels comfortable as we go.”','Brakka asks whether you would like to hear the remembered song. You say yes. “It ends with the boatman coming home with one oar and an excellent explanation. I have always suspected the explanation cost him the other oar.” She sings softly beside you, then welcomes your kiss.','The small thing that stays','Brakka turns a simple keepsake between her fingers. “I remember little evenings more clearly than grand occasions. I would like us to keep having them.”','You agree. She sets the keepsake down, asks to draw you close, and smiles when you welcome her. Tonight becomes another small thing worth remembering.')],
'fenna':[
 ('No wager attached','Fenna holds out her hand. “Dance with me? I promise to explain at least most of the steps.”','You follow her lead through a few dance steps. Fenna changes the last one without warning, then claims your stumble was an ambitious flourish. You demand a fair rematch; she takes your hand again, grinning.','The joke she lets go','Fenna begins to make a joke, then stops. “Actually, I would rather ask to kiss you and mean it.”','You agree. She is quiet for a moment afterwards, then smiles. You both know the joke can return without having to hide the answer.'),
 ('The trail can wait','Fenna puts her route notes aside. “Could I stay here a while? I have been good company all day and would like to stop trying quite so hard.”','“The coat was the same colour as my guide’s,” Fenna says. “I followed it through the rain for half a mile. Then its owner opened a garden gate and asked whether I had come for turnips.” You ask what she said. “That I was comparing routes. He gave me a turnip. Pity, I think.” She leans against you while you laugh.','A little less quick on her feet','“I know how to make an exit,” Fenna says. “I am getting better at saying when I would rather stay.”','You ask whether this is one of those times. She says yes. You share an embrace, and she lets the moment continue without inventing a reason to escape it.'),
 ('The game left outside','Fenna pauses at the quiet room’s doorway. “Would you like a private evening? I promise not to turn it into a competition.”','Fenna greets you at the bedroom door. “Your navigation has improved. No wrong stair, no detour through the pantry.” You point out that she invited you here. “Yes. I am beginning to think direct instructions have their uses.” She asks for a kiss, then draws you to sit beside her.','A promise without a loophole','“If something matters, I will try saying it before I make the joke,” Fenna tells you. “Tonight, being here matters.”','You tell her it matters to you too. She takes your hand and kisses you. The evening remains playful, with the important answer already safely spoken.')],
'kaede':[
 ('After the last practice','Kaede has finished at the training yard. “Would you walk with me? I want to tell you about my first glasswork lesson.”','“I squeezed the glass before it had cooled,” Kaede says, showing you the small scar. “My teacher asked whether I also intended to wrestle the furnace.” You ask what she answered. “Nothing dignified.” She takes your hand. “I did learn to wait. Eventually.”','A beginning she can leave alone','Kaede looks at you with an uncertain smile. “May I kiss you without deciding afterwards how I could have done it better?”','You welcome the kiss. She laughs when you tell her you would like to remember it exactly as it happened. For once she lets a good beginning stay uncorrected.'),
 ('No need for composure','Kaede sits beside you. “I keep thinking about a move from an old match. May I show you? It is partly an excuse to hold your hand.”','Kaede draws a little square on your palm. “I moved back here. My opponent followed, and I turned past her guard.” You ask whether she planned the opening. “I planned to avoid being hit. The rest was an unexpected benefit.” She keeps your hand after the diagram is finished.','The unfinished account','“I lost a practice bout and spent the rest of the afternoon pretending it had not bothered me,” Kaede says. “It did. I wanted to win. I would rather admit that here than invent a noble lesson.”','You tell her she is allowed to be disappointed and ask whether she wants to discuss the bout. “Tomorrow. Tonight I would like to be held without being coached.” You welcome her into an embrace.'),
 ('An evening without rehearsal','Kaede offers you a place beside her in a quiet room. “I would like to stay close tonight. We need not decide anything beyond that.”','You share a kiss and sit together. Kaede asks you to tell her when she starts turning tomorrow’s plans into tonight’s work. You catch her once; she laughs and draws you closer. The rest of the evening remains private.','The ordinary days she chooses','“I wanted you to see me at my best,” Kaede says. “Now I think I would also like you here on the days I am simply myself.”','You tell her those are days you want to share. She takes your hand with an easy confidence, then asks for a kiss. The evening continues without a performance to maintain.')],
'elowen':[
 ('The walk she kept','Elowen puts her work aside. “Walk with me? I wanted to tell you about the first herb I managed to keep alive.”','You walk hand in hand while she describes her first attempt at growing lemon balm. The plant survived; the carefully painted label did not. She still remembers her teacher calling the unnamed pot her finest mystery.','Something she asks for','Elowen smiles, then gathers her courage. “May I ask for a kiss simply because I would enjoy one?”','You say yes. Afterwards she keeps your hand in hers, visibly pleased that an ordinary wish was enough reason to speak.'),
 ('Care in the other direction','Elowen settles beside you. “Could I tell you about my day? I caught myself giving advice I should have taken.”','You sit close and ask about her own day. Elowen admits she was annoyed by an unsolicited remedy for her perfectly ordinary tiredness. “Yes, I heard myself halfway through objecting.” She leans against you and laughs at the irony.','The tiredness she names','“I kept saying I was all right because nobody had done anything wrong,” Elowen admits. “I am learning those are different things.”','You thank her for telling you and ask what would help. She chooses quiet company. You stay beside her, leaving tomorrow’s solutions for tomorrow.'),
 ('The evening protected','Elowen welcomes you into a quiet room. “I made time for us. Would you like a kiss, and then to see how we feel?”','You share a kiss and rest together. Elowen asks whether you mind the scent of the dried herbs near the window. You tell her you like it here. She smiles, and the scene closes with her hand in yours.','A welcome in both directions','“I want us both to be able to ask for comfort,” Elowen says. “Even when the other has had a difficult day too.”','You agree to keep asking and answering honestly. She rests against you after checking that you would like it. The evening closes with room for both of you to be cared for.')],
'nyssara':[
 ('An invitation clearly named','Nyssara makes room beside her. “I am inviting you to hold my hand. I thought precision might be welcome.”','You take her hand and listen as rain begins outside. Nyssara distinguishes the water against the window from the deeper note in the stone channel. She smiles when you finally hear the sound she remembers from home.','One answer she wants','“I would like to kiss you,” Nyssara says. “I have considered several subtler ways to ask and rejected all of them.”','You agree. Afterwards she lets herself laugh at the unnecessary research. Some things, you both decide, are pleasant to know plainly.'),
 ('A confidence, freely offered','Nyssara closes her working notes. “There is something personal I would like to tell you. May we have a little quiet?”','“For six days I blamed the customer’s clock,” Nyssara says. “Then I checked the charm against my own. I had copied the hour mark backward.” You ask how she explained it. “‘Your clock is correct’ was the difficult sentence.” She takes your hand, amused that you waited to laugh until she did.','A door that need not be forced','“I like that you ask,” Nyssara says. “And that an unanswered question does not become a challenge.”','You tell her she can keep parts of her life private. Nyssara nods. “Then I will volunteer this: I practised saying ‘Your clock is correct’ all the way to the customer’s door.” She asks for an embrace, smiling at the admission.'),
 ('No interpretation required','In a quiet room, Nyssara offers her hand. “I would like an affectionate evening with you. You are welcome to choose the gentler version at any point.”','Nyssara asks which story of hers you would retell. You choose the charm that rang at the wrong hour. “Accurate, but unkind to my professional reputation. Include that I repaired it.” You promise the correction its own sentence. She kisses you, satisfied with the terms, and settles close.','The confidence she keeps choosing','Nyssara looks at your joined hands. “I do not think trust is the end of having boundaries. I think it makes them easier to speak about.”','You agree, and tell each other what would make tonight comfortable. She kisses you with a small, contented smile. There is nothing to decipher before you can enjoy being together.')],
'sylva':[
 ('The place between the leaves','Sylva makes room on the conservatory bench. “The plants need nothing from us just now. Would you like to hold hands?”','You hold her hand while she tells you about a traveller who mistook a seed pod for a tiny rattle. The child kept shaking it until the seeds fell into her mother’s pocket. Sylva still wonders where they were planted.','A small thing allowed to grow','“I have been looking forward to seeing you here,” Sylva says. “May I show you how much with a kiss?”','You agree. The kiss is gentle and welcome, and afterwards you stay beside her without needing to turn the moment into anything larger.'),
 ('Room beside her','Sylva sets her tools aside and lifts two fallen leaves. “Sit close. I want your opinion on these colours.”','Sylva places two fallen leaves on your knee. “This yellow one lost its green first. The mottled one is changing in patches.” You prefer the yellow; she chooses the mottled leaf. “Yours knows what it wants to be. Mine is keeping its options.” She rests against your shoulder while you defend your choice.','Growth without a deadline','“Sometimes I worry that a good thing must always be becoming something more,” Sylva says. “I would like to enjoy where we are.”','You tell her you would like that too. She takes your hand, relieved that resting in a relationship does not mean neglecting it.'),
 ('The garden left to night','Sylva has finished tending for the evening. “Would you stay with me tonight? I would like to be close.”','Sylva draws the blanket over your knees. “After rain, I notice the crushed mint before the wet soil. People always mention the soil.” You tell her the scent you notice first. She listens, asks where you remember it from, and offers a kiss before you finish the story together.','A place to return freely','“I like having somewhere to return,” Sylva says. “And knowing returning is still a choice.”','You welcome her offered hand and tell her you are glad she chose tonight. A kiss ends the conversation. The private evening needs no promise to be repeated exactly.')],
'velis':[
 ('The ledger closed early','Velis closes the ledger. “Walk with me? I have a delivery story that still makes me laugh.”','“The parcel was addressed to ‘the man with the unfortunate hat’,” Velis says. “Three men claimed it. I asked what was inside. Two said money. The third said a new hat.” You laugh. “He was the recipient. The sender had not entirely abandoned him.” She takes your hand as you walk.','Something she need not price','Velis catches herself weighing the perfect phrase. “May I ask for a kiss without first making a persuasive case?”','You say yes. Afterwards she smiles at how little needed arranging, and how much she enjoyed being able to ask directly.'),
 ('No arrangement to negotiate','Velis leaves her correspondence unopened. “May I sit close? I would like an evening with no terms to settle.”','You sit close while she describes the first day she travelled without an invoice book. She checked the empty pocket at every stop. By the end she had filled it with a pastry wrapper and a pressed flower. “A better inventory.”','The favour that is not a debt','“I am used to remembering what I owe,” Velis admits. “I do not want to turn your kindness into another account.”','You ask her to tell you when she needs company, without balancing it against yesterday. She takes your hand. The conversation ends with an agreement to keep asking, not a ledger to keep.'),
 ('Tomorrow’s letters','In a quiet room, Velis puts tomorrow’s letters aside. “Would you like a private evening? I have left the planning at the door.”','“If tomorrow were free, I would go to the pear market,” Velis says. “There is a seller who has defeated me in two consecutive negotiations.” You ask why she would return. “The pears. Revenge is a poor lunch.” You laugh, share a kiss and leave the route map folded.','A place beyond the route','Velis unfolds a familiar route map, then closes it. “It feels different now, knowing there is someone I want to come back to. May I say that without making it a grand promise?”','You tell her you are glad she said it. She takes your hand and asks for a kiss. Tonight is allowed to matter without either of you having to predict every road ahead.')],
'rhess':[
 ('The watch handed over','Rhess confirms the handover and turns to you. “Would you keep me company now that looking out of the window is optional?”','You take her hand and listen while she tells you how the carved bird lost its tail. She dropped it during a startled salute. “The commander asked whether it was regulation equipment. I said it was now damaged equipment.”','A signal meant for one','Rhess smiles with a little uncertainty. “I can make myself understood across a valley. May I try asking plainly for a kiss?”','You say yes. Afterwards she laughs, relieved to have found a signal that requires no lamp, tower, or careful rehearsal.'),
 ('Nothing on the horizon','Rhess sits beside you after her watch. “I keep listening for a signal that is somebody else’s responsibility now. Could I rest here a while?”','Rhess lifts the bent pin from her keepsake box. “My first watch partner used this when my cloak clasp broke. He said the bend would stop me borrowing it twice.” You ask why she kept it. “Because he refused it back.” She rests against your shoulder while you examine the improvised clasp.','The relief she accepts','“I thought being dependable meant never needing to hand anything over,” Rhess says. “I would like to learn the other part with you.”','You listen, then ask what she needs tonight. “Company,” she answers. She rests against you, trusting that someone else can keep the watch while she is simply here.'),
 ('The lamp shuttered','With the watch covered, Rhess joins you in a quiet room. “No signals tonight. Would you like to stay close for a while?”','Rhess sets her keepsake box beside you. “Choose one. I will tell you why I kept it.” You point to the carved bird. “That was meant to look stern. The beak broke, and now it looks offended.” She asks for a kiss, still smiling, and leaves the bird watching over the two of you.','Coming back, not keeping watch','“I used to think home was where I could see danger coming,” Rhess says. “Now I think it is also where I can stop looking for a little while.”','You ask to hold her, and she welcomes you. You share a kiss and choose a quiet evening together. Tomorrow will still have its watch; tonight has room for rest.')],
}
FIRST={
'mira':('A chair turned toward you','Mira turns her chair away from the desk. “I thought I might stop pretending this visit was about the index. Will you sit with me?”','You sit beside Mira while she reads a note from a former pupil. He has become a teacher and now complains about his pupils’ handwriting. “Justice,” she says, delighted. Her shoulder rests against yours as she reads the worst example.','A note with no citation','“I saved this page because I wanted to read it with you,” Mira says. “I like having someone in mind before I find a good line.”','You tell her you look forward to her recommendations. She marks the page with your shared ribbon. “Then I shall be selective. Occasionally.”'),
'tamsin':('Tea before the errands','Tamsin has saved a quiet seat. “Would you join me before either of us invents something that needs doing?”','“Three needles in the coat hem,” Tamsin says. “An excellent travelling repair kit until the owner asked why sitting down had become so hazardous.” You ask whether she removed them. “All three. He still counted them twice.” She pours your tea, then sits before finding another task.','The invitation she keeps','“I caught myself setting out your cup before you arrived,” Tamsin says. “I hoped you would.”','You tell her you were hoping to see her too. She sets the cup within your reach and sits beside you before either of you invents an errand.'),
'iona':('A meeting on purpose','Iona catches your eye and pats the seat beside her. “We could call this a coincidence, but I would rather call it an invitation.”','Iona tells you about a ferryman who added a much longer route to her map because it passed his brother’s bakery. “The bread was excellent. His distances were fiction.” She grins when you ask whether she kept the bakery marked.','The route she admits taking','“I took the long corridor to see whether you were here,” Iona admits. “Not my finest navigation.”','You tell her she can ask for your company directly. “Good. Will you stay?” she says at once, pleased with the shorter route.'),
'aurelia':('A moment after the report','Aurelia finishes her report and stays. “That was the duty part. Would you like a few minutes of my company?”','Aurelia describes the goose once given to her at the hospice. It stole a ribbon from a visiting official and would return it only for bread. Her imitation of the official’s dignity is so exact that she struggles to finish it without laughing.','A request in her own name','“Could we do this again?” Aurelia asks. “I would like to see you when neither of us is waiting for a report.”','You agree. She suggests tea after the evening meal and asks what you like in it. The invitation feels more personal for being specific.'),
'neris':('An observation shared','Neris points out a small play of light on the wall. “There is no practical use for this. I hoped you might enjoy it with me.”','You watch the reflection move across the wall. Neris shows how turning the cup splits one bright patch into two. You try it yourself, and she guides your wrist with a light touch. “There. Much better than my explanation.”','A reason she names','“I wanted you to see that reflection,” Neris says. “You usually notice a different part from me. I like hearing which.”','You tell her what caught your eye this time. She turns the cup to find it, then smiles at you. “Yes. I am glad I asked.”'),

'sabine':('The second attempt','Sabine catches your attention with a flourish, then smiles. “Would you prefer the impressive invitation or the one where I ask you to sit with me?”','Sabine takes a theatrical breath. “Acting Deputy Keeper of the West Stair, Assistant to the Assistant Steward, Honorary Inspector of—” She stops. “The printer put ‘Name omitted for space’ at the bottom.” You ask if the owner objected. “To being left off? Naturally. He wanted smaller type.” She is laughing when she sits beside you.','A compliment she believes','“You looked pleased before I said anything clever,” Sabine says. “I liked that.”','You tell her you came to see her, not to judge a performance. She smiles. “Then I can save my best line until after the tea.”'),
'maren':('The visit without a fault','Maren arrives with nothing to mend. “Everything seems to work. Would you still like me to stay a little while?”','“The cupboard door opened whenever someone sat in the next room,” Maren says. “A loose floorboard tipped the cabinet. The owner insisted it was perfectly level.” You ask how she convinced him. “I asked him to sit down and watched the door open. It made the argument rather well.”','A reason good enough','“I nearly brought something to repair as an excuse,” Maren admits. “Instead, I would like to ask if you want to see me again.”','You say yes. She looks relieved, then amused. “Good. The door I was considering was perfectly sound.”'),
'brakka':('The small sound','Brakka pauses over a little music box. “Would you listen with me? I like the part just before the tune repeats.”','You listen for the pause before the tune repeats. Brakka points out that the last note hangs just long enough to make you expect another. “The maker knew how to keep someone listening.” She looks pleased when you ask to hear it again.','Something she wanted to show you','“I thought you might get bored with such a small thing,” Brakka says. “You listened right through.”','You ask for another favourite. Brakka hums a slower tune and taps where the music-box teeth would catch. “This one never rushes its last note. I like that.” She smiles when you ask her to hum it again.'),
'fenna':('A very poor excuse','Fenna leans against the doorframe. “I have come to inspect whether you are available for entirely unnecessary conversation.”','You welcome the “inspection.” Fenna asks whether your chair passes comfort regulations, then admits she invented the regulations on the way in. You make her demonstrate the required level of lounging. She takes the seat beside you.','The honest part','“The inspection was an excuse,” Fenna admits. “I wanted to see you. I hope that was reasonably obvious.”','You tell her you were hoping she would visit. She drops the official voice. “Good. Next time I can save us both the paperwork.”'),
'kaede':('A little unplanned time','Kaede pauses beside you. “I have finished what I meant to do. Would you like some company before I find another task?”','Kaede tells you about a training game she lost because she explained her plan aloud. “I wanted to demonstrate the principle. My opponent demonstrated listening.” She finally laughs when you ask whether the lesson was successful.','The question asked once','“I enjoyed this,” Kaede says. “Would you like to spend more time together?”','You say yes. She smiles without trying to improve the wording of her question. “Then I shall ask sooner next time.”'),
'elowen':('A pleasure to share','Elowen offers you a seat beside her. “Nothing is wrong. I just thought it might be pleasant to see you.”','Elowen tells you that a visitor returned a borrowed herb pot with a new cutting tucked beside it. “She said the original looked lonely.” Elowen is trying to identify the gift and enjoys your completely unqualified guesses.','A wish spoken aloud','“I have been looking forward to telling you about that cutting,” Elowen says. “You remember the details I thought were too small to mention.”','You ask her to show you the plant when she identifies it. She agrees and suggests that you keep your ridiculous guess on its label until then.'),
'nyssara':('A plainly personal visit','Nyssara closes her notes when you arrive. “Would you stay a little? This is a personal invitation, in case the notes were misleading.”','Nyssara describes a customer who wanted a warning charm to remain completely silent. “He objected to the warning.” Her dry imitation has you laughing before she explains the compromise: a small red indicator beside his desk.','The thing she makes clear','“I do not tell everyone about the clock charm,” Nyssara says. “I find I like how you laugh at it.”','You promise to let Nyssara tell the clock-charm story herself. “Thank you. I reserve the right to mention that I fixed it.” She pauses. “After rehearsing the apology three times outside his door. You may laugh at that part.”'),
'sylva':('A pause among the leaves','Sylva looks up from a new leaf. “Would you stay and look with me? It will not become more impressive if we hurry.”','You examine the new leaf together. Sylva points out where it was folded inside the bud and lets you compare it with an older one. “That seam will disappear.” She is pleased when you ask what changes next.','A welcome that can be simple','“I was glad to see you before I had anything new to show you,” Sylva says. “Would you visit even on a day when every leaf looks the same?”','You say you would. She makes room beside her. “Good. They cannot all be remarkable days. I would still like your company.”'),
'velis':('An unlisted appointment','Velis glances at her list, then turns it over. “This visit is not on there. I was hoping you might stay anyway.”','Velis tells you about a roadside seller who labelled every pear “best in the county.” She bought one, challenged the claim, and was offered a second for comparison. “I lost that negotiation. The pears were very good.”','No business left to discuss','“I used to wait until I had business to discuss,” Velis says. “I would rather ask whether you want to see me.”','You tell her you do. She closes the ledger. “Tea, then. No prices, quantities or delivery dates.”'),
'rhess':('A signal off duty','Rhess turns away from the window. “I saw you coming. Would you like to sit with me for a while?”','Rhess describes a crow that repeatedly stole the cord from a signal cover. “It watched me tie the replacement. Then improved its technique.” Her imitation of its victorious hop is much less dignified than her usual reports.','The welcome she names','“I was hoping that would be you,” Rhess says. “I recognised your steps before I looked up.”','You sit beside Rhess and ask about the carved bird. “I dropped it during a salute,” she says. “The commander asked whether it was regulation equipment. I told him it was now damaged equipment.” She shows you the broken tail, still amused by the exchange.')}
for who,scene in FIRST.items():ROWS[who].insert(0,scene)
assert len(ROWS)==15 and all(len(rows)==4 and all(len(row)==6 for row in rows) for rows in ROWS.values())
