"""A ruined pavilion, three different ambitions, one shared household legacy."""
from beacon_expedition import method,specialist,team,magic
SITE='lantern-pavilion'
CAST=['mira','tamsin','iona']
DEFINITION={'id':SITE,'name':'The forgotten lantern pavilion','description':'Recover a festival lantern, its songbook and the record of the people who kept a woodland pavilion open. Mira, Tamsin and Iona have different hopes for what comes home. Bring any willing members of this trio, or investigate alone.','approaches':{'survey':{'name':'Follow the last festival programme','description':'One phase out, five obstacles and one legacy decision, then one phase home. Patient solo, specialist, spell and teamwork solutions. Optional conversations never spend time.','reward':'3 advancement per returning participant, 2 moon glass and 3 binding thread, once. Recover a lantern corner for the common room and choose its purpose.'}}}
STEPS=[
 {'id':'approach','name':'A path under the fallen arch','description':'An old festival arch lies across the woodland path. Its carved names face the mud. Moving it safely will keep the inscriptions intact.','choices':{
 'patient':method('Clear the loose pieces and move the arch on rollers',3,'Safe, free and available alone.'),
 'levers':specialist('Read the load and place the levers precisely','intelligence','artifice','One phase, without damaging the inscriptions.'),
 'team':team('Brace the arch while a partner frees its foot',('might','athletics'),('dexterity','artifice'),'Two distinct participants, score 8 in each role. One phase.'),
 'spell:giant-grasp':magic('Lift the arch with Giant’s grasp','giant-grasp','One phase; preserve the carved names.')}},
 {'id':'bridge','name':'The musicians’ crossing','description':'The small bridge to the pavilion has lost its deck. The lower bank offers a longer, safe approach.','choices':{
 'patient':method('Follow the bank and build a temporary plank crossing',3,'No special ability or material cost.'),
 'traverse':specialist('Secure a line along the surviving side braces','dexterity','fieldcraft','One phase with a careful route assessment.'),
 'team':team('Anchor a line for a precise crossing',('might','athletics'),('dexterity','athletics'),'Two different people make the crossing secure. One phase.'),
 'spell:borne-flight':magic('Carry the party across with Borne flight','borne-flight','One phase. Only this crossing is resolved.')}},
 {'id':'water','name':'The flooded programme chest','description':'A low storage pit holds a sealed chest. Its release wheel is underwater. The paper inside remains dry, but forcing the lid would ruin its seal.','choices':{
 'patient':method('Drain the pit through its maintenance channel',3,'Safe and free; no diving required.'),
 'valve':specialist('Restore the dry bypass valve','intelligence','artifice','One phase using the surviving mechanism.'),
 'team':team('Hold the service arm while a partner releases the pin',('vitality','athletics'),('dexterity','artifice'),'One steady brace and one precise pair of hands. One phase.'),
 'spell:water-breath':magic('Release the wheel under Undertide breath','water-breath','One phase; protection applies to this encounter.')}},
 {'id':'names','name':'The names behind the programme','description':'The programmes credit a patron in large letters. Repair notes name the cooks, musicians, copyists and neighbours who kept the festival running. Two incomplete indices must be reconciled.','choices':{
 'patient':method('Compare every programme with the repair ledger',3,'Patient reading identifies the people without a scholarship requirement.'),
 'read':specialist('Reconstruct the missing index references','intelligence','scholarship','One phase of careful cross-reference.'),
 'team':team('Explain the notation while a partner tests it aloud',('intelligence','scholarship'),('charisma','diplomacy'),'A scholar and a clear communicator, score 8 each. One phase.'),
 'spell:lucid-sight':magic('Read the damaged sequence under Lucid sight','lucid-sight','One phase; clarify the surviving marks, without inventing missing facts.')}},
 {'id':'echo','name':'A rehearsal that never ends','description':'The lantern repeats the start of a festival melody. Its old timing mechanism interrupts the tune at the same bar. A gentle reset can quiet the repeating sound without destroying the instrument.','choices':{
 'patient':method('Observe the whole cycle and reset its stops by hand',3,'Safe ordinary observation; no combat or injury.'),
 'cadence':specialist('Hold a steady counter-rhythm while reading the stops','resolve','channeling','One phase, without using a spell.'),
 'team':team('Read the light while a partner turns the timing cradle',('resolve','channeling'),('dexterity','artifice'),'Two distinct roles make a precise adjustment. One phase.'),
 'spell:calm-tide':magic('Quiet the echo with Calming tide','calm-tide','One phase. This affects the repeating magical sound, not anyone’s willingness.')}},
 {'id':'legacy','name':'What should the lantern light?','description':'The lantern, songbook and working ledger can all be preserved. Choose the purpose of the corner you will make at home. Nobody’s contribution needs to be discarded.','choices':{
 'archive':method('Create a reading and discoveries corner',1,'Preserve all three finds; emphasise comparing records. Once installed, ordinary cipher/search character-quest work takes two phases instead of three.'),
 'music':method('Create a music and rehearsal corner',1,'Preserve all three finds; emphasise learning together. Once installed, ordinary repair/crossing character-quest work takes two phases instead of three.'),
 'hospitality':method('Create a welcoming supper and planning corner',1,'Preserve all three finds; emphasise a place people can use. Once installed, ordinary lift/water/bargaining character-quest work takes two phases instead of three.')}}]
PURPOSES={'archive':('Reading and discoveries corner',('cipher','search')),'music':('Music and rehearsal corner',('repair','crossing')),'hospitality':('Supper and planning corner',('lift','water','bargain'))}
BEATS={
 'arrival':{'title':'Three reasons to follow a programme','after':0,'opening':'The pavilion’s last programme promises music, lamplight and a table for anyone who arrives. The paper survived longer than the path. Before the work begins, there is time to decide what deserves attention.',
 'voices':{'mira':'Mira studies the names. “I want to know who made this possible, not just who paid for the grandest lettering.”','tamsin':'Tamsin points to the supper list. “And I want to know whether the people making it possible ever got to sit down.”','iona':'Iona taps the printed rhythm. “I would like to hear what brought them here. A programme is a promise somebody meant to perform.”'},
 'pair':'Mira starts to explain the paper’s value. Tamsin answers, “I know. I am asking about the people holding it.” Iona folds the programme carefully. “Then let us bring home more than a relic.”',
 'choices':{'history':('Follow the people behind the record','You agree to preserve names as well as objects. The work begins with a question about the people who did it, rather than a hunt for a prestigious trophy.'),'use':('Look for something that can belong to daily life again','You agree to judge the recovery by whether someone can enjoy it at home. Keeping the record matters, but it need not remain behind a closed cover.'),'listen':('Let the findings change the plan','You leave room for the expedition to surprise you. Nobody is asked to surrender a hope before seeing what survived.')}},
 'camp':{'title':'A supper without a committee','after':2,'opening':'On a dry rest ledge beyond the crossing, the packed food is divided and the programme is spread where everyone can reach it. There is no urgent danger and no need to turn the pause into another task.',
 'voices':{'mira':'Mira admits she has already been arranging the recovered names into a catalogue. “I may be putting shelves around something before we have met it.”','tamsin':'Tamsin leaves the shared cup where someone else can refill it. “For once, I would like the plan to include sitting still.”','iona':'Iona hums the first few notes. “We can keep the catalogue, have supper, and sing something badly. None of those things cancels the others.”'},
 'pair':'Iona offers a deliberately terrible rhyme for Mira’s proposed catalogue title. Mira supplies a worse one. Tamsin laughs and tells them both to keep it out of the official record.',
 'choices':{'company':('Put the report aside and enjoy the company','For a while, no one produces a useful finding. The pause becomes part of why the journey will be remembered.'),'ask':('Ask what each person would miss if the pavilion stayed forgotten','The answers turn practical hopes into personal ones. You listen without deciding that the most eloquent answer must win.'),'share':('Name something you have changed your mind about','You admit that the programme first looked like a simple recovery job. The conversation leaves room for everyone to revise an opinion without losing face.')}},
 'credit':{'title':'Whose name belongs above the door?','after':4,'opening':'The ledger shows a festival maintained by many ordinary hands. Its patron paid for the lantern, but the repeated repairs came from people whose names barely fit in the margins.',
 'voices':{'mira':'“A catalogue can repeat an injustice very neatly,” Mira says. “I want the smaller names copied at the same size.”','tamsin':'“And the repairs should not disappear into a charming story about generosity,” Tamsin adds. “Someone had to do them.”','iona':'Iona points to a song written between supply orders. “They also enjoyed themselves. Let us not remember them only as people who worked.”'},
 'pair':'Mira nods to Tamsin. “Credit and labour, then.” Iona adds, “And delight.” This time neither of the others treats that as a less serious contribution.',
 'choices':{'names':('Record names, work and celebrations together','You agree to bring home a record spacious enough to include both effort and pleasure. The future display will preserve all the finds, whichever purpose you choose.'),'voices':('Let each companion describe the part they want remembered','Nobody must compress their concern into another person’s explanation. The three purposes begin to sound complementary rather than mutually exclusive.'),'humble':('Leave honest gaps where the record cannot answer','You preserve uncertainty as well as names. No spell or confident guess is allowed to turn missing evidence into a convenient story.')}}}
CAMP={
'mira':('The joke she keeps out of the catalogue','Mira shows you the terrible rhyme from her notes. “I am keeping it. An archive should be allowed evidence that its keeper enjoyed herself.”','You trade another bad line and leave the catalogue closed for a little while. Mira seems pleased to have company without an audience.'),
 'tamsin':('A place on the rest ledge','Tamsin pats the place beside her. “Nobody needs me to organise this conversation. I thought I might simply enjoy having you here.”','You sit with her and ask what she would like to do once you are home. The answer contains no list of things she owes anyone.'),
 'iona':('A quieter sort of encore','Iona asks whether you want to hear the melody without the ridiculous words. “I can be sincere occasionally. Try not to look too alarmed.”','You listen to the short unfinished tune. Iona lets the last note rest without disguising it as a joke.')}
HOME={
'mira':'Mira writes the recovered names beside the lantern. “The keeper, the carrier and the repairer. All three helped bring it back. All three belong on the card.”',
 'tamsin':'Tamsin places a chair where it will not become a convenient shelf. “This is a place somebody gets to sit. I shall defend that quite fiercely.”',
 'iona':'Iona leaves a playable copy of the tune within reach. “The original is safe. This one is allowed to get fingerprints.”'}
