"""Three authored journeys. Method rules are data, never runtime language-model decisions."""
from beacon_expedition import method, specialist, team, magic

CAST=['mira','tamsin','iona','aurelia','neris','sabine','koharu','zahra','fenna','kaede','elowen','nyssara','sylva']

def obstacle(key,name,text,patient,expert,attribute,skill,partners,form,spelltext,ritual,principles,lasting):
 return {'id':key,'name':name,'description':text,'choices':{
  'patient':method(patient,3,'Three phases, no supplies or attribute requirement. Safe alone.'),
  'specialist':specialist(expert,attribute,skill,'One phase. A qualified member of the actual party leads.'),
  'team':team(partners[0],partners[1],partners[2],'One phase. Two distinct, qualified party members fill the listed roles.'),
  'spell:'+form:magic(spelltext,form,'One phase; this specific obstacle is resolved. Pay the prepared spell’s components once.'),
  'ritual':method(ritual,2,'Two phases. Inscribe a permanent change at this site: '+lasting+' Requires a present conductor who has learned both listed principles; 1 moon glass and 1 binding thread, paid once.',ritualPrinciples=principles,inputs={'moon-glass':1,'binding-thread':1},lasting=lasting)}}

SITES={
 'flooded-monastery':{
  'name':'The monastery beneath the rain','description':'A hillside monastery has become a chain of flooded courts. Its last caretaker wants the water made safe and the names of the missing recovered. The bell still rings below the surface.',
  'principle':'water-guidance','room':'library','legacy':'The rainkeeper’s atlas','skill':'channeling','helps':['water','search'],
  'legacyText':'A water-level atlas, a working siphon model and the names recovered from the memorial court. While displayed: +1 to Channeling expedition approaches, and ordinary water/search character-quest work takes two phases.',
  'campPlace':'On the dry upper cloister, rain beads on the rail. Spare blankets and a screened changing alcove give everyone a chance to get comfortable before supper.',
  'home':'The atlas opens on a repaired library table. The siphon model turns a bowl of water into a small, comprehensible landscape.',
  'steps':[
   obstacle('court','A courtyard without a shore','Floodwater hides the flagstones between the gate and cloister. A raised maintenance route survives along the wall.','Assemble a raised walkway along the maintenance ledge','Read the shallow ridges and secure a dry line','dexterity','fieldcraft',('Anchor a walkway while a partner places its boards',('might','athletics'),('dexterity','artifice')),'water-walk','Cross the court with Waterwalk','Bind a permanent water-level boundary',['water-guidance','reference-binding'],'The courtyard’s safe flood line remains visible.'),
   obstacle('wheel','The wheel beneath the stairs','The drain’s release pin lies below a sealed stairwell. The inspection channel can empty the chamber without anyone diving.','Open the inspection channel and drain the stairwell','Rebuild the dry bypass from its witness marks','intelligence','artifice',('Brace the release arm while a partner guides its pin',('vitality','athletics'),('dexterity','artifice')),'water-breath','Turn the submerged wheel with Undertide breath','Inscribe a self-clearing overflow',['water-guidance','gentle-preservation'],'The stairwell drains safely after later storms.'),
   obstacle('lamp','The lamp room’s last fire','A cracked oil reservoir feeds fire across a stone threshold. Bare sand and a safe service hatch are within reach.','Smother the burning oil with sand from the service hatch','Close the reservoir feed through the inspection slot','intelligence','artifice',('Shield the hatch while a partner closes the feed',('resolve','channeling'),('dexterity','artifice')),'water-jet','Quench the fire with Water jet','Set a lasting heat boundary around the reservoir',['steady-hearth-wards','reference-binding'],'Future heat stays inside the lamp enclosure.'),
   obstacle('guardian','The watch beneath the bell','An undead bell keeper circles a memorial stair. Its old watch can be ended by completing the roll of names, or its hostile binding can be broken.','Reconstruct the memorial roll and finish the watch','Identify the unfinished name in the bell keeper’s charge','intelligence','scholarship',('Read the roll while a partner steadies the bell’s resonance',('charisma','diplomacy'),('resolve','channeling')),'dawn-lance','Break the undead binding with Dawn lance','Consecrate the memorial threshold',['luminous-copying','reference-binding'],'The threshold prevents this watch from binding another keeper.'),
   obstacle('caretaker','An account worth trusting','The caretaker fears that reopening the monastery will erase why it was abandoned. She asks for a record of the flooding before handing over her atlas.','Hear her account and write the flood history together','Agree a clear plan for preserving names and flood marks','charisma','diplomacy',('Compare the physical marks while a partner records her corrections',('intelligence','fieldcraft'),('charisma','diplomacy')),'calm-tide','Quiet the distressing alarm echo with Calming tide','Bind a public flood record',['clear-instruction','reference-binding'],'Her corrections remain attached to the flood markers. The spell route quiets an alarm; she still decides to share the atlas.'),
   obstacle('bell','A bell that can ring for the living','The bell’s cradle is pinned beneath a fallen stone. Its inscriptions describe a warning system that could serve the valley again.','Roll the stone onto a crib and realign the cradle','Calculate a safe lever position from the cradle’s load','might','athletics',('Hold the cradle while a partner resets the bearing',('might','athletics'),('dexterity','artifice')),'giant-grasp','Lift the stone with Giant’s grasp','Set a stable bell foundation',['settling-flow','field-calibration'],'The bell foundation settles without dragging the restored drain out of alignment.')],
  'decision':'Who should guide the monastery’s next chapter?',
  'endings':{
   'keepers':('Support the valley’s volunteer keepers','The caretaker forms a rota with the valley households. Your report records that care belongs to people with names and limits.'),
   'refuge':('Make the dry cloister a refuge for travellers','The repaired cloister becomes a stopping place above the flood line. Its memorial court stays quiet and intact.'),
   'study':('Arrange visits for watercraft students','Students are invited to learn from the real flood marks, with the caretaker’s corrections beside every diagram.')}
 },
 'frozen-skybridge':{
  'name':'The frozen skybridge','description':'An abandoned highland crossing joins two weather stations. Ice has trapped its mechanisms, and a signal automaton cannot tell a repair party from the storm that broke its orders.',
  'principle':'field-calibration','room':'workshop','legacy':'The skybridge survey rig','skill':'fieldcraft','helps':['crossing','lift'],
  'legacyText':'A calibrated survey rig, reusable climbing tackle and a weather log. While displayed: +1 to Fieldcraft expedition approaches, and ordinary crossing/lifting character-quest work takes two phases.',
  'campPlace':'Inside the western signal hut, a small stove warms the benches. Cloaks hang on pegs; the wind outside makes the borrowed shelter feel unusually intimate.',
  'home':'The survey rig stands in the workshop with its weather log open. The line weights still bear the marks of the party’s repairs.',
  'steps':[
   obstacle('ascent','The stair swallowed by ice','Ice covers the direct stair. A sheltered maintenance zigzag reaches the same landing.','Clear footholds along the sheltered zigzag','Read the wind-carved snow and choose a protected ascent','vitality','athletics',('Break a safe track while a partner anchors the line',('might','athletics'),('dexterity','fieldcraft')),'fire-lance','Melt the isolated ice plug with a controlled Fire lance','Set a permanent thaw channel',['steady-hearth-wards','water-guidance'],'Meltwater runs clear of the stair instead of freezing on its treads.'),
   obstacle('span','The missing middle of the bridge','The central deck has fallen. A lower service crossing survives, sheltered beneath the main cables.','Repair the lower service crossing and rig handlines','Traverse the sound side cable and secure the crossing','dexterity','athletics',('Anchor the cable while a partner fixes a travelling line',('might','athletics'),('dexterity','fieldcraft')),'borne-flight','Carry the party across with Borne flight','Bind a supported passage between the anchors',['courteous-passage','joined-fibres'],'A lasting guide line marks the repaired service crossing.'),
   obstacle('sentinel','The sentinel with a broken order','A conductive automaton sweeps the signal platform. Its maintenance interlock is reachable from a shielded crawlway.','Follow the shielded crawlway and engage the interlock','Recognise the gaps in the automaton’s service sequence','intelligence','artifice',('Draw its sensor while a partner reaches the service latch',('charisma','diplomacy'),('dexterity','artifice')),'arc-bolt','Discharge the conductive sentinel with Arc bolt','Inscribe a maintenance recognition seal',['clear-instruction','reference-binding'],'The sentinel recognises the station’s repair signal in future.'),
   obstacle('gust','The wind in the speaking tube','A violent draught shakes the tube that carries weather signals. The relief shutters can be balanced from the sheltered side.','Balance the shutters one quiet interval at a time','Match the shutters to the pressure cycle','resolve','channeling',('Hold the vane steady while a partner resets the stops',('vitality','athletics'),('dexterity','artifice')),'ice-bind','Brace the loose vane temporarily with Icebind','Bind a pressure relief rhythm',['water-guidance','field-calibration'],'The vane releases excess pressure without losing its signal setting.'),
   obstacle('log','The weather log no one finished','The final week’s observations are scattered across frosted plates. Wrong ordering would send the restored warning at the wrong time.','Thaw the plates gently and compare every timestamp','Reconstruct the missing order from repeating measurements','intelligence','scholarship',('Compare the plates while a partner reproduces their readings',('intelligence','scholarship'),('resolve','channeling')),'lucid-sight','Clarify the damaged readings with Lucid sight','Bind the surviving observations into a stable index',['reference-binding','clear-instruction'],'The plates remain legible and their uncertainties stay marked.'),
   obstacle('signal','A light on both sides','The eastern signal must be aligned with the western station. An exposed ledge offers a long, safe sequence of observation points.','Walk the sheltered observation circuit and align both lights','Sight the two stations from their original survey marks','dexterity','fieldcraft',('Turn the mirror while a partner reads the reflected light',('dexterity','artifice'),('resolve','channeling')),'wisp-scout','Observe the far alignment with a Wisp scout','Anchor a lasting paired signal',['luminous-copying','field-calibration'],'Both stations retain a visible calibration reference.')],
  'decision':'What should the restored crossing serve first?',
  'endings':{
   'caravans':('Share the safe route with valley caravans','A plain route sheet goes to the valley carriers, including the longer sheltered crossing and its load limits.'),
   'warnings':('Give storm warnings priority','The keepers agree a warning schedule. The bridge’s first useful message is a forecast somebody can act on.'),
   'students':('Open a supervised survey station','The maintenance circuit becomes a teaching route. Every bold shortcut is printed beside its patient alternative.')}
 },
 'masquerade-manor':{
  'name':'The manor after the last dance','description':'A deserted manor repeats the last night of a masquerade. The guests are echoes, the host is an unfinished invitation, and the servant passages tell a different story from the ballroom.',
  'principle':'clear-instruction','room':'common-room','legacy':'The open invitation cabinet','skill':'diplomacy','helps':['bargain','cipher'],
  'legacyText':'An invitation cabinet, a repaired music roll and the staff’s account book. While displayed: +1 to Diplomacy expedition approaches, and ordinary bargaining/cipher character-quest work takes two phases.',
  'campPlace':'The dressing salon is quiet beyond the ballroom. Clean opaque silk wraps, theatrical half-masks and a curtained mirror survive in a sealed costume chest. Trying them is entirely optional.',
  'home':'The invitation cabinet sits in the common room with blank cards beside it. The music roll and staff ledger have equal space on the shelf.',
  'steps':[
   obstacle('door','An invitation with no name','The door asks for an invitation addressed to someone who no longer exists. A servant entrance has an ordinary, weathered latch.','Restore the servant entrance’s latch','Explain the contradiction in the host’s invitation','charisma','diplomacy',('Read the etiquette while a partner answers its formal challenge',('intelligence','scholarship'),('charisma','diplomacy')),'silver-tongue','Redirect the enchanted doorkeeper with Silver suggestion','Write a lasting guest threshold',['courteous-passage','clear-instruction'],'The door admits invited guests by a clear rule, without influencing living people.'),
   obstacle('mirrors','The corridor that admires itself','Mirrors repeat the same turn until the corridor looks endless. The backs of the frames still have ordinary mounting numbers.','Cover the mirrors and follow the mounting numbers','Reconstruct the frame order from the reflected moulding','intelligence','scholarship',('Track the frame numbers while a partner marks the real turns',('intelligence','scholarship'),('dexterity','fieldcraft')),'wisp-scout','Send a Wisp scout through the real corridor','Bind truthful waymarks',['luminous-copying','reference-binding'],'The corridor retains plain markers that its reflections cannot move.'),
   obstacle('dancers','The dance that will not release its guests','Echo dancers circle a floor that repeats the same eight bars. The service gallery provides a patient route around them.','Restore the gallery rail and pass above the dance','Identify the pause between the repeated bars','resolve','channeling',('Keep the beat while a partner opens the silent side door',('charisma','diplomacy'),('dexterity','artifice')),'mirror-decoy','Let a Mirror decoy draw the echo dancers aside','Inscribe an ending to the repeated measure',['gentle-refraction','clear-instruction'],'The dance can finish without trapping another echo.'),
   obstacle('stairs','The stair beneath the winter garden','A collapsed planter has pinned the stair door. Sound garden beams can be used as rollers.','Crib the planter and move it on the spare beams','Balance the planter’s load before lifting the door','might','athletics',('Brace the planter while a partner frees the hinge',('might','athletics'),('dexterity','artifice')),'giant-grasp','Lift the planter with Giant’s grasp','Settle the winter garden’s foundations',['settling-flow','joined-fibres'],'The repaired stair no longer carries the planter’s load.'),
   obstacle('ledger','The people below the guest list','The staff ledger records who actually kept the house running. Spilled ink hides several names, but duplicate wage entries survive.','Compare the wage books and restore the missing names','Match the duplicate entries through their reference marks','intelligence','scholarship',('Read the damaged names while a partner checks the duplicate book',('resolve','channeling'),('intelligence','scholarship')),'lucid-sight','Clarify the surviving ink with Lucid sight','Bind equal names into the house record',['reference-binding','luminous-copying'],'The staff’s names stay readable beside the guest list; gaps remain honestly marked.'),
   obstacle('host','The last toast','The host’s echo waits for applause before ending the evening. Its invitation mechanism can be reset by completing the closing announcements.','Read the closing announcements and release the old latch','Address the unfinished farewell in the host’s own terms','charisma','diplomacy',('Speak the farewell while a partner steadies the music roll',('charisma','diplomacy'),('resolve','channeling')),'calm-tide','Quiet the repeating applause with Calming tide','Bind an open-ended invitation',['courteous-passage','gentle-preservation'],'Future gatherings can end freely; the host’s echo is finally still.')],
  'decision':'What deserves to survive the masquerade?',
  'endings':{
   'names':('Give staff and guests equal space in the record','The restored record names the people who laid the tables alongside those who danced beside them.'),
   'music':('Give the music back to ordinary gatherings','A playable copy of the roll leaves the manor. It will accompany evenings that people can freely leave.'),
   'welcome':('Turn the invitation into a welcome without obligation','The new invitation promises company without debt. The old host’s grandest sentence is replaced by room to say no.')}
 }
}

for key,d in SITES.items():
 d['id']=key
 d['definition']={'id':key,'name':d['name'],'description':d['description'],'approaches':{'survey':{'name':'Follow the whole journey','description':'One phase out, six obstacles and a final decision, then one phase home. Ordinary routes are free and safe alone. Each obstacle also has specialist, teamwork, prepared spell and permanent ritual routes.','reward':'3 advancement for each returning participant, 2 moon glass, 3 binding thread, shared practical knowledge, and '+d['legacy']+'. Rewards arrive once, on a completed return.'}}}
 d['steps'].append({'id':'future','name':d['decision'],'description':'Every recovered object is preserved. Choose the commitment recorded in the final report; no option discards another find.','choices':{k:method(v[0],1,v[1]) for k,v in d['endings'].items()}})

# Each companion has a distinct line at each destination, and a personal camp exchange.
VOICES={
 'mira':('A flood mark is a measurement and a memory. I want both in the atlas.','Please keep the uncertain readings. A tidy error is still an error.','The servants kept two books because the guests only wanted to read one.'),
 'tamsin':('We should find out who kept clearing these drains after everyone else stopped noticing.','Who carried the spare cable up here? The log ought to say.','A beautiful invitation can hide a very long list of unpaid work.'),
 'iona':('That bell has a lovely note. I would like it to mean something hopeful again.','The speaking tube sings when the wind changes. I am resisting the obvious duet.','Eight bars forever sounds romantic only to someone who has never rehearsed.'),
 'aurelia':('A warning is useful when people know they can trust it.','We need a safe way back before we celebrate a daring way forward.','An invitation should never become a command.'),
 'neris':('The bypass is less elegant than the main drain. I suspect it is also why the building survived.','This interlock is a good idea badly explained. I recognise the temptation.','The door was given impeccable manners and terrible instructions.'),
 
 'sabine':('Wet cloaks have their charms in paintings. In practice I vote for the changing screen.','I can look windswept after we are safely inside. It need not be a full-time commitment.','At last, a ruin that understands accessories. I am still suspicious of its hospitality.'),
 'koharu':('I would like to take home a working model, not a heroic story about a pump.','The worn part tells us more than the polished plaque.','The music roll is repairable. Whether anyone wants to dance is a separate question.'),
 'zahra':('We can move the stone. First we find out what else it is holding up.','Tie the rope properly. I refuse to become an inspiring cautionary tale.','If the door wants a title, tell it I am Acting Director of Getting Through Doors.'),
 'fenna':('The high-water route is still here. Whoever marked it expected someone ordinary to need it.','The long way around has excellent views and very few opportunities to fall.','The servant passage goes everywhere the grand staircase pretends to go.'),
 'kaede':('Listen between the bell strokes. There is a quieter pattern underneath.','Balance is partly knowing when to stop moving.','The dancers cannot choose another step. We can.'),
 'elowen':('A memorial needs space for living people to sit beside it.','There is moss on the sheltered side. It has already done half our route finding.','The winter garden kept growing after the invitations stopped.'),
 'nyssara':('A dead keeper is still owed a finished watch.','A warning light should not require someone to stay alone forever.','The echo is not a person we can persuade into owing us affection.'),
 'sylva':('The water has made a home here. We can guide it without pretending it was an intruder.','I like the places where the bridge bends a little and keeps standing.','A garden growing through a ballroom is an interesting criticism of the ballroom.')
}
CAMPS={
 'mira':('A margin for something personal','Mira shuts her notebook and deliberately sets it beyond reach. “Ask me something I cannot answer with a diagram.”','“An hour reading something I did not choose for research,” Mira says. “Then a walk with someone willing to argue about the ending. I want to collect the stories people actually reread, even the ones they hide behind respectable books.” She asks which would go on your shelf.'),
 'tamsin':('A chair she does not have to earn','Tamsin has claimed the comfortable seat. “I have finished being useful for the next few minutes. You may join me on those terms.”','“A customer asked me to rebind his accounts so they would look less alarming,” Tamsin says. “I suggested smaller numbers. He asked whether I could do that too.” She accepts a cup from you. “I repaired the cover. The debts remained impressively intact.”'),
 'iona':('An audience of one','Iona offers you a tiny, exaggerated bow. “One quiet song. Afterwards you may applaud with your eyebrows.”','Iona sings softly, “Bring the boat home, leave your boots by the door.” On the repeated line she points at your muddy boots. You applaud with exaggerated eyebrows. “An exacting audience,” she says, pleased.'),
 'aurelia':('The watch can wait','Aurelia loosens her travelling collar and sits where she can stop watching the door. “I trust the shelter. I am practising behaving as though I do.”','Aurelia points out a seam in her travelling gloves. “I have mended that three times. I keep them because a new pair never fits between the fingers.” She turns the worn leather over. “Tomorrow I shall ask about a lining. Tonight I would like your opinion on the tea.”'),
 'neris':('An experiment in doing nothing','Neris admits she has invented three repairs since sitting down. “Please distract me before I create a fourth.”','You propose using the buckle as a crown for a very small monarch. Neris turns it sideways. “A portrait frame for a beetle.” Then she considers a folding handle and catches herself. “No. Back to the beetle. Does it look sufficiently royal?”'),
 
 'sabine':('The unnecessary flourish','Sabine adjusts a ribbon with theatrical care. “There. An entirely unnecessary improvement to expedition morale.”','You admire the flourish. She admits she likes looking lovely for her own amusement, then asks which part amused you.'),
 'koharu':('Hands without a task','Koharu holds her cup in both hands. “If I put this down, I shall find something to mend. Help me maintain the obstacle.”','“I want to carve something that serves no purpose,” Koharu says. “A bird so offended that nobody can mistake it for a hook.” You ask how she will keep people from hanging coats on it. “Carve two. Let them look disapprovingly at each other.”'),
 'zahra':('A very dignified blanket','Zahra has wrapped herself in a blanket with only her face showing. “You may address the expedition commander. Briefly.”','“Two biscuits remain, Commander,” you report. “Both requesting immediate transfer.” Zahra extends one hand from the blanket. “Granted. Send the first to me and retain the second as your reward for accurate intelligence.” She breaks character when you salute with it.'),
 'fenna':('The route she chose to stay on','Fenna stretches her legs and watches the doorway. “Usually I would be wondering what is round the next corner. This is a pleasant exception.”','“You asked about the innkeeper before asking whether the shortcut saved time,” Fenna says. “Most people want the route and stop listening when they have it. I like that you want to know who opens the door.” She stretches out her legs. “Also, this bench is exceptionally good.”'),
 'kaede':('A pause with no lesson','Kaede sets her practice cord aside. “We do not have to improve at anything for a little while.”','Kaede points to the amber light inside her cup. “I used to hold coloured glass against a lamp to compare it with the finished piece. That colour was always harder to keep once the glass cooled.” She turns the cup. “I still want to make a panel that looks like this.”'),
 'elowen':('A small extravagant comfort','Elowen has saved a fragrant leaf for the shared kettle. “It changes nothing essential. I wanted it anyway.”','“Lemon balm by the seat. Thyme where I can brush it with my sleeve. Something with flowers I can cut without losing every bloom.” Elowen inhales the steam. “And one shelf too high for a cat. I have learned to budget for the cat.”'),
 'nyssara':('Off duty, visibly','Nyssara unfastens her outer cloak. “There. Evidence that I am not secretly keeping watch while claiming to rest.”','Nyssara watches the rain run past the shelter. “At home you could tell whose workshop was open by the lamps under the doors. One neighbour left his burning after he went to bed so nobody would call him lazy.” She smiles. “The snoring compromised the deception.”'),
 'sylva':('An excellent place to linger','Sylva finds the warmest patch of the bench and leaves room beside her. “No discovery. No emergency. Just a rather good place.”','“A traveller described a magnificent flowering tree to me for ten minutes. I asked what she liked best. She said it was the only shade on the road.” Sylva stretches her hands along the warm bench. “I liked her better for that answer. Where would you stop if you were choosing?”')
}
PAIRS=[
 ('mira','neris','Mira proposes a precise label. Neris asks whether anyone will understand it while cold and tired. Mira crosses out half the words.'),
 ('tamsin','zahra','Tamsin starts counting the work still ahead. Zahra counts the empty cups instead. “We can solve this problem first.”'),
 ('iona','sabine','Iona offers a grand introduction for Sabine’s improvised travel outfit. Sabine supplies an even grander entrance, taking exactly one step.'),
 ('aurelia','kaede','Aurelia asks whether sitting still counts as practice. Kaede replies, “Only if you stop trying to win.”'),
 
 ('koharu','elowen','Koharu explains how she would improve the kettle. Elowen pours the tea before the explanation can become another job.'),
 ('fenna','sylva','Fenna points out the quickest way onward. Sylva points out the best place to sit. They agree that both belong on the map.')
]
