"""Authored field disciplines for the remaining established household.

The engine owns effects; this catalogue owns names, applications and voices.
No procedural resident is silently assigned a named companion's identity.
"""
def t(key,name,tags,damage=0,guard=0,cost=0,text='',**effects):
 return (key,name,tags.split(),damage,guard,cost,text,effects)
def branch(key,name,theme,enchant,root,advanced,passive,effect):
 meaning={'damage':'techniques gain 1 damage.','block':'techniques gain 1 guard.','pace':'obstacle work takes 1 phase instead of 2.','support':'obstacle work takes 1 phase; restorative techniques heal 1 additional vitality.','keeper':'obstacle work takes 1 phase; binding attacks gain 1 additional damage against constructs or undead.'}
 return (key,name,theme,enchant,root,advanced,(key+'-practice',passive,name+' '+meaning[effect],effect))
ADDITIONS={
'founder':{'room':'workshop','branches':[
 branch('scholar-reader','Field scholar','Understand the mechanism before putting your hand inside it.','clear-measure',
  t('scholar-annotation','Working annotation','insight social',text='Compare the instructions and explain a workable agreement.'),
  t('scholar-unbinding','Unbinding stroke','enemy insight',2,0,text='Strike the flaw in an artificial binding; +2 damage against constructs and undead.',bonusAgainst=['construct','undead'],bonusDamage=2),
  'Read twice','keeper'),
 branch('scholar-warden','Hearth warden','Make a dependable home, and carry a little of that steadiness outside.','warded-cover',
  t('scholar-ward','Portable ward','enemy physical',1,2,text='Hold a short ward while making a careful strike.'),
  t('scholar-relief','A place to breathe','enemy',1,1,text='Create cover and restore 1 vitality to an injured companion.',healsAlly=1),
  'A familiar shelter','block'),
 branch('scholar-practical','Practical explorer','Let useful tools turn theory into a safe route.','sure-footing',
  t('scholar-handline','Tested handline','gap trail',text='Rig and test a handline before committing the party.'),
  t('scholar-apparatus','Improvised apparatus','submerged physical height',text='Combine the available fittings into a stable working rig.'),
  'Useful field notes','pace')]},
'mira':{'room':'library','branches':[
 branch('mira-archive','Archivist','Bring the overlooked instruction back into the conversation.','clear-measure',
  t('mira-margins','Read the margins','insight social',text='Find the small correction that makes the instructions agree.'),
  t('mira-release','Release from service','enemy insight',1,1,text='Read a dismissal into an old binding; +3 damage against undead.',bonusAgainst=['undead'],bonusDamage=3),
  'Living cross-reference','keeper'),
 branch('mira-lamplight','Lamplight','A reading lamp can reveal more than a page.','measured-force',
  t('mira-lamp','Shuttered beam','enemy fire',2,0,text='Focus useful light; +2 damage against undead.',bonusAgainst=['undead'],bonusDamage=2),
  t('mira-afterimage','Held afterimage','enemy',2,2,text='A short flare conceals a guarded step back.'),
  'A clear impression','damage'),
 branch('mira-fieldnotes','Field correspondent','Come home with both the notes and their author.','sure-footing',
  t('mira-route','Annotated route','trail gap',text='Mark the small route details that everyone needs to follow.'),
  t('mira-return','Return margin','height submerged physical',text='Find the inspection path that the grand plan left out.'),
  'Leave room for the route','pace')]},
'tamsin':{'room':'kitchen','branches':[
 branch('tamsin-binding','Binder','Mend the part carrying the strain.','clear-measure',
  t('tamsin-stitch','Load-bearing stitch','physical insight',text='Secure a failing fastening and redistribute its load.'),
  t('tamsin-snare','Binding loop','enemy physical',1,2,text='Catch a moving limb in a temporary binding, then withdraw.'),
  'Sound stitching','pace'),
 branch('tamsin-quickpaw','Quickpaw','A small, well-timed movement is quite enough.','sure-footing',
  t('tamsin-feint','Needle feint','enemy gap',2,1,text='A quick feint creates space for a precise strike.'),
  t('tamsin-return','Returning needle','enemy',1,1,text='Turn a missed attack aside; counter for 2 damage if the foe survives.',counter=2),
  'An exact opening','damage'),
 branch('tamsin-hearth','Hearth companion','Useful care is often a matter of noticing first.','warded-cover',
  t('tamsin-wrap','Firm wrapping','enemy',1,1,text='Cover a quick field dressing; restore 1 vitality to an injured companion.',healsAlly=1),
  t('tamsin-carry','Shared burden','physical flood',text='Secure the awkward load and help the others carry it.'),
  'Attentive hands','support')]},
'iona':{'room':'command-room','branches':[
 branch('iona-crossings','Crossing keeper','Every crossing should have a clear way back.','sure-footing',
  t('iona-foothold','Mark the far foothold','gap height trail',text='Map the sound footholds and establish a return line.'),
  t('iona-service','Service passage','submerged insight',text='Trace the maintenance route rather than forcing the main opening.'),
  'An atlas of small ways','pace'),
 branch('iona-signals','Field coordinator','A useful instruction arrives before the danger.','warded-cover',
  t('iona-signal','Signal and brace','enemy physical',2,1,text='Call the moment to brace and answer with a guarded strike.'),
  t('iona-relief','Call the relief','enemy',1,2,text='Cover a companion’s recovery; restore 1 vitality to the most injured other traveller.',healsAlly=1),
  'Unmistakable signals','support'),
 branch('iona-threshold','Threshold warden','Read what the boundary is actually asking for.','clear-measure',
  t('iona-watchword','Practical watchword','social insight',text='Explain the party’s purpose in the terms the keeper expects.'),
  t('iona-sever','Sever the false command','enemy insight',2,0,text='Interrupt a faulty command; +2 damage against constructs.',bonusAgainst=['construct'],bonusDamage=2),
  'The right boundary','keeper')]},
'aurelia':{'room':'guard-barracks','branches':[
 branch('aurelia-guard','Shieldbearer','Protection should leave room for the person inside it.','warded-cover',
  t('aurelia-turn','Room to turn','enemy physical',2,1,text='Turn behind cover and answer with a measured thrust.'),
  t('aurelia-catch','Catch the overreach','enemy',1,2,text='Let the attack pass the guard; counter for 2 damage if the foe survives.',counter=2),
  'An open guard','block'),
 branch('aurelia-lantern','Lantern bearer','Aim the light where it helps someone act.','measured-force',
  t('aurelia-ray','Guiding ray','enemy fire',2,0,text='A focused line of light; +2 damage against undead.',bonusAgainst=['undead'],bonusDamage=2),
  t('aurelia-shutter','Close the shutter','enemy',3,1,text='A bright, brief opening followed by immediate cover.'),
  'Steady radiance','damage'),
 branch('aurelia-relief','Relief guard','A guard who can accept relief can offer it well.','clear-measure',
  t('aurelia-breath','Sheltered breath','enemy',1,1,text='Hold the line while an injured companion recovers 1 vitality.',healsAlly=1),
  t('aurelia-carry','Carry the lantern home','gap height flood',text='Secure a bright, steady route for the slower travellers.'),
  'A watch shared','support')]},
'neris':{'room':'hot-spring','branches':[
 branch('neris-water','Tidewalker','Work with the current before arguing with it.','sure-footing',
  t('neris-current','Read the current','flood submerged gap',text='Find the quiet water and use it to secure the crossing.'),
  t('neris-pressure','Pressure ribbon','enemy fire',2,0,text='Direct a narrow ribbon of water; +2 damage against ember creatures.',bonusAgainst=['ember'],bonusDamage=2),
  'Sure hands in the rain','pace'),
 branch('neris-glass','Glass edge','Let the angle do the work.','measured-force',
  t('neris-facet','Facet stroke','enemy insight',2,0,text='Find the exposed joint; +1 damage against constructs.',bonusAgainst=['construct'],bonusDamage=1),
  t('neris-reflect','Reflected opening','enemy',1,1,text='Follow the opponent’s reflected movement; counter for 2 damage if it survives.',counter=2),
  'A clean facet','damage'),
 branch('neris-still','Still pool','Find a quiet moment even inside a rough exchange.','warded-cover',
  t('neris-cool','Cooling cover','enemy',1,1,text='Protect a quick cooling compress; restore 1 vitality to an injured companion.',healsAlly=1),
  t('neris-settle','Settle the surface','enemy',2,1,text='Recover composure behind a watery screen; restore 1 own vitality after retaliation.',restoresSelf=1),
  'Unruffled care','support')]},

'koharu':{'room':'workshop','branches':[
 branch('koharu-repair','Repairwright','Keep the useful wear and mend the troublesome part.','clear-measure',
  t('koharu-joint','Read the joint','physical insight',text='Find the fastening that carries the strain.'),
  t('koharu-wedge','Service wedge','enemy physical',2,1,text='Wedge a moving joint; +1 damage against constructs.',bonusAgainst=['construct'],bonusDamage=1),
  'Useful wear','keeper'),
 branch('koharu-brace','Stagecraft','Use misdirection, timing and a well-placed prop.','warded-cover',
  t('koharu-shoulder','Set the screen','enemy flood',2,1,text='Set a folding screen to divert the pressure and keep a safe working space.'),
  t('koharu-lift','Feint and turn','enemy physical',4,0,1,'Draw attention to a moving decoy, then strike from the side; costs 1 vitality.'),
  'A dependable stance','block'),
 branch('koharu-care','Careful hands','Notice the loose strap before somebody trips.','sure-footing',
  t('koharu-strap','A better strap','gap height trail',text='Refit a strap and guide the party along the safer footing.'),
  t('koharu-dressing','Maker’s dressing','enemy',1,1,text='Keep cover while securing a dressing; restore 1 vitality to an injured companion.',healsAlly=1),
  'Care made practical','support')]},
'zahra':{'room':'smithy','branches':[
 branch('zahra-survey','Surveyor','Mark the line, then test what the mark promises.','clear-measure',
  t('zahra-level','Find the level','flood submerged insight',text='Check the channel gradient and choose a controlled way through.'),
  t('zahra-fulcrum','Measured fulcrum','physical gap height',text='Set a reliable fulcrum or anchor where the measurements support it.'),
  'An honest measure','pace'),
 branch('zahra-hammer','Hammerwright','Place a controlled stroke exactly where the fitting needs it.','measured-force',
  t('zahra-peen','Peen the weak joint','enemy physical',2,0,text='Strike the failing fitting; +2 damage against constructs.',bonusAgainst=['construct'],bonusDamage=2),
  t('zahra-drive','True driving stroke','enemy',4,0,1,'Drive through the marked line; costs 1 vitality.'),
  'Nothing wasted','damage'),
 branch('zahra-anchor','Anchor','Hold steady while the others do their part.','warded-cover',
  t('zahra-hold','Hold the working line','enemy physical',1,2,text='Keep the working line stable behind a broad guard.'),
  t('zahra-answer','Answer the strain','enemy',1,2,text='Return the force through a controlled counter: 2 extra damage if the foe survives.',counter=2),
  'A sound foundation','block')]},
'fenna':{'room':'common-room','branches':[
 branch('fenna-path','Pathfinder','The small route is often the useful one.','sure-footing',
  t('fenna-trail','Listen to the trail','trail gap',text='Read footprints, small sounds and the usable side path.'),
  t('fenna-highway','The overlooked way','height submerged flood',text='Find the low-risk route that never made it onto the grand map.'),
  'Notes instead of boasts','pace'),
 branch('fenna-flank','Outflanker','Make the opponent turn before making your move.','measured-force',
  t('fenna-angle','Oblique strike','enemy',3,0,text='Circle into a clean opening.'),
  t('fenna-return','The returning step','enemy',1,1,text='Slip around a committed attack; counter for 2 damage if the foe survives.',counter=2),
  'Read the footfall','damage'),
 branch('fenna-company','Trail companion','A good route includes the person who is falling behind.','warded-cover',
  t('fenna-close','Close the gap','enemy physical',2,1,text='Close the dangerous space before a companion has to cross it.'),
  t('fenna-recover','A sheltered pause','enemy',1,1,text='Give an injured companion time to recover 1 vitality.',healsAlly=1),
  'No one left behind','support')]},
'elowen':{'room':'infirmary','branches':[
 branch('elowen-mender','Mender','Give care that the person receiving it can understand.','warded-cover',
  t('elowen-dressing','Cover and dress','enemy',1,1,text='Protect a quick field dressing; restore 1 vitality to an injured companion.',healsAlly=1),
  t('elowen-recovery','Guided recovery','enemy',1,0,text='Concentrate on a companion’s recovery; restore 2 vitality to the most injured other traveller.',healsAlly=2),
  'A reassuring hand','support'),
 branch('elowen-ward','Wardscribe','Make the working clear to the people depending on it.','clear-measure',
  t('elowen-warning','Legible warning','insight social',text='Explain the ward’s limits and agree a safe way forward.'),
  t('elowen-release','Gentle dismissal','enemy insight',2,1,text='Unpick an old animating instruction; +2 damage against undead.',bonusAgainst=['undead'],bonusDamage=2),
  'A readable circle','keeper'),
 branch('elowen-poise','Steady voice','Composure can make a difficult action possible.','sure-footing',
  t('elowen-count','Count the crossing','gap height flood',text='Set a calm pace and guide each person to the next secure hold.'),
  t('elowen-balance','Recover the balance','enemy',2,1,text='Regain your own footing; restore 1 own vitality after retaliation.',restoresSelf=1),
  'Patience in practice','block')]},
'nyssara':{'room':'enchanting-room','branches':[
 branch('nyssara-inscriber','Inscriber','Use the inscription that passed its proof.','measured-force',
  t('nyssara-score','Score the binding','enemy insight',2,0,text='Strike across a binding seam; +2 damage against constructs.',bonusAgainst=['construct'],bonusDamage=2),
  t('nyssara-discharge','Measured discharge','enemy',4,0,1,'Release a tested charge through the fitting; costs 1 vitality.'),
  'A proven line','damage'),
 branch('nyssara-assayer','Assayer','Measure twice, then let somebody else read the result.','clear-measure',
  t('nyssara-test','Test the mark','insight social',text='Compare marks and records until the mismatch is clear.'),
  t('nyssara-service','Isolate the working','physical submerged fire',text='Separate the active part from the damaged housing.'),
  'Repeatable results','pace'),
 branch('nyssara-control','Channel keeper','Control includes knowing when to stop feeding the spell.','warded-cover',
  t('nyssara-buffer','Buffered contact','enemy',1,2,text='Test the opponent through a guarded channel.'),
  t('nyssara-return','Return the impulse','enemy',1,1,text='Redirect an overcommitted strike; counter for 2 damage if the foe survives.',counter=2),
  'A clean cutoff','block')]},
'sylva':{'room':'conservatory','branches':[
 branch('sylva-roots','Rootkeeper','Use what is already holding the ground together.','warded-cover',
  t('sylva-anchor','Living anchor','enemy physical',1,2,text='Brace with a rooted stance and a short, guarded strike.'),
  t('sylva-draw','Draw the snag','enemy',2,1,text='Catch the attack and turn its momentum; counter for 1 damage if the foe survives.',counter=1),
  'Deep holding roots','block'),
 branch('sylva-tending','Green tender','Help recovery without exhausting the living source.','clear-measure',
  t('sylva-poultice','Leaf dressing','enemy',1,1,text='Shield a quick green dressing; restore 1 vitality to an injured companion.',healsAlly=1),
  t('sylva-regrow','Patient renewal','enemy',1,1,text='Preserve enough strength to recover 2 own vitality after retaliation.',restoresSelf=2),
  'Room to recover','support'),
 branch('sylva-thicket','Thicket walker','A living route can be asked, not simply cut.','sure-footing',
  t('sylva-thread','Thread the growth','trail gap',text='Follow the spaces between roots and secure them for the party.'),
  t('sylva-bank','Read the living bank','flood height physical',text='Use the sound growth to stabilize a crossing or a lift.'),
  'Leave the roots intact','pace')]},
'velis':{'room':'supply-office','branches':[
 branch('velis-broker','Broker','Keep the promise legible to both sides.','clear-measure',
  t('velis-account','Reconcile the account','social insight',text='Compare the claims, identify the mismatch, and agree a workable correction.'),
  t('velis-seal','Break the false seal','enemy insight',2,0,text='Disrupt a seal that is enforcing the wrong order; +2 damage against constructs or undead.',bonusAgainst=['construct','undead'],bonusDamage=2),
  'Both copies agree','keeper'),
 branch('velis-route','Route factor','Deliver the people before counting the goods.','sure-footing',
  t('velis-load','Choose the safe load','physical trail',text='Sort the burden and choose a route the party can actually manage.'),
  t('velis-bridge','A bridge worth trusting','gap flood height',text='Check the supports and arrange a controlled crossing.'),
  'A dependable route','pace'),
 branch('velis-provisioner','Quartermaster','The useful supply is the one somebody remembered to bring.','warded-cover',
  t('velis-cover','Receiving-yard guard','enemy',2,1,text='Keep a clear lane and a guarded stance.'),
  t('velis-kit','The ready field kit','enemy',1,1,text='Use a ready dressing under cover; restore 1 vitality to an injured companion.',healsAlly=1),
  'Nothing essential forgotten','support')]},
}
