"""Authored preferences, invitations and a shared household disagreement."""
# Preferences are personal, not ancestry bonuses. Boundary-respecting alternatives
# are ordinary choices; no attribute can override consent.
PREFERENCES = {
 'mira': ('Careful questions and shared discoveries', 'Ask before correcting her work in public', 'An unfinished index', 'Mira leaves two cards beside an unfinished index. “Would you help me name a category? I am asking for a second mind, not an audience.”', 'You compare two stubborn entries. Mira keeps your different interpretation in the margin. “Useful. We can disagree without one of us disappearing.”'),
 'tamsin': ('Company without making her responsible for everyone', 'Ask what she wants before offering her help to others', 'A cup for herself', 'Tamsin has poured one cup, then hesitates over a second. “Will you sit? I do not want to plan supper while we do.”', 'She leaves the household list folded. The conversation wanders, and nobody turns it into a job. “I had forgotten I could invite someone without hosting them.”'),
 'iona': ('Playfulness and permission to start again', 'Do not turn a private joke into a public performance', 'A tune with no audience', 'Iona taps a rhythm on the table. “Help me find an ending? Nobody else needs to hear this version.”', 'The first ending collapses into laughter. You try a quieter one and keep both. “A rehearsal can be a good evening all by itself.”'),
 'aurelia': ('Direct invitations and dependable follow-through', 'Let her decline duty when she is off watch', 'Beyond the watch', 'Aurelia sets down her gloves. “A circuit of the courtyard, without an inspection? I would like to see what you notice.”', 'You stop where she usually checks the gate. This time she points out a climbing flower. “It has been there all week. Apparently so have I.”'),
 'neris': ('Precise questions and room to think', 'Do not mistake quiet concentration for agreement', 'Two possible answers', 'Neris has drawn two explanations of the same mechanism. “Choose the one you distrust. I want to know where you get lost.”', 'She crosses out a beautiful but misleading arrow. “That was my favourite part. Thank you for telling me it was unhelpful.”'),
 
 'sabine': ('Being heard beyond a polished first impression', 'Do not presume charm is consent or intimacy', 'The unpolished version', 'Sabine folds a graceful little speech. “Can I tell you the version without the elegant ending?”', 'The story finishes untidily. You let it. Sabine smiles without reaching for a better line. “That was much less exhausting.”'),
 'maren': ('Practical experiments and honest uncertainty', 'Ask before moving tools or unfinished work', 'The spare piece', 'Maren holds up a spare wooden joint. “No commission. No deadline. Want to see whether our bad idea holds?”', 'It holds until you both lean on it, then parts cleanly. Maren studies the break with delight. “Now that is an answer we can use.”'),
 'brakka': ('Patience and recognition of careful work', 'Do not volunteer her strength as a household resource', 'Something small', 'Brakka is sorting tiny wooden pegs. “People ask me about beams. Would you like to help with something that needs a gentler hand?”', 'You sort by grain rather than size. She shows you how a peg can split a joint if rushed. “Strong is useful. Careful is what makes it last.”'),
 'fenna': ('Curiosity and invitations without obligation', 'Do not repeat a confidence as an entertaining story', 'A story to keep here', 'Fenna leans across the table. “I have a story that is not for retelling. Still interested?”', 'The story is funny, then unexpectedly tender. You leave the names where she left them. “Thank you for letting it belong to the people inside it.”'),
 'kaede': ('Quiet companionship and deliberate practice', 'Do not demand a performance to prove competence', 'The imperfect attempt', 'Kaede lays a practice cord between you. “A slow attempt together? I would rather learn than demonstrate today.”', 'You stop at the same awkward turn and untie it together. “I can show uncertainty when it does not become a verdict.”'),
 'elowen': ('Gentle attention and specific offers of help', 'Ask before treating her kindness as an unlimited promise', 'Leave one thing undone', 'Elowen closes a basket. “Sit with me while I leave this until later? I could use company in being sensible.”', 'You leave the basket closed. She talks about something she wants, instead of something someone needs. “Tomorrow can have its own share of me.”'),
 'nyssara': ('Thoughtful questions and control over disclosure', 'A declined question stays declined', 'The question she chooses', 'Nyssara moves a chair into the light. “You may ask about my work. Today I would rather tell you why I chose it.”', 'You follow the part she offers instead of searching for the part she leaves out. “An account need not be complete to be honest.”'),
 'sylva': ('Unhurried observation and shared stewardship', 'Do not promise living things a use before understanding them', 'A quiet observation', 'Sylva has found a new shoot beside an old pot. “Will you look with me before we decide what it should become?”', 'You notice the direction it is leaning and turn neither pot nor conversation toward a task. “A little attention can come before a plan.”'),
}
PEOPLE = ['founder', 'mira', 'tamsin']
# choice = (label, response, relationship dimension)
STORY = [
 {'id':'table','title':'One table, two kinds of work', 'opening':'Mira has spread damp archive copies across the common-room table. Tamsin arrives with a basket and stops. “I said I needed this space.” Mira lifts an ink-stained hand. “I thought you meant after the copies dried.” Neither looks at you for a verdict, but both make room for you to join them.', 'choices':{
  'listen':('Ask each of them what the interruption cost.', 'Mira explains that moving the sheets now would muddle their order. Tamsin says the basket is not the problem: asking twice and still being overlooked is. Mira stops defending the ink. “Then I answered a different question from the one you asked.”', 'trust'),
  'name':('Name the misunderstanding without choosing a winner.', '“I treated quiet as agreement,” Mira says. Tamsin sets the basket down. “And I assumed a reminder would sound like nagging.” They agree that politeness has been doing a poor job of keeping the table clear.', 'respect'),
  'comfort':('Offer company while they find words for it.', 'You pull up a third chair. After a while Tamsin says, “I do want your work here, Mira. I want mine to count as work too.” Mira makes space for the basket before answering. “It does. I have not been showing that.”', 'affection')}},
 {'id':'needs','title':'What the room is for', 'opening':'The table is clear enough for three cups. Mira brings a list of things that damage wet copies. Tamsin brings no list. “If we make a schedule, I need it to include time when nobody is responsible for being useful.”', 'choices':{
  'ask':('Ask them to suggest one change for each other.', 'Mira offers to ask before spreading work out. Tamsin offers to warn her before the room gets noisy. “And neither offer means always,” Tamsin adds. Mira writes that down first.', 'trust'),
  'boundary':('Keep a right to say no in any agreement.', '“Even when the work matters?” asks Mira. “Especially then,” Tamsin replies. Mira considers it, then strikes out the word urgent from her proposed exception. “I would have used that too freely.”', 'respect'),
  'rest':('Include time together that has no work attached.', 'Tamsin suggests a table that is simply a table for part of the day. Mira admits she has been bringing research downstairs because she wanted company. They discover they had both been asking for the same room in different ways.', 'affection')}},
 {'id':'agreement','title':'An agreement small enough to keep', 'opening':'Mira and Tamsin want to try one small agreement before writing any permanent rules. They ask what part you are willing to take. They will not treat your silence as a promise.', 'choices':{
  'turns':('Promise to help mark a shared table plan.', 'Mira proposes movable name cards, not permanent claims. Tamsin adds a blank card for anyone who wants the table without explaining why. You agree to sit down together later and make the first plan.', 'trust'),
  'askfirst':('Promise to practise asking before taking the space.', 'Tamsin offers the first question: “Is this a good time?” Mira tries answering “Not yet” without an apology. You promise to rehearse the exchange with them after everyone has had a little distance.', 'respect'),
  'company':('Promise to share a break without bringing work.', 'Mira closes her notebook. Tamsin leaves the basket where it is. You agree that the next shared break will be company, without using it to slip in one last request.', 'affection'),
  'no_promise':('Offer support, but make no promise about your time.', '“Thank you for saying so before we relied on it,” Tamsin says. Mira and Tamsin decide to make their own trial arrangement, then invite you to hear how it went. Your chair stays at the table.', 'respect')}},
 {'id':'followthrough','title':'Returning to the table', 'opening':'Mira and Tamsin have left room for the conversation you agreed to return to. There is no deadline. They want to know what you can actually do, rather than hear a reassuring answer you cannot keep.', 'choices':{
  'keep':('Follow through on the agreed small step together.', '', 'trust'),
  'renegotiate':('Explain that the original offer was too much; agree a smaller one.', 'You name what you cannot sustain. Tamsin asks for one clear question before shared space changes hands. Mira agrees to ask it too. You practise now, and record this smaller agreement as completed. “An honest revision is something I can plan around,” Tamsin says.', 'respect'),
  'apologise':('Apologise for making the offer too quickly and withdraw it.', '“I wanted to give you the answer you hoped for,” you say. Mira puts the unfinished card aside. Tamsin accepts the apology without pretending it fulfils the promise. “Tell us sooner next time. You are still welcome here.” They take responsibility for their own arrangement.', 'trust')}},
 {'id':'review','title':'The first awkward revision', 'opening':'The arrangement has had time to settle in. Mira laughs at how formal their first exchange sounded. Tamsin says the formality helped her answer honestly. They disagree about whether the cards belong on the table every day.', 'choices':{
  'flex':('Let them keep different habits, with the same right to ask.', 'Mira will use a card when she has fragile work. Tamsin will ask aloud when she wants company. “We do not need to become the same person to be considerate,” Mira says. Tamsin nudges a cup toward her.', 'respect'),
  'repair':('Ask each to name something the other changed.', 'Tamsin noticed Mira moved her copies before being asked twice. Mira noticed Tamsin gave a direct answer instead of quietly finding another room. They thank each other, a little awkwardly, without asking you to translate.', 'trust'),
  'laugh':('Make room for an imperfect agreement that is helping.', 'Tamsin displays a card that says DEFINITELY NOT A MEETING. Mira has annotated it with “subject to tea.” They argue cheerfully about whether annotation counts as work, then put the card between their cups.', 'affection')}},
 {'id':'callback','title':'A place left open', 'opening':'Later, you find Mira and Tamsin at the table before either has called for you. Mira asks whether Tamsin wants quiet or conversation. “Conversation,” Tamsin says. “But I reserve the right to change my mind.” There is an empty chair.', 'choices':{
  'join':('Join them and ask what they are talking about.', 'They have been comparing the work they once mistook for effortless. You listen as Mira asks a question and Tamsin answers it herself. For once you are company, not the person holding the conversation together.', 'affection'),
  'notice':('Tell them you noticed they no longer need you to mediate.', '“We needed help beginning,” Mira says. “Not a permanent referee.” Tamsin adds, “You can still have the chair.” The invitation is warm, and it is theirs to make.', 'respect'),
  'space':('Thank them for the invitation and leave them their conversation.', 'Tamsin waves you on without taking offence. Mira moves a cup away from the empty chair so it stays available. Later they tell you a little of what they discussed, only the part they both wanted to share.', 'trust')}}
]
FOLLOWTHROUGH = {
 'turns':'You write three movable cards together: fragile work, company welcome, and space wanted. Tamsin tests the blank card without giving a reason. Mira clears a place for it. Your promised planning conversation is complete; no work assignment or room ownership changes.',
 'askfirst':'You practise asking, waiting for an answer and accepting “not yet.” Mira tries it with Tamsin, then Tamsin tries it with Mira. Your promised rehearsal is complete. “That is clearer than guessing which sigh meant yes,” Tamsin says.',
 'company':'You sit with them and leave the reports unopened. Mira tells a story that has no useful conclusion. Tamsin does not offer to fetch anything. You have shared the break you promised; the next work phase still waits for your choice.',
 'no_promise':'Mira and Tamsin show you their trial arrangement. They made it themselves, as agreed. You hear what worked without taking credit for their effort. No promise was expected of you, and none is marked fulfilled.'
}
