"""Authored resident friendships. Replies are shown only after the relevant event."""

PROJECTS = {
    'neris|zahra': dict(
        title='A glass chime with a proper last note', room='workshop', displayRoom='common-room', keepsake='Glass-and-brass chime',
        invitation='Zahra has tapped out a tune on the table. Neris wants to hear it played on glass. They ask for time at the workbench together.',
        introduction=[('zahra', 'The little tune needs four notes. Most chimes would give us four notes at once.'), ('neris', 'Then we make something you can play. Four glass drops, four brass hooks. May I choose the colours?'), ('zahra', 'Choose the colours. I am keeping the last note.')],
        completion=[('neris', 'The blue drop rings longest. Put that one last.'), ('zahra', 'That is the note I wanted. Listen.'), ('narrator', 'Zahra plays the four drops in order. Neris steadies the frame until the final blue note fades. They write their names under the stand and place it in the common room.')],
        outing='Zahra and Neris want to try their chime away from the noisy workbench.',
        outingLines=[('neris', 'By the hearth, the blue note sounds warmer.'), ('zahra', 'That is the rug taking the sharp edge off it. Hold it over the bare floor.'), ('narrator', 'They try both places, then choose the shelf beside the rug. Neris marks four coloured dots on a card so anyone can learn the tune.')],
        reflection=[('zahra', 'I used to wait for you to finish changing the glass before I tried the tune.'), ('neris', 'And I used to keep changing it because you had not played anything yet.'), ('narrator', 'They laugh at the old misunderstanding. This time Zahra plays while Neris tries a fifth glass drop; together they find a short variation worth keeping.')]),
    'mira|tamsin': dict(
        title='A book rest that keeps the page open', room='library', keepsake='Adjustable shared book rest',
        invitation='Mira wants to read a large travel journal without flattening its spine. Tamsin proposes a small book rest they can fit together.',
        introduction=[('mira', 'The traveller has reached the desert. The binding is trying to close the account.'), ('tamsin', 'Because you are holding it flat. Let the boards sit at an angle.'), ('mira', 'Can we keep the map visible?'), ('tamsin', 'Yes. Two wedges and a loose page ribbon. You choose the angle; I will keep the spine intact.')],
        completion=[('tamsin', 'The ribbon holds the page. Do not tighten it like a parcel.'), ('mira', 'The desert remains accessible. A triumph for travellers who prefer chairs.'), ('narrator', 'They fit the two wedges and test three heavy books. Tamsin marks the safe openings beneath the rest; Mira leaves the travel journal ready for the next reader.')],
        outing='Mira and Tamsin invite you to a reading using their finished book rest.',
        outingLines=[('mira', 'He describes the oasis as a welcome surprise. It is on his own map.'), ('tamsin', 'Perhaps he had folded that part underneath.'), ('narrator', 'They check the foldout and find a second oasis drawn beside a stain. Mira adds a removable note; Tamsin repairs the fold without covering the mark.')],
        reflection=[('tamsin', 'You leave space for the repair notes now.'), ('mira', 'You read the travel account before deciding where to mend it.'), ('narrator', 'They turn the rest to a new journal. The map opens easily, and both lean in when the route crosses the edge of the page.')]),
    'iona|kaede': dict(
        title='A route board with two ways home', room='command-room', keepsake='Reversible practice route board',
        invitation='Iona proposes a tabletop route puzzle. Kaede wants a version whose quickest route is not automatically the best one.',
        introduction=[('kaede', 'If the red line is the answer, the exercise is over before I start.'), ('iona', 'Then the red line will be the flooded road. I enjoy a confident wrong turning.'), ('kaede', 'Give me a second way back. I want to test a retreat as well.')],
        completion=[('iona', 'The bridge token comes off. Now choose your return route.'), ('kaede', 'Along the ridge. Longer, but we do not have to ford the stream.'), ('narrator', 'They build a reversible board with removable bridges and two marked shelters. Iona writes the distances; Kaede adds a simple rule for changing conditions halfway through a round.')],
        outing='Iona and Kaede want to play the first full round with the new route board.',
        outingLines=[('kaede', 'You moved the bridge after I committed to the road.'), ('iona', 'Rain is notoriously poor at waiting its turn.'), ('narrator', 'Kaede takes the longer ridge route, then wins the return round by keeping a shelter token in reserve. Iona records the winning route on the back of the board.')],
        reflection=[('iona', 'I can no longer catch you with the bridge.'), ('kaede', 'You still catch me when I hurry. Set the board again.'), ('narrator', 'They agree to alternate who changes the conditions. The next round lasts longer because both now notice the unused routes.')]),
    'aurelia|koharu': dict(
        title='A lantern shutter that works with gloves', room='workshop', keepsake='Glove-friendly practice lantern',
        invitation='Aurelia has trouble turning a small lantern shutter with gloves on. Koharu asks her to help test a wider handle.',
        introduction=[('aurelia', 'Without gloves, the handle is excellent. Unfortunately, that is not when I need it.'), ('koharu', 'Show me where your thumb lands. I can widen the loop without changing the hinge.'), ('aurelia', 'And leave enough room that I do not catch the cuff.')],
        completion=[('koharu', 'Try it without looking down.'), ('aurelia', 'Open. Closed. And my glove is still attached to me.'), ('narrator', 'They fit a wider shutter loop and smooth its edges. Aurelia tests it with both hands before they put the practice lantern beside the household duty notes.')],
        outing='Aurelia and Koharu propose a short courtyard test of their lantern shutter.',
        outingLines=[('aurelia', 'I can find the loop in the dark. The stop needs to be firmer.'), ('koharu', 'There. A small washer. Try the signal again.'), ('narrator', 'Aurelia opens and closes the shutter across the courtyard. Koharu answers each signal from the doorway, then they add a tactile mark to the handle.')],
        reflection=[('koharu', 'You point out the awkward part before I polish it now.'), ('aurelia', 'You hand me the unfinished piece before deciding it is ready.'), ('narrator', 'They check the shutter together and replace its worn washer. Their original test notes stay with the lantern.')]),
    'elowen|sylva': dict(
        title='A cutting tray with honest labels', room='conservatory', keepsake='Labelled mint cutting tray',
        invitation='Elowen and Sylva want to compare two ways of rooting mint cuttings. They ask for a tray and a place where neither sample will be moved by mistake.',
        introduction=[('elowen', 'I labelled this one “probably mint”. I hoped you might improve the description.'), ('sylva', 'It is mint. The other pot is also mint, which is about to occupy the first pot.'), ('elowen', 'Separate compartments, then. And labels that admit when we started them.')],
        completion=[('sylva', 'Water for these cuttings, damp soil for those. Same light.'), ('elowen', 'And the date on both labels. We are ready to disagree usefully.'), ('narrator', 'They divide the tray, set the cuttings at equal height and label each method. The tray remains on the conservatory bench as their shared project.')],
        outing='Elowen and Sylva invite you to check the cutting tray and record what has changed.',
        outingLines=[('elowen', 'No roots on this one yet. Shall I change the water?'), ('sylva', 'Yes, but leave the cutting in the same place. We will learn nothing by changing everything.'), ('narrator', 'They check the stems and add a dated observation to each label. Neither marks the trial successful before roots appear.')],
        reflection=[('elowen', 'You have left my question on the label.'), ('sylva', 'We still have to answer it. That is what the next tray is for.'), ('narrator', 'They clean a spare compartment and agree which condition to compare next. Their first dated labels stay clipped to the tray.')]),
    'fenna|sabine': dict(
        title='An invitation worth keeping', room='common-room', keepsake='Hand-lettered games-night board',
        invitation='Fenna wants a games-night notice people will actually read. Sabine offers to write it, provided Fenna is allowed to cross things out.',
        introduction=[('sabine', 'An evening of unparalleled diversion—'), ('fenna', 'Cards. Tea. You can leave whenever you like.'), ('sabine', 'You have removed every adjective.'), ('fenna', 'And kept every reason to come.')],
        completion=[('sabine', 'May I at least keep “excellent company”?'), ('fenna', 'Only if we leave room for somebody to object.'), ('narrator', 'They letter the notice on a small reusable board and leave a strip for guests to suggest games. Sabine adds a neat border; Fenna writes the first suggestion inside it.')],
        outing='Fenna and Sabine are ready to try the games-night format on their notice.',
        outingLines=[('fenna', 'One short round. That was the promise.'), ('sabine', 'Then I shall have to win with admirable efficiency.'), ('narrator', 'Fenna wins the round. Sabine writes “rematch requested” below the notice, and Fenna supplies a box marked “whenever you feel like it”.')],
        reflection=[('sabine', 'You have kept my border through every revision.'), ('fenna', 'You stopped restoring the speech above it.'), ('narrator', 'They wipe the game suggestions clean and keep the little rematch box. It has become part of how they invite each other.')]),
    'mira|nyssara': dict(
        title='A comparison page with room for doubt', room='library', keepsake='Paired observation folio',
        invitation='Nyssara and Mira have conflicting readings of a ward diagram. They propose a folio that keeps both observations beside the evidence.',
        introduction=[('nyssara', 'The line is broken. That does not prove it was meant to be broken.'), ('mira', 'The copyist has reproduced it three times.'), ('nyssara', 'Then we have three copies of the same uncertainty.'), ('mira', 'Two columns, then. Observation on the left. Our quarrel on the right.')],
        completion=[('mira', 'I have called the second column “interpretation”. You may consider that a concession.'), ('nyssara', 'I have left your explanation in it. You may do the same.'), ('narrator', 'They bind a small folio with separate columns for observed marks, proposed explanations and tests still needed. Both sign the first comparison.')],
        outing='Mira and Nyssara want to try their comparison folio on a second diagram.',
        outingLines=[('nyssara', 'This copy has a pinhole where the other one has a break.'), ('mira', 'A mark from mounting the original?'), ('narrator', 'They compare the edges and record mounting damage as a possibility. The folio keeps the observation separate from the explanation until another copy can settle it.')],
        reflection=[('mira', 'I no longer mistake your question mark for an insult.'), ('nyssara', 'I no longer assume your first explanation is your last.'), ('narrator', 'They turn to a clean comparison page. This time each asks the other which test would be worth making first.')]),
}

HABITS = {
    'reading': dict(label='Compare a passage from the household travel book', title='Two readings of the same journey',
        lines=[('{a}', 'The traveller calls the hill a gentle climb. The drawing has six switchbacks.'), ('{b}', 'Perhaps “gentle” describes the person who carried the bags.'), ('narrator', '{a_name} and {b_name} compare the drawing with the account, then mark a second passage to read together another day.')],
        keepsake='Shared reading folio', project='Make a folio for their shared reading', room='library',
        completion=[('narrator', '{a_name} folds the pages while {b_name} fits a loose cord through the cover. They copy the hill passage onto the first page and leave space for both sets of notes.')],
        outingLines=[('{a}', 'The next page gives the hill a different name.'), ('{b}', 'Keep both names in the folio. We may find out who uses which one.'), ('narrator', 'They add the two names beside their first sketch and leave the page open for a later comparison.')],
        reflection=[('{a}', 'We have filled the space beside that first passage.'), ('{b}', 'Turn the page. I have another one for us.'), ('narrator', 'They put a fresh sheet in their shared folio and settle beside the book. Both have brought a passage to compare.')]),
    'game': dict(label='Try a short game with an open score sheet', title='A game worth repeating',
        lines=[('{a}', 'Shall we leave the moves visible? I would like to understand where I went wrong.'), ('{b}', 'Only if we keep my mistakes on the same sheet.'), ('narrator', 'They play a short round, retrace the turning point and agree to swap starting positions next time.')],
        keepsake='Two-sided game board', project='Make a board for their rematch', room='common-room',
        completion=[('narrator', '{a_name} marks the squares while {b_name} sorts the counters. They put their names on opposite sides, ready to swap seats for the next round.')],
        outingLines=[('{a}', 'You have left the centre open again.'), ('{b}', 'Take it and see where my next counter goes.'), ('narrator', 'They finish the rematch, then replay the opening with the counters reversed. Their score sheet records the move both missed the first time.')],
        reflection=[('{a}', 'Shall we keep score today?'), ('{b}', 'Yes. I still intend to win.'), ('narrator', 'They turn the board and trade starting positions. The old score sheets stay underneath it, including the rounds neither had understood at the time.')]),
    'walk': dict(label='Take a short walk around the castle courtyard', title='A route with somewhere to sit',
        lines=[('{a}', 'There is a dry seat by the wall. Shall we stop there on the way back?'), ('{b}', 'Yes. Let us see which way catches the afternoon light first.'), ('narrator', 'They walk the courtyard in both directions and choose a sheltered place to sit. They agree to leave enough time to stop when they come this way again.')],
        keepsake='Courtyard sketch and seat marker', project='Mark their courtyard route', room='common-room',
        completion=[('narrator', '{a_name} sketches the courtyard path while {b_name} marks the sheltered seat. They mount the sketch beside a small wooden marker for the table they use when they return.')],
        outingLines=[('{a}', 'The longer path brings us back to the sheltered seat.'), ('{b}', 'Then we have time to take it today.'), ('narrator', 'They follow the longer courtyard route and stop beside the wall. On returning, they add the turning point to their sketch.')],
        reflection=[('{a}', 'The long way, or straight to our seat?'), ('{b}', 'The long way. I want to show you where the afternoon shadow ends.'), ('narrator', 'They follow the shaded side of the courtyard and compare it with the warm seat they chose together. Both stop there on the way back.')]),
}
