"""Rhess, the dragonkin watchkeeper: authored household and relationship content."""
def register(g):
 import local_encounters as local,living_stories as life,resident_specialties as rs,character_quest_content as quests,household_chapter_content as home,romance_content as romance,romance as love,companion_almanac_content as almanac,customization_content as custom,signature_equipment as sig,outfit_progression as outfits,art_catalogue,party_journey_content as journey,armoury,provisions
 local.PEOPLE['rhess']={'name':'Rhess','age':24,'ancestry':'Dragonkin','background':'lampwright','temperament':'poised','story':'repair-method','occupation':'watchtower keeper','place':'The old watchtower','lead':'An unanswered signal points towards a keeper guarding the broken boundary alone.','unlock':'Return from the Chapter 7 watchtower trail.','greeting':'“Rhess. Keeper of this tower.” Her tail shifts behind her. “There are two cups. That is not a formal invitation. Unless you would like it to be.”','appearance':'Youthful clearly adult dragonkin woman, copper skin, bronze scales on cheeks shoulders arms and hips, swept horns, substantial scaled tail, chestnut waves, amber eyes with vertical reptilian slit pupils. Cropped leather vest and separate moss trousers, exposed navel, flat boots. All three outfits are two-piece with exposed midriff and navel.','origin':'A dragonkin lampwright who stayed at an abandoned watchtower to protect travellers from a damaged stone guardian.','ambition':'Build a watch that can keep people safe even when its keeper takes a night off.'}
 life.ROUTINES['rhess']={'morning':['watchtower','guard-barracks'],'afternoon':['training-yard','watchtower'],'evening':['common-room','watchtower','bedroom']}
 life.GREETINGS['rhess']='“The next watch is covered. I checked once. Perhaps twice. Sit with me?”'
 life.CHAINS['rhess']=life.chain('watchtower','The second cup','Rhess has polished two cups and placed them precisely opposite each other. “The symmetry is incidental.”',{'sit':('Sit opposite her','She pours before you finish pulling out the chair.'),'view':('Ask her to show you the road','“From here you can see people arrive long before they know they are expected.”')},'The second cup stays beside the first. A chair has moved closer to the window.',{'sit':'“You may come without sending a signal first.”','view':'“I have started looking for familiar steps.”'},'“When someone else takes the watch, I find I do not know what to do with my hands.”',{'rest':('Offer your hand','She takes it, then stops watching the door.'),'listen':('Ask what she would like to do','“Stay here a little. With you. Without it being a duty.”')})
 rs.NAMES['rhess']='Rhess';rs.SPECIALTIES['rhess']=rs.specialty('rhess','watchtower','Rhess’s Keeper’s Vigil',28,'When Rhess is assigned to road patrol at home, each completed two-phase patrol returns 6 provisions and 3 crowns instead of 4 and 2. Shares the castle pantry.');rs.register()
 quests.PERSONAL['rhess']=('What the tower keeps','recover a keeper’s box and decide which promises still belong to her','cipher','repair','Rhess asks you to help open a weathered keeper’s box. “It was here before me. I have been treating its instructions as though they were addressed to me.”','The papers name a watch that once had six people. “I thought leaving would mean abandoning them. Most of them left years before I arrived.”','She copies the names into a new roster with room for relief. The old orders go into the archive, no longer on her bedside table.','“Will you stay? I am asking because I want you here. I am learning the difference.”')
 b=home.beat
 home.PROFILES['rhess']={'room':'watchtower','activity':'maps','relaxed':'“The upper room is warm. I can set the travelling layers aside.”','daring':'“I chose this for your visit. You may stop pretending you are studying the map.”','thanks':'“Good. I had hoped you would notice.”','tease':'“Your powers of observation remain impressive.”','beats':[
 b('The little keepsake hoard', 'Rhess opens a box containing a carved bird, a smooth button and a bent brass pin. “People expect coins. Coins rarely remind me of anyone in particular.”', '“A watchkeeper who could carve during any argument. He gave it to me after I finally learned when to stop talking.”', '“Laugh if you like. I know exactly which piece I would rescue first.” She protects the bird with one finger.', 'Ask who made the bird', 'Call it an impressively affordable hoard'),
 b('Tea at different temperatures', 'Rhess lets you test her tea before drinking it. “Too hot for you? I keep forgetting that a comfortable cup means different things to different people.”', 'She adds a little cool water to yours and leaves hers alone. “Easy enough. I should have asked sooner.”', '“A small forge.” She smiles into the steam. “I am exercising restraint.”', 'Explain how you prefer it', 'Accuse her of brewing tea for a forge'),
 b('The watch that never ended', '“I stayed at the old boundary because travellers still needed warning,” Rhess says. “The old roster named six people. I began treating all six places as my responsibility, though most had left before I arrived.”', '“When I could not remember whom I expected to relieve me. That was an unpleasantly clear morning.”', 'She looks at you. “You appear to have appointed yourself. I have decided not to object.”', 'Ask when she realised the difference', 'Ask who checks on the watcher now'),
 b('A shelf for the carved bird', 'Rhess puts the carved bird on a shelf instead of back in her bag. “There. Now I have to remember where I put it, like everyone else in this house.”', '“I can see it when I come in. I wanted something here that was mine before the next watch began.”', '“A serious responsibility.” She steps closer. “Payment is tea and exceptionally good company.”', 'Ask what made her choose that shelf', 'Say you will guard the hoard during her next patrol')]}
 home.PERSPECTIVES['rhess']='“A promise should have room for relief.”'
 home.ACTIVITIES['watchtower']={'title':'Share the quiet watch','opening':'Rhess sets a second cup beside the shuttered lamp. The road is quiet, and someone else has the next shift.','view':'firstPatrol','use':'Review the patrol notebook or remain for company.'}
 home.SPECIALIST_VOICES['rhess']=('“A watch needs people who can leave it in safe hands.”','“The route is checked. The supplies are in the shared pantry.”','“I did take my relief. You need not look so pleased.”')
 home.PAIRS.append(('rhess','aurelia','guard-barracks','The name beside yours','Aurelia points to the second name on the roster. Rhess has written her own in both spaces.','Discuss a fair rotation','Rhess erases the second entry and asks who would like that watch.','Ask about the empty chairs','Aurelia says a working roster includes people who are resting.','The relief arrives','Rhess hands over the lamp without adding another inspection. Aurelia makes room for her at the table.'))
 almanac.PAIRS.append(('rhess','velis','Things that cannot be priced',[
 ('The chipped bird','Velis notices the wooden bird in Rhess’s box.','Rhess explains who carved it; Velis asks for the story instead of its value.'),
 ('A dependable arrival','Rhess waits at the gate for a late porter.','Velis brings tea and a message: delayed, safe, expected tomorrow.'),
 ('A place on the shelf','Velis brings a small shelf with no receipt attached.','Rhess places the bird on it and invites her to stay for supper.')]))
 romance.SCENES['rhess']=[
 ('An invitation without a signal','“I keep finding reasons for you to visit. Would you prefer an honest one? I like you.”','You return her interest. Her smile is suddenly less guarded. “Then stay for the next cup.”'),
 ('Within reach','Rhess leaves a small space between you on the window seat. “May I close that?”','You agree. She leans close and kisses you, warm and careful, her hand finding yours.'),
 ('A promise with room in it','“I would like to be your partner. Not your guard. Though I reserve the right to worry occasionally.”','You agree, and Rhess takes your hand. “Time together that is not borrowed from a watch. And if one of us needs help, I want us to ask instead of silently taking over.” She laughs against your shoulder. “You may remind me that I proposed that second part.”'),
 ('The lamp is covered','“The relief is here. Would you like to stay with me tonight?”','You agree and share a lingering kiss. She shutters the lamp; the private evening unfolds behind a closed door.')]
 love.GREETINGS['rhess']='“There you are. Come within reach.”'
 custom.PROFILES['rhess']=('bronze','stargazing','smoky plum tea','watchtower','a tiny carved bird','“I remember who made it. That is what makes it mine.”','“I would like your company. No inspection required.”')
 almanac.PHYSICAL['rhess']=(174,69,(98,70,101),'Athletic and softly curved, with copper skin, bronze scales, horns and a substantial tail.','Her amber eyes have vertical slit pupils; her youthful face and proportions are clearly adult.')
 almanac.PERSONAL['rhess']=dict(hand='Right',habit='Checks the lamp shutters before sitting down.',history='Stayed to guard a damaged boundary long after its original watch dispersed.',comfort='Warm stone, shared tea and an answered relief signal.',worry='That resting will allow someone else to be hurt.',attraction='Dependability, gentle humour and people who remember small gifts.',turnoff='Treating her loyalty as an unlimited resource.',affection='Making a place beside her and trusting someone with her cherished keepsakes.',private='She likes being invited to put duty aside and welcomes attentive compliments.',initiative=('The watch is covered','Rhess brings two cups. “I checked. We have time.”','watchtower'),idle=('Turning a tiny wooden bird in her fingers.','Closing the watch book with deliberate care.','Tilting her horns clear of a low beam.'))
 sig.ROOMS['rhess']='watchtower';sig.CONTENT['rhess']=('The returning point','Mark the grip where I can hand it to someone else. A familiar weapon should know when its work is done.','The balance comes back to my hand. And now I can let it go.','relief');armoury.STARTERS['rhess']='steel-spear';provisions.PREFERENCES['rhess']='hunt'
 journey.CAST.append('rhess');journey.CAMPS['rhess']=('Someone else takes first watch','Rhess starts to volunteer, then catches herself. “Would you take the first watch? I would like to hear the fire for a while.”','You agree the rotation. She settles beside the fire and takes the cup offered to her.');journey.VOICES['rhess']=('Mark the way back before choosing the way forward.','I can hold this ground. Tell me when you are ready to take over.','We all came home. That is the line I wanted to write.')
 outfits.CATALOGUE['rhess']={'2':{'id':'rhess-outfit-2','name':'The relief has arrived','description':'Opaque moss cropped wrap top, separate charcoal shorts, exposed navel and flat calf boots.'},'3':{'id':'rhess-outfit-3','name':'The lamp is shuttered','description':'Opaque wine halter crop top, separate short bronze wrap skirt, exposed navel and flat sandals.'}}
 for suffix in ('','-outfit-2','-outfit-3'):
  key='rhess'+suffix
  for asset,path in [(key,'/assets/portraits/'+key+'.webp'),('overview-'+key,'/assets/portraits/overview/'+key+'.webp')]:g['ORIGINAL_ASSETS'][asset]=path;art_catalogue.ART_ASSETS[asset]=path
 g['ORIGINAL_ASSETS']['signature-rhess']='/assets/equipment/signature-rhess.webp'
