"""Four authored, non-explicit romantic milestones per established adult companion."""
# Four (title, invitation, accepted response) records per person.
SCENES = {
'mira':[
('A remarkably personal footnote','Mira has marked a passage about two scholars who invent excuses to keep reading together. “I believe the author has discovered our method. Would you like to stop pretending it is entirely academic?”','You tell her the attraction is mutual. Mira closes the book on a finger to keep her place. “Good. I had another three excellent excuses prepared, but this seems more efficient.”'),
('The line she leaves blank','Mira invites you to a reading with no work afterward. At the end she puts the book down. “I know how the scene finishes on the page. May we choose our own ending?”','You ask to kiss her. She says yes, and the kiss is brief enough to leave both of you smiling. “A promising first draft,” she says. This time neither of you reaches for the book.'),
('A place in the next chapter','Mira has begun leaving a second cup beside her evening book. “I like that this is becoming familiar. I would like to call us partners, if that describes what you want too.”','You agree. Mira takes your hand over the closed book. “Then we should keep making room for questions. Even the inconvenient ones.” Her next smile is much less scholarly.'),
('Midnight, without an excuse','Mira has left tonight’s reading unfinished on purpose. “Stay a little longer? We could be very poor scholars and excellent company.”','You settle beside her and she leans into you. A kiss interrupts an increasingly unconvincing discussion of literature. Later, with the book forgotten, the evening belongs quietly to the two of you.')],
 'tamsin':[
('A seat kept for you','Tamsin has kept a seat beside her without setting a place for anyone else. “I want your company because I like you. Would you rather I said it that plainly?”','You tell her you like her that way too. Her shoulders relax. “Excellent. Then I can stop offering you unnecessary cups of tea to keep you here.”'),
('The guest of honour','Tamsin asks you to meet her for an evening where neither of you hosts anyone. “You may fuss over me a little. I have decided I might enjoy it.”','You ask if she would like a kiss before you sit down. She smiles and says yes. “That is a very good beginning. Do not spoil it by asking what needs washing.”'),
('Something she wants','“I am usually very good at saying what would help,” Tamsin says. “I am practising saying what I want. I want to be your partner. What do you want?”','You give her a clear answer and take her offered hand. “Then we should both get to ask for things,” she says. “Including an evening of doing absolutely nothing useful.”'),
('Nothing left to organise','Tamsin closes the household notebook before you arrive. “Everything can wait. I have decided to be rather selfish about your company tonight.”','You join her on the cushions. She draws close for a kiss, then settles happily against you. Nobody is hosting, serving or keeping watch over the other person’s enjoyment. The private evening unfolds at your shared pace.')],
 'iona':[
('A less accidental meeting','Iona admits that your recent meetings have been rather carefully arranged. “It would save me a great deal of choreography if I could simply say I fancy you.”','You return the feeling. She laughs with delighted relief. “Wonderful. I can keep the choreography for an actual dance.”'),
('The last measure','Iona offers her hand for a slow dance. “We can stop when the music does. Or I could ask for a very small encore.”','When the final measure ends, she asks to kiss you. You agree. The kiss leaves the two of you standing a little closer, with the next dance entirely optional.'),
('No audience required','“I can make an entrance,” Iona says. “But I would like the ordinary mornings with you too. Would you like to make this a partnership?”','You agree, and she kisses your hand with extravagant ceremony before laughing at herself. “There. The last performance for at least five minutes. Now tell me about your day.”'),
('The dance after the music','Iona has put the music away but holds out her hand again. “I thought we might manage without counting tonight.”','You sway together in the quiet. She kisses you, smiles against your cheek, and lets the dance turn into an unhurried embrace. There is no audience and no need for a grand ending.')],
 'aurelia':[
('A direct question','Aurelia waits until her duties are finished. “I would like to spend time with you as more than a friend. I can be direct about that if you can.”','You tell her the interest is mutual. She smiles openly. “Good. I did not want a tactical analysis. I wanted to ask you out.”'),
('Beyond the last watch','Aurelia meets you without her watch coat. “I have no report, no warning and no request for assistance. Is this a good time for a date?”','The evening ends with you asking to kiss her. “Yes,” she says, with the same calm certainty she brings to important decisions. Afterward she keeps your hand in hers.'),
('A chosen place beside you','“I want a place beside you that is chosen, not assigned,” Aurelia says. “Would you call this a partnership?”','You agree. She rests her forehead briefly against yours. “Then we should make time for it. Not just whatever is left after every duty is finished.”'),
('Off duty, completely','Aurelia leaves her gloves outside the sitting area. “I have arranged the evening. Nobody needs me to be on watch. May I stay with you?”','You welcome her close. She kisses you without hurrying and lets herself relax in your arms. The doors are secure, the duties are elsewhere, and the rest of the evening remains yours.')],
 'neris':[
('An unusually clear signal','Neris turns a glass cup until its blue edge catches the light, then looks at you. “I keep finding things I want to show you. Some of them are even interesting. Would you like to see me when I have no demonstration prepared?”','You tell her the attraction is mutual. Neris smiles. “Good. I was beginning to suspect you had developed an unlikely passion for cup handles. Shall we plan an evening together?”'),
('Without a measurement','Neris invites you to watch the evening light through a piece of blue glass. “I like this colour against your hand. Would you sit beside me? The glass is only part of the invitation.”','You ask to kiss her, and she agrees. Afterwards she turns the glass towards the window again. “I still want you to see this edge. You have become wonderfully distracting.” She keeps hold of your hand.'),
('A useful name for it','“I want more evenings with you, including the ones when I have broken something and am not charming about it,” Neris says. “Would you like to be partners?”','You agree. Neris takes your hand. “Then tell me when you want company. I can become absorbed in a design and miss a hint. I would rather miss a little work than miss your invitation.”'),
('The unrecorded evening','Neris puts two cups beside the cushions and offers you her hand. “I would like a private evening with you. Tea first, unless you have a more appealing suggestion?”','You ask for a kiss. Neris draws close and gives you a smiling yes. Afterwards she reaches for the blanket and asks you to stay beside her. The conversation softens as the scene fades to your private evening.')],
 
 'sabine':[
('The compliment underneath','Sabine lets a polished joke fall away. “I enjoy flirting with you. I would like to know whether you enjoy it for the same reason.”','You tell her your attraction is real. Her smile changes, becoming less practised. “Lovely. I was beginning to feel rather over-rehearsed.”'),
('An entrance for one','Sabine has dressed for your evening together, but her invitation is simple. “May I be a little nervous without ruining the effect?”','You tell her she can, and later ask to kiss her. She agrees. For a moment she has no ready line afterward. Then she laughs. “You must promise not to mistake that for a complaint.”'),
('Beyond the curtain call','“You have seen the performance,” Sabine says. “I would like you to know the person who has to find her shoes afterward. Shall we call ourselves partners?”','You agree, and she kisses your cheek. “Good. I shall still make entrances. But you may know when I am tired of being impressive.”'),
('No performance tonight','Sabine welcomes you with her hair loosely pinned and no prepared speech. “I thought we could have an evening nobody needs to applaud.”','You draw her close and share a kiss. She rests against you without trying to turn the moment into a beautiful line. The remaining hours are private, warm and free of an audience.')],
 'koharu':[
('A reason beyond the repairs','Koharu turns a sound little clasp over in her hand. “I have run out of things that need your opinion. Would you like to keep visiting anyway? Personally, I mean.”','You tell her you would. She grins. “Good. I was about to break something perfectly respectable just to prolong the conversation.”'),
('Tools put away','Koharu has cleaned the workbench and left it behind. “I am taking you somewhere with no unfinished joints to distract me. You may be distracting enough.”','At the end of the evening you ask to kiss her. She says yes, then laughs at the care with which you both close the distance. “A good fit. No adjustment required.”'),
('Something worth maintaining','“I like making things that last,” Koharu says. “I know people are not projects. But I would like to make the time and care for a partnership with you.”','You agree. She takes your hand and smiles. “And if something troubles us, we say so before it becomes a repair job. I have learnt that much.”'),
('An intentionally unfinished project','Koharu covers the work on her bench. “Tomorrow. I have plans to spend this evening being very pleasantly unproductive with you.”','You settle together and she leans in for a kiss. The workshop plans stay untouched while the two of you enjoy the kind of closeness that needs no useful result.')],
 'zahra':[
('The careful question','Zahra chooses her words with unusual care. “I like your company. I have begun hoping that you might want the sort that involves holding hands.”','You tell her you do and offer yours. Her smile is slow and warm. “Then I am glad I asked instead of trying to look less obvious.”'),
('A gentle beginning','Zahra has saved a quiet place beside the music box. “I thought this might make a good first date. Small enough that neither of us has to perform.”','When you ask to kiss her, she says yes and leans close. The music continues while you share a gentle kiss. “Small things,” she says, “can matter a great deal.”'),
('More than being needed','“It is good to be useful,” Zahra says. “But I would like to be your partner because we want each other here. Is that what you want too?”','You agree and take her hand. “Good,” Zahra says. “I want the evenings when we have nothing impressive to report too.”'),
('Room to rest together','Zahra has put the careful little tasks away. “Come and sit with me? I would like an evening when being close is the whole plan.”','You join her, and a kiss becomes a quiet embrace. She rests comfortably beside you. Nothing needs moving, mending or proving; the evening is simply shared.')],
 'fenna':[
('The joke with an honest ending','Fenna begins another outrageous compliment, then stops. “Actually, let me ask properly. Would you like me to be flirting because I fancy you?”','You say yes, because you fancy her too. “Splendid,” she says. “I was very close to making a sincere declaration. Think of the damage to my reputation.”'),
('A wager already won','Fenna invites you on a date with no competition attached. “I have discovered that wanting your company is sufficient grounds. Quite a loophole.”','At the end she asks whether she may kiss you. You agree. Her grin afterward is delighted rather than triumphant. “I like this much better when nobody has to lose.”'),
('No clever escape clause','“I have something to say without a joke after it,” Fenna warns. “I would like us to be partners. Really.”','You agree, and she holds your hand for a moment before smiling. “Good. I shall keep the jokes, but I will try not to hide every important thing inside one.”'),
('The game put aside','Fenna abandons a half-invented wager. “No. Tonight I would simply like to be close to you. Astonishingly honest of me.”','You welcome her into your arms. She kisses you, then settles beside you with a contented sigh. The evening stays playful, but neither of you needs a game to explain why you are there.')],
 'kaede':[
('A deliberate risk','Kaede looks directly at you. “I am comfortable practising difficult things. Asking whether you share my interest has proved less comfortable. I would like to ask anyway.”','You tell her the feeling is mutual. She exhales, then smiles. “Good. I should remember that not every uncertainty needs another week of preparation.”'),
('No perfect approach','Kaede invites you to a quiet evening without rehearsal. “If I am awkward, you may be kind enough to remain interested.”','You ask to kiss her, and she agrees. The first kiss is a little tentative and entirely welcome. “That,” she says, smiling, “does not need correcting.”'),
('A steady choice','“I want the ordinary days as well as the occasions,” Kaede says. “Would you like to make this a partnership?”','You agree. She reaches for your hand with more confidence than before. “Then we need not be impressive every time we see each other. I suspect that will take practice too.”'),
('No need to hold the pose','Kaede welcomes you into a quiet evening. “I have no intention of keeping my composure merely to prove I can. Will you stay?”','You stay, and she draws close for a kiss. The careful poise softens into an easy embrace. She can rest beside you without feeling that the moment is an assessment.')],
 'elowen':[
('A want of her own','Elowen hesitates, then smiles. “I would like to ask for your company because I am attracted to you. Not because I need help with anything.”','You tell her the attraction is mutual. “I am glad,” she says. “I kept thinking I should invent a more useful reason. This one feels rather lovely by itself.”'),
('The place beside her','Elowen invites you to a little evening walk. “I have left everything else until tomorrow. I want to pay attention to this.”','At the end you ask to kiss her. She says yes and takes your hand afterward. “I like being asked,” she says. “And I like having something I very much want to say yes to.”'),
('Care in both directions','“I would like us to be partners,” Elowen says. “And I would like to get better at letting you care for me too.”','You agree, promising to ask rather than guess. She leans against your shoulder. “Then perhaps neither of us needs to be the endlessly capable one.”'),
('The evening she kept','Elowen has protected a quiet stretch of evening from all the things she might have offered to do. “This time is for us, if you would like it.”','You accept and draw close. She kisses you, then settles into your embrace. It is a private, unhurried evening in which she is allowed to want comfort as well as give it.')],
 'nyssara':[
('One mystery answered','Nyssara sets aside a carefully indirect remark. “I would rather you knew this part plainly. I am interested in you. Would you like that interest to be romantic?”','You tell her you would. She smiles. “Good. There are plenty of things we can discover slowly. We need not make uncertainty about this one a permanent occupation.”'),
('The invitation she names','Nyssara offers you a place beside her for the evening. “A date,” she says before you can ask. “I thought I would spare us an elaborate interpretation.”','Later, you ask whether she would welcome a kiss. She says yes. Afterward she keeps your hand in hers. “Some answers are better when they are unmistakable.”'),
('A chosen confidence','“I do not promise to become a person without private thoughts,” Nyssara says. “I would like to become your partner. Those are different things. Would you like that too?”','You agree. She touches your hand, visibly at ease. “Then there can be closeness without either of us becoming a locked room the other must conquer.”'),
('No mask between you','Nyssara puts her mask aside before inviting you to stay. “I have nothing to perform tonight. I would like your company exactly as we are.”','You settle close and share a lingering kiss. The conversation grows quiet without becoming guarded. What follows belongs to a private evening neither of you needs to explain to anyone else.')],
 'sylva':[
('Something allowed to grow','Sylva looks up from the small new leaves. “I have been enjoying the way we seek each other out. Would you like to let that become something romantic?”','You tell her you would. She takes your offered hand. “Then we can pay attention without hurrying it into a shape neither of us chose.”'),
('An evening without a task','Sylva invites you to watch the light change. “The plants do not need us this evening. I thought we could be here for ourselves.”','You ask to kiss her, and she agrees. Afterward she smiles and stays close. “There. A good evening need not leave an impressive list of accomplishments.”'),
('Making room for each other','“I would like us to be partners,” Sylva says. “I want to spend more of my days with you. Is that what you want too?”','You agree. She rests her hand in yours. “Then we should keep asking what helps us flourish, rather than assuming it will always be the same thing.”'),
('A quiet place to return to','Sylva has left the tools where tomorrow can find them. “Stay with me a while? I would like a little closeness without making an occasion of it.”','You stay, sharing a kiss before settling together. The quiet feels welcoming rather than empty. There is room for affection, conversation and a private evening that asks nothing more of you.')]
}
STAGES=['Not romantically involved','Mutual attraction','Dating','Partners','Partners · private evening shared']
# History and three independent bond dimensions, in stage order.
REQUIREMENTS=[(2,1,1,0),(4,2,2,1),(6,3,3,1),(8,4,4,2)]
DATES={
 'pool':('An afternoon by the pool','You agree to spend some time swimming, then rest beside the water. There is room for playful conversation without turning the afternoon into a lesson.','You share a light kiss before returning to the conversation. The invitation was to enjoy each other’s company, and neither of you feels a need to make it more complicated.'),
 'sauna':('The quiet after the heat','You meet in the sauna’s cooling vestibule, comfortably wrapped for a quiet rest. The warmth has made an unhurried conversation particularly welcome.','You sit a little closer, exchanging affectionate teasing and a brief kiss. The rest of the break is comfortable companionship.'),
 'hot-spring':('Lanterns by the spring','You meet on the resting ledge beside the spring after changing privately. The water and low lamplight make a peaceful setting for an evening together.','You ask to hold their hand and are welcomed close. A kiss and a quiet conversation make the evening memorable without either of you having to perform.')}
