"""Authored conversations. No generated dialogue or inferred relationship scores."""
def scene(title, opening, *choices):
    return {'title': title, 'opening': opening, 'choices': {k:{'label':label,'response':reply} for k,(label,reply) in zip(('curious','warm','candid'),choices)}}

PERSONAL = {
'mira':[
 scene('The correction in red', 'Mira has crossed out a note you left in a shared book. “I corrected the date. Then I realised I had corrected your description of the place as well.” She turns the page towards you. “That part was not an error.”',
 ('Ask what bothered her about the description','“You called it lonely. My notes called it disused.” Mira studies the two words. “I was pretending mine contained less of me. It did not.”'),
 ('Tell her you want both accounts on the page','“Side by side?” She fetches a fresh sheet instead of scraping yours clean. “That will make the catalogue untidy. I find I can survive it.”'),
 ('Say you want her to ask before changing your words','Her first reply comes quickly, then stops. “Yes. Accuracy did not give me ownership of the whole page.” She returns your pencil. “I will ask.”')),
 scene('An argument worth keeping','“I brought two copies,” Mira says. “One for each of us to disagree with.” The passage concerns whether a house remembers its inhabitants. She has already written a very firm no, then underlined a sentence that suggests otherwise.',
 ('Ask why that sentence survived her objections','“Because I recognised something in it.” She taps the margin. “Annoying evidence. My favourite kind, when it happens to someone else.”'),
 ('Offer to read the opposing part aloud','You take turns defending positions neither of you quite believes. Mira loses her place laughing. “An excellent adversary. Dreadful reading discipline.”'),
 ('Tell her an argument need not end in agreement','“Then let us stop before I turn liking you into a requirement to persuade you.” She puts a bookmark between the two accounts. “Both remain.”')),
 scene('Two hands in the catalogue','Mira brings a small index headed with both your names. “I have left the descriptions unsigned in the main catalogue. But here, I want to remember who saw what.” She waits before putting your name beside an entry.',
 ('Ask her to keep track of how your views change','“A history of revisions, including mine.” She leaves room beneath the first entry. “I should like to find us less certain and better informed.”'),
 ('Write a private note of appreciation beside hers','Mira reads it twice. “This is not a bibliographic category.” She folds the index carefully. “I will have to invent one.”'),
 ('Keep separate opinions, but share the collection','“Shared shelves, individual margins.” Mira nods. “We have finally designed a system capable of accommodating two people.”'))],
'tamsin':[
 scene('Who gets the last helping','Tamsin has saved a portion for someone who missed supper, then found three more empty chairs. “I keep saying there is enough. Sometimes I mean that I will have less.” She pushes her own plate back towards the table.',
 ('Ask when hospitality began to feel compulsory','“When people started thanking me for never needing to be asked.” Her ears lower. “It sounds lovely until you try to be unavailable.”'),
 ('Offer to sit and eat with her before sorting anything else','“While it is still warm?” She takes up her spoon. “That would be a surprisingly radical arrangement.” You let the empty chairs wait.'),
 ('Say she needs to tell you when there is not enough','“I can do that. But you must let an honest no remain a no, without making me present a defence.” She moves the serving dish within her own reach.')),
 scene('A place she did not set','Tamsin arrives carrying no tray. “I told the others I was coming to talk. Then I nearly brought something so it would count as a reason.” She looks at the seat beside you. “May this be the reason?”',
 ('Ask what she would choose for an evening of her own','“A terrible guessing game. One with ridiculous rules.” She is immediately full of opinions about which rules would be most ridiculous.'),
 ('Make room and let her choose the conversation','She tells you about a market singer who could never remember the last verse. By the third attempted ending, neither of you can finish a sentence without laughing.'),
 ('Admit you sometimes mistake helpfulness for happiness','“Thank you for saying that.” Her tail stills. “I do enjoy looking after people. I want there to be room for the days when I do not.”')),
 scene('Her name on the invitation','A note from Tamsin invites you to a small evening at the table. Beneath the time she has written: I am a guest too. “It looked impertinent the first time,” she says. “Now I rather like it.”',
 ('Ask what she wants the evening to become','“Something we can remember without listing what I served.” She adds a place for a game and leaves the menu blank.'),
 ('Accept, and promise her your company','“Good. That is what I meant to ask for.” She folds the note into your hand instead of returning to the kitchen.'),
 ('Suggest that both of you take turns asking for care','“Including the ungraceful requests?” She considers it. “Especially those, perhaps. We should not have to become charming before we can be tired.”'))],
'iona':[
 scene('The route she left off','Iona shows you a map with one road deliberately omitted. “It leads to somewhere I used to stay. Leaving it out was easier than explaining why I did not want to visit.” She has not brought a travelling case.',
 ('Ask whether she wants to tell you about the place','“Not the whole story.” She describes a window, a noisy stair and someone who always expected her to leave. “That is enough for today.”'),
 ('Tell her a map need not be an invitation to return','“I was hoping you would understand the distinction.” She draws the road lightly, without an arrow at its end.'),
 ('Say you would rather hear a boundary than follow a misleading map','“Fair.” Iona writes private beside the road. “There. A truthful map, and a destination I am not offering.”')),
 scene('A letter without a departure','“I sent a letter,” Iona says. “I did not promise to come.” She seems pleased and uneasy in equal measure. “It is remarkable how often I used travel to avoid answering a question.”',
 ('Ask what she managed to say this time','“That I am well. That I stayed somewhere because I wished to. I did not turn either sentence into an itinerary.”'),
 ('Celebrate the small decision with her','“No grand announcement?” She smiles. “A cup raised to not packing. An occasion severely neglected by the poets.”'),
 ('Ask whether staying can become another way of avoiding things','“Of course.” She sits with the question instead of reaching for a map. “If you notice me doing that, ask. Do not decide for me.”')),
 scene('Somewhere she can be found','Iona places a forwarding address in her correspondence book: the castle. “Not forever by decree,” she says. “Just where I want a letter to find me now.”',
 ('Ask what makes an address feel like hers','“Someone can knock without assuming I am already halfway away.” She pauses. “And I can still choose to go out.”'),
 ('Tell her you are glad she can be found here','She closes the book. “That is a much better welcome than asking how long I mean to stay.”'),
 ('Say belonging should leave the door open','“Then we agree on the architecture.” Iona offers you the pen. “An address, not a tether.”'))],
'aurelia':[
 scene('The alarm that was only wind','Aurelia admits she interrupted a conversation to check a noise that proved to be a loose shutter. “Nobody complained. That made it harder to come back and say I had been frightened.”',
 ('Ask what she thought she heard','“Three hard knocks, then a scrape,” Aurelia says. “I thought someone was forcing the door. The wind was lifting the shutter against its catch. I knew that when I saw it; my hands took longer to believe me.”'),
 ('Tell her she can return without an explanation','“Even if I have broken the mood?” She sits again. “I am used to thinking a room must be put right before I can enter it.”'),
 ('Say constant vigilance can interrupt other people as well','Her wings draw close. “Yes. I want to protect the evening, and sometimes I am the one preventing it.” She asks to try again.')),
 scene('Who watches the watcher','“Would you tell me if I were doing too much?” Aurelia asks. “Not order me to rest. Tell me what you see.” She has chosen a chair facing the room instead of the entrance.',
 ('Ask what kind of reminder she could hear','“My name first. A question, not an accusation.” She tries the words herself: “Aurelia, are you still with us?”'),
 ('Offer the reminder quietly, between the two of you','“Quietly would help.” Her shoulders settle. “I would rather not become a household lesson in accepting help.”'),
 ('Admit you cannot always know when she needs it','“Then I must learn to say so.” She considers this with unusual seriousness. “I had hoped you might be able to guess. That was unfair.”')),
 scene('The shutter can wait','A shutter taps while you and Aurelia are talking. She notices it, pauses and asks you to finish your sentence. Afterwards she says, “I heard both things this time.”',
 ('Ask which part felt different','“I did not have to prove I had noticed first.” She smiles faintly. “The wind was permitted to exist without receiving my immediate attention.”'),
 ('Keep talking without making her into an achievement','You return to the story. Aurelia contributes a dry observation you would have missed if the evening had become an inspection of her progress.'),
 ('Say you will still speak up when something really needs attention','“Good. Rest should not depend on pretending nothing can happen.” She leaves the chair where it is.'))],
'neris':[
 scene('The cup that leaked','Neris presents a beautiful cup with a tiny crack. “I made it look finished before I admitted it was not.” She catches your glance at the cloth beneath it. “Yes. That is part of the presentation now.”',
 ('Ask why admitting the flaw mattered so much','“People call me graceful when they mean effortless. I begin to feel I ought to keep the work out of sight.”'),
 ('Admire the work while making room for the mistake','“You can like it and still notice the puddle.” She laughs, relieved. “A very useful combination.”'),
 ('Tell her you want honest warnings more than polished appearances','“Then: do not put anything precious in this cup.” She sets it between you. “There. We may now enjoy it honestly.”')),
 scene('A lesson neither of you prepared','Neris suggests teaching you the rhythm of a water song, then forgets the middle. “I should have practised.” She starts again and loses it in exactly the same place.',
 ('Ask her to explain the rhythm rather than perform it','She taps it on the table; you supply a decidedly uneven answer. “There it is. Much less impressive. Much more useful.”'),
 ('Invent a new middle together','Your version involves a duck with extravagant opinions. Neris objects to the metre and immediately proposes a worse rhyme.'),
 ('Ask whether this needs to be a lesson at all','“Perhaps I wanted an excuse to sing with you.” She puts the imaginary lesson plan aside. “Would that have been enough to ask?”')),
 scene('The repaired seam','The cup has returned, repaired with a visible seam. “I could have hidden it under another glaze,” Neris says. “But then we would lose the duck story.”',
 ('Ask what she wants to make next','“Something I can show you halfway through.” She turns the cup. “You may be subjected to several very ugly first attempts.”'),
 ('Choose the repaired cup for your next shared drink','“Careful. That is how objects become impossible to throw away.” She looks pleased by the possibility.'),
 ('Say the seam does not need to become a moral','“Agreed. It is also simply a cup that leaked.” She fills it, checks the table, and lets that be enough.'))],

'sabine':[
 scene('A compliment too carefully made','Sabine offers an elegant compliment, then winces. “That sounded as though I wanted something. I do not. I merely liked what you said.” She looks annoyed with her own fluency.',
 ('Ask what made the simpler version difficult','“It gives the listener more power. They can receive it badly, and I have no ornament behind which to retreat.”'),
 ('Accept the compliment without making her repeat it','“How mercifully undramatic.” She smiles. “I shall resist the urge to improve the sentence now that it has survived.”'),
 ('Say you sometimes cannot tell when she is being sincere','“That is useful to hear, if not flattering.” Sabine sets down her cup. “You may ask. I will try not to answer with another performance.”')),
 scene('The joke that missed','Sabine mentions a joke she made at supper that landed badly. “I intended to puncture pomposity. I suspect I punctured someone who was trying very hard to belong.”',
 ('Ask whether she has spoken to the person privately','“Not yet. I was composing an apology so faultless it could not be refused.” She catches herself. “There is the problem.”'),
 ('Tell her a plain apology can be enough to offer','“Offer. Not secure acceptance.” She repeats the distinction. “You have spared me an exceedingly polished mistake.”'),
 ('Ask her to leave room for the other person to remain annoyed','“An unpleasant but entirely reasonable privilege.” She nods. “I will not try to charm it out of them.”')),
 scene('No audience required','“I apologised,” Sabine says. “They were still annoyed. We nevertheless managed to discuss the weather.” She seems almost proud of the anticlimax.',
 ('Ask what she learned from the exchange','“That repair need not arrive as a verdict. Sometimes it is permission for the next ordinary conversation.”'),
 ('Enjoy her company without asking for a polished conclusion','She tells you something small and unedited about her day. Halfway through, she stops checking whether the story is entertaining enough.'),
 ('Ask her to use that same plainness with you','“Very well. I enjoy your company. I occasionally find you exasperating. I would like both facts to be permitted.”'))],
'maren':[
 scene('The repair nobody requested','Maren has improved a chair someone liked as it was. “The joint was loose,” she says, then adds, “The cushion was not. I changed that because I thought mine was better.”',
 ('Ask what she noticed when they saw it','“They thanked me with the wrong face.” She turns a scrap of fabric between her fingers. “I had solved a problem they did not give me.”'),
 ('Offer to help her ask what they want restored','“I should do the asking.” She looks up. “But I would appreciate company afterwards, whatever the answer.”'),
 ('Tell her a gift can still take something away','Maren is quiet. “Their right to like an inconvenient cushion.” She folds the fabric. “That is an irritatingly accurate way to put it.”')),
 scene('The part left deliberately crooked','Maren shows you a repair plan with a crooked detail preserved. “They wanted this kept. I have annotated it so future clever people will not rescue it.”',
 ('Ask what history the detail carries','“A child measured it. They remember the measuring more than the chair.” She taps the note. “That changes what sound work means.”'),
 ('Tell her restraint belongs among her skills','“Do not tell the tools. They already think I neglect them when I sit down.” She leaves the plan unfinished for once.'),
 ('Ask how she will handle a truly unsafe sentimental repair','“Explain the danger, then offer choices. Not secretly make the choice.” She draws two alternatives instead of one.')),
 scene('Before she reaches for a tool','Maren notices a worn clasp on your belongings and asks, “Would you like that repaired, or are you keeping it that way?” Her hand stays on the table.',
 ('Ask her to explain the options first','“I can replace the worn pin and keep the clasp,” Maren says. “Or fit a larger clasp with a wider hinge. That will show, but it will take more strain. Which matters more to you: keeping this one, or carrying more weight?”'),
 ('Thank her for asking before offering your answer','“I am attempting a new craft. It appears to involve not already holding a screwdriver.” Her grin breaks the solemnity.'),
 ('Keep it as it is for now','“Then it stays.” She changes the subject without making you defend the decision. The clasp does not become a referendum on her usefulness.'))],
'brakka':[
 scene('The story everyone expects','Brakka stops halfway through a tale about a broken anvil. “You know, I have other stories. People laugh so readily at the loud ones that I forget to tell them.”',
 ('Ask for one she rarely gets to tell','She describes spending an afternoon making a tiny latch for a music box. “Nobody was impressed by how gently I held it. That was the best part.”'),
 ('Tell her she need not entertain you to keep your attention','“Dangerous offer. I know a great deal about rivet spacing.” She tests your patience with a very small smile.'),
 ('Admit you have sometimes encouraged the performance','“I enjoyed it too.” She leans back. “Let us not pretend I was dragged through every punchline. I would simply like more than one.”')),
 scene('A quiet boast','Brakka has brought a small object wrapped in cloth. The hinge barely makes a sound. “I wanted to show someone who would not immediately ask what I can lift.”',
 ('Ask her to show you the difficult part','She points out the alignment, holding it close enough for you to see. The explanation becomes animated; quiet does not mean she has less to say.'),
 ('Let yourself be delighted by something small','“Yes, exactly that face.” She unwraps the second piece. “I brought another. I had hopes.”'),
 ('Ask her to tell you when your teasing becomes repetitive','“I can do that. You may survive a direct comment.” She grins. “I will attempt not to reinforce the problem by bellowing it.”')),
 scene('Room for more than one story','At the next comfortable pause, Brakka asks, “Would you like the ridiculous story or the very particular one?” She seems equally ready to tell either.',
 ('Choose the very particular one','You learn why a certain joint failed in winter. Brakka watches you follow the explanation, pleased to be understood rather than merely applauded.'),
 ('Ask her which one she wants to tell','“The ridiculous one today.” She smiles. “It feels different when that is a choice.”'),
 ('Offer one of your own less impressive stories first','She listens, then asks about the person who helped you. “You skipped the best part. What did they say when they saw the damage?”'))],
'fenna':[
 scene('A joke at the wrong moment','Fenna makes a quick joke when the conversation turns uncomfortable, then notices the silence. “I do that when I do not know where to put my hands. Or the rest of me.”',
 ('Ask what she was trying not to say','“That I was worried you meant it.” She looks at the tabletop. “A joke lets me check without admitting I need an answer.”'),
 ('Let her try the question again without a punchline','She asks directly this time. The words are less nimble and much easier to answer. “Oh. That was considerably less exhausting.”'),
 ('Say humour sometimes makes you feel she has not heard you','“I have heard you. I was trying to outrun the uncomfortable part.” She puts both hands flat on the table. “I can stay here instead.”')),
 scene('The pause she does not fill','Fenna allows an unusually long silence. “I have thought of four jokes,” she announces at last. “You are witnessing exceptional restraint.” Then she asks how you actually are.',
 ('Give her a complicated answer','She starts to offer a solution, stops, and asks which part you want her to understand. It is a slower conversation than usual, and a good one.'),
 ('Thank her, then invite one of the four jokes','“Only one? Cruel rationing.” She chooses the gentlest. The joke rests beside the conversation instead of replacing it.'),
 ('Tell her you do not need solemnity every time','“Good. I was beginning to fear a lifetime of meaningful nodding.” She checks your expression before laughing.')),
 scene('A question with no escape route','“Do you mind when I have no story ready?” Fenna asks. “I liked sitting with you the other day, but I kept wondering whether I was boring you.”',
 ('Tell her which quiet moment you remember','She recognises the moment before you finish describing it. “I thought nothing had happened. Apparently I was wrong.”'),
 ('Tell her yes, without turning it into a grand reassurance','“All right.” She lets the answer stand. After a while she leans back, no longer looking for the hidden qualification.'),
 ('Say you want room for both honesty and nonsense','“A sensible arrangement. We must be careful not to let it damage our reputations.” The warmth comes before the joke this time.'))],
'kaede':[
 scene('An invitation she nearly refused','Kaede admits she declined a harmless game because she did not know its rules. “I said I was occupied. I was not. I disliked the thought of being clumsy in front of everyone.”',
 ('Ask who taught her that being a beginner was embarrassing','“Nobody in one lesson. Many people in little ones.” She turns a game piece over. “I have probably taught it too.”'),
 ('Offer to learn something unfamiliar alongside her','“You must actually be unfamiliar with it. No pretending so I may feel generous.” Her expression softens. “Then yes.”'),
 ('Say avoiding the game denied the others her company','“I had thought only about what they might see.” She sets the piece down. “Not what I was withholding.”')),
 scene('Losing without a lesson','Kaede has lost a practice game and begun analysing every move. Halfway through the explanation she stops. “Were you asking why I lost, or whether I enjoyed myself?”',
 ('Ask what was enjoyable before the analysis began','“The move I did not predict.” She smiles. “For a moment I was simply surprised.”'),
 ('Invite a rematch with no instruction afterwards','“A difficult condition.” She arranges the pieces anyway. “I accept, though I reserve the right to be delighted by a clever move.”'),
 ('Tell her you would like to play without being coached','“Thank you for making the request clear.” She withdraws her hand from your side of the board. “Your next move is yours.”')),
 scene('The move she cannot predict','Kaede asks you to choose the game this time. “I have decided I can be seen learning. I have not decided to enjoy losing. These are separate negotiations.”',
 ('Choose something that rewards curiosity over speed','She studies the first unfamiliar piece and asks a question without apologising for it. The game begins there.'),
 ('Choose an old favourite and enjoy the rivalry','Her answering smile is immediate. “Very well. Affectionate company is apparently compatible with wanting to beat you.”'),
 ('Suggest taking turns making up the rules','“That sounds like a terrible system.” She considers it. “Start. I want to see what you do with it.”'))],
'elowen':[
 scene('The advice you did not request','Elowen begins suggesting remedies before you have finished describing your day. She catches herself. “I am doing it again. You have offered me a conversation and I have opened a consultation.”',
 ('Ask whether she finds listening harder than helping','“Sometimes. Advice lets me believe I have changed the outcome.” She closes the little notebook. “Listening leaves more beyond my reach.”'),
 ('Tell her company would help today','“Then I shall attempt the difficult treatment of sitting beside you.” The joke is dry; the attention that follows is patient.'),
 ('Ask her to check before offering advice','“Yes. I would insist upon being asked in your place.” She puts the notebook away entirely.')),
 scene('A day she cannot improve','Elowen describes a frustrating afternoon for which there is no useful remedy. When you begin to answer, she raises a hand with an embarrassed smile. “Could I ask for company first?”',
 ('Ask what she most wants you to understand','“That I did my work carefully and still feel disappointed.” She is relieved not to have the feeling corrected.'),
 ('Stay with her without finding a bright side','She names the small frustrations one by one. Eventually her voice lightens on its own, without either of you announcing that it ought to.'),
 ('Tell her when you are unsure what to say','“That is considerably better than inventing certainty.” She offers you the spare cup. “We may both be unsure here.”')),
 scene('The question before the answer','“Would you like a thought, a practical suggestion, or simply an attentive person?” Elowen asks. “I am trying to stop treating those as interchangeable.”',
 ('Ask for a thought you can consider without following','“An offer of help can become another decision someone is too tired to make,” Elowen says. “I sometimes give people three choices when they asked for a cup of water. Perhaps I should start by listening to the request.” She asks whether you have noticed her doing it.'),
 ('Choose the attentive person','“Available immediately.” She moves the notebook out of the way and asks you to begin wherever you wish.'),
 ('Say you may change your mind halfway through','“Then tell me when you do.” She smiles. “A conversation need not submit its final requirements in advance.”'))],
'nyssara':[
 scene('The mark beneath the warning','Nyssara finds that someone has copied a warning beside her maker’s mark. “The warning is sensible. Its placement suggests my name is the dangerous part.” She speaks evenly, leaving you room to answer carefully.',
 ('Ask which part she wants changed','“Move the warning to the working instructions. Keep my name beside what I made.” She points to each separately. “Two different pieces of information.”'),
 ('Tell her you will hear the distinction without asking her to soften it','“Good. I would rather spend the evening talking than persuading you that this is worth mentioning.”'),
 ('Ask how to raise a real concern without repeating the mistake','“Name the behaviour or the enchantment. Be specific. I can answer a question about my work; I cannot repair a suspicion attached to my existence.”')),
 scene('An explanation offered freely','Nyssara brings a harmless practice pattern. “I want to show you how I see it. This is an invitation, not a defence.” She waits for you to draw the first line.',
 ('Ask what detail she notices first','“The point where the maker expects obedience instead of understanding.” She traces a junction. “That is usually where the design will fail.”'),
 ('Tell her you enjoy seeing her absorbed in her craft','She glances up, momentarily less composed. “That is an agreeable reason to be watched.” Then she returns to the pattern, making room for your hand.'),
 ('Ask her to tell you when your questions become intrusive','“I will. And you may accept the boundary without turning the remainder of the evening into an apology.”')),
 scene('Her name, correctly placed','The revised label carries Nyssara’s name beside the work and clear instructions beneath. “Ordinary credit,” she says. “I find I am becoming quite ambitious about being treated ordinarily.”',
 ('Ask what she wants to be known for next','“Precision. Imagination. The occasional excellent joke, if this household develops the taste to recognise one.”'),
 ('Invite her company without making the label the whole evening','“Gladly.” She sets the pattern aside and asks for your opinion on a book instead. You do not need to remain inside the same difficult conversation forever.'),
 ('Say you may still disagree about her work','“I should hope so. Respect which cannot survive a technical objection would be a very poor enchantment.”'))],
'sylva':[
 scene('The cutting she did not offer','Sylva notices someone assuming that any flourishing plant can spare a cutting. “It may be able to. That does not mean it has been offered.” A leaf at her wrist curls as she considers how to explain.',
 ('Ask how she distinguishes tending from taking','“By whether I leave room for an answer I did not want.” She touches the pot, not the stem. “Care cannot be measured only in what comes home with us.”'),
 ('Tell her she can want something left alone','“Without proving it is fragile?” She looks relieved. “I would like that to be an ordinary reason.”'),
 ('Ask how people can learn without being afraid to touch anything','“By asking, and by being told clearly.” Her voice warms. “A garden of unspoken prohibitions would be a lonely place.”')),
 scene('A season that looks like nothing','Sylva has kept a bare pot where visitors expect a blossom. “Everyone offers to replace it. It is resting.” She smiles wryly. “I am considering a little sign for myself as well.”',
 ('Ask what rest looks like to her','“Less explanation. Familiar company. Being allowed to leave a thought unfinished.” She leans against the warm stone.'),
 ('Share the quiet without asking when the pot will flower','For a while you discuss the changing light instead. Sylva relaxes when the conversation does not keep circling back to future usefulness.'),
 ('Say she will need to tell you when she wants solitude','“Yes. I cannot expect you to read a leaf correctly every time.” She lifts her wrist. “Sometimes this means only that I am cold.”')),
 scene('A gift she chose to give','Sylva offers you a pressed leaf, carefully wrapped. “This one I wanted to share. I thought the difference deserved something you could hold.”',
 ('Ask which moment the leaf preserves','“The wall was grey until the sun reached it,” Sylva says. “Then the leaf cast a red patch through a crack in the shutters. I stayed to watch it move. That was the first thing I wanted to tell you.”'),
 ('Accept it as a personal gift','“Keep it however you like.” She smiles. “You need not turn appreciation into excellent plant care.”'),
 ('Ask whether you may someday give it to someone else','She considers it. “Yes. Tell them where it came from. A gift may continue travelling after I have finished making it.”'))]
}

# Each pair has an introduction, a negotiated change, and a later outcome.
# The final opening includes an authored branch based on the preceding choice.
PAIRS = {}
def pair(key, people, label, rows, branches):
    PAIRS[key]={'participants':people,'label':label,'scenes':rows,'branches':branches}

pair('mira-tamsin',['mira','tamsin'],'Making room for different kinds of care',[
 scene('The recipe in the margin','Mira has tidied a recipe that Tamsin remembers by feel. “A generous handful is not a measurement,” Mira says. “It is if you know whose hand,” Tamsin replies. Neither wants to surrender the page.',
 ('Ask each of them to explain what the other version loses','Mira wants a stranger to reproduce it. Tamsin wants the cook to notice the dough. “Then we have two readers,” Mira concedes. “Perhaps two kinds of instruction.”'),
 ('Suggest trying the recipe together before editing it','Tamsin offers the bowl; Mira offers the pencil. Their first discovery is that neither object belongs anywhere near the other when the stirring becomes enthusiastic.'),
 ('Ask them to keep both versions without declaring a winner','“Facing pages,” Mira proposes. “And no quietly correcting mine at night,” Tamsin adds. Mira accepts the condition.')),
 scene('Flour on the index cards','Tamsin reports that the written recipe worked until the weather changed. Mira reports that “you will know” was unhelpful precisely when she did not. They arrive with the same slightly embarrassed smile.',
 ('Help them record the signs a beginner can observe','They write what the dough should feel like, not merely how long to knead. Tamsin supplies the sensation; Mira asks the questions an unfamiliar cook might need.'),
 ('Encourage them to make the experiment a regular shared evening','“Only if we may make something we cannot catalogue afterwards,” Tamsin says. “I can probably tolerate cake,” Mira replies.'),
 ('Suggest they choose which version to use each time','They put both cards in the box. “An invitation to choose,” says Mira. “Rather than a test you can fail,” Tamsin adds.')),
 scene('A note in two hands','A flour-marked card appears on the table. Mira’s small writing shares it with Tamsin’s broad corrections. “We have both become rather opinionated about bowls,” Tamsin tells you.',
 ('Ask what they learned about one another','Mira says Tamsin notices hesitation before a question is spoken. Tamsin says Mira asks questions she had stopped remembering were difficult. They look pleased to have been noticed accurately.'),
 ('Enjoy being invited into their new shared joke','“Do not say generous handful,” Mira warns you. Tamsin raises both hands with exaggerated innocence. You have arrived in the middle of a friendship with its own vocabulary.'),
 ('Let them keep the project theirs','They return to their argument about bowls without needing you to settle it. This time you can hear the pleasure beneath the disagreement.'))],
 {'curious':'Their next card describes texture as carefully as quantity; both have signed the explanation.','warm':'They have begun keeping one evening for experiments, including failures nobody has to serve.','candid':'Two complete recipes remain in the box, and choosing one has stopped being a declaration of loyalty.'})

pair('iona-fenna',['iona','fenna'],'Routes, stories and reliability',[
 scene('The scenic shortcut','Fenna calls a route a shortcut. Iona points out that it is longer. “But the journey feels shorter,” Fenna says. “An excellent distinction to tell someone before they depart,” Iona answers.',
 ('Ask them to distinguish fast from pleasant','Iona draws a clock beside one route. Fenna draws a cup beside the other. “Now I know which kind of late I am choosing,” Iona says.'),
 ('Invite Fenna to tell the story of the detour','The story involves a stubborn gate and unexpectedly good tea. Iona listens, then asks for the location of the gate. Both kinds of detail survive.'),
 ('Support giving travellers the inconvenient facts first','Fenna nods. “Longer road, better company. I can sell that honestly.” Iona relaxes at the word honestly.')),
 scene('Waiting at the wrong turning','Iona says she waited while Fenna stopped to talk. Fenna had assumed the delay was obvious. “I enjoy surprises,” Iona says. “Less so when I think someone is missing.”',
 ('Help them agree on a meeting place before wandering','They choose a simple rule: name where to meet and say when plans change. Fenna calls it an arrangement with room to breathe.'),
 ('Ask Fenna to explain why she stops for people','“Because they may not ask twice.” Iona hears the care behind the wandering. “Then tell me. Sometimes I would like to stop too.”'),
 ('Ask Iona to say when she would rather travel separately','“I can do that without calling her unreliable,” Iona says. “And I can hear it without calling her dull,” Fenna replies.')),
 scene('Two marks on the map','Fenna and Iona bring you a map with separate marks for places to reach and places to linger. “Nobody has been officially declared dull,” Fenna reports.',
 ('Ask how the arrangement is working','Iona admits she has discovered a good bench. Fenna admits she has discovered the relief of knowing someone will be where they said. Neither lets the other make too much of it.'),
 ('Ask to hear about their favourite unplanned stop','They disagree about which stop was best and tell you both stories. Their disagreement now adds detail rather than requiring a referee.'),
 ('Point out that they do not need identical travelling habits','“Fortunately,” they say together. The simultaneous answer amuses them more than either intended.'))],
 {'curious':'A meeting place is written clearly on the next route, leaving the paths between it open.','warm':'Their latest detour was agreed together; Iona has added the name of the person they stopped to see.','candid':'One recent journey was made separately, and their accounts became the evening’s conversation.'})

pair('aurelia-kaede',['aurelia','kaede'],'Respect beyond readiness',[
 scene('An exercise that never ended','Kaede has been discussing practice after Aurelia believed the session was over. “I put the equipment down,” Aurelia says. “I thought that meant I could stop being evaluated.” Kaede looks genuinely startled.',
 ('Ask them to say explicitly when practice has ended','They settle on a plain ending, spoken aloud. Kaede admits she can continue a lesson entirely inside her own head and expect everyone else to follow.'),
 ('Ask what each enjoys about company outside practice','Aurelia likes dry stories. Kaede likes games she pretends not to take seriously. Both seem surprised that the other might supply either.'),
 ('Say unsolicited instruction can feel like a judgement','Kaede accepts the point without explaining her good intentions again. “Then I will ask before offering the next correction.”')),
 scene('The missing invitation','Kaede invites Aurelia to sit with her, then adds that there will be no practice discussion. “I had not realised an invitation needed that clause,” Aurelia says. “I am learning that some of mine do,” Kaede replies.',
 ('Ask them to find a subject neither has mastered','They choose an unfamiliar board game. Aurelia discovers that Kaede reads rules with the suspicion usually reserved for ambushes.'),
 ('Suggest swapping an embarrassing harmless story','Aurelia describes saluting a coat hung in a dark doorway. Kaede laughs, then supplies a mishap of her own without turning either story into advice.'),
 ('Let them decide the evening without a facilitator','You excuse yourself from choosing. Their first shared decision is to leave the equipment exactly where it is.')),
 scene('Companions off duty','Aurelia and Kaede are already talking when you arrive. Neither stands. “We have declared the chairs outside the training jurisdiction,” Kaede explains.',
 ('Ask what has become easier between them','“Not needing to be impressive,” Aurelia says. Kaede takes a moment, then agrees without qualifying it.'),
 ('Join their gentle argument about the game','Aurelia accuses Kaede of tactical cup placement. Kaede maintains that a stable drink is not a military doctrine.'),
 ('Remind them that they can still enjoy practising together','“Certainly,” Kaede says. “We have simply acquired a second subject.” Aurelia adds that it is a considerable relief.'))],
 {'curious':'The unfamiliar game is still on the table, with corrections to the rules in two equally baffled hands.','warm':'An insignificant coat has become an enduring private joke, which Aurelia now tells better than Kaede.','candid':'They have begun inviting one another directly; their company no longer depends on your arrangements.'})

pair('sabine-elowen',['sabine','elowen'],'Candour and tact',[
 scene('A truth wrapped too tightly','Sabine thinks Elowen gave a blunt answer to a nervous question. Elowen thinks Sabine’s kinder version concealed the answer. “A truth still needs a door,” Sabine says. “And an address,” Elowen replies.',
 ('Ask what the nervous person actually needed to know','They reconstruct the question and discover that each answered a different part. Neither finds this comfortable; both find it useful.'),
 ('Invite each to rewrite one sentence in the other’s style','Sabine’s plain version is admirably short. Elowen’s tactful version is so formal that Sabine laughs, then apologises and helps.'),
 ('Say kindness should not require guessing the answer','Sabine agrees to stop before tact becomes fog. Elowen agrees to distinguish clarity from abruptness.')),
 scene('An honest answer, gently delivered','Elowen brings a draft reply to Sabine. “Will you tell me where this becomes unnecessarily sharp?” Sabine reads it without picking up a pen. “Would you like suggestions or a rewrite?”',
 ('Encourage suggestions that leave the original author in control','Elowen keeps the pen. Sabine asks what each sentence is meant to do. The reply remains Elowen’s, with fewer accidental thorns.'),
 ('Ask them to read it aloud together','They hear an impatient rhythm neither noticed on the page. A pause fixes more than an elaborate new phrase would have.'),
 ('Ask them to keep the difficult fact unmistakable','They put the answer in the first sentence and the explanation afterwards. Sabine observes that directness need not arrive alone.')),
 scene('No translation required','Sabine and Elowen disagree about a letter, then each summarises the other’s concern accurately. They look at you. “That was rather better than last time,” Elowen says.',
 ('Ask what helped them hear each other','“She stopped assuming precision meant indifference,” Elowen says. “She stopped assuming tact meant dishonesty,” Sabine answers.'),
 ('Enjoy their increasingly dry shared humour','They offer competing versions of an invitation to tea. One is brutally concise; the other threatens to outlast the tea itself.'),
 ('Say they need not merge their voices','“Thank goodness,” Sabine says. Elowen nods. “I have only just become comfortable with my own.”'))],
 {'curious':'Elowen still holds the pen; Sabine’s questions have replaced her habitual silent revisions.','warm':'Reading aloud has become a shared ritual, and both have developed a merciless ear for overlong sentences.','candid':'Their replies now lead with the answer, followed by enough care to help the reader receive it.'})

pair('neris-elowen',['neris','elowen'],'Different temperatures, shared space',[
 scene('The argument about the window','Neris opens the window; Elowen closes it. They have repeated the exchange twice before either speaks. “I thought you had not noticed,” Neris says. “I noticed,” Elowen replies.',
 ('Ask each to describe what would make the room comfortable','The problem turns out to be a draught at one chair and stagnant air at another. Moving the chairs seems embarrassingly simple once both descriptions are heard.'),
 ('Invite them to laugh at the silent window contest','“A devastating tactical stalemate,” Elowen says. Neris concedes that the window has shown admirable neutrality.'),
 ('Say neither should silently decide for the whole room','They agree to ask before adjusting it again. Nobody claims that being uncomfortable gave her the only legitimate vote.')),
 scene('A cup cooled too soon','Neris cooled a drink that Elowen meant to sip slowly. Elowen added hot water from the kettle. “We appear to have invented a very elaborate way not to ask a question,” Neris says.',
 ('Suggest asking before helping, even with familiar preferences','They practise with excessive ceremony until the joke gives way to an ordinary question. “How do you want yours?” turns out to be enough.'),
 ('Encourage them to share the table with differently prepared drinks','Two cups arrive at different temperatures. Elowen calls it a scandalous failure of uniformity and looks perfectly content.'),
 ('Ask them to leave one another’s cups alone','“A clear jurisdiction,” Neris says. Elowen marks an imaginary border around her saucer. Both respect it.')),
 scene('The window left halfway','You find the two of them sharing a table with the window ajar. “We have not solved the climate,” Elowen says. “Only the conversation about it,” Neris adds.',
 ('Ask which assumption was hardest to stop making','Neris had assumed comfort was obvious. Elowen had assumed asking would become an argument. They are amused by how thoroughly each had been wrong.'),
 ('Join them with your own preference stated plainly','They make room without treating your preference as a tie-breaking vote. Three people are allowed three different cups.'),
 ('Leave the compromise open to revision','“Naturally,” Neris says. “The weather has declined to sign a permanent agreement.” Elowen reaches for her own cup and no one else’s.'))],
 {'curious':'They ask first now, including on days when they are almost certain of the answer.','warm':'Two deliberately different drinks have become their preferred way of sharing a table.','candid':'The saucer borders remain a joke, but the habit of leaving another person’s cup alone is real.'})

pair('maren-brakka',['maren','brakka'],'Giving and receiving practical trust',[
 scene('The borrowed chisel','Brakka borrowed a chisel and returned it sharpened differently. Maren notices at once. “I made it better,” Brakka begins, then hears herself. “For my hand, perhaps.”',
 ('Ask Maren to explain the difference in use','Maren demonstrates the angle without accusing Brakka of carelessness. Brakka tries it and immediately understands why the change mattered.'),
 ('Suggest they compare their favourite tools','The comparison becomes a lively catalogue of apparently unreasonable preferences, each with a precise physical reason.'),
 ('Ask them to agree that borrowing does not include alteration','Brakka agrees. Maren adds that a question would have been welcome. The disagreement ends with a rule both can actually remember.')),
 scene('A tool made for another hand','Brakka brings a sketch, not a finished gift. “I thought I might ask first this time.” Maren looks it over and asks for a smaller grip. Brakka changes the drawing immediately.',
 ('Ask them to test the shape together before making it','They use scrap wood and discover a second adjustment. Maren seems especially pleased that the unfinished version is allowed to be wrong.'),
 ('Ask why Brakka wanted to make the gift','“Because I watch her work and wanted to make it easier.” Maren’s reply is quieter than her usual workshop voice. “I noticed.”'),
 ('Make room for Maren to decline the design','Maren considers the offer rather than reassuring Brakka. She chooses to accept, with changes. Brakka treats the changes as useful information.')),
 scene('The grip with two makers','Maren brings the finished grip to the table. “Her patience,” she says, indicating Brakka, “was the most surprising material.” Brakka claims it was exceptionally expensive.',
 ('Ask what each contributed','Brakka names Maren’s exacting questions. Maren names Brakka’s willingness to start again. Neither pretends that collaboration meant agreeing on the first sketch.'),
 ('Invite them to tell the least dignified part of making it','The story involves a convincing prototype that fitted neither hand. Their laughter is the laughter of people who were embarrassed together and survived.'),
 ('Let the gift remain between them','They pass the tool back and forth, discussing a detail you do not need to judge. Their trust has a practical life beyond your approval.'))],
 {'curious':'A scruffy prototype hangs beside the finished grip as a reminder that testing together saved time.','warm':'Maren has begun noticing small ways to make Brakka’s work easier in return, always asking first.','candid':'The accepted changes remain visible in the sketch; neither has erased the evidence of negotiation.'})

pair('nyssara-sylva',['nyssara','sylva'],'Patterns that leave room to grow',[
 scene('The line that would not stay straight','Nyssara draws an elegant support pattern around a climbing stem. Sylva turns the page. “It will want to grow there.” Nyssara studies the awkward bend. “Then my elegant pattern has failed its first resident.”',
 ('Ask them to design for change rather than the current shape','Nyssara leaves adjustable junctions. Sylva points out where she cannot predict the direction. Uncertainty becomes part of the drawing.'),
 ('Ask what each finds beautiful in the other’s approach','Sylva admires the care in a deliberate line. Nyssara admires the stem’s unembarrassed refusal to follow it. Both seem surprised by the answer.'),
 ('Ask whether the plant needs an enchantment at all','They put the design aside and examine the ordinary support first. Nyssara is the one who says it may be sufficient.')),
 scene('An experiment allowed to fail','Sylva reports that the stem chose an unexpected direction. Nyssara says, “I had a revised drawing ready. Then I realised I was making an argument, not a support.”',
 ('Suggest an adjustable ordinary frame before further magic','They choose something that can be moved by hand. Nyssara labels it provisional with visible satisfaction.'),
 ('Invite them to observe it together without fixing it today','Sylva finds a new tendril behind the upright; Nyssara points out that it has reached the rough wood rather than her polished ring. “It prefers a grip to an elegant surface,” Nyssara says. “A defensible preference.” Sylva laughs and asks her to write that beside the drawing.'),
 ('Let Sylva choose whether the experiment continues','Sylva asks to stop the enchantment trial and keep the conversation. Nyssara agrees without making the unfinished diagram into a debt.')),
 scene('A shape neither predicted','Nyssara and Sylva show you a sketch with a generous blank area. “Reserved for developments,” Nyssara says. “Or for leaving well enough alone,” Sylva adds.',
 ('Ask how their definition of a good design changed','Nyssara says a good design can admit what it does not know. Sylva says careful planning need not be a promise to control everything.'),
 ('Ask to hear about their conversations away from the project','They have discovered a shared fondness for unlikely metaphors and a disagreement about whether vines can be described as sarcastic.'),
 ('Say the friendship need not produce a finished object','“An excellent outcome specification,” Nyssara says. Sylva laughs and draws a leaf in the margin, outside every planned line.'))],
 {'curious':'The ordinary frame can be adjusted without anyone having to defend a theory first.','warm':'Watching the plant has become an excuse to meet; they now sometimes forget to discuss it.','candid':'The enchantment diagram remains unfinished by agreement, while their visits continue.'})

pair('mira-brakka',['mira','brakka'],'Whose expertise counts',[
 scene('The word for what her hands know','Mira uses a technical term for a joint Brakka has made for years. Brakka supplies another name. “I thought that was a local expression,” Mira says. “It is. Local to people who make it,” Brakka replies.',
 ('Ask where both names come from','Mira finds a printed source; Brakka recalls the workshop where she learned. The accounts describe the same useful idea travelling by different routes.'),
 ('Invite a demonstration in exchange for the written explanation','Brakka shows the movement of the tool. Mira reads the diagram aloud and realises which crucial motion the book never mentions.'),
 ('Ask Mira not to rank knowledge by whether it was printed','Mira nods. “I was doing precisely that.” Brakka accepts the acknowledgement without making her repeat it.')),
 scene('The diagram with a missing hand','Mira brings a diagram and asks Brakka what is missing. “A hand here,” Brakka says. “And a person swearing quietly when this slips.” Mira reaches for a pencil.',
 ('Help them make the instructions usable by a beginner','They add a view from the worker’s side and an honest warning about the difficult step. Brakka insists the warning should not blame the reader.'),
 ('Enjoy the unlikely partnership','Mira’s dry footnotes and Brakka’s exact demonstrations turn out to suit each other. Their argument about the swearing becomes a running joke.'),
 ('Ask them to credit the practical corrections by name','Mira writes Brakka’s name beside the amended figure. Brakka looks at it longer than she looks at the new diagram.')),
 scene('An authority in the footnote','Brakka catches Mira referring to her correction during another discussion. “You quoted me?” she asks. “You were the authority on the point,” Mira answers.',
 ('Ask how they decide when to trust a source now','Mira says she asks what experience the source can answer for. Brakka says she has become more willing to open a book that admits where it needs a teacher.'),
 ('Let Brakka enjoy being quoted','She requests an increasingly elaborate title. Mira grants her an exceptionally short footnote instead. Both appear satisfied.'),
 ('Point out that either of them may still be mistaken','“Obviously,” Brakka says. Mira agrees. The easy agreement is a better sign than any promise never to argue again.'))],
 {'curious':'Their revised diagram has already survived a beginner’s most inconvenient questions.','warm':'A note reading insert appropriate quiet swearing remains in the private draft, to their continuing delight.','candid':'Brakka’s named contribution is preserved beside the formal citation, with neither treated as decoration.'})

pair('iona-nyssara',['iona','nyssara'],'Trusting an unfamiliar method',[
 scene('The route through the threshold','Iona asks whether an instant crossing leaves a traveller enough time to understand where she has arrived. Nyssara answers the technical question, then notices that it was not the only question.',
 ('Ask Iona what she wants to preserve about a journey','“Orientation. The feeling that I can turn back.” Nyssara explains which parts a threshold can offer and which require an ordinary pause afterwards.'),
 ('Ask them to imagine a comfortable arrival together','They describe a clear landing place, a moment to look around and someone who does not immediately demand the next decision.'),
 ('Say a faster journey is not automatically everyone’s preference','Nyssara agrees. “A capability is not an instruction.” Iona looks relieved to hear it from her.')),
 scene('A map with room for hesitation','Iona sketches a threshold beside an ordinary road. Nyssara asks why the road remains so prominent. “Because a choice should be visible even when it is slower,” Iona says.',
 ('Encourage a plan that explains both methods clearly','They write separate descriptions, including what each traveller must know beforehand. Neither route is labelled the sensible one.'),
 ('Ask what would make them choose differently on a tired day','Iona admits she might welcome the shorter crossing. Nyssara admits she sometimes wants the walk. Their apparent opposition becomes less tidy.'),
 ('Ask them to leave the final decision to the traveller','They remove a suggested default from the sketch. “We can offer information without voting on someone else’s comfort,” Nyssara says.')),
 scene('An agreement about arrival','The two of them have stopped debating which journey is better and started debating what a welcome requires. Iona wants a clear destination. Nyssara wants room for the traveller to ask a question twice.',
 ('Ask them to explain the welcome they designed','Their account includes practical detail and time to recover from disorientation. It is an idea for care, not a newly funded facility.'),
 ('Enjoy their shared enthusiasm','They interrupt one another once, apologise at the same time, and laugh. The conversation has acquired a pace both can enjoy.'),
 ('Keep the plan optional, even after all that thought','“Yes,” Iona says. Nyssara adds, “Especially after all that thought. We are not owed a passenger.”'))],
 {'curious':'Both routes now have equally clear instructions, including the option to reconsider before departing.','warm':'Their margins contain personal reasons to walk and personal reasons not to, with neither list winning.','candid':'The traveller’s choice remains the final line, instead of a decision already made by the designers.'})

pair('tamsin-sabine',['tamsin','sabine'],'Hosting without performing',[
 scene('The guest list and the empty chair','Sabine has arranged names to make conversation flow. Tamsin has left a chair for someone unexpected. “A seating plan is not a locked gate,” Sabine says. “Then let us leave the gate visible,” Tamsin answers.',
 ('Ask what each hopes a guest will feel','Sabine wants nobody stranded. Tamsin wants nobody to feel uninvited. They discover that their plans began with the same fear from opposite sides.'),
 ('Suggest trying a deliberately informal table','Sabine moves one carefully placed name. Tamsin agrees that a newcomer might still appreciate an introduction. Neither abandons her care.'),
 ('Ask them not to arrange people without asking what they prefer','They decide to offer seats rather than assign them. Sabine admits that elegant planning can become a very polite command.')),
 scene('The compliment after supper','Sabine praises Tamsin for making everything look easy. Tamsin says, carefully, “I would rather you noticed that it was work.” Sabine puts down the list she was about to discuss.',
 ('Ask for a more specific acknowledgement','Sabine names the timing, the welcome and the missed chance for Tamsin to sit. Tamsin says the last observation matters most.'),
 ('Invite them both to be guests for a moment','They sit with the remains of the conversation rather than the remains of the meal. Sabine proves unexpectedly good at a ridiculous guessing game.'),
 ('Ask how future invitations can include their own enjoyment','They remove two unnecessary flourishes from the next imaginary evening. Neither needs to make her own exhaustion part of the welcome.')),
 scene('An invitation with two signatures','Tamsin and Sabine show you a note signed by them both. “Company requested,” Sabine reads. “Perfection not available,” Tamsin adds. The second line is also written down.',
 ('Ask how they divided the things they enjoy doing','Sabine will introduce people; Tamsin will choose the game. Both reserve the right to sit down.'),
 ('Accept the spirit of the invitation','They exchange a pleased look before either answers you. Their collaboration now includes the enjoyment they once forgot to plan.'),
 ('Remind them that a quiet evening counts too','“Then this may already be one,” Tamsin says. Sabine folds the unsigned spare invitations away.'))],
 {'curious':'Their thanks have become specific enough that neither has to guess whether the other saw the effort.','warm':'The guessing game now has a thoroughly unnecessary diplomatic vocabulary, supplied by Sabine.','candid':'Their next plan explicitly leaves time for both hosts to become ordinary company.'})

# Contextual conversations require actual saved evidence, not speculative narration.
REACTIONS={
'mira':('spell','After the working', 'Mira asks about a spell you have actually cast. “Did understanding what it would do change the experience of doing it? I used to think explanation would spoil wonder.”',
 ('Ask whether precision has changed her own sense of wonder','“It has given it somewhere to stand.” She smiles. “I can admire the thing that happened instead of insisting it must secretly be something else.”'),
 ('Tell her you wanted to share the moment with her','“Then I am glad you did not turn it straight into a report.” She asks what you noticed first, before the useful result.'),
 ('Say a useful spell can still feel ordinary','“Yes. We need not perform astonishment on demand.” She looks pleased by the freedom to discuss the work plainly.')),
'tamsin':('journey','The part after coming home','Tamsin waits until you have returned from a journey. “Would you like to tell it, or would you like to be home before you become a story?” She leaves the question open.',
 ('Tell her one detail that did not belong in the report','She listens closely to the small account. “That is the part I would have missed if I only asked whether it went well.”'),
 ('Choose familiar company before an account of the journey','“Then we can talk about something wonderfully local.” She begins with a minor disagreement about where a cup belongs.'),
 ('Tell her you will choose when to discuss it','“Of course.” She changes the subject without becoming distant. You do not have to earn a welcome by delivering a story.')),
'iona':('journey','The journey and the report','Iona has read the practical record of a returned expedition. “That tells me what came home. It does not tell me what the journey was like for you.”',
 ('Talk about a decision rather than a discovery','She asks which alternative you considered and why. It feels different to have a choice understood instead of simply counted as success.'),
 ('Ask about a journey she still remembers','She chooses one with no remarkable reward, only a conversation at the end. The account is a gift in return, not an attempt to outdo yours.'),
 ('Say you would rather leave the journey in the journal today','“Then the report can do its job.” She closes it and asks what you want from the rest of the evening.')),
'aurelia':('journey','Safe is not the whole answer','After your return, Aurelia starts to ask whether everyone is safe, then changes the question. “How are you finding being here again?”',
 ('Explain what is taking time to settle','She listens without translating every feeling into an injury to inspect. “I am glad I asked the longer question.”'),
 ('Tell her her familiar presence helps','Her wings shift. “I can be familiar without standing guard. That is good to know.”'),
 ('Ask her not to check on you repeatedly','“One honest question, then room for your answer.” She nods. “Tell me if you want another.”')),
'neris':('spell','What the water did not decide','Neris has heard that the household has completed a casting. “People talk as if magic makes the choice for you. A working still needs someone to decide when it is worth using.”',
 ('Ask how she makes that decision','“By asking what I am trying to change, and whose day changes with it.” She admits she has occasionally remembered the second question late.'),
 ('Enjoy talking about a successful piece of work','She lets herself sound pleased without turning the conversation into instruction. Her curiosity is about your experience of it.'),
 ('Say convenience can be a sufficient reason','“Certainly. Every ordinary kindness need not pass an examination in grandeur.” She raises her cup to modest improvements.')),

'sabine':('spell','An easier answer','Sabine raises the subject of magic after a real household casting. “An easier conversation is not necessarily a more truthful one. I hope we will remember that when ease becomes available.”',
 ('Ask how she distinguishes reassurance from persuasion','“Whether I leave the other person room to give an answer I dislike.” She does not pretend the distinction is always comfortable.'),
 ('Tell her you would rather hear her unpolished opinion','“Then here it is: useful power deserves exact questions, including from someone fond of you.”'),
 ('Say persuasion is part of ordinary conversation too','“Indeed. That is why I distrust a neat division between innocent words and complicated magic. We should pay attention to both.”')),
'maren':('spell','What remains handmade','After a casting, Maren turns a small unfinished piece in her hands. “If a working can do part of this faster, I want to choose which part I still enjoy doing slowly.”',
 ('Ask which part she would keep for herself','“Fitting the pieces until I understand why they belong together.” She smiles. “You may magically tidy every shaving afterwards.”'),
 ('Tell her you value the time she chooses to put into things','“Choose is the useful word.” She returns to the piece without making slowness into an obligation.'),
 ('Say speed can make room for another pleasure','“Yes. I do not want to defend drudgery because it happens near craftsmanship.” She lays aside the dullest part of the explanation first.')),
'brakka':('spell','Strength without a contest','Brakka considers the news of a completed spell. “Someone will inevitably ask whether magic is stronger than a smith. I should like to ask why we are lifting the same thing competitively.”',
 ('Ask what cooperation would look like instead','“One person steadies, one person watches the fit. Neither needs an audience.” She seems delighted by this deeply unheroic arrangement.'),
 ('Invite her to make fun of the imaginary contest','She invents increasingly useless feats until the winner is a person who sensibly uses a trolley. “An overlooked champion.”'),
 ('Ask whether she would miss being the strongest person present','Brakka takes the question seriously. “Some days. Then I would have to find out whether people liked having me there for another reason.”')),
'fenna':('journey','The version without embellishment','Fenna asks for the story of a completed journey. “Accurate version first. I will seek permission before introducing a spectacularly implausible bird.”',
 ('Give her the accurate version and ask what catches her interest','She notices an awkward pause you would have edited out. “That is where it starts sounding like people rather than a noticeboard.”'),
 ('Invite a clearly imaginary retelling afterwards','Her bird is indeed implausible. Both of you know which parts are inventions; the tale remains unmistakably a tale.'),
 ('Ask her to keep this one out of public storytelling','“Then it stays here.” She does not bargain for an anonymous version. The next tale she tells is her own.')),
'kaede':('journey','After the difficult choice','Kaede asks about a returned expedition. “I can discuss what you might do differently, if you want. I can also refrain. I have been informed this is an important skill.”',
 ('Invite questions about the alternatives you considered','She asks what you knew at the time instead of judging with the convenience of hindsight. The distinction makes it possible to think aloud.'),
 ('Choose an evening that is not a debriefing','“Understood.” She asks whether you would like company over a game, making no attempt to turn the game into a field exercise.'),
 ('Tell her you have already judged yourself enough today','Her expression softens. “Then I will not add a second examiner.” She leaves room for the conversation to become ordinary.')),
'elowen':('journey','Care after the account','Elowen speaks with you after a journey has been brought home. “People sometimes answer how are you with an inventory. It is a useful inventory. It is not always the answer.”',
 ('Tell her how the journey felt','She follows the account without insisting that it end cheerfully. She lets the account take the shape you give it.'),
 ('Ask for familiar company rather than advice','“A perfectly reasonable request.” She puts her notes aside before you have to ask a second time.'),
 ('Keep the account practical for now','She accepts the boundary. “If the other answer arrives later, it is still welcome.”')),
'nyssara':('ritual','Living beside a permanent working','After a lasting circle is completed, Nyssara asks what it means to keep a working active for the household. “Permanent should describe the inscription. It should not prevent us from asking whether we still want its effect.”',
 ('Ask how she would revisit that decision','“With the people who use the space, and without treating a changed mind as an insult to the maker.” She suggests asking the people who live alongside it.'),
 ('Enjoy the fact that the household made something lasting','“Yes. We are allowed to be pleased before beginning the next improvement.” She deliberately closes the notebook.'),
 ('Say constant reconsideration could become exhausting','“Then choose a sensible occasion to review it. Reflection need not be a permanent meeting.”')),
'sylva':('ritual','What changes around a circle','Sylva has noticed the household living with a completed ritual. “I wonder which changes we will stop noticing first. Not because they cease to matter, but because they become ordinary.”',
 ('Ask what she wants you to keep noticing','“Who uses it. Who finds it less helpful than expected. And whether anyone feels unable to say so.”'),
 ('Share a small pleasure in the changed household','She contributes one of her own without making a prophecy about what the ritual will become. A present pleasure can be enough.'),
 ('Say a lasting effect should not decide how everyone lives','“Then we should keep asking one another.” She smiles. “An inscription cannot perform the whole work of being neighbours.”')),
}

GATHERINGS=[
 (['mira','tamsin'],'A supper with no report','Tamsin asks for one story that does not concern completed work. Mira immediately offers an unfinished book. “That is dangerously close,” Tamsin says. Mira insists the book has been unfinished for years and therefore qualifies.',
 ('Ask everyone for a small thing they enjoyed','The answers wander from a patch of light to a badly told joke. The table acquires a picture of the day that no work ledger could have supplied.'),
 ('Offer something ordinary about your own day','Mira asks a precise question; Tamsin asks an unexpected one. Between them, your unremarkable account becomes an actual conversation.'),
 ('Admit you do not feel talkative','Tamsin leaves your place in the conversation open without repeatedly returning to you. Mira tells the unfinished-book story badly enough that listening is quite sufficient.')),
 (['fenna','kaede'],'Rules for a harmless game','Fenna proposes a guessing game. Kaede requests a complete explanation of the rules. Fenna admits some of them have not been invented yet. Kaede looks at you with profound but not unhappy suspicion.',
 ('Ask them to agree on the rules before the first round','The negotiation becomes almost as entertaining as the game. Kaede concedes one absurd exception; Fenna promises not to invent another after seeing her hand.'),
 ('Join the experimental version','You all agree that this round is an experiment. A spectacular disagreement about what counts as a bird becomes part of the entertainment, not a retroactive victory.'),
 ('Offer to watch the first round','They make room for a spectator without recruiting you as judge. Their inability to agree on a winner turns out to be survivable.')),
 (['iona','sabine'],'Letters that will not be sent','Iona proposes writing one sentence you do not intend to send. Sabine asks whether it must be elegant. “It must be yours,” Iona says. The paper stays with its writer.',
 ('Write privately and share only what you choose','Nobody reaches for anyone else’s page. Sabine reads a surprisingly plain sentence; Iona chooses not to read hers and remains entirely part of the evening.'),
 ('Suggest writing a fond note to the household instead','Their drafts disagree about punctuation and agree about the value of finding familiar company at the end of a day.'),
 ('Decline to write but stay for the company','Iona puts your blank sheet away without comment. Sabine observes that declining an exercise may itself be an admirably concise statement.')),
 
 (['maren','brakka'],'Objects with no impressive value','Maren brings a worn toy; Brakka brings an ordinary fastening from an early piece of work. Neither object would win an exhibition. Both owners are unusually careful placing them on the table.',
 ('Ask what each object lets them remember','Their answers concern people, mistakes and afternoons, not craftsmanship alone. Neither offers to improve the other’s keepsake.'),
 ('Tell a story about an ordinary possession of your own','They listen as makers who understand that an object can matter beyond its quality.'),
 ('Ask before handling either keepsake','Maren invites you to turn hers over. Brakka prefers to hold hers while explaining it. The two answers require no comparison.')),
 (['nyssara','sylva','elowen'],'An evening without improvement','Elowen proposes an evening in which nobody recommends a remedy. Nyssara asks whether this includes technical improvements. Sylva asks whether the proposal itself counts as an improvement. The experiment is in immediate difficulty.',
 ('Keep the spirit of the idea without policing every sentence','You all settle into a conversation that occasionally contains useful thoughts without obliging anyone to act on them. Elowen calls that a more realistic success.'),
 ('Ask what each enjoys simply as it is','Nyssara chooses a clever phrase; Sylva chooses the light; Elowen chooses a scent with no medicinal justification. Their answers are different and compatible.'),
 ('Say advice is welcome when someone actually asks for it','“Then the rule is a question,” Elowen says. Nyssara approves the efficient design; Sylva points out that you have all immediately improved it.')),
]

def catalogue():
    rows={}
    for who,arc in PERSONAL.items():
        for i,d in enumerate(arc):rows[f'personal:{who}:{i}']={**d,'participants':[who],'category':'personal','arc':who,'stage':i,'previous':f'personal:{who}:{i-1}' if i else None}
    for key,arc in PAIRS.items():
        for i,d in enumerate(arc['scenes']):rows[f'pair:{key}:{i}']={**d,'participants':arc['participants'],'category':'pairs','arc':key,'stage':i,'previous':f'pair:{key}:{i-1}' if i else None,'relationship':arc['label'],**({'branches':arc['branches']} if i==2 else {})}
    for who,(trigger,title,opening,*choices) in REACTIONS.items():rows[f'reaction:{who}']={**scene(title,opening,*choices),'participants':[who],'category':'reactions','arc':who,'stage':0,'previous':None,'trigger':trigger}
    for i,(people,title,opening,*choices) in enumerate(GATHERINGS):rows[f'gathering:{i}']={**scene(title,opening,*choices),'participants':people,'category':'gatherings','arc':str(i),'stage':0,'previous':None}
    return rows
PERSONAL_BRANCHES={
'mira': {'curious':'Mira has left the most troublesome sentence underlined instead of correcting it.', 'warm':'The passage you read together now has a note in the margin: requires two unconvincing actors.', 'candid':'Your disagreement remains on the page. Mira has resisted the temptation to add a final rebuttal.'},
'tamsin': {'curious':'Tamsin has written down the ridiculous game she wanted to play, including one rule that makes her laugh every time.', 'warm':'Tamsin remembers being able to choose the conversation and asks whether you would like another story.', 'candid':'Tamsin has begun saying when she wants company rather than looking for a useful task to bring along.'},
'iona': {'curious':'Iona has kept a copy of the letter that explained why she stayed without promising a departure.', 'warm':'Iona refers to your small celebration as the evening of not packing, with increasing affection.', 'candid':'Iona returns to your difficult question. “I checked. Today I am staying because I want to, not because I am afraid to answer a letter.”'},
'aurelia': {'curious':'Aurelia recalls the reminder you discussed: her name, followed by a question she can actually answer.', 'warm':'Aurelia thanks you for keeping her request private rather than making it a lesson for the household.', 'candid':'Aurelia begins plainly: “I would like company. I decided not to make you guess.”'},
'neris': {'curious':'Neris taps the rhythm you worked out together before beginning the conversation.', 'warm':'The invented duck has acquired another verse. Neris warns you that its opinions have not improved.', 'candid':'“No lesson today,” Neris says. “I wanted to see you. That is the whole proposal.”'},

'sabine': {'curious':'Sabine shows you the plain first sentence of the apology she finally offered, without asking you to admire its elegance.', 'warm':'“Offer, not secure acceptance,” Sabine repeats. “Your distinction proved annoyingly useful.”', 'candid':'Sabine acknowledges your warning: she let the other person remain annoyed instead of trying to win a warmer response.'},
'maren': {'curious':'Maren has kept the history of the crooked detail with the repair notes, where the next maker will find it.', 'warm':'Maren makes a show of placing every tool out of reach before sitting down with you.', 'candid':'Maren has drawn two safe repair options. “You asked what I would do. I thought I should have an answer that still leaves a choice.”'},
'brakka': {'curious':'Brakka has brought a second small mechanism because you asked to understand the difficult part of the first.', 'warm':'Brakka remembers your delight more vividly than the object itself. She says so, then looks faintly embarrassed.', 'candid':'Brakka tries the direct request you agreed on: “Another subject today. I have exhausted my own patience with the strong-person jokes.”'},
'fenna': {'curious':'Fenna asks about the complicated answer you gave her before offering a new subject of her own.', 'warm':'Fenna has saved one particularly good joke. “It may wait. I learned that it will not dissolve if I ask a real question first.”', 'candid':'Fenna is relieved that honesty has not required a permanent solemn voice. The laughter and the questions now have separate room.'},
'kaede': {'curious':'Kaede remembers the unexpected move as a pleasure rather than immediately explaining how she should have prevented it.', 'warm':'Kaede proposes another game under the no-instruction-afterwards agreement, which she has apparently taken very seriously.', 'candid':'Kaede asks before offering an observation about your play. Your earlier request has become a habit she is practising.'},
'elowen': {'curious':'Elowen remembers being able to say she was disappointed without being told how to correct the feeling.', 'warm':'“That was good company,” Elowen says of your unhurried evening. She does not attach an improvement plan to it.', 'candid':'Elowen returns your earlier uncertainty with her own: “I do not have the right answer ready. I would still like to talk.”'},
'nyssara': {'curious':'Nyssara has marked the junction you discussed, including the question that made her reconsider it.', 'warm':'Nyssara admits she enjoyed being watched with interest rather than suspicion, then asks what has caught your attention today.', 'candid':'Nyssara refers to the boundary you agreed to respect and moves comfortably into a different subject.'},
'sylva': {'curious':'Sylva leaves a thought unfinished, then smiles when the silence does not demand that she complete it.', 'warm':'The bare pot remains where it was. Sylva greets you without feeling obliged to report new growth.', 'candid':'Sylva tells you directly that she wants company today. “I thought I should spare you the difficult business of interpreting a leaf.”'},
}
CATALOGUE=catalogue()
for who,branches in PERSONAL_BRANCHES.items():
    CATALOGUE[f'personal:{who}:2']['branches']=branches


EVERYDAY={
'mira':scene('The worst opening sentence','Mira has found a novel that begins with three consecutive weather reports. “By the second paragraph I knew the wind better than the protagonist.” She wants to know whether you would continue reading.',
 ('Defend the weather as a promising main character','“It has certainly shown more range.” Mira reads the next sentence in a grand tragic voice. The rain has developed an opinion.'),
 ('Invent a worse first sentence together','Your combined effort introduces a mysterious door, seven relatives and a portentous spoon. Mira insists the spoon deserves its own chapter.'),
 ('Admit you enjoy a slow beginning','Mira considers the page again. “Perhaps I wanted a different sort of evening from the author.” She lends you the argument, rather than declaring the book beyond rescue.')),
'tamsin':scene('A scandal concerning raisins','Tamsin asks whether raisins belong in a savoury loaf with the gravity of a person discussing castle law. Her tail gives away that she is enjoying the dispute before it has begun.',
 ('Ask who introduced this controversy','“Someone said everybody likes a surprise. I maintain that a surprise should not resemble an unexpected raisin.” She has evidently prepared her case.'),
 ('Declare yourself willing to conduct a very small taste trial','Her ears lift. “An admirable dedication to evidence. We should arrange one when we next bake.” For now she describes increasingly improbable test conditions.'),
 ('Defend the raisins','“Then I shall save you the controversial end.” She laughs. Your difference in taste appears likely to make future meals more entertaining.')),
'iona':scene('A city drawn from memory','Iona tries to draw a city she visited long ago and discovers that every street leads to the same bakery. “This is a reliable record of my priorities, at least.”',
 ('Ask what else she remembers about the bakery','“A bell that rang after you had already come in. The owner always said it was considering the matter.” Her map gains a delayed bell.'),
 ('Draw a place you remember beside hers','Your account follows landmarks more personal than accurate. Iona names the combined sheet an atlas of where we were paying attention.'),
 ('Ask whether either of you could navigate with this map','“Certainly. We would be lost within minutes, but extremely well prepared to discuss pastry.” She leaves it gloriously uncorrected.')),
'aurelia':scene('The bird that challenged the lantern','Aurelia describes a small bird that treated a lantern’s reflection as a rival. “It was determined. Entirely mistaken, but determined.” She then admits she saluted it before noticing anyone was watching.',
 ('Ask whether the bird accepted the salute','“It attacked the reflection again. I interpreted that as a refusal to stand down.” Her solemn expression lasts almost to the end.'),
 ('Tell her you would have liked to see it','“The bird was a more commanding presence than I was.” She tries the salute again, this time with a smile she makes no effort to hide.'),
 ('Suggest the reflection may have started it','Aurelia considers this with exaggerated fairness. “I had only one witness. My investigation was clearly incomplete.”')),
'neris':scene('A song with too many verses','Neris remembers a river song whose verses were added by every town along the water. “By the time it reached the sea, nobody could finish it before supper.” She knows three incompatible beginnings.',
 ('Ask to hear the oldest beginning she knows','She sings softly, tapping the rhythm with a finger. The words describe a boat, a missing boot and a ferryman who refuses to explain.'),
 ('Offer a verse about the castle','Neris helps fit your line into the rhythm. It scans badly until you both decide the castle is entitled to one extra beat.'),
 ('Choose the shortest version on principle','“An inland prejudice,” she says, laughing. She offers a mercifully abbreviated account in which the boot remains unexplained.')),

'sabine':scene('A truly dreadful ghost story','Sabine offers a ghost story in which the haunting consists entirely of misplaced correspondence. “The apparition was eventually accused of being an inefficient secretary.” She is waiting for your objection.',
 ('Ask what the ghost wanted','“Acknowledgement of receipt. A tragic and unfulfilled ambition.” She folds an imaginary letter with grave precision.'),
 ('Demand an appropriately melodramatic performance','Sabine supplies an excellent spectral voice and a terrible bureaucratic one. The bureaucrat is considerably more frightening.'),
 ('Defend the ghost’s right to a reply','“Then you are the sympathetic figure in this account.” She revises the ending so the correspondence finally reaches the correct desk, to general supernatural relief.')),
'maren':scene('The drawer full of almost useful things','Maren admits she keeps a drawer of pieces that might become useful. “One of them has been almost useful for six years. We have grown attached.”',
 ('Ask her to describe the oldest piece','It is a bent fitting from a toy she took apart to understand. Her account becomes less about the fitting and more about the afternoon she learned something.'),
 ('Invent improbable uses for its contents','You propose a hat for a very particular beetle. Maren improves the fastening before realising that she has accepted the entire premise.'),
 ('Ask whether almost useful is another word for keepsake','“Sometimes.” She smiles. “Please do not tell the drawer. It believes it is a professional collection.”')),
'brakka':scene('A lullaby with an alarming chorus','Brakka remembers a lullaby with a chorus about thunder. “It was meant to reassure us. I preferred the quiet verse about sheep.” Her attempt to whisper the chorus is wonderfully unsuccessful.',
 ('Ask for the sheep verse','She remembers every word and pretends to be surprised by this. The verse is gentler than the introduction led you to expect.'),
 ('Join in with whatever words you can guess','Your sheep acquire an improbable number of legs. Brakka keeps singing until the arithmetic defeats her composure.'),
 ('Suggest that thunder is a questionable bedtime strategy','“An opinion I held firmly at the time.” She says the next generation deserves a version with less weather and more sensible sheep.')),
'fenna':scene('Three rumours about a perfectly ordinary hill','Fenna offers three local explanations for a hill’s peculiar name. One involves a lost crown, one a sleeping giant and one a farmer with an unfortunate surname. “You may choose which deserves to be true.”',
 ('Choose the farmer and ask for the least glamorous details','She produces a magnificent quarrel over a fence and no treasure whatsoever. The farmer becomes oddly more memorable than the giant.'),
 ('Invent a fourth explanation together','Your hill is now named after a disastrous picnic. Fenna carefully identifies this as your addition when retelling the game to you.'),
 ('Ask which story she actually believes','“The farmer. But I would ask someone who lived there before putting it on a map.” She enjoys a story without requiring you to mistake it for evidence.')),
'kaede':scene('The dignity of falling over','Kaede recalls slipping while demonstrating an especially graceful turn. “I landed correctly,” she insists. Then, after a pause: “In a basket.”',
 ('Ask whether the basket survived','“It showed excellent structural discipline.” Her expression finally breaks. “I was less successful at remaining impressive.”'),
 ('Share an undignified mishap of your own','She listens with growing amusement and offers no corrective technique. You are exchanging stories, not incident reports.'),
 ('Argue that landing in the basket demonstrates remarkable precision','“An interpretation I wish I had thought of at the time.” She borrows it, with your permission, for any future telling.')),
'elowen':scene('An herb with no respectable purpose','Elowen names a plant she likes solely because its scent reminds her of a warm wall. “People find this disappointingly unclinical. I think walls have been undervalued.”',
 ('Ask her to describe the place she remembers','She describes stone holding the afternoon’s heat and someone talking on the other side. The plant is only the beginning of the memory.'),
 ('Tell her a scent you associate with comfort','She asks about the place attached to it rather than searching for a medicinal property. The conversation stays pleasantly personal.'),
 ('Champion the cause of unclinical pleasures','“A neglected field with excellent prospects.” She suggests that the household pursue it without creating an examination.')),
'nyssara':scene('A signature hidden in a joke','Nyssara shows you a practice flourish that resembles an excessively offended spider. “It began as a mistake. I have become rather fond of its opinion.”',
 ('Ask what offended the spider','“Poor spacing. Unjustified confidence. Possibly the entire preceding sentence.” Her dry delivery suggests the spider has inherited its maker’s tastes.'),
 ('Draw an equally opinionated creature beside it','She examines your contribution as though assessing a serious commission, then adds a tiny chair so the creatures may argue comfortably.'),
 ('Suggest keeping it out of official instructions','“Naturally. I cannot have the spider taking responsibility for work it has not reviewed.” She keeps the doodle for company instead.')),
'sylva':scene('The most interesting patch of wall','Sylva asks whether you have noticed a small patch of lichen. “It looks like a very important person in a very bad hat. I have been waiting to tell someone.”',
 ('Ask to hear the important person’s imaginary complaints','The hat is damp, the wall is unfashionable and passing birds are insufficiently respectful. Sylva gives the lichen a surprisingly imperious voice.'),
 ('Offer another shape you can see in it','Your interpretation changes the hat into a boat. Sylva turns her head and laughs. “Now I cannot unsee it. You have demoted a dignitary into transport.”'),
 ('Admit that you only see lichen','“Then I shall enjoy having a private acquaintance.” She does not insist that you see what she sees, but is pleased you looked.')),
}
for who,d in EVERYDAY.items():
    CATALOGUE[f'everyday:{who}']={**d,'participants':[who],'category':'everyday','arc':who,'stage':0,'previous':None}
