"""Velis: authored dark elf broker, resident and companion."""
from copy import deepcopy

def register(g):
 import party_journey_content as journey
 import local_encounters as local,living_stories as life,resident_specialties as rs,character_quest_content as quests,household_chapter_content as home,romance_content as romance,romance as love,companion_almanac_content as almanac,customization_content as custom,signature_equipment as sig,outfit_progression as outfits,art_catalogue
 journey.CAST.append('velis')
 journey.CAMPS['velis']=('No invoice for the evening','Velis settles beside you with two cups. “I know I said I would check the supplies. They can manage without me for a little while.”','Velis asks which meal you missed most on the road. You compare disastrous camp suppers until she admits she once paid extra for a pear just to avoid another stew.')
 journey.VOICES['velis']=('Every name belongs to someone. I am glad we kept the list intact.','A safe route is a promise you have to maintain, not merely draw.','Let us make sure the people who did this work are remembered with it.')
 home.SPECIALIST_VOICES['velis']=('“A standing agreement should still work on the morning I take off.”','“Four provisions, no invoice. Both copies say so.”','“The deliveries came while I was having tea. Precisely the arrangement I wanted.”')
 home.ACTIVITIES['supply-office']={'title':'Close the ledger together','opening':'Velis puts the day’s paperwork aside and pours two cups. The receiving window can wait.','view':'stores','use':'Review shared supplies whenever you choose. Conversation spends no food or time.'}
 almanac.PAIRS.append(('velis','tamsin','What a supper is worth',[
  ('The name on the sack','Velis describes the grower who supplied the flour. Tamsin asks what she likes to eat herself.','Velis answers the personal question; Tamsin saves her a plate.'),
  ('A sensible surplus','Tamsin worries about ordering more than they use. Velis suggests a small standing delivery with an easy pause.','They settle on a modest pantry target and keep the plan adjustable.'),
  ('A meal off the books','The ledger is closed before supper. Tamsin asks Velis to stay at the table instead of checking the crates.','Velis stays. The accounts can wait until morning.')]))
 local.PEOPLE['velis']={'name':'Velis','age':22,'ancestry':'Dark elf','background':'courier','temperament':'poised','story':'route-notes','occupation':'caravan broker','place':'The Hollow Road caravan','lead':'The overdue wagon carries a dark elf broker who puts people before invoices.','unlock':'Complete the Chapter 6 caravan rescue and return home.','greeting':'“Velis. Both copies should say the same thing. You would be surprised how controversial that makes me.” She closes her ledger. “Thank you for bringing everyone home.”','appearance':'Clearly adult dark elf woman with warm dusky plum-brown skin, amber eyes, long dark auburn hair, long pointed ears, fit softly curving figure. Teal fitted waistcoat over an ivory blouse, charcoal trousers and worn boots.','origin':'An independent dark elf caravan broker from the wooded western trade towns. She settled the wagon dispute without charging either innocent party.','ambition':'Establish a supply office with reliable deliveries, fair accounts and enough staff to let her take a day off.'}
 life.ROUTINES['velis']={'morning':['supply-office','common-room'],'afternoon':['kitchen','conservatory','supply-office'],'evening':['common-room','chapel','bedroom']}
 life.GREETINGS['velis']='“The ledger is closed. Any attention you receive now is entirely personal.”'
 life.CHAINS['velis']=life.chain('supply-office','A drawer left empty','Velis has labelled every drawer except one. “For something I did not anticipate. I am trying to become less professionally offended by surprises.”',{'space':('Leave room for surprises','“A sound policy with dangerously little paperwork.”'),'tea':('Suggest a place for her favourite cup','“You have found an excellent use for uncertainty.”')},'The drawer now holds a cup and a folded letter, neither entered in the stock book.',{'space':'“Not everything needs an account.”','tea':'“I kept a second cup. A calculated risk.”'},'“Perhaps I can stay without having to justify every inch I occupy.”',{'stay':('Tell her her company is enough','She lets that answer stand without offering anything in exchange.'),'listen':('Ask what staying would mean to her','“Having plans that include tomorrow morning, even when there is no delivery.”')})
 rs.NAMES['velis']='Velis';rs.SPECIALTIES['velis']=rs.specialty('velis','supply-office','Velis’s standing provision contract',24,'Four free provisions arrive each morning up to your pantry target. No assignment or crown charge. Optional paid top-ups are configured separately.');rs.register()
 quests.PERSONAL['velis']=('Both copies agree','settle a disputed delivery and choose what belonging means','cipher','bargain','Velis asks you to compare two copies of a shipment record. “If we make the porter pay for somebody else’s error, we have balanced nothing.”','The missing entry is found. The supplier offers her a permanent post elsewhere. “I want to choose where I live for more than the quality of its filing system.”','The porter receives a corrected account. Velis leaves her travelling case unpacked for one more evening, this time by choice.','“No, this is not a negotiation.” Her smile warms. “I wanted your company before I thought of an excuse.”')
 b=home.beat
 home.PROFILES['velis']={'room':'supply-office','activity':'maps','relaxed':'“I can take off the travelling layers without being ready to leave.”','daring':'“I chose this for an evening with you. The attention is quite intentional.”','thanks':'“Good. I would rather be noticed than appraised.”','tease':'“An unusually persuasive offer of company.”','beats':[
 b('The porter’s tea recipe', 'Velis pours spiced pear tea. “A porter gave me this blend after I delayed a wagon so he could reach his family. It cost me a profitable departure. I still think I chose well.”', '“Yes. His next letter was mostly about the baby. I kept the tea instructions on the back.”', '“Only the recipe. I was unusually restrained.” She pours a little more into your cup.', 'Ask whether he made it home in time', 'Ask whether she negotiated a lifetime tea supply'),
 b('The wedding letter', 'Velis opens a letter without an invoice attached. “A supplier sent news of her daughter’s wedding. I know every number in our account and had forgotten to ask the date.”', '“Congratulations, a proper question about the ceremony, and no mention of delivery schedules.” She pushes the ledger aside.', '“Please do. If I write ‘favourable terms’, take the pen away.”', 'Ask what she plans to write back', 'Offer to prevent any accidental price negotiations'),
 b('An empty appointment', 'Velis has crossed one appointment out of tomorrow’s diary. “It was unnecessary. I arranged it because a blank line made me feel idle.”', '“Walk somewhere without checking the road surface. Possibly buy a pear just because I want one.”', '“You would give it a heading.” She considers the blank line. “No. I am leaving it empty.”', 'Ask what she wants to do with the time', 'Suggest scheduling an official hour of idleness'),
 b('The unpacked travelling bag', 'Velis’s travelling bag is unpacked. “I used to keep everything ready in case staying became inconvenient. Now I keep losing my comb because it has a drawer.”', '“More often than not. The missing comb is surprisingly convincing evidence.”', '“A terrible bargain. I would have stayed anyway.” She draws up a second chair.', 'Ask whether the castle feels like home', 'Offer to help her search if she stays for tea')]}
 home.PERSPECTIVES['velis']='“A promise should leave room for the person making it.”'
 home.PAIRS.extend([
 ('velis','tamsin','kitchen','A spice worth the detour','Velis offers an unusual spice. Tamsin asks whether she has actually tasted it.','Try a small batch together','They settle on a small pot and reserve judgement until supper.','Ask about its source','Velis describes the grower; Tamsin writes down her name.','The supper with a name','The recipe credits its grower. Velis asks for seconds before anyone mentions trade.'),
 ('velis','fenna','common-room','Two kinds of reliable','Fenna marks a safe shortcut. Velis marks the innkeeper who opens early.','Combine their notes','The route now includes a friendly breakfast stop.','Ask which matters in bad weather','They agree that a dependable door matters as much as distance.','A road with people on it','Their joint notes list both the crossing and the person who maintains it.')])
 romance.SCENES['velis']=[
 ('An offer without terms','“I like you. I would rather say that clearly than invent another delivery to discuss.”','You return her interest. “Good. That is the whole agreement. We can work out dinner together.”'),
 ('The ledger stays closed','Velis invites you to an evening with no errands. “Would you like to kiss me before we start pretending to discuss the weather?”','You agree, and she leans in for a warm, unhurried kiss. The forecast goes unmentioned.'),
 ('An address of her own','“I want the ordinary days with you, too. Shall we call ourselves partners?”','You agree. She takes your hand. “Then let us keep asking, rather than assuming we already know.”'),
 ('Nothing owed','“Stay tonight? Not because either of us has earned it. Because we would enjoy it.”','You draw close and share a kiss. The door closes on the workday; the rest of the evening belongs to you both.')]
 love.GREETINGS['velis']='“There you are. Entirely worth closing the ledger for.”'
 custom.PROFILES['velis']=('teal','stargazing','spiced pear tea','supply-office','a pressed roadside flower','“I remember people by what they are pleased to tell me.”','“The invitation is personal. Delightfully little paperwork.”')
 almanac.PHYSICAL['velis']=(169,63,(96,70,99),'Fit, softly curved, with an easy, assured posture.','Her ancestry does not prescribe her shape; these details describe Velis.')
 almanac.PERSONAL['velis']=dict(hand='Right',habit='Checks both copies, then puts the ledger away.',history='She once delayed a profitable departure to help a porter reach his family.',comfort='Spiced pear tea, warm lamplight and a morning without appointments.',worry='People may value her contacts more than her company.',attraction='Plain promises, humour and attention without an ulterior request.',turnoff='Treating affection as a debt or assuming every kindness has a price.',affection='Remembering small preferences and making time that belongs to nobody else.',private='She enjoys a perceptive compliment and being invited to leave the workday behind.',initiative=('A cup that arrived for you','Velis sets down two cups. “No commission attached. I simply remembered how you take yours.”','supply-office'),idle=('Closing the ledger before someone has to ask.','Turning an old brass clasp between her fingers.','Reading a letter twice, smiling at the same line.'))
 sig.ROOMS['velis']='supply-office';sig.CONTENT['velis']=('The road-weight staff','Fit the balance where my hand expects it. I want a walking staff I can trust when the road changes underneath me.','The mark is exactly where I reach for it. Thank you for listening to the unremarkable part.','balance')
 outfits.CATALOGUE['velis']={'2':{'id':'velis-outfit-2','name':'The last delivery is in','description':'Opaque cropped teal wrap top, charcoal knee-length side-slit skirt, oxblood belt and ankle boots.'},'3':{'id':'velis-outfit-3','name':'An evening without terms','description':'Opaque short deep-teal halter dress, covered low neckline, side waist cutouts, bare legs and ankle-strap sandals.'}}
 for suffix in ('','-outfit-2','-outfit-3'):
  key='velis'+suffix;g['ORIGINAL_ASSETS'][key]='/assets/portraits/'+key+'.webp';g['ORIGINAL_ASSETS']['overview-'+key]='/assets/portraits/overview/'+key+'.webp'
  art_catalogue.ART_ASSETS[key]=g['ORIGINAL_ASSETS'][key];art_catalogue.ART_ASSETS['overview-'+key]=g['ORIGINAL_ASSETS']['overview-'+key]
