// Headless template and controller integration checks; not browser/layout QA.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const vm = require('node:vm');
const {execFileSync} = require('node:child_process');
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'castle-ui-'));
const elements = new Map();
const events = {};
function element(id) {
  if (!elements.has(id)) elements.set(id, {innerHTML:'',textContent:'',classList:{add(){},remove(){}},addEventListener(type, callback){events[type]=callback;},showModal(){this.open=true;}});
  return elements.get(id);
}
let dropCreationResponse = false;
const bridge = `import json,sys\nfrom server import CampaignLibrary\nfrom dialogue import ProviderSettings,DialogueService\nfrom game import public_state\nfrom urllib.parse import urlsplit,parse_qs\nlibrary=CampaignLibrary(sys.argv[1])\nurl=urlsplit(sys.argv[2])\npayload=json.load(sys.stdin)\ntry:\n if url.path=='/api/provider':\n  settings=ProviderSettings(sys.argv[1])\n  result=settings.save(payload) if payload else settings.public()\n elif url.path=='/api/dialogue/drafts':\n  store=library.get(parse_qs(url.query).get('campaign',['default'])[0])\n  with store.connect() as db:\n   result={'drafts':[json.loads(row[0]) for row in db.execute('SELECT result FROM dialogue_drafts ORDER BY rowid DESC LIMIT 8')]}\n elif url.path in ('/api/dialogue/draft','/api/dialogue/accept'):\n  store=library.get(parse_qs(url.query).get('campaign',['default'])[0])\n  service=DialogueService(ProviderSettings(sys.argv[1]),lambda settings,messages:{'text':json.dumps({'formId':'warm-twist','name':'<Cord suggestion>','explanation':'Bind plant fibres into cord.','limitations':['No powers beyond the listed effect.']}) if 'Suggest a bounded spell construction' in messages[0]['content'] else 'A generated <reply> with quiet wit.','usage':{'total_tokens':17}})\n  result=service.generate(store,payload) if url.path.endswith('/draft') else public_state(service.accept(store,payload))\n elif url.path=='/api/campaigns':\n  result=library.create(payload) if payload else {'campaigns':library.list()}\n else:\n  store=library.get(parse_qs(url.query).get('campaign',['default'])[0])\n  result=public_state(store.action(payload) if payload else store.read())\n print(json.dumps(result))\nexcept Exception as error:\n print(json.dumps({'error':str(error)}))`;
const context = vm.createContext({
  FormData:class {constructor(form){this.fields=form.fields;} get(name){return this.fields[name]??null;}},
  console, URLSearchParams, crypto:require('node:crypto').webcrypto,
  setTimeout(){return 0;},clearTimeout(){},
  document:{querySelector(selector){return selector==='.dialogue-history'?null:element(selector);},body:element('body')},
  window:{scrollTo(){}},location:{reload(){}},
  fetch:async(url, options)=>{
    const body = options?.body || '{}';
    const json=JSON.parse(execFileSync(process.env.PYTHON || 'python', ['-c',bridge,directory,url], {input:body, encoding:'utf8',maxBuffer:32*1024*1024}));
    if(url==='/api/campaigns' && options?.method==='POST' && dropCreationResponse) {dropCreationResponse=false;throw new Error('Simulated lost response');}
    return {ok:!json.error,async json(){return json;}};
  }
});
(async()=>{
  try {
    vm.runInContext(fs.readFileSync('static/app.js','utf8'),context);
    await new Promise(resolve=>setImmediate(resolve));
    assert.match(element('#app').innerHTML,/The living wing/);
    for (const page of ['castle','ledger','workroom','housing','contacts','spells','rituals','summoning','development','focus','room','household','conversation','wardrobe','research','restoration','workshop','stores','requests','expeditions','resonance','journal','review','settings']) {
      vm.runInContext(`setView('${page}')`,context);
      assert(!element('#app').innerHTML.includes('undefined'),`${page} contains undefined data`);
      assert.match(element('#app').innerHTML,/<main/);
    }
    const click=dataset=>events.click({target:{closest(){return {dataset,disabled:false};}}});
    const clickRendered=async(attribute,value)=>{
      if(attribute==='data-character' && !element('#app').innerHTML.includes(`data-character="${value}"`) && element('#app').innerHTML.includes('id="ui-person-switch"')) {
        const select=element('#app').innerHTML.match(/<select id="ui-person-switch">([\s\S]*?)<\/select>/)[1];
        assert(select.includes(`value="${value}"`),'Character must be offered by the visible switcher');
        return events.change({target:{id:'ui-person-switch',value}});
      }
      if(attribute==='data-view' && !element('#app').innerHTML.includes(`data-view="${value}"`)) {
        const hub=value==='journal'?'storyJournal':vm.runInContext(`Object.keys(SYSTEM_GROUPS).find(k=>SYSTEM_GROUPS[k].views.some(v=>v[0]===${JSON.stringify(value)}))`,context);
        if(hub)await clickRendered('data-view',hub);
      }
      const button=[...element('#app').innerHTML.matchAll(/<button\b[^>]*>/g)].map(match=>match[0]).find(markup=>markup.includes(`${attribute}="${value}"`));
      assert(button,`Missing visible control: ${attribute}=${value}`);
      assert(!/\sdisabled(?:[\s=>])/.test(button),`Disabled control: ${attribute}=${value}`);
      const dataset={};
      for(const match of button.matchAll(/data-([a-z-]+)="([^"]*)"/g)) dataset[match[1].replace(/-([a-z])/g,(_,letter)=>letter.toUpperCase())]=match[2];
      await click(dataset);
    };
    const submitCraft=async()=>{
      const markup=element('#app').innerHTML.match(/<form id="craft-form">([\s\S]*?)<\/form>/)?.[1];
      assert(markup,'The real workshop template must contain the crafting form');
      assert(!/<button[^>]*disabled/.test(markup),'Craft button should be enabled');
      const fields={recipeId:markup.match(/name="recipeId" value="([^"]+)"/)[1],crafterId:markup.match(/name="crafterId" value="([^"]+)"/)[1]};
      for(const field of ['firstComponent','secondComponent']) {
        const select=markup.match(new RegExp('<select[^>]*name="'+field+'"[^>]*>([\\s\\S]*?)<\\/select>'))[1];
        const selected=select.match(/<option value="([^"]+)"[^>]*selected[^>]*>/);
        assert(selected,'An owned material must be explicitly selected for '+field);
        assert(!selected[0].includes('disabled'));
        fields[field]=selected[1];
      }
      return events.submit({preventDefault(){},target:{id:'craft-form',fields}});
    };
    vm.runInContext("setView('workshop')",context);
    assert.match(element('#app').innerHTML,/Before you can craft/);
    assert.match(element('#app').innerHTML,/Open hearth research/);

    await click({room:'library'});
    assert.match(element('#app').innerHTML,/Research|A little knowledge/);
    await click({furnishing:'violet-lamp'});
    assert.equal(vm.runInContext("state.roomFurnishings.library",context),'violet-lamp');
    vm.runInContext("setView('wardrobe')",context);
    await click({layer:'plum-shawl'});
    assert.match(element('#app').innerHTML,/mira.webp/);
    await click({action:'invitation'});
    assert.match(element('#app').innerHTML.replace(/<[^>]*>/g,''),/A moment with Mira/);
    assert.equal(vm.runInContext('state.resonancePoints',context),2);
    await click({topic:'flirt'});
    assert.equal(vm.runInContext('state.resonancePoints',context),2);
    await vm.runInContext("commit({type:'free-text',text:'<img src=x onerror=alert(1)>'},'')",context);
    assert.match(element('#app').innerHTML,/&lt;img src=x onerror=alert\(1\)&gt;/);
    assert(!element('#app').innerHTML.includes('<img src=x'));
    await click({action:'start-research'});
    await click({action:'advance'});
    assert.equal(vm.runInContext('state.researchCompletedPhases',context),1);
    assert.equal(vm.runInContext('state.currentDayPhase',context),'evening');
    assert.equal(element('#advance-dialog').open,true);
    await click({action:'start-restoration'});
    await click({resident:'archive'});
    for (let i=0;i<3;i++) await click({action:'advance'});
    assert.equal(vm.runInContext('state.restorationStatus',context),'complete');
    assert.equal(vm.runInContext('state.researchStatus',context),'complete');
    await click({room:'conservatory'});
    assert.match(element('#app').innerHTML,/Choose what the garden provides/);
    assert.match(element('#app').innerHTML,/NOT YET CRAFTED/);
    assert.match(element('#app').innerHTML,/data-recipe="watering-charm">Craft a Self-watering charm/);
    await click({resident:'garden'});
    await click({action:'advance'});
    assert.equal(vm.runInContext("state.materialInventory['silver-ivy']",context),1);
    await click({production:'surplus-sales'});
    const funds=vm.runInContext('state.sharedFunds',context);
    await click({action:'advance'});
    assert.equal(vm.runInContext('state.sharedFunds',context),funds+4);
    vm.runInContext("setView('workshop')",context);
    assert.match(element('#app').innerHTML,/Ready to craft/);
    await submitCraft();
    assert.match(element('#app').innerHTML,/Crafting is underway/);
    await click({action:'advance'});await click({action:'advance'});
    assert.equal(vm.runInContext("state.craftedArtifacts['warming-lantern']",context),1);
    await click({action:'display-lantern'});
    await click({room:'common-room'});
    assert.match(element('#app').innerHTML,/Warm household light; no numerical bonus while displayed here/);
    assert(!element('#app').innerHTML.includes('artifact-lantern'));
    vm.runInContext("setView('expeditions')",context);
    assert.match(element('#app').innerHTML,/The old waterworks/);
    element('#carry-lantern').checked=true;
    await click({action:'start-expedition'});
    assert.match(element('#app').innerHTML.replace(/<[^>]*>/g,''),/Party away/);
    await click({action:'advance'});
    assert.match(element('#app').innerHTML,/A choice at the sluice house/);
    await click({approach:'survey'});
    await click({action:'advance'});
    await click({action:'return-expedition'});
    await click({action:'advance'});
    assert.equal(vm.runInContext("state.archivePrinciples.includes('water-guidance')",context),true);
    await click({recipe:'watering-charm'});
    assert.match(element('#app').innerHTML,/Porous clay/);
    await click({buy:'porous-clay'});
    await submitCraft();
    await click({action:'advance'});await click({action:'advance'});
    await click({room:'conservatory'});
    assert.match(element('#app').innerHTML,/READY TO INSTALL/);
    assert.match(element('#app').innerHTML,/<button class="primary" data-action="install-watering-charm">Install Self-watering charm/);
    const placementTime=vm.runInContext('`${state.dayNumber}:${state.currentDayPhase}`',context);
    await click({action:'install-watering-charm'});
    assert.equal(vm.runInContext('state.wateringCharmInstalled',context),true);
    assert.match(element('#app').innerHTML,/INSTALLED/);
    assert.match(element('#app').innerHTML,/Remove Self-watering charm/);
    assert.match(element('#app').innerHTML,/Sell designated surplus · \+6 crowns/);
    await click({action:'install-watering-charm'});
    assert.equal(vm.runInContext('state.wateringCharmInstalled',context),false);
    assert.match(element('#app').innerHTML,/READY TO INSTALL/);
    assert.match(element('#app').innerHTML,/Sell designated surplus · \+4 crowns/);
    assert.equal(vm.runInContext('`${state.dayNumber}:${state.currentDayPhase}`',context),placementTime);
    // The whole new loop goes through visible controls and the real save layer.
    await clickRendered('data-view','ledger');
    assert.match(element('#app').innerHTML,/The household ledger/);
    await clickRendered('data-facility','washroom');
    await clickRendered('data-action','advance');
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext("state.facilityProjects.washroom.status",context),'complete');
    await clickRendered('data-recipe','hearth-kettle');
    await clickRendered('data-buy','porous-clay');
    await submitCraft();
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    await clickRendered('data-view','ledger');
    await clickRendered('data-install-artifact','hearth-kettle');
    assert.match(element('#app').innerHTML,/Remove Hearth kettle/);
    await clickRendered('data-facility','kitchen');
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    await clickRendered('data-facility','service-wards');
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.livingWingCelebration',context),'available');
    assert.match(element('#advance-content').innerHTML,/Milestone: A Proper Living Wing/);
    const celebrationPhase=vm.runInContext('`${state.dayNumber}:${state.currentDayPhase}`',context);
    await clickRendered('data-action','celebrate-living-wing');
    assert.match(element('#app').innerHTML,/in danger of becoming respectable/);
    assert.equal(vm.runInContext('`${state.dayNumber}:${state.currentDayPhase}`',context),celebrationPhase);
    assert.equal(vm.runInContext('state.livingWingCelebration',context),'completed');
    await clickRendered('data-view','expeditions');
    await clickRendered('data-site','reedbank-waystation');
    assert.match(element('#app').innerHTML,/Study the storage seals/);
    element('#carry-lantern').checked=true;
    await clickRendered('data-action','start-expedition');
    assert.equal(vm.runInContext('state.expedition.siteId',context),'reedbank-waystation');
    await clickRendered('data-action','advance');
    await clickRendered('data-approach','survey');
    await clickRendered('data-action','advance');
    await clickRendered('data-action','return-expedition');
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext("state.founderKnownPrinciples.includes('gentle-preservation')",context),true);
    await clickRendered('data-recipe','pantry-seal');
    await clickRendered('data-buy','porous-clay');
    await clickRendered('data-buy','binding-thread');
    await submitCraft();
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    await clickRendered('data-view','ledger');
    await clickRendered('data-install-artifact','pantry-seal');
    assert.match(element('#app').innerHTML,/Remove Pantry seal/);
    await clickRendered('data-view','castle');
    await clickRendered('data-room','conservatory');
    await clickRendered('data-action','install-watering-charm');
    assert.match(element('#app').innerHTML,/Sell designated surplus · \+8 crowns/);
    const upgradedFunds=vm.runInContext('state.sharedFunds',context);
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.sharedFunds',context),upgradedFunds+8);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext("state.householdArtifactPlacements['pantry-seal']",context),true);
    assert.equal(vm.runInContext('state.livingWingCelebration',context),'completed');
    await clickRendered('data-view','ledger');
    const beforeCopying=vm.runInContext('state.sharedFunds',context);
    await clickRendered('data-founder','commissions');
    await clickRendered('data-resident','rest');
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.sharedFunds',context),beforeCopying+4);
    await clickRendered('data-view','development');
    await clickRendered('data-character','mira');
    await clickRendered('data-prepare','archive-focus');
    await clickRendered('data-ui-character-tab','quests');
    assert.match(element('#app').innerHTML,/An archive worth getting lost in/);
    await clickRendered('data-action','start-archive-project');
    await clickRendered('data-founder','archive-project');
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.miraArchiveProject.status',context),'ready-to-bind');
    await clickRendered('data-recipe','index-charm');
    await clickRendered('data-maker','mira');
    await clickRendered('data-buy','porous-clay');
    await clickRendered('data-buy','binding-thread');
    await submitCraft();
    assert.equal(vm.runInContext('state.craftingProject.crafterId',context),'mira');
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    await clickRendered('data-room','library');
    await clickRendered('data-action','install-index-charm');
    assert.match(element('#app').innerHTML,/Remove living index charm/);
    await clickRendered('data-character','mira');
    await clickRendered('data-ui-character-tab','quests');
    await clickRendered('data-action','finish-archive-story');
    assert.match(element('#app').innerHTML,/ask me along/);
    await clickRendered('data-view','development');
    await clickRendered('data-train','careful-assembly');
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    await clickRendered('data-prepare','careful-assembly');
    await clickRendered('data-train','field-notes');
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    await clickRendered('data-prepare','archive-focus');
    await clickRendered('data-prepare','field-notes');
    assert.equal(vm.runInContext('state.characterSheets.mira.preparedPractices.length',context),2);
    await clickRendered('data-view','expeditions');
    await clickRendered('data-site','hillfold-bindery');
    element('#carry-lantern').checked=false;
    await events.change({target:{id:'journey-party-mira',checked:true}});
    await clickRendered('data-action','start-expedition');
    assert.equal(vm.runInContext('state.expedition.companionId',context),'mira');
    assert.equal(vm.runInContext('state.residentRoomId',context),null);
    // Every view must remain usable while the only resident is out with the party.
    for (const page of ['castle','ledger','workroom','housing','contacts','spells','rituals','summoning','development','focus','room','household','conversation','wardrobe','research','restoration','workshop','stores','requests','expeditions','resonance','journal','review','settings']) {
      await click({view:page});
      assert(!element('#app').innerHTML.includes('undefined'),`${page} contains undefined while Mira is away`);
    }
    await clickRendered('data-view','expeditions');
    await clickRendered('data-action','advance');
    await clickRendered('data-approach','survey');
    assert.equal(vm.runInContext('state.expedition.remainingWorkPhases',context),1);
    await clickRendered('data-action','advance');
    await clickRendered('data-action','return-expedition');
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext("state.materialInventory['moon-glass']",context),2);
    assert.equal(vm.runInContext('state.residentAtCastle',context),true);
    await clickRendered('data-view','development');
    await clickRendered('data-character','founder');
    await clickRendered('data-train','archive-focus');
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    await clickRendered('data-prepare','archive-focus');
    assert.equal(vm.runInContext('state.copyingIncomePerPhase',context),6);
    await clickRendered('data-action','start-training-reset');
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.characterSheets.founder.investedAdvancement',context),0);
    assert.equal(vm.runInContext("state.founderKnownPrinciples.includes('reference-binding')",context),true);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.miraArchiveProject.status',context),'complete');
    assert.equal(vm.runInContext('state.libraryIndexInstalled',context),true);
    // Research branches feed real recipes and room-level installation controls.
    const finishWork=async(expression,limit=8)=>{
      for(let phase=0;vm.runInContext(expression,context);phase++) {
        assert(phase<limit,'Work should finish within its displayed bound');
        await clickRendered('data-action','advance');
      }
    };
    for(const [researchId,recipeId,components,room] of [
      ['root-rhythms','root-tender',['silver-ivy','porous-clay'],'conservatory'],
      ['luminous-impressions','scribe-stone',['sun-amber','porous-clay'],'library'],
      ['shared-lessons','lesson-tablet',['porous-clay','binding-thread'],'library'],
    ]) {
      await clickRendered('data-view','research');
      await clickRendered('data-research',researchId);
      await finishWork('state.activeResearchId !== null');
      await clickRendered('data-recipe',recipeId);
      await clickRendered('data-maker','founder');
      for(const component of components) await clickRendered('data-buy',component);
      await submitCraft();
      await finishWork('state.craftingProject !== null');
      await clickRendered('data-view','castle');
      await clickRendered('data-room',room);
      await clickRendered('data-utility',recipeId);
      assert.equal(vm.runInContext(`state.utilityArtifactPlacements['${recipeId}']`,context),true);
    }
    await clickRendered('data-view','stores');
    const ivyBefore=vm.runInContext("state.materialInventory['silver-ivy']",context);
    assert.match(element('#app').innerHTML,/<form id="reserve-silver-ivy"/);
    await events.submit({preventDefault(){},target:{id:'reserve-silver-ivy',fields:{target:String(ivyBefore+2)}}});
    assert.equal(vm.runInContext("state.materialReserveTargets['silver-ivy']",context),ivyBefore+2);
    await clickRendered('data-room','conservatory');
    await clickRendered('data-production','stock-first');
    assert.equal(vm.runInContext('state.gardenForecast.automated',context),true);
    assert.equal(vm.runInContext('state.gardenForecast.output',context),'silver-ivy');
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext("state.materialInventory['silver-ivy']",context),ivyBefore+2);
    assert.equal(vm.runInContext('state.gardenForecast.output',context),'surplus-sales');
    const automatedFunds=vm.runInContext('state.sharedFunds',context);
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.sharedFunds',context),automatedFunds+2);
    assert.equal(vm.runInContext("state.materialInventory['silver-ivy']",context),ivyBefore+2);
    await clickRendered('data-view','development');
    await clickRendered('data-character','mira');
    await clickRendered('data-study','steady-growth');
    assert.equal(vm.runInContext('state.trainingProjects.mira.requiredWorkPhases',context),1);
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext("state.residentKnownPrinciples.includes('steady-growth')",context),true);
    await clickRendered('data-view','stores');
    const orderMarkup=element('#app').innerHTML.match(/<form id="work-order-form">([\s\S]*?)<\/form>/)[1];
    const orderFields={};
    for(const field of ['recipeId','crafterId','firstComponent','secondComponent']) {
      const select=orderMarkup.match(new RegExp('<select[^>]*name="'+field+'"[^>]*>([\\s\\S]*?)<\/select>'))[1];
      orderFields[field]=select.match(/<option value="([^"]+)"[^>]*selected[^>]*>/)[1];
    }
    assert.match(orderMarkup,/<option value="fireglass"/);
    assert.match(orderMarkup,/<option value="binding-thread"/);
    orderFields.firstComponent='fireglass';orderFields.secondComponent='binding-thread';orderFields.requestedCount='2';
    const orderFunds=vm.runInContext('state.sharedFunds',context);
    const lanternsBefore=vm.runInContext("state.craftedArtifacts['warming-lantern']",context);
    await events.submit({preventDefault(){},target:{id:'work-order-form',fields:orderFields}});
    assert.equal(vm.runInContext('state.sharedFunds',context),orderFunds);
    assert.equal(vm.runInContext('state.workOrders.length',context),1);
    for(let copy=1;copy<=2;copy++) {
      const cost=vm.runInContext('state.workOrderViews[0].purchaseCostCrowns',context);
      if(cost) {
        const before=vm.runInContext('state.sharedFunds',context);
        await clickRendered('data-order-buy','order-1');
        assert.equal(vm.runInContext('state.sharedFunds',context),before-cost);
      }
      await clickRendered('data-order-start','order-1');
      assert.equal(vm.runInContext('state.craftingProject.workOrderId',context),'order-1');
      await finishWork('state.craftingProject !== null');
      assert.equal(vm.runInContext('state.workOrders[0].completedCount',context),copy);
      if(copy===1) {
        await clickRendered('data-action','advance');
        assert.equal(vm.runInContext('state.workOrders[0].completedCount',context),1);
        assert.equal(vm.runInContext('state.craftingProject',context),null);
      }
    }
    await clickRendered('data-order-remove','order-1');
    assert.equal(vm.runInContext("state.craftedArtifacts['warming-lantern']",context),lanternsBefore+2);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.workOrders.length',context),0);
    assert.equal(vm.runInContext("state.utilityArtifactPlacements['root-tender']",context),true);
    assert.equal(vm.runInContext("state.materialReserveTargets['silver-ivy']",context),ivyBefore+2);
    // Real rendered requests -> delivery -> route -> survey -> new recipe -> installation.
    await clickRendered('data-view','requests');
    assert.match(element('#app').innerHTML,/A lamp for the footbridge/);
    await clickRendered('data-request-accept','brook-lamps');
    await clickRendered('data-request-defer','brook-lamps');
    await clickRendered('data-request-accept','brook-lamps');
    await clickRendered('data-view','workshop');
    for(let i=0;vm.runInContext("state.materialInventory['binding-thread'] < 2",context);i++) {
      assert(i<3);await clickRendered('data-buy','binding-thread');
    }
    await clickRendered('data-view','requests');
    const beforeDelivery=vm.runInContext('state.sharedFunds',context);
    await clickRendered('data-request-deliver','brook-lamps');
    assert.equal(vm.runInContext('state.sharedFunds',context),beforeDelivery+24);
    assert.equal(vm.runInContext("state.siteAccess['fern-nursery']",context),true);
    assert.match(element('#app').innerHTML,/lamp holds its warmth/);
    await clickRendered('data-household-scene','first-letter');
    assert.match(element('#app').innerHTML,/An archive should remember/);
    await clickRendered('data-view','requests');
    await clickRendered('data-site','fern-nursery');
    element('#carry-lantern').checked=false;
    await events.change({target:{id:'journey-party-mira',checked:true}});
    await clickRendered('data-action','start-expedition');
    await clickRendered('data-action','advance');
    await clickRendered('data-approach','survey');
    await finishWork("state.expedition.stage === 'working'");
    assert.equal(vm.runInContext("state.archivePrinciples.includes('capillary-wicking')",context),false);
    await clickRendered('data-action','return-expedition');
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext("state.characterSheets.mira.knownPrinciples.includes('capillary-wicking')",context),true);
    await clickRendered('data-view','workshop');
    await clickRendered('data-recipe','capillary-mat');
    await clickRendered('data-maker','founder');
    await clickRendered('data-buy','silver-ivy');
    await clickRendered('data-buy','binding-thread');
    await submitCraft();
    await finishWork('state.craftingProject !== null');
    await clickRendered('data-view','castle');
    await clickRendered('data-room','conservatory');
    await clickRendered('data-utility','capillary-mat');
    assert.equal(vm.runInContext("state.utilityArtifactPlacements['capillary-mat']",context),true);
    await clickRendered('data-gardener','mira');
    await clickRendered('data-production','silver-ivy');
    assert.match(element('#app').innerHTML,/Keep binding plants · \+3 silver ivy/);
    assert.equal(vm.runInContext('state.gardenForecast.amount',context),3);
    await clickRendered('data-view','requests');
    await clickRendered('data-request-accept','nursery-exchange');
    assert.match(element('#app').innerHTML,/Need 1 spare capillary mat/);
    const blocked=[...element('#app').innerHTML.matchAll(/<button\b[^>]*>/g)].find(match=>match[0].includes('data-request-deliver="nursery-exchange"'));
    assert.match(blocked[0],/disabled/);
    await clickRendered('data-household-scene','green-fingers');
    assert.match(element('#app').innerHTML,/stay a little closer/i);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext("state.neighbourRequestProgress['brook-lamps'].status",context),'delivered');
    assert.equal(vm.runInContext("state.completedHouseholdScenes.length",context),2);
    assert.equal(vm.runInContext("state.utilityArtifactPlacements['capillary-mat']",context),true);
    // Personal focus forms commit real components; upgrades and preparations persist.
    await clickRendered('data-view','workshop');
    await clickRendered('data-founder','commissions');
    for(let i=0;vm.runInContext('state.sharedFunds < 90',context);i++) {
      assert(i<30);await clickRendered('data-action','advance');
    }
    for(const component of ['sun-amber','binding-thread','binding-thread','porous-clay','porous-clay','porous-clay']) await clickRendered('data-buy',component);
    await clickRendered('data-view','focus');
    await clickRendered('data-focus-character','founder');
    const submitFocus=async()=>{
      const markup=element('#app').innerHTML.match(/<form id="focus-work-form">([\s\S]*?)<\/form>/)?.[1];
      assert(markup);assert(!/<button[^>]*disabled/.test(markup),'Focus work must be ready');
      const fields={};
      for(const name of ['firstComponent','secondComponent']) {
        const options=markup.match(new RegExp('<select[^>]*name="'+name+'"[^>]*>([\\s\\S]*?)<\\/select>'))[1];
        fields[name]=options.match(/<option value="([^"]+)"[^>]*selected/)[1];
      }
      await events.submit({preventDefault(){},target:{id:'focus-work-form',fields}});
    };
    await events.submit({preventDefault(){},target:{id:'rename-focus-form',fields:{name:'<Ink & ash>'}}});
    assert.match(element('#app').innerHTML,/&lt;Ink &amp; ash&gt;/);
    await submitFocus();
    await finishWork('state.focusProjects.founder !== null');
    await clickRendered('data-focus-toggle','steady-hand');
    assert.equal(vm.runInContext("state.focusViews.founder.householdLoadout[0]",context),'steady-hand');
    await events.change({target:{id:'focus-design',value:'scholarly-thread'}});
    await submitFocus();await finishWork('state.focusProjects.founder !== null');
    await events.change({target:{id:'focus-design',value:'capacity'}});
    await submitFocus();await finishWork('state.focusProjects.founder !== null');
    assert.equal(vm.runInContext('state.focusViews.founder.capacity',context),2);
    await clickRendered('data-focus-toggle','scholarly-thread');
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.focusViews.founder.householdLoadout.length',context),2);
    // Accommodation: fund, restore, reserve, agree a bedroom and enter its room.
    await clickRendered('data-view','housing');
    await clickRendered('data-founder','commissions');
    for(let i=0;vm.runInContext('state.sharedFunds < 45',context);i++) {assert(i<20);await clickRendered('data-action','advance');}
    await clickRendered('data-housing-fund','west-chamber');
    await finishWork('state.activeHousingRoomId !== null');
    await events.submit({preventDefault(){},target:{id:'beds-west-chamber',fields:{reservedBeds:'1'}}});
    assert.equal(vm.runInContext('state.housingSummary.availableBeds',context),0);
    await events.submit({preventDefault(){},target:{id:'beds-west-chamber',fields:{reservedBeds:'0'}}});
    // Pick Mira's explicitly offered option, not the founder's similarly labelled room control.
    await click({bedroom:'west-chamber',bedroomPerson:'mira'});
    assert.equal(vm.runInContext('state.bedroomAssignments.mira',context),'west-chamber');
    await clickRendered('data-housing-fund','garden-chamber');await finishWork('state.activeHousingRoomId !== null');
    assert.equal(vm.runInContext('state.housingSummary.usableBeds',context),5);
    await clickRendered('data-room','west-chamber');
    assert(!element('#app').innerHTML.includes('undefined'));
    assert.match(element('#app').innerHTML,/West chamber/);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.bedroomAssignments.mira',context),'west-chamber');
    console.log('PASS: housing restoration, reservation, bedroom choice, room access and reload.');
    // Spell designs, personal preparation, one-shot work and a genuinely shared ritual.
    await clickRendered('data-view','spells');
    await clickRendered('data-spell-owner','founder');
    await clickRendered('data-founder','commissions');
    for(let i=0;vm.runInContext('state.sharedFunds < 180',context);i++) {
      assert(i<40);await clickRendered('data-action','advance');
    }
    await clickRendered('data-view','workshop');
    for(const component of ['sun-amber','sun-amber','sun-amber','binding-thread','binding-thread','binding-thread','binding-thread','porous-clay','porous-clay','porous-clay','silver-ivy','silver-ivy']) await clickRendered('data-buy',component);
    const submitSpellForm=async(id,overrides={})=>{
      const markup=element('#app').innerHTML.match(new RegExp('<form id="'+id+'">([\\s\\S]*?)<\\/form>'))?.[1];
      assert(markup,`Missing rendered form ${id}`);assert(!/<button[^>]*disabled/.test(markup));
      const fields={};
      for(const match of markup.matchAll(/<select[^>]*name="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g)) {
        const selected=match[2].match(/<option value="([^"]+)"[^>]*selected/);
        assert(selected);fields[match[1]]=selected[1];
      }
      for(const match of markup.matchAll(/<input[^>]*name="([^"]+)"[^>]*value="([^"]*)"/g)) fields[match[1]]=match[2];
      for(const match of markup.matchAll(/<textarea[^>]*name="([^"]+)"[^>]*>([\s\S]*?)<\/textarea>/g)) fields[match[1]]=match[2];
      await events.submit({preventDefault(){},target:{id,fields:{...fields,...overrides}}});
    };
    const spellKeys=[];
    for(const formId of ['warm-twist','root-song','luminous-copy']) {
      await clickRendered('data-view','spells');
      await events.change({target:{id:'spell-form',value:formId}});
      const before=vm.runInContext('state.sharedFunds',context);
      await submitSpellForm('spell-draft-form',{name:'<Working '+formId+'>',intent:'Make something useful <without extra powers>.'});
      assert.equal(vm.runInContext('state.sharedFunds',context),before);
      assert(!element('#app').innerHTML.includes('<Working '));
      assert.doesNotMatch(element('#app').innerHTML,/without extra powers/);
      assert.equal(vm.runInContext('state.spellbook.at(-1).name',context),vm.runInContext('state.spellForms[spellFormId].name',context));
      const key=vm.runInContext('state.spellbook.at(-1).id',context);spellKeys.push(key);
      await clickRendered('data-spell-test',key);
      await finishWork('state.spellWork.founder !== null');
      assert.equal(vm.runInContext('state.preparedSpells.founder.length',context),spellKeys.length-1);
      if(spellKeys.length<3) await clickRendered('data-spell-prepare',key);
      else {
        const blocked=[...element('#app').innerHTML.matchAll(/<button\b[^>]*>/g)].find(match=>match[0].includes(`data-spell-prepare="${key}"`));
        assert.match(blocked[0],/disabled/);
      }
    }
    await clickRendered('data-spell-cast',spellKeys[0]);
    await clickRendered('data-spell-cancel','founder');
    assert.equal(vm.runInContext('state.spellbook[0].castCount',context),0);
    await clickRendered('data-view','rituals');
    await submitSpellForm('spell-ritual-form');
    await clickRendered('data-action','advance');
    await clickRendered('data-resident','rest');
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.spellRitual.contributions.founder',context),1);
    await clickRendered('data-ritual-resume','concordant-lesson');
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.spellPreparationCapacity',context),3);
    await clickRendered('data-view','spells');
    await clickRendered('data-spell-prepare',spellKeys[2]);
    for(const key of spellKeys) {
      await clickRendered('data-spell-cast',key);await clickRendered('data-action','advance');
      assert.equal(vm.runInContext(`state.spellbook.find(item=>item.id==='${key}').castCount`,context),1);
    }
    for(const room of ['common-room','library','conservatory']) {
      await click({room});assert.match(element('#app').innerHTML,/PRACTICAL MAGIC HERE/);
      const formId={ 'common-room':'warm-twist',library:'luminous-copy',conservatory:'root-song'}[room];
      const key=vm.runInContext(`state.spellbook.find(spell=>spell.formId==='${formId}'&&spell.ownerId==='founder').id`,context);
      await clickRendered('data-spell-cast',key);await clickRendered('data-action','advance');
    }
    await clickRendered('data-view','development');
    await clickRendered('data-character','founder');
    assert.match(element('#app').innerHTML,/Personal spellbook/);
    await clickRendered('data-spell-owner','founder');
    await clickRendered('data-spell-owner','mira');
    await events.change({target:{id:'spell-form',value:'root-song'}});
    await submitSpellForm('spell-draft-form');
    const miraSpell=vm.runInContext('state.spellbook.at(-1).id',context);
    await clickRendered('data-spell-test',miraSpell);await finishWork('state.spellWork.mira !== null');
    await clickRendered('data-spell-prepare',miraSpell);await clickRendered('data-spell-cast',miraSpell);
    assert.equal(vm.runInContext('state.residentRoomId',context),'conservatory');
    await clickRendered('data-action','advance');
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.spellbook.length',context),4);
    assert.equal(vm.runInContext('state.spellRitual.status',context),'complete');
    assert.equal(vm.runInContext('state.preparedSpells.founder.length',context),3);
    assert.match(vm.runInContext("state.originalAssets['west-chamber']",context),/west-chamber.webp/);
    assert.match(vm.runInContext("state.originalAssets['garden-chamber']",context),/garden-chamber.webp/);
    console.log('PASS: rendered spell drafts, all three forms, individual testing/preparation/casting, cancellation, escaped prose, cooperative ritual pause/resume and reload.');
    // A longer expedition, a persistent complication, skill investment and useful discoveries.
    await clickRendered('data-view','development');await clickRendered('data-character','founder');
    for(const skill of ['scholarship','artifice','fieldcraft','fieldcraft']) {
      await clickRendered('data-skill-train',skill);await finishWork('state.trainingProjects.founder !== null');
    }
    assert.equal(vm.runInContext('state.characterSheets.founder.skills.fieldcraft',context),2);
    await clickRendered('data-view','expeditions');await clickRendered('data-site','rainward-observatory');
    assert.match(element('#app').innerHTML,/rainward-observatory.webp/);
    assert.equal(vm.runInContext("state.siteAccess['rainward-observatory']",context),true);
    await events.change({target:{id:'journey-party-mira',checked:true}});element('#carry-lantern').checked=false;
    await clickRendered('data-action','start-expedition');await clickRendered('data-action','advance');
    await clickRendered('data-approach','survey');
    await clickRendered('data-encounter-method','trace-channels');await finishWork("state.expedition.stage==='working'");
    await clickRendered('data-encounter-method','open-auxiliary');await finishWork("state.expedition.stage==='working'");
    assert.equal(vm.runInContext("state.observatoryProgress.survey.complication",context),'misaligned-rack');
    const glassBefore=vm.runInContext("state.materialInventory['moon-glass']",context);
    await clickRendered('data-action','return-expedition');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext("state.materialInventory['moon-glass']",context),glassBefore);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    await events.change({target:{id:'journey-party-mira',checked:true}});
    await clickRendered('data-action','start-expedition');await clickRendered('data-action','advance');await clickRendered('data-approach','survey');
    await clickRendered('data-encounter-method','align-by-hand');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.expedition.remainingWorkPhases',context),1);
    await clickRendered('data-action','return-expedition');await clickRendered('data-action','advance');
    await events.change({target:{id:'journey-party-mira',checked:true}});
    await clickRendered('data-action','start-expedition');await clickRendered('data-action','advance');await clickRendered('data-approach','survey');
    assert.equal(vm.runInContext('state.expedition.remainingWorkPhases',context),1);
    await clickRendered('data-action','advance');await clickRendered('data-encounter-method','bind-references');await finishWork("state.expedition.stage==='working'");
    assert.equal(vm.runInContext("state.archivePrinciples.includes('gentle-refraction')",context),false);
    await clickRendered('data-action','return-expedition');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext("state.characterSheets.mira.knownPrinciples.includes('gentle-refraction')",context),true);
    assert.equal(vm.runInContext("state.materialInventory['moon-glass']",context),glassBefore+1);
    // The second lead has independent encounter progress and finite rewards.
    for(const id of vm.runInContext('journeyPartySelection.slice()',context))await events.change({target:{id:'journey-party-'+id,checked:false}});
    await clickRendered('data-action','start-expedition');await clickRendered('data-action','advance');await clickRendered('data-approach','salvage');
    for(const method of ['trace-channels','handle-lenses','bind-references']) {
      await clickRendered('data-encounter-method',method);await finishWork("state.expedition.stage==='working'");
    }
    await clickRendered('data-action','return-expedition');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.observatoryDiscoveries.length',context),2);
    await clickRendered('data-view','workshop');await clickRendered('data-maker','founder');
    for(const material of ['fireglass','fireglass','moon-glass','moon-glass']) await clickRendered('data-buy',material);
    await clickRendered('data-recipe','reading-prism');await submitCraft();await finishWork('state.craftingProject !== null');
    await clickRendered('data-room','library');
    const copyingBefore=vm.runInContext('state.copyingIncomePerPhase',context);
    await clickRendered('data-utility','reading-prism');assert.equal(vm.runInContext('state.copyingIncomePerPhase',context),copyingBefore+2);
    await clickRendered('data-view','spells');await clickRendered('data-spell-owner','founder');
    await events.change({target:{id:'spell-form',value:'clarify-glass'}});
    await submitSpellForm('spell-draft-form');
    const clarification=vm.runInContext('state.spellbook.at(-1).id',context);
    await clickRendered('data-spell-test',clarification);await finishWork('state.spellWork.founder !== null');
    await clickRendered('data-spell-prepare',spellKeys[0]);await clickRendered('data-spell-prepare',clarification);
    const clarifiedBefore=vm.runInContext("state.materialInventory['moon-glass']",context);
    await clickRendered('data-spell-cast',clarification);await clickRendered('data-action','advance');
    assert.equal(vm.runInContext("state.materialInventory['moon-glass']",context),clarifiedBefore+2);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.characterSheets.founder.skills.artifice',context),1);
    console.log('PASS: personal skills, multi-stage expeditions, capability choices, recoverable complication, partial-work return/reload, both finite leads, new recipe/installation and fourth spell.');
    // A third member joins only after her own conversation and a real available bed.
    await clickRendered('data-view','expeditions');await clickRendered('data-site','hillfold-bindery');
    if(!vm.runInContext("state.siteDiscoveries['hillfold-bindery'].includes('salvage')",context)) {
      for(const id of vm.runInContext('journeyPartySelection.slice()',context))await events.change({target:{id:'journey-party-'+id,checked:false}});element('#carry-lantern').checked=false;
      await clickRendered('data-action','start-expedition');await clickRendered('data-action','advance');await clickRendered('data-approach','salvage');
      await finishWork("state.expedition.stage==='working'");await clickRendered('data-action','return-expedition');await clickRendered('data-action','advance');
    }
    await clickRendered('data-view','contacts');await clickRendered('data-candidate-meet','tamsin');
    for(const topic of ['work','home','plans']) await clickRendered('data-candidate-topic',topic);
    assert.match(element('#app').innerHTML,/available, unreserved one-bed room/);
    await clickRendered('data-view','housing');
    await click({bedroom:'garden-chamber',bedroomPerson:'mira'});
    assert.equal(vm.runInContext('state.bedroomAssignments.mira',context),'garden-chamber');
    await clickRendered('data-view','contacts');await clickRendered('data-candidate-invite','west-chamber');
    assert.equal(vm.runInContext("state.housingSummary.rooms['west-chamber'].arrivalReservedBeds",context),1);
    assert.equal(vm.runInContext('Boolean(state.characterCatalog.tamsin)',context),false);
    const arrivalIdentity=vm.runInContext('JSON.stringify(state.people.tamsin)',context);
    await clickRendered('data-view','housing');
    assert.match(element('#app').innerHTML,/Expected arrivals/);
    assert.match(element('#app').innerHTML.replace(/<[^>]*>/g,''),/Tamsin · West chamber/);
    await clickRendered('data-arrival-cancel','tamsin');
    assert.equal(vm.runInContext('state.additionalResidents.tamsin.status',context),'contacted');
    assert.equal(vm.runInContext('state.arrivalReservationViews.length',context),0);
    assert.equal(vm.runInContext('JSON.stringify(state.people.tamsin)',context),arrivalIdentity);
    await clickRendered('data-view','contacts');await clickRendered('data-candidate-invite','west-chamber');
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.housingSummary.residentCount',context),2);
    assert.equal(vm.runInContext('state.bedroomAssignments.tamsin',context),'west-chamber');
    assert.equal(vm.runInContext('state.additionalResidents.tamsin.assignment',context),'rest');
    for(const view of ['castle','housing','contacts','development','focus','household','spells','rituals','research','workshop','review']) {
      vm.runInContext(`setView('${view}')`,context);assert(!element('#app').innerHTML.includes('undefined'),view+' has missing third-resident data');
    }
    await clickRendered('data-view','workshop');
    for(const material of ['binding-thread','binding-thread','binding-thread','porous-clay']) await clickRendered('data-buy',material);
    await clickRendered('data-view','contacts');await clickRendered('data-resident-project','tamsin');
    await clickRendered('data-action','advance');
    await click({worker:'tamsin',workerAssignment:'rest'});await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.additionalResidents.tamsin.personalProject.completedWorkPhases',context),1);
    await click({worker:'tamsin',workerAssignment:'personal-project'});
    await finishWork("state.additionalResidents.tamsin.personalProject.status==='in-progress'");
    assert.equal(vm.runInContext("state.characterSheets.tamsin.knownPrinciples.includes('joined-fibres')",context),true);
    assert.equal(vm.runInContext("state.characterSheets.founder.knownPrinciples.includes('joined-fibres')",context),false);
    await clickRendered('data-character','tamsin');await clickRendered('data-skill-train','artifice');await finishWork('state.trainingProjects.tamsin !== null');
    await clickRendered('data-prepare','careful-assembly');
    await clickRendered('data-view','workshop');await clickRendered('data-recipe','binding-press');await clickRendered('data-maker','tamsin');
    await submitCraft();assert.equal(vm.runInContext('state.craftingProject.crafterId',context),'tamsin');
    await finishWork('state.craftingProject !== null');
    await clickRendered('data-room','library');await clickRendered('data-utility','binding-press');
    assert.equal(vm.runInContext("state.utilityArtifactPlacements['binding-press']",context),true);
    assert.match(element('#app').innerHTML,/Sharing this room|Practical|PRACTICAL/);
    await clickRendered('data-view','spells');await clickRendered('data-spell-owner','tamsin');
    assert.match(element('#app').innerHTML,/0 \/ 2 spells prepared/);
    await clickRendered('data-view','rituals');assert(!element('#app').innerHTML.includes('undefined'));
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.additionalResidents.tamsin.personalProject.status',context),'complete');
    assert.equal(vm.runInContext('state.characterSheets.tamsin.skills.artifice',context),1);
    await clickRendered('data-view','contacts');
    const miraWardrobe=vm.runInContext('JSON.stringify(state.wardrobe)',context);
    const lifePhase=vm.runInContext('state.currentDayPhase',context);
    const lifePoints=vm.runInContext('state.resonancePoints',context);
    await clickRendered('data-resident-layer','plum-shawl');
    await events.submit({preventDefault(){},target:{id:'tamsin-style-form',fields:{styleName:'A quiet evening'}}});
    await clickRendered('data-resident-layer','none');await clickRendered('data-resident-style','A quiet evening');
    assert.match(element('#app').innerHTML,/portraits\/tamsin.webp/);
    await clickRendered('data-resident-scene','tea-and-margins');
    assert.equal(vm.runInContext('state.resonancePoints',context),lifePoints);
    await clickRendered('data-resident-scene','a-playful-margin');
    assert.equal(vm.runInContext('state.resonancePoints',context),lifePoints+2);
    assert.equal(vm.runInContext('JSON.stringify(state.wardrobe)',context),miraWardrobe);
    assert.equal(vm.runInContext('state.currentDayPhase',context),lifePhase);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.additionalResidents.tamsin.wardrobe.outerLayer',context),'plum-shawl');
    assert.equal(vm.runInContext('state.additionalResidents.tamsin.completedScenes.length',context),2);
    await clickRendered('data-view','stores');
    await events.submit({preventDefault(){},target:{id:'work-order-form',fields:{recipeId:'warming-lantern',crafterId:'mira',requestedCount:'2',firstComponent:'sun-amber',secondComponent:'binding-thread'}}});
    const delegatedId=vm.runInContext('state.workOrders.at(-1).id',context);
    for(const material of ['sun-amber','binding-thread'])await vm.runInContext(`commit({type:'set-material-reserve',materialId:'${material}',target:state.materialInventory['${material}']},'')`,context);
    assert.match(element('#app').innerHTML,new RegExp('id="delegate-order-'+delegatedId+'"'));
    const beforeDelegation=vm.runInContext('state.sharedFunds',context);
    await events.submit({preventDefault(){},target:{id:'delegate-order-'+delegatedId,fields:{orderId:delegatedId,budgetCrowns:'20'}}});
    assert.equal(vm.runInContext('state.sharedFunds',context),beforeDelegation-20);
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.workOrders.at(-1).delegation.spentCrowns',context),9);
    await clickRendered('data-delegation-pause',delegatedId);
    const pausedCount=vm.runInContext('state.workOrders.at(-1).completedCount',context);
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.workOrders.at(-1).completedCount',context),pausedCount);
    await events.submit({preventDefault(){},target:{id:'fund-delegation-'+delegatedId,fields:{orderId:delegatedId,budgetCrowns:'3'}}});
    await clickRendered('data-delegation-resume',delegatedId);
    await finishWork("state.workOrders.at(-1).completedCount<2");
    assert.equal(vm.runInContext('state.workOrders.at(-1).delegation.status',context),'complete');
    assert.equal(vm.runInContext('state.workOrders.at(-1).delegation.returnedCrowns',context),5);
    assert.equal(vm.runInContext('state.sharedFunds',context),beforeDelegation-18);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.workOrders.at(-1).delegation.spentCrowns',context),18);
    for(const material of ['sun-amber','binding-thread'])await vm.runInContext(`commit({type:'set-material-reserve',materialId:'${material}',target:0},'')`,context);
    console.log('PASS: delegated batch forms, protected reserves, budget commitment, pause/resume, explicit top-up, finite completion, exact refund and reload.');
    await clickRendered('data-view','ledger');
    assert.match(element('#app').innerHTML,/id="allowance-form"/);
    const treasuryBeforeAllowance=vm.runInContext('state.sharedFunds',context);
    await events.submit({preventDefault(){},target:{id:'allowance-form',fields:{founder:'1',mira:'1',tamsin:'1',minimumTreasuryCrowns:'20'}}});
    assert.equal(vm.runInContext('state.sharedFunds',context),treasuryBeforeAllowance);
    while(vm.runInContext('state.currentDayPhase',context)!=='morning')await clickRendered('data-action','advance');
    if(vm.runInContext('state.personalFunds.founder',context)===0)for(let phase=0;phase<3;phase++)await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.personalFunds.founder',context),1);
    await events.submit({preventDefault(){},target:{id:'personal-allocation-form',fields:{characterId:'mira',crowns:'4'}}});
    await clickRendered('data-personal-item','poetry-book');
    assert.equal(vm.runInContext('state.personalFunds.mira',context),1);
    await clickRendered('data-wealth-plan','half-personal');
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.householdAllowancePlan.dailyCrowns.tamsin',context),1);
    assert.equal(vm.runInContext('state.personalPossessions.mira.length',context),1);
    assert.equal(vm.runInContext('state.expeditionWealthPlan',context),'half-personal');
    await events.submit({preventDefault(){},target:{id:'allowance-form',fields:{founder:'0',mira:'0',tamsin:'0',minimumTreasuryCrowns:'20'}}});
    console.log('PASS: personal finance forms, morning allowance transfers, individual purchase, expedition arrangement and reload.');
    await clickRendered('data-view','development');await clickRendered('data-character','founder');
    await clickRendered('data-lesson-target','joined-fibres');
    assert.equal(vm.runInContext('state.trainingProjects.founder.teacherId',context),'tamsin');
    await clickRendered('data-view','workroom');
    assert.match(element('#app').innerHTML.replace(/<[^>]*>/g,''),/Lesson with Tamsin/);
    await click({worker:'founder',workerAssignment:'rest'});await clickRendered('data-action','advance');
    assert.equal(vm.runInContext("state.characterSheets.founder.knownPrinciples.includes('joined-fibres')",context),false);
    await clickRendered('data-lesson-resume','founder');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext("state.characterSheets.founder.knownPrinciples.includes('joined-fibres')",context),true);
    await clickRendered('data-character','mira');await clickRendered('data-lesson-target','scholarship');
    const mentorPoints=vm.runInContext('state.characterSheets.founder.earnedAdvancement',context);
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.characterSheets.mira.skills.scholarship',context),1);
    assert.equal(vm.runInContext('state.characterSheets.founder.earnedAdvancement',context),mentorPoints);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.lessonHistory.length',context),2);
    console.log('PASS: offered principle and skill lessons, two-person assignment, workroom pause/resume, personal results and persistent history.');
    await clickRendered('data-view','spells');await clickRendered('data-spell-owner','founder');
    assert.match(element('#app').innerHTML,/id="casting-plan-founder"/);
    const repeatSpell=spellKeys[2];
    const castCountBeforePlan=vm.runInContext(`state.spellbook.find(spell=>spell.id==='${repeatSpell}').castCount`,context);
    await events.submit({preventDefault(){},target:{id:'casting-plan-founder',fields:{characterId:'founder',spellId:repeatSpell,requestedCount:'2'}}});
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.castingPlans.founder.completedCount',context),1);
    await clickRendered('data-cast-plan-pause','founder');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.castingPlans.founder.completedCount',context),1);
    await clickRendered('data-cast-plan-resume','founder');await clickRendered('data-view','workroom');
    assert.match(element('#app').innerHTML,/Agreed casting plan/);
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.castingPlans.founder.status',context),'complete');
    assert.equal(vm.runInContext(`state.spellbook.find(spell=>spell.id==='${repeatSpell}').castCount`,context),castCountBeforePlan+2);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.castingPlans.founder.completedCount',context),2);
    console.log('PASS: finite casting plan form, pause/resume, phase-bound count, workroom visibility, completion and persistent reload.');
    await clickRendered('data-view','workshop');
    for(const [material,count] of [['binding-thread',3],['porous-clay',1]])while(vm.runInContext(`state.materialInventory['${material}']`,context)<count)await clickRendered('data-buy',material);
    await clickRendered('data-view','requests');
    await clickRendered('data-personal-request-action','accept-personal-request');
    const requestKey='mira-reading-folio';
    await events.submit({preventDefault(){},target:{id:'fund-personal-request-'+requestKey,fields:{requestId:requestKey,fundingSource:'shared'}}});
    await clickRendered('data-action','advance');await clickRendered('data-view','workroom');
    assert.match(element('#app').innerHTML,/A folio for the loose leaves/);
    await clickRendered('data-worker','mira');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext("state.personalRequests['mira-reading-folio'].completedWorkPhases",context),1);
    await clickRendered('data-view','requests');await clickRendered('data-personal-request-action','resume-personal-request');await clickRendered('data-action','advance');
    await clickRendered('data-personal-request-action','read-personal-note');await clickRendered('data-keepsake',requestKey);
    const personalBedroom=vm.runInContext('state.bedroomAssignments.mira',context);
    await click({room:personalBedroom});assert.match(element('#app').innerHTML,/ON THE PERSONAL SHELF/);
    await clickRendered('data-view','ledger');
    await events.submit({preventDefault(){},target:{id:'personal-allocation-form',fields:{characterId:'tamsin',crowns:'8'}}});
    const personalBeforeRequest=vm.runInContext('state.personalFunds.tamsin',context);
    await clickRendered('data-view','requests');await clickRendered('data-personal-request-action','accept-personal-request');
    await events.submit({preventDefault(){},target:{id:'fund-personal-request-tamsin-repair-case',fields:{requestId:'tamsin-repair-case',fundingSource:'personal'}}});
    assert.equal(vm.runInContext('state.personalFunds.tamsin',context),personalBeforeRequest-8);
    await clickRendered('data-action','advance');await clickRendered('data-personal-request-action','cancel-personal-request');
    assert.equal(vm.runInContext('state.personalFunds.tamsin',context),personalBeforeRequest);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext("state.residentKeepsakes.mira.includes('mira-reading-folio')",context),true);
    assert.equal(vm.runInContext("state.personalRequests['tamsin-repair-case'].status",context),'accepted');
    console.log('PASS: personal request acceptance, explicit funding, independent work, pause/resume, note, owned bedroom keepsake, personal-wallet cancellation refund and reload.');
    console.log('PASS: contact conversation, private accommodation, protected arrival reservation, third resident, independent work/training, personal notebook, eleventh recipe and persistent roster.');
    // Optional provider settings and draft review use the actual saved draft service with a fake transport.
    await clickRendered('data-view','settings');
    await vm.runInContext('loadProvider()',context);
    await events.submit({preventDefault(){},target:{id:'provider-form',fields:{enabled:'on',model:'example/text-model',maxOutputTokens:'500',apiKey:'fake-private-key'}}});
    assert(!element('#app').innerHTML.includes('fake-private-key'));
    await clickRendered('data-view','household');await clickRendered('data-action','conversation');
    element('#dialogue-message').value='What does practical magic mean to you?';
    const beforeReply=vm.runInContext('JSON.stringify({day:state.dayNumber,phase:state.currentDayPhase,funds:state.sharedFunds,conversation:state.conversation})',context);
    await clickRendered('data-action','draft-dialogue');
    assert.equal(vm.runInContext('JSON.stringify({day:state.dayNumber,phase:state.currentDayPhase,funds:state.sharedFunds,conversation:state.conversation})',context),beforeReply);
    assert.match(element('#app').innerHTML,/A generated &lt;reply&gt;/);
    await clickRendered('data-action','recover-dialogue');
    assert.equal(vm.runInContext('recentDialogueDrafts.length',context),1);
    await clickRendered('data-draft-open',vm.runInContext('dialogueDraft.id',context));
    await clickRendered('data-action','retry-dialogue');
    await clickRendered('data-action','accept-dialogue');
    assert.equal(vm.runInContext('state.conversation.at(-1).source',context),'generated');
    assert.equal(vm.runInContext('state.sharedFunds',context),JSON.parse(beforeReply).funds);
    assert.equal(vm.runInContext('state.currentDayPhase',context),JSON.parse(beforeReply).phase);
    console.log('PASS: provider settings hide the saved key; generated draft preview is escaped and nonmutating; retry and explicit acceptance persist dialogue only.');
    await clickRendered('data-view','contacts');
    await events.submit({preventDefault(){},target:{id:'tamsin-message-form',fields:{message:'<A line for Tamsin only>'}}});
    assert.match(element('#app').innerHTML.replace(/<[^>]*>/g,''),/&lt;A line for Tamsin only&gt;/);
    const miraHistory=vm.runInContext('JSON.stringify(state.conversation)',context);
    element('#dialogue-message').value='How is your repair notebook coming along?';
    await clickRendered('data-action','draft-dialogue');
    assert.equal(vm.runInContext('dialogueDraft.characterId',context),'tamsin');
    await clickRendered('data-action','recover-dialogue');
    const tamsinDraft=vm.runInContext('dialogueDraft.id',context);
    await clickRendered('data-draft-open',tamsinDraft);await clickRendered('data-action','retry-dialogue');
    assert.equal(vm.runInContext('dialogueDraft.characterId',context),'tamsin');
    await clickRendered('data-action','accept-dialogue');
    assert.equal(vm.runInContext('JSON.stringify(state.conversation)',context),miraHistory);
    assert.equal(vm.runInContext('state.additionalResidents.tamsin.conversation.at(-1).speaker',context),'Tamsin');
    console.log('PASS: resident-specific free text, generated draft recovery/retry and acceptance leave Mira’s conversation and game mechanics unchanged.');

    await clickRendered('data-view','journal');
    element('#journal-draft-brief').value='Write a short account of the settled results.';
    const beforeJournal=JSON.parse(vm.runInContext('JSON.stringify(state)',context));
    await clickRendered('data-action','draft-dialogue');
    assert.match(element('#app').innerHTML,/Save reviewed journal account/);
    assert.match(element('#app').innerHTML,/&lt;reply&gt;/);
    assert.equal(vm.runInContext('state.revision',context),beforeJournal.revision);
    await clickRendered('data-action','accept-dialogue');
    assert.equal(vm.runInContext("state.journal.at(-1).source",context),'generated');
    assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify(state.conversation)',context)),beforeJournal.conversation);
    assert.equal(vm.runInContext('state.sharedFunds',context),beforeJournal.sharedFunds);
    await clickRendered('data-action','recover-dialogue');
    const journalDraftId=vm.runInContext("recentDialogueDrafts.find(item=>item.purpose==='journal').id",context);
    await clickRendered('data-draft-open',journalDraftId);
    assert.equal(vm.runInContext('currentView',context),'journal');
    assert.match(element('#app').innerHTML,/Reviewed generated account/);
    await clickRendered('data-action','discard-dialogue');
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext("state.journal.at(-1).source",context),'generated');
    console.log('PASS: reviewed journal draft, escaped preview, source events, prose-only acceptance, recovery and reload.');

    await click({room:'common-room'});
    const furnishingBefore=JSON.parse(vm.runInContext('JSON.stringify({day:state.dayNumber,funds:state.sharedFunds,resonance:state.resonancePoints})',context));
    await clickRendered('data-decoration','ink-rug');
    await clickRendered('data-decoration','star-chart');
    assert.match(element('#app').innerHTML,/Furnishings &amp; effects|Furnishings & effects/);
    assert.match(element('#app').innerHTML,/Ink-blue woven rug/);
    assert.match(element('#app').innerHTML,/Decorative; no numerical bonus/);
    assert(!element('#app').innerHTML.includes('class="furniture '));
    assert(!element('#app').innerHTML.includes('artifact-lantern'));
    await events.submit({preventDefault(){},target:{id:'room-arrangement-form',fields:{arrangementName:'Quiet evening'}}});
    await click({decorationSlot:'floor',decoration:'none'});
    await click({decorationSlot:'wall',decoration:'none'});
    await clickRendered('data-arrangement-action','load-room-arrangement');
    assert.equal(vm.runInContext("state.roomDecorations['common-room'].floor",context),'ink-rug');
    assert.equal(vm.runInContext("state.roomDecorations['common-room'].wall",context),'star-chart');
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext("state.savedRoomArrangements['common-room']['Quiet evening'].decorations.floor",context),'ink-rug');
    await clickRendered('data-arrangement-action','delete-room-arrangement');
    assert.equal(vm.runInContext("state.roomDecorations['common-room'].floor",context),'ink-rug');
    assert.deepEqual(JSON.parse(vm.runInContext('JSON.stringify({day:state.dayNumber,funds:state.sharedFunds,resonance:state.resonancePoints})',context)),furnishingBefore);
    await events.submit({preventDefault(){},target:{id:'room-arrangement-form',fields:{arrangementName:'<Evening "notes">'}}});
    assert.match(element('#app').innerHTML,/&lt;Evening &quot;notes&quot;&gt;/);
    await click({room:'conservatory'});await clickRendered('data-decoration','reed-mat');
    assert.match(element('#app').innerHTML,/Self-watering charm/);
    assert.match(element('#app').innerHTML,/Does not increase the unattended harvest/);
    assert(!element('#app').innerHTML.includes('room-decoration'));
    console.log('PASS: text furnishings/effects, no furniture overlays, independent slots, named arrangements, escaped names, deletion without removal and reload.');

    await clickRendered('data-view','household');
    assert.match(element('#app').innerHTML,/People, plans &amp; invitations|People, plans & invitations/);
    assert.match(element('#app').innerHTML,/A room that grows back/);
    const beforeMoments=vm.runInContext('JSON.stringify({day:state.dayNumber,phase:state.currentDayPhase,funds:state.sharedFunds,resonance:state.resonancePoints,assignments:[state.founderAssignment,state.residentAssignment]})',context);
    await click({residentMoment:'mira-greenhouse',momentAction:'defer-resident-moment'});
    assert.match(element('#app').innerHTML,/Set aside for later/);
    await clickRendered('data-resident-moment','mira-greenhouse');
    assert.equal(vm.runInContext("state.residentMoments['mira-greenhouse'].status",context),'waiting');
    await clickRendered('data-resident-moment','mira-greenhouse');
    assert.match(element('#app').innerHTML,/Plants seem to take that personally/);
    await clickRendered('data-resident-moment','shared-shelf');
    assert.match(element('#app').innerHTML,/Comfortable enough to disagree/);
    await clickRendered('data-resident-moment','shared-margins');
    assert.match(element('#app').innerHTML,/Growing friends/);
    await clickRendered('data-resident-moment','mira-close-reading');
    assert.match(element('#app').innerHTML,/How inconvenient for my excuse/);
    assert.equal(vm.runInContext('JSON.stringify({day:state.dayNumber,phase:state.currentDayPhase,funds:state.sharedFunds,resonance:state.resonancePoints,assignments:[state.founderAssignment,state.residentAssignment]})',context),beforeMoments);
    await clickRendered('data-view','contacts');
    assert.match(element('#app').innerHTML,/A door that closes/);
    assert(!element('#app').innerHTML.includes('data-resident-moment="mira-folio"'));
    await clickRendered('data-resident-moment','tamsin-settling');
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext("state.residentMoments['tamsin-settling'].status",context),'complete');
    await clickRendered('data-view','household');
    assert.match(element('#app').innerHTML,/Read this moment again/);
    console.log('PASS: progress-aware moments, defer/restore/join, shared friendship scenes, individual flirtation followup, unchanged time/rewards/work, private panels and persistent rereading.');

    await clickRendered('data-view','development');await clickRendered('data-character','mira');
    assert.match(element('#app').innerHTML,/Comparative study/);
    assert.match(element('#app').innerHTML,/Scholarship rank 1/);
    assert.match(element('#app').innerHTML,/Where the work comes from/);
    const investedBefore=vm.runInContext('state.characterSheets.mira.investedAdvancement',context);
    await clickRendered('data-train','comparative-study');
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.characterSheets.mira.investedAdvancement',context),investedBefore+2);
    const previousPrepared=JSON.parse(vm.runInContext('JSON.stringify(state.characterSheets.mira.preparedPractices)',context));
    for(const key of previousPrepared)await clickRendered('data-prepare',key);
    await clickRendered('data-prepare','comparative-study');await clickRendered('data-prepare','archive-focus');
    await events.submit({preventDefault(){},target:{id:'preparation-set-form',fields:{setName:'Archive afternoon'}}});
    await clickRendered('data-prepare','comparative-study');
    await clickRendered('data-preparation-action','load-preparation-set');
    assert.equal(vm.runInContext("state.characterSheets.mira.preparedPractices.includes('comparative-study')",context),true);
    assert.equal(vm.runInContext('state.characterSheets.mira.preparedPractices.length',context),2);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext("state.practicePreparationSets.mira['Archive afternoon'].length",context),2);
    await clickRendered('data-action','start-training-reset');await clickRendered('data-action','advance');
    assert.match(element('#app').innerHTML,/Learn Comparative study again before loading this set/);
    assert.equal(vm.runInContext("state.preparationSetViews.mira['Archive afternoon'].length",context),1);
    console.log('PASS: advanced practice prerequisites, training cost, individual preparation, work breakdown, named set restore/reload and safe invalidation after retraining.');

    await clickRendered('data-view','workshop');
    for(const key of ['moon-glass','binding-thread']) {
      const stock=vm.runInContext(`state.materialInventory['${key}']-state.materialReserveTargets['${key}']`,context);
      for(let i=stock;i<1;i++)await clickRendered('data-buy',key);
    }
    await clickRendered('data-view','development');await clickRendered('data-character','founder');
    assert.match(element('#app').innerHTML,/Lamplit sight/);
    const baseSpellCapacity=vm.runInContext('state.spellPreparationCapacities.founder',context);
    await clickRendered('data-augmentation-action','begin-augmentation');
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.spellPreparationCapacities.founder',context),baseSpellCapacity+1);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.personalAugmentations.founder.active',context),true);
    await clickRendered('data-augmentation-action','reverse-augmentation');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.spellPreparationCapacities.founder',context),baseSpellCapacity);
    assert.equal(vm.runInContext('state.personalAugmentations.founder.active',context),false);
    console.log('PASS: personal blessing offered with exact costs, two assigned phases, personal capacity, persistent reload and one-phase reversal.');

    await click({spellOwner:'tamsin'});
    assert.ok(element('#app').innerHTML.includes(vm.runInContext('Object.keys(state.spellForms).length',context)+' authored spells'));
    assert.doesNotMatch(element('#app').innerHTML,/Describe a spell idea|spell-proposal-idea/);
    await events.change({target:{id:'spell-form',value:'warm-twist'}});
    const beforeCatalogue=vm.runInContext('state.sharedFunds',context);
    await submitSpellForm('spell-draft-form');
    assert.equal(vm.runInContext('state.sharedFunds',context),beforeCatalogue);
    assert.equal(vm.runInContext("state.spellViews.find(item=>item.ownerId==='tamsin'&&item.formId==='warm-twist').name",context),'Warm-twist binding');
    console.log('PASS: authored catalogue, fixed names and effects, free explicit study plan, no runtime spell proposal UI.');


    // Full authored summoning: research, contact, visit, two decisions, resident work and return.
    await clickRendered('data-view','research');
    await click({research:'courteous-passage',researchLead:'founder'});
    await finishWork("state.researchProjects['courteous-passage'].status==='in-progress'");
    assert.equal(vm.runInContext("state.researchProjects['courteous-passage'].status",context),'complete');
    await clickRendered('data-view','stores');
    for(const material of ['porous-clay','binding-thread']) await clickRendered('data-buy',material);
    await clickRendered('data-view','summoning');
    assert.match(element('#app').innerHTML,/summoning-form/);
    await events.submit({preventDefault(){},target:{id:'summoning-form',fields:{conductorId:'founder',component0:'porous-clay',component1:'binding-thread'}}});
    assert.equal(vm.runInContext('Object.values(state.summoningContacts)[0].contactStatus',context),'preparing');
    await clickRendered('data-action','advance');await clickRendered('data-action','advance');
    assert.match(element('#app').innerHTML,/Iona/);
    for(const topic of ['intentions','home','visit']) await clickRendered('data-topic',topic);
    await clickRendered('data-visit-room','garden-chamber');
    assert.equal(vm.runInContext('state.residency.iona.residencyStatus',context),'arrival-agreed');
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.residency.iona.residencyStatus',context),'visiting');
    assert.equal(vm.runInContext('Boolean(state.characterCatalog.iona)',context),false);
    const visitorRoom=vm.runInContext("Object.entries(state.roomOccupants).find(([,people])=>people.includes('iona'))[0]",context);
    await click({room:visitorRoom});
    assert.match(element('#app').innerHTML,/Visiting · no household work assigned/);
    for(const page of ['housing','castle','household','room','workroom','summoning']) {
      vm.runInContext(`setView('${page}')`,context);assert(!element('#app').innerHTML.includes('undefined'),page+' visitor missing data');
    }
    assert.match(element('#app').innerHTML,/Maps can wait a little/);
    await clickRendered('data-topic','quiet-company');
    assert.match(element('#app').innerHTML,/a letter from the river towns/);
    await clickRendered('data-topic','flirt');
    assert.match(element('#app').innerHTML,/A little flirting is welcome/);
    assert.equal(vm.runInContext('dialogueCharacter()',context),'iona');
    await clickRendered('data-summoning-action','summoning-ask-stay');
    assert.equal(vm.runInContext('state.residency.iona.residencyStatus',context),'visiting');
    await clickRendered('data-stay-decision','invite-to-stay');
    assert.equal(vm.runInContext('state.residency.iona.residencyStatus',context),'resident');
    await click({founder:'commissions'});
    for(let phase=0;phase<35&&vm.runInContext('state.sharedFunds<75',context);phase++)await clickRendered('data-action','advance');
    assert(vm.runInContext('state.sharedFunds>=75',context));
    await click({founder:'rest'});
    await clickRendered('data-view','stores');
    for(const material of ['porous-clay','porous-clay','porous-clay','binding-thread','binding-thread','binding-thread','binding-thread'])await clickRendered('data-buy',material);
    await clickRendered('data-view','summoning');
    await clickRendered('data-action','start-iona-atlas');
    await clickRendered('data-action','advance');
    await click({worker:'iona',workerAssignment:'rest'});await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.ionaAtlasView.completedWorkPhases',context),1);
    await clickRendered('data-action','resume-iona-atlas');
    await finishWork("state.ionaAtlasView.status==='in-progress'");
    assert.equal(vm.runInContext('state.characterSheets.iona.earnedAdvancement',context),2);
    await clickRendered('data-resident-moment','iona-atlas-finished');
    await clickRendered('data-view','household');await clickRendered('data-resident-moment','iona-mira-map');
    assert.equal(vm.runInContext("state.residentFriendships.some(row=>row.participants.includes('iona'))",context),true);
    await clickRendered('data-view','requests');
    await click({personalRequestAction:'accept-personal-request',personalRequest:'iona-map-case'});
    await events.submit({preventDefault(){},target:{id:'fund-personal-request-iona-map-case',fields:{requestId:'iona-map-case',fundingSource:'shared'}}});
    await finishWork("state.personalRequests['iona-map-case'].status==='in-progress'");
    await click({keepsake:'iona-map-case',keepsakeShow:'true'});
    assert.equal(vm.runInContext("state.residentKeepsakes.iona.includes('iona-map-case')",context),true);
    await clickRendered('data-view','ledger');
    await click({founder:'commissions'});
    for(let phase=0;phase<15&&vm.runInContext('state.sharedFunds<state.householdAllowancePlan.minimumTreasuryCrowns+3',context);phase++)await clickRendered('data-action','advance');
    await click({founder:'rest'});
    const ionaWalletBeforeGift=vm.runInContext('state.personalFunds.iona',context);
    await clickRendered('data-personal-gift','travel-tea-tin');
    assert.equal(vm.runInContext('state.personalFunds.iona',context),ionaWalletBeforeGift);
    assert.equal(vm.runInContext("state.personalPossessions.iona.includes('travel-tea-tin')",context),true);
    await clickRendered('data-view','summoning');
    const ionaIdentity=vm.runInContext('JSON.stringify(state.people.iona)',context);
    await clickRendered('data-character','iona');
    for(const page of ['development','focus','spells','housing','household','workroom','research','stores','summoning']) {
      vm.runInContext(`setView('${page}')`,context);assert(!element('#app').innerHTML.includes('undefined'),page+' fourth-resident missing data');
    }
    await clickRendered('data-summoning-action','summoning-depart');
    await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('state.residency.iona.residencyStatus',context),'away');
    assert.equal(vm.runInContext('Boolean(state.bedroomAssignments.iona)',context),false);
    assert.match(element('#app').innerHTML.replace(/<[^>]*>/g,''),/Remembered conversations with Iona/);
    assert.match(element('#app').innerHTML,/Visits & crossings/);
    assert.match(element('#app').innerHTML,/A little flirting is welcome/);
    assert(!element('#app').innerHTML.includes('id="summoned-message-form"'));
    await clickRendered('data-visit-room','garden-chamber');await clickRendered('data-action','advance');
    assert.equal(vm.runInContext('JSON.stringify(state.people.iona)',context),ionaIdentity);
    await vm.runInContext('readState().then(result=>{state=result;render();})',context);
    assert.equal(vm.runInContext('state.residency.iona.residencyStatus',context),'visiting');
    console.log('PASS: Iona’s exact-cost atlas, pause/resume, own rewards, personal map case, displayed keepsake, shared scene and treasury-funded gift.');
    console.log('PASS: authored summoning research, explicit contact costs, visitor exclusion, separate membership decisions, fourth-resident views, departure and persistent same-person return.');

    // Lost creation replies retry the exact identifier; the existing campaign survives.
    await clickRendered('data-view','settings');
    await vm.runInContext('loadCampaigns()',context);
    assert.match(element('#app').innerHTML,/href="\/api\/export\?campaign=default"/);
    await clickRendered('data-view','campaigns');
    assert.match(element('#app').innerHTML,/Current campaign/);
    const originalDay=vm.runInContext('state.dayNumber',context);
    dropCreationResponse=true;
    await events.submit({preventDefault(){},target:{id:'new-campaign-form',fields:{name:'A separate chapter'}}});
    assert.match(element('#app').innerHTML,/Retry the same creation safely/);
    const creationId=vm.runInContext('campaignCreationRequest.campaignId',context);
    await clickRendered('data-action','retry-campaign');
    assert.equal(context.location.href,'/?campaign='+creationId);
    await vm.runInContext('loadCampaigns()',context);
    assert.equal(vm.runInContext('campaignRows.length',context),2);
    assert.equal(vm.runInContext('state.dayNumber',context),originalDay);
    const second=JSON.parse(execFileSync(process.env.PYTHON || 'python',['-c',bridge,directory,'/api/state?campaign='+creationId],{input:'{}',encoding:'utf8',maxBuffer:32*1024*1024}));
    assert.equal(second.dayNumber,1);assert.equal(second.campaignName,'A separate chapter');
    assert.equal(second.focusViews.founder.capacity,1);
    console.log('PASS: 24 views at home and with Mira away; all eleven recipes use rendered form fields.');
    console.log('PASS: rendered focus inscription and capacity forms, prepared effects, escaped names, reload, campaign list/export scope and creation retry after a lost response.');
    console.log('PASS: neighbour acceptance/deferral/delivery, saved letter, nursery route and survey, capillary crafting and installation, protected delivery control, both invitations and persistent reload.');
    console.log('PASS: research catalogue, three utility installations, stock-first production, personal study, multi-copy work orders, exact purchases, manual starts and reload; prior connected playthrough remains working.');
    console.log('These checks do not measure layout, painting, focus behavior or real browser interaction.');
  } finally {fs.rmSync(directory,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
